### ISSUE TITLE
[Bug] CleanupSystem would not be generated in version 1.13

### ISSUE THREAD

**Issue by rayss1** [sschmid/Entitas-CSharp#1004]
Hi,

I found a bug that CleanupSystem cannot be generated in entitas1.13

Here's the code

using Entitas;
using Entitas.CodeGeneration.Attributes;
using UnityEngine;

[Input, Cleanup(CleanupMode.DestroyEntity)]
public sealed class InputComponent : IComponent
{
    public Vector2Int value;
}

After click Jenny->Generate, I can't find CleanupInputSystem in generated code

Cheers

**Comment by sschmid** [comment]
Hi! Cleanup is currently only in the [Entitas Unity Asset Store](http://u3d.as/NuJ) version.

Cleanup and all Roslyn code generators will be part of all Entitas 1.14.

I posted an update to share more info about it:
https://github.com/sschmid/Entitas-CSharp/issues/992#issuecomment-1227761712

**Comment by sschmid** [comment]
All Entitas versions now have this!
See #978
