### ISSUE TITLE
Update the wiki

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#103]
Check all entries of the wiki if they need to be updated. Add more examples and more explanations. Make it easier to get all basic questions answered. Add a FAQ

**Comment by sschmid** [comment]
Hope that will help you guys to get started easier 👍

**Comment by sschmid** [comment]
Feel free to add your top 3 questions so I don't forget them in the FAQ

**Comment by JamesMcMahon** [comment]
I mentioned it in my multiple pool ticket, but I think adding the [proper way to restart a game](https://github.com/sschmid/Entitas-CSharp/issues/82) to the FAQ would be useful.

**Comment by JamesMcMahon** [comment]
I'd probably also add:

* [Test Teardown](https://github.com/sschmid/Entitas-CSharp/issues/80)
* [An explanation of the various OnEntity behaviors](https://github.com/sschmid/Entitas-CSharp/issues/44)

**Comment by mcavila** [comment]
Added a new section for Attributes.

**Comment by carlos-avila** [comment]
Updated Attributes to reflect the latest release.

**Comment by sschmid** [comment]
Awesome! Thanks for your help

**Comment by CFusion** [comment]
It would be nice to have at least a single non-unity example project.

**Comment by carlos-avila** [comment]
No problem, I think it would be nice if the project had some solid docs. Would you like to use something like [ReadTheDocs](http://docs.readthedocs.io/en/latest/index.html)? I could start working on that.

**Comment by carlos-avila** [comment]
[Here's a mockup](http://entitas-csharp.readthedocs.io/en/feature-readthedocs_init/) of what I have in mind. It would also share the same file with the wiik, that way both the wiki and the site get updated at the same time. Let me know if you like the idea.

**Comment by sschmid** [comment]
@carlos-avila Nice! We can use that in the future

**Comment by JuDelCo** [comment]
It's cool but i prefer this wiki because text is CENTERED in the screen

I have a large screen ....

**Comment by srivello** [comment]
It would be helpful for the wiki to include more info on;

- Features (vs Systems)

**Comment by Thraka** [comment]
I second the motion for a non-unity based example. I cannot figure this thing out 😢

**Comment by grumpyoldman1066** [comment]
I second the request for a non-Unity example project, even one sans graphics that simply outputs to a log file.
