### ISSUE TITLE
Components updating in the inspector 

### ISSUE THREAD

**Issue by derwish-pro** [sschmid/Entitas-CSharp#107]
Components stopped updating their values in the inspector after update 0.30.0>0.30.3. The values change only when I open again the page of the entity in the inspector. But nothing is updated if I don't touch anything. Returned 0.30.0. Everything works as it should.

**Comment by vladpazych** [comment]
For temporary fix you can open `EntityInspector.cs` and add:
```
public override bool RequiresConstantRepaint () {
    return true;
}
```

**Comment by derwish-pro** [comment]
Ok. Thank you.

**Comment by sschmid** [comment]
Ah, I see. I opened Pandora's box with the Blueprints feature ;) I'll take a look... Thanks for the hint
