### ISSUE TITLE
GUI Null ref when trying to view entity in inspector

### ISSUE THREAD

**Issue by wes-kay** [sschmid/Entitas-CSharp#1083]
Unity `2023.3.0a13`

Unable to view entities components in the inspector, following the basic `AddHealth` component. 

![Screenshot_9](https://github.com/sschmid/Entitas/assets/40011470/8b2c68aa-4a42-4148-a2ab-9c77e20454ef)

**Comment by SidiaDevelopment** [comment]
There is a solution some answers down in here: https://github.com/sschmid/Entitas/issues/1067
