### ISSUE TITLE
Fixed Point

### ISSUE THREAD

**Issue by silencebin1993** [sschmid/Entitas-CSharp#1091]
I use custom fixed-point trees fixInt, fixVec3, etc., I can't use the entitas inspector correlation, is the editor source open, or what folder is the source in, how should I replace the dll with the source？

**Comment by silencebin1993** [comment]
sorry，founded！🤣
![Snipaste_2024-05-22_14-43-49](https://github.com/sschmid/Entitas/assets/53089639/5207ae1f-6c17-4021-b57e-6fc935d00281)

**Comment by sschmid** [comment]
For reference: https://github.com/sschmid/Entitas/tree/main/src/Entitas.Unity.Editor/TypeDrawer

This folder contains supported type drawers used to display common types. You can add more TypeDrawers to your project if needed, there's a button in the Entitas preferences to generate a template that you can use.
