### ISSUE TITLE
Entitas DSL (Domain Specific Language)

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#110]
# The current code generator
The code generator is very flexible and can be customized heavily to fit all your need.
It currently works like this:

1. `ICodeGeneratorDataProvider` converts a specific source format into `ComponentInfo[]`
2. `ICodeGenerator` converts `ComponentInfo[]` into `CodeGenFile[]`
3. `ICodeGenFilePostProcessor` writes files to disc.

Again:
1. DataProvider(source) returns `ComponentInfo[]` (source to intermediate format)
2. Generators(`ComponentInfo[]`) => `CodeGenFile[]` (intermediate format to source code)
3. PostProcessor (source code to disk)

Example:
You write a new `PositionComponent` (source)
1. TypeReflectionProvider(sourceCode) uses reflection to create `ComponentInfo[]` (intermediate format)
2. ComponentExtensionsGenerator (and others) create `CodeGenFile[]` based on `ComponentInfo[]` (result)

### source => intermediate format => result

As we all know, the TypeReflectionProvider uses reflection based on the last compiled assembly. This means, if there are compile errors the assembly is not updated and generating again won't include any changes made to the source code until it can compile again.

That's why we're working on a new code generator DataProvider based on [Roslyn](https://github.com/dotnet/roslyn) to be able to create the intermediate format even when the solution does not compile.

Once we have it, we can simply swap the current `ICodeGeneratorDataProvider` which is the TypeReflectionProvider with the RoslynDataProvider and we're done. Everything works because the source analysis is decoupled from the actual code generation.

That means we can write any kind of `ICodeGeneratorDataProvider` that converts any kind of source into the intermediate format and swap it. E.g. a JsonDataProvider that can parse a json where all components are defined.

# Suggestion
We could write a custom DSL which defines all components in a single file and we can create a new DSLDataProvider to convert this source into ComponentInfo[]. This file is not affected if there a compile errors or not. That means, we can regenerate anytime we want.

This would be an alternative to the RoslynDataProvider. Currently, Roslyn doesn't fully work on all platforms, that's why I'm looking to find alternatives.

Let me know what you think.

**Comment by sschmid** [comment]
If you have doubts or arguments against it, let me know.

**Comment by JuDelCo** [comment]
Looks good, but when Roslyn will work in those platforms? The DSL solution looks like a temp workaround until it works (and in those platforms where Roslyn works is better to use it because you don't need to write that DSL)

In any case, the concept is cool !

PS: Question, i'm currently on windows, how would be for me the swap to Roslyn ? I need to install something ? Or will be bundled with entitas releases?

**Comment by sschmid** [comment]
Afaik it's up to the Microsoft/Xamarin/Mono guys to implement missing features for all platforms. I cannot really tell when / if.

It's planned that any new code generator will be bundled with Entitas, so nothing to do on your part.

**Comment by carlos-avila** [comment]
I'm not sure if you are aware of this yet, but all of the uFrame ECS system was open sourced recently: [link](https://github.com/micahosborne/uFrame). uFrame was also using a code generator that did not rely on reflection. Maybe something can be lifted from there?

**Comment by sschmid** [comment]
They use CodeDom. I did not look at CodeDom yet, but now would be a perfect time to do so :)

**Comment by carlos-avila** [comment]
Nice, I wish I could give you any pointers but I never had time to dive into that part of uFrame..

**Comment by sschmid** [comment]
That was already a good hint to finally fiddle with CodeDom :) Thanks

**Comment by sschmid** [comment]
Will close because of #77
