### ISSUE TITLE
[Suggestion] Cache access to single entities

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#113]
Simple suggestion that I'd like to run past everyone.

Rather then an `[SingleEntity]` entity doing a look up this way:
```csharp
public Entity audioSourceEntity { get { return GetGroup(Matcher.AudioSource).GetSingleEntity(); } }
```

Why not store a reference to the group so it's only looked up once?
```csharp
public Entity audioSourceEntity { get { return groupRef.GetSingleEntity(); } }
```

I imagine dictionary lookup you are doing for the group is fairly fast, but I wonder for every frame execution systems if this would be a little bit faster. Enough to satisfy a little bit more complexity for the generated code.

Thoughts?

**Comment by JuDelCo** [comment]
Groups are cached the first time you get one. So there's no lookup :)

**Comment by JamesMcMahon** [comment]
There is a still a dictionary lookup:

```csharp
public virtual Group GetGroup(IMatcher matcher) {
    Group group;
    if (!_groups.TryGetValue(matcher, out group)) {
        group = new Group(matcher);
        var entities = GetEntities();
        for (int i = 0, entitiesLength = entities.Length; i < entitiesLength; i++) {
            group.HandleEntitySilently(entities[i]);
        }
        _groups.Add(matcher, group);

        for (int i = 0, indicesLength = matcher.indices.Length; i < indicesLength; i++) {
            var index = matcher.indices[i];
            if (_groupsForIndex[index] == null) {
                _groupsForIndex[index] = new List<Group>();
            }
            _groupsForIndex[index].Add(group);
        }

        if (OnGroupCreated != null) {
            OnGroupCreated(this, group);
        }
    }

    return group;
}
```

`_groups.TryGetValue(matcher, out group)` is pretty fast, but for an extra boost it might be worth caching.

**Comment by sschmid** [comment]
Thanks, I'm always happy if we can identify more places where we can save some cycles :)
Yes, this would save one dict lookup.
Thoughts:
- We would need to store a group in the entity for each SingleEntity which increases the memory footprint of each entity.
- When you store references to groups, you should also always subscribe to [pool.OnGroupCleared](https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas/Entitas/Pool.cs#L223) and add logic to set the group field to null and retrieve it again from the pool if it's null.

I could add a test in the performance test suite and profile it, to see if there are any gains that would justify the increased complexity.

**Comment by JamesMcMahon** [comment]
I guess the more obvious thing would be to cache the entity itself.

I find myself doing a enity lookup in a system and saving it to a local var just to avoid duplicate lookups. It would be nice to not have to do that but the performance difference is probably pretty slight.

**Comment by JamesMcMahon** [comment]
I looked into this further in my system code where I am caching bool for component flags. I actually don't see much difference (doesn't show up in the visual debuger so it's less then 0.001ms) between caching in a boolean, using the current code or caching the group like the following:

```csharp
Group _cachedGroup;

public Entity gameOverEntity {
    get {
        if (_cachedGroup == null)
        {
            _cachedGroup = GetGroup(Matcher.GameOver);
        }
        return _cachedGroup.GetSingleEntity(); 
    } 
}
```

So this may be a case of premature optimization on my part. In this case it was just a system with a single lookup, it may make more a difference on systems with multiple lookups.
