### ISSUE TITLE
Change custom pool's name from setting and generated got some errors.

### ISSUE THREAD

**Issue by chiuan** [sschmid/Entitas-CSharp#121]
like from UI to ui
or Character to character
just re generated but some scripts maybe still Character.
like the 'Character' same as 'character'

**Comment by sschmid** [comment]
Hi, when you want to rename a pool I suggest following steps:

- Use rename refactoring of your IDE to rename the existing XyzPoolAttribute class name first, e.g. [Core] to [CoreGame]
- Change the name in the Entitas Preferences
- Generate

**Comment by chiuan** [comment]
ok。thanks for the tip!
