### ISSUE TITLE
Multiple Pools and Components exclusive to a subset of them

### ISSUE THREAD

**Issue by sschoener** [sschmid/Entitas-CSharp#124]
Hi,

depending on the intended usage, the following can either be classified as a bug or as a lack of important documentation.

The setup is as follows: I have three pools named _TestA_, _TestB_, and _TestC_. Furthermore, I have three components _ComponentAB_, _ComponentAC_, and _ComponentBC_, set up like this:

```C#
[TestB, TestC]
public class ComponentBC : IComponent { public int K; }

[TestA, TestC]
public class ComponentAC : IComponent { public int K; }

[TestA, TestB]
public class ComponentAB : IComponent { public int K; }
```

Take note of the attributes. The following code throws an exception when trying to add components (specifically _ComponentBC_) to entity _b_:
```C#
var a = Pools.testA.CreateEntity();
a.AddComponentAB(0).AddComponentAC(1);
var b = Pools.testB.CreateEntity();
b.AddComponentAB(0).AddComponentBC(1);
var c = Pools.testC.CreateEntity();
c.AddComponentAC(0).AddComponentBC(1);
```

The problem here is that the generated code claims that each of the entities of the pools needs only two components, but the component _ComponentBC_ has id 2 (thus producing an out-of-range exception).

**Comment by sschmid** [comment]
I'll will look into this. This looks like a bug

**Comment by sschmid** [comment]
Fox will be in the next version. Thanks for finding!
