### ISSUE TITLE
Using Entitas in Unity Editor

### ISSUE THREAD

**Issue by micz84** [sschmid/Entitas-CSharp#126]
Is it possible to use Entitas in Editor, for example to create unity extension for level editor, which would be serialized and deserialized?

**Comment by sschmid** [comment]
Yes, I do this for my levelEditor and even execute the same systems that will add and remove views etc. You need a way to serialize and deserialize the state, e.g. json so you can recreate the entites when you reload the scene

**Comment by micz84** [comment]
That's great, I will try Entitas for my next project then :). Thanks for fast replay,
