### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by pateras** [sschmid/Entitas-CSharp#133]
[This link](https://github.com/sschmid/Entitas-CSharp/tree/develop/Entitas.Unity.VisualDebugging/Assets/Entitas.Unity.VisualDebugging/Entity/Editor/TypeDrawer) on [this page](https://github.com/sschmid/Entitas-CSharp/wiki/Unity-integration) (link text: "Take a look at these implementations") is broken.

**Comment by sschmid** [comment]
Thanks! Is fixed now
https://github.com/sschmid/Entitas-CSharp/tree/master/Entitas.Unity/Assets/Entitas/Unity/VisualDebugging/Entity/Editor/TypeDrawer
