### ISSUE TITLE
[Suggestion] Building Entitas for Unity on Windows

### ISSUE THREAD

**Issue by mstrchrstphr** [sschmid/Entitas-CSharp#138]
Atm, building and packaging up Entitas for use in Unity can only be easily done on OS X.  This is a major bummer! Is anyone working on this? I might try to work something out if nobody has already.

### Details

The `build.sh` script contains some OS X specific directories:

```sh
/Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -logfile -projectPath "$PWD/$ESU/Assets/../" -executeMethod Commands.GenerateProjectFiles
```

I also noticed that this line behaved very strangely on Windows running Cygwin:

```sh
cp -r "$ESU_ASSETS/$ES/Unity/" $SRC_DIR/$ESU
```

Instead of recursively copying the contents of `Unity/` as expected it is recursively copying the contents AND pulling over the `Unity/` directory itself! I don't know if this is a bug in Cygwin or what but it sucks.

**Comment by mstrchrstphr** [comment]
I just made a fresh clone of master on my mac and ran `Build/build.sh` and it failed:

```
Scripts have compiler errors.
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Utilities/Argv.cpp Line: 152)


Aborting batchmode due to failure:
Scripts have compiler errors.

***Thread 'UnityLookForNewInputDevices' is still running!***
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Threads/Thread.cpp Line: 68)

***Thread was not cleaned up!***
 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Threads/Posix/PlatformThread.cpp Line: 39)

empty()
 
(Filename: ./Runtime/Utilities/LinkedList.h Line: 180)
```

Any thoughts? I can't seem to build on either OS 😢

**Comment by sschmid** [comment]
Hi, yes, atm there's only a script that's tested on mac. I'd be happy to accept an PR if you want to provide a script for windows. If you need more information about the idea behind the various scripts let me know.
build.sh should work out of the box. It seems like there are compiler errors that's why the Unity task cancels
```
Aborting batchmode due to failure:
Scripts have compiler errors
```

When you open Unity manually you should be able to identify the spot where it's breaking for you. Maybe sth went wrong with update_project_dependencies.sh

**Comment by mstrchrstphr** [comment]
Ah I was compiling via command line and only compiling a subset of the files. The script was compiling everything thus the discrepancies - thanks!

I wrote up a new script to make working on Entitas and testing in unity on Windows a little smoother. I'll open a separate PR for that when i return from traveling next week.
