### ISSUE TITLE
Is Entitas being used in any live video game?

### ISSUE THREAD

**Issue by angelotadres** [sschmid/Entitas-CSharp#140]
Hi.

I'm just curious, Is Entitas being used right now in a live video game?

Regards

**Comment by sschmid** [comment]
Hi @angelotadres,
yes, Futurama has some Entitas in it
https://itunes.apple.com/de/app/futurama-game-of-drones/id1009200976?mt=8
https://play.google.com/store/apps/details?id=com.wooga.futurama

and there have been a few games in production already. I'm currently working on a game that we plan to go live with.
There have been soft-launches with the objective-c and swift version already, too.

There have also been multiplayer games proving that you can run the simulation on a server and reuse existing code. Unfortunately they haven't been released.

**Comment by angelotadres** [comment]
That's is awesome!
Thanks for the information.

**Comment by JamesMcMahon** [comment]
I have a game that is going to go live shortly. Stay tuned.

**Comment by Skybladev2** [comment]
@angelotadres Check out this game: https://twitter.com/dash_and_dot/status/765106758608191488

**Comment by JamesMcMahon** [comment]
See https://github.com/sschmid/Entitas-CSharp/issues/148
