### ISSUE TITLE
Naming Convention Discussion

### ISSUE THREAD

**Issue by srivello** [sschmid/Entitas-CSharp#144]
One of many existing examples of C# codings standards is the [Microsoft (MS) C# Coding Standards.](https://msdn.microsoft.com/en-us/library/ff926074.aspx) 

In the professional projects of my team, we use a modified form of that standards for all our projects. In general we like using the establish standard (its thorough, well documented, eases adoption of new staff) and the MS standards is appropriate. In MS, the fields use [camelCase](https://en.wikipedia.org/wiki/CamelCase) and the properties use [PascalCase](https://en.wikipedia.org/wiki/PascalCase). That is also how Unity documentation seems to name members too. In my team, we choose to use no public fields, only public properties. 

Currently the Entitas of convention is correct per MS but looks odd within the code of our team. This is not a big issue. I mention it only to encourage discussion.

Ex. Entitas Naming Convention (field)
`myComponent.highScore = 10;`

Ex. My Non-Entitas Naming Convention (property)
`myMonoBehavior.HighScore = 10;`

So you can see they are different.

A few questions about Entitas...
 1. What do you think about allowing (per code generation) properties on Components? This would allow for more control (inc. validation on the getter) ?

**Comment by sschmid** [comment]
I think codings standards are great and important. Although we call them standards, many teams have their own "sub standards". Personally, I've set the conventions for Entitas to sth very similar I saw when looking at the Unity API, e.g. `gameObject.transform.x`.
If the generated code doesn't conform to the convention your team has decided on, I suggest you duplicate the existing code generators and update the affected code. Then you can deselect the generators that ship with Entitas and choose your custom ones.
