### ISSUE TITLE
I, Falling Robot #madeWithEntitas

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#148]
Brand new game for iOS / Android using Entitas.

[![Trailer](https://img.youtube.com/vi/9r7IDotYCcc/0.jpg)](https://www.youtube.com/watch?v=9r7IDotYCcc)

http://ifallingrobot.com

**Comment by JamesMcMahon** [comment]
I also will post on twitter, I do know how hashtags work. 😆

**Comment by sschmid** [comment]
Awesome! Great to see that you have a Entitas game in the stores! Will link it in the wiki

**Comment by JamesMcMahon** [comment]
Thanks Simon!

And thanks for all the help. Entitas a great framework, you should be proud.

**Comment by JamesMcMahon** [comment]
@sschmid Just noticed an issue. When you added the game to the wiki, you also accidentally duplicated the Entitas Tank blurb.
