### ISSUE TITLE
GroupChanged

### ISSUE THREAD

**Issue by RvRooijen** [sschmid/Entitas-CSharp#151]
If i get a group like so:
var positionEntities = _pool.GetGroup(Matcher.AllOf(Matcher.GameElement, Matcher.Position));
        
And watch the group
positionEntities.OnEntityAdded += (group, entity, index, component) => OnPositionEntityAdded(entity, component);

Is there any way to get both the component changes that i am watching ?

void OnPositionEntityAdded(Entity entity, IComponent component)

The component parameter is now always filled with the last component added to the Entity.

Thanks in advance !

**Comment by RvRooijen** [comment]
Alright. I added a type check and now it behaves the way i want :)

```
void OnEntityRemoved(Entity entity, IComponent component)
    {
        if (component.GetType() != typeof(PositionComponent))
            return;

        PositionComponent p = (PositionComponent)component;
        _pool.gridCache.Grid[p.X, p.Y].Remove(entity);
    }
```

**Comment by sschmid** [comment]
Ok cool.
Here's a suggestion for a minor improvement:
```
void OnEntityRemoved(Entity entity, IComponent component)
{
    var pos = component as PositionComponent;
    if (pos != null) {
    _pool.gridCache.Grid[pos.X, pos.Y].Remove(entity);
    }
}
```

**Comment by RvRooijen** [comment]
Thanks!
