### ISSUE TITLE
Walkthrough

### ISSUE THREAD

**Issue by alimoeeny** [sschmid/Entitas-CSharp#152]
Hi Guys,
First of all, thank you very much for creating and sharing Entitas.
Second, I really appreciate all the efforts you put into advancing and fixing bugs and adding features and such, but I think a walkthrough or simple tutorial is very much needed.
You may, rightly, say why don't you do it? if you so much like Entitas, and I'd say I'd love to do it, but I don't understand Entitas well enough to do a tutorial. 
Even if it is just you two creating a project from scratch and just doing a screen capture and talk while doing it, even if it is a simple project like a simple version of one of the demos that will be very helpful. 

Thanks again for Entitas,

**Comment by sschmid** [comment]
Hi, great to hear you get started with Entitas. Good choice ;)
I would really love to do more tutorials and even video tutorials. I really plan to do this someday. Currently, it is very hard for me to find additional time after work or on the weekend and after adding more useful features.
I hope the videos from Unite 2015 and 2016 will already help a little bit. Make sure to checkout the example projects that you can find in the wiki https://github.com/sschmid/Entitas-CSharp/wiki/Example-projects

If you have questions, feel free to add more issues here on GitHub.

**Comment by alimoeeny** [comment]
Looking forward to the tutorials.
