### ISSUE TITLE
How do Pools work in 0.32.0?

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#159]
Congrats on releasing 0.32.0!

I am unclear about what the changes to Pools means for my projects. Can you expand upon what this means?

> * Added new Pools class. There is no static Pools anymore but an instance.
* Added ISetPools to inject the shared pools instance
* Removed pool.CreateSystem<T>() and pool.CreateSystem(Type type) (Apply migration 0.32.0)

It would also be useful to update the docs / example projects to demonstrate the new way of doing things.

**Comment by alimoeeny** [comment]
- If I am not mistaken the first one means you can access your "default" pool as `Pools.pool` from anywhere (it's a singleton)

**Comment by JamesMcMahon** [comment]
Oh so rather then needing to implement `ISetPool` you can just access the pool directly?

**Comment by alimoeeny** [comment]
I believe, in most cases, having only one pool is enough, so the answer is yet. 
my understanding is that you implement `ISetPool` only if you have multiple `Pool`s and you want to control which pool is being accessed by which classes.

**Comment by sschmid** [comment]
The new Pools class fixes a few flaws of the previous version: The Pools class in previous version was a static class with all its drawbacks. It was a hardcoded singleton, you couldn't set your pools manually. The new Pools class is more flexible. You can create multiple instances of it, you can set (or not) your pools as you please. For convenience, there is still a static sharedPools getter to get easy access in other places like MonoBehviours.
It is one step (of more to come) to make work with multiple pools easier. Previously, you only could set one pool with ISetPool. Depending on your design, you might have more than just one pool for a e.g. the core game. Example. Entitas Shmup [GameController.cs](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Scripts/GameController.cs#L47-L48)
```csharp
.Add(new ReactiveSystem(new AnimateOutOfScreenViewSystem(corePool, bulletsPool)))
.Add(new ReactiveSystem(new AnimateDestroyViewSystem(corePool, bulletsPool)))
```
These systems need more than just one pool. Imagine you have even more, like AnimationPool, SoundPool, etc. 
To simplify this, use the new Pools class (it has a reference to all pools like pool.core, pool.animation, ect) and use 'ISetPools' to get this instance.
More convenient and less code to write.

**Comment by JamesMcMahon** [comment]
Sounds interesting. I used a single pool in my game but this looks like it would make it easier to juggle multiple pools.

> You can create multiple instances of it

What would the point be of constructing multiple instances of a pool? Would the different instances share the same content?

Thanks for the answers Simon, and keep up the good work.
