### ISSUE TITLE
[Suggestion]Enum with component IDs

### ISSUE THREAD

**Issue by ivankuzev** [sschmid/Entitas-CSharp#161]
I think it is a good idea to make the [PoolName]ComponentIds static class to contain an enum with all the ids. instead of(or in addition to) the integer constants.with the enum its easier to make an Unity inspector to pick a component to use in the code;
With the current version i have to write 10+ different scripts to look for 10+ components,
or specify the component by the id number in the inspector(not a good idea when components change order)

**Comment by sschmid** [comment]
In the very beginning I tried enums instead of const int. Unfortunately it was slower than plain integers. This is basically the main reason why it's integers now.

**Comment by ivankuzev** [comment]
What about making the CodeGenerator  to output Enum in addition to all the constants? you wont use it anywhere in the system so no performance drawbacks. and it will only be compiled if somebody decides to use it to get the component ids this way.

**Comment by sschmid** [comment]
Does it help using the [componentNames array?](https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Generated/ComponentIds.cs#L24-L36

If not, the code generator is pretty flexible: you can just duplicate the existing `ComponentIndicesGenerator` and change its name and update it to generate enums instead to a different file like ComponentIdEnums or sth like that. It will automatically appear in the Entitas Preferences in Unity for you to select. Would that help you?

**Comment by ivankuzev** [comment]
String array was no good. I went with the other suggested way. Nice extendable generator system.
Had a bump with the ComponentLookupTags function. its somewhere in the core code generator but it is used exclusively by the  ComponentIndicesGenerator same with the filename constant.
Here is my solution. In case anyone wants to use it.
`using System.Collections.Generic;
using System.Linq;
namespace Entitas.CodeGenerator
{
    public class ComponentIndexEnumsGenerator : IPoolCodeGenerator, IComponentCodeGenerator
    {
        public const string DEFAULT_COMPONENT_LOOKUP_TAG = "ComponentIdEnums";
        // Important: This method should be called before Generate(componentInfos)
        // This will generate empty lookups for all pools.
        public CodeGenFile[] Generate(string[] poolNames)
        {
            var emptyInfos = new ComponentInfo[0];
            var generatorName = GetType().FullName;
            return poolNames
                .Select(poolName => poolName.PoolPrefix() + DEFAULT_COMPONENT_LOOKUP_TAG)
                .Select(lookupTag => new CodeGenFile(
                    lookupTag,
                    generateIndicesLookup(lookupTag, emptyInfos),
                    generatorName
                )).ToArray();
        }

        // Important: This method should be called after Generate(poolNames)
        // This will overwrite the empty lookups with the actual content.
        public CodeGenFile[] Generate(ComponentInfo[] componentInfos)
        {
            var orderedComponentInfos = componentInfos.OrderBy(info => info.typeName).ToArray();
            var lookupTagToComponentInfosMap = getLookupTagToComponentInfosMap(orderedComponentInfos);
            var generatorName = GetType().FullName;
         
            return lookupTagToComponentInfosMap
                .Select(kv => new CodeGenFile(
                    kv.Key,
                    generateIndicesLookup(kv.Key, kv.Value.ToArray()),
                    generatorName
                )).ToArray();
        }

        static Dictionary<string, ComponentInfo[]> getLookupTagToComponentInfosMap(ComponentInfo[] componentInfos)
        {
            var currentIndex = 0;

            // order componentInfos by pool count
            var orderedComponentInfoToLookupTagsMap = componentInfos
                .Where(info => info.generateIndex)
                .ToDictionary(info => info, info => ComponentLookupTags(info))
                .OrderByDescending(kv => kv.Value.Length);

            var lookupTagToComponentInfosMap = orderedComponentInfoToLookupTagsMap
                .Aggregate(new Dictionary<string, ComponentInfo[]>(), (map, kv) =>
                {
                    var info = kv.Key;
                    var lookupTags = kv.Value;
                    var componentIsAssignedToMultiplePools = lookupTags.Length > 1;
                    var incrementIndex = false;
                    foreach (var lookupTag in lookupTags)
                    {
                        if (!map.ContainsKey(lookupTag))
                        {
                            map.Add(lookupTag, new ComponentInfo[componentInfos.Length]);
                        }

                        var infos = map[lookupTag];
                        if (componentIsAssignedToMultiplePools)
                        {
                            // Component has multiple lookupTags. Set at current index in all lookups.
                            infos[currentIndex] = info;
                            incrementIndex = true;
                        }
                        else
                        {
                            // Component has only one lookupTag. Insert at next free slot.
                            for (int i = 0; i < infos.Length; i++)
                            {
                                if (infos[i] == null)
                                {
                                    infos[i] = info;
                                    break;
                                }
                            }
                        }
                    }
                    if (incrementIndex)
                    {
                        currentIndex++;
                    }

                    return map;
                });


            foreach (var key in lookupTagToComponentInfosMap.Keys.ToArray())
            {
                var infoList = lookupTagToComponentInfosMap[key].ToList();
                while (infoList.Count != 0)
                {
                    var last = infoList.Count - 1;
                    if (infoList[last] == null)
                    {
                        infoList.RemoveAt(last);
                    }
                    else
                    {
                        break;
                    }
                }
                lookupTagToComponentInfosMap[key] = infoList.ToArray();
            }

            return lookupTagToComponentInfosMap;
        }
        public static string[] ComponentLookupTags(ComponentInfo componentInfo)
        {
            return componentInfo.pools
                .Select(poolName => poolName.PoolPrefix() + DEFAULT_COMPONENT_LOOKUP_TAG)
                .ToArray();
        }

        static string generateIndicesLookup(string lookupTag, ComponentInfo[] componentInfos)
        {
            return addHeader(lookupTag)
                    + addIndices(componentInfos)
                    + addClose();
        }

        static string addHeader(string lookupTag)
        {
            return string.Format("public enum {0} {{\n", lookupTag);
        }

        static string addIndices(ComponentInfo[] componentInfos)
        {
            const string fieldFormat = "    {0} = {1},\n";
            var code = string.Empty;
            for (int i = 0; i < componentInfos.Length; i++)
            {
                var info = componentInfos[i];
                if (info != null)
                {
                    code += string.Format(fieldFormat, info.typeName.RemoveComponentSuffix(), i);
                } else {
                    code += i + "\n";
                }
            }
            return code;
        }


        static string addClose()        {
            return "\n}";
        }
    }
}
`

**Comment by echeg** [comment]
If we use enum as key for dictionary 
http://stackoverflow.com/questions/26280788/dictionary-enum-key-performance

I use 

`public struct MyEnumCOmparer : IEqualityComparer<MyEnum>
{
    public bool Equals(MyEnum x, MyEnum y)
    {
        return x == y;
    }

    public int GetHashCode(MyEnum obj)
    {
        // you need to do some thinking here,
        return (int)obj;
    }
}`

This is much faster and does not cause unboxing
