### ISSUE TITLE
Unloading / Destroying / Stopping Entities Systems Pools 

### ISSUE THREAD

**Issue by alimoeeny** [sschmid/Entitas-CSharp#162]
Imagine an app that has a lobby or menu scene and a game scene, the game scene uses Entitas but the lobby does not (and let's say cannot).  
I need to the systems to re-`Initialize` every time the game scene loads (every time the player goes into the game scene.  
What is the 'correct' way to do this?  
Should just call `Pool.pool.DestroyAll` and also destroy all the systems by looping over them? or is there a more elegant way of winding things down?

**Comment by sschmid** [comment]
There are multiple ways to do this. I think a "correct" answer is strongly depend on which platform (PC or Mobile) your game runs and how powerful your minimum target devices are (again PC or Mobile). Can you give more information?

**Comment by alimoeeny** [comment]
Thanks @sschmid , running on mobile (daydream/cardboad VR), not hugely constrained by resources yet, but as always being efficient is good. the target device is an iPhone 6 or newer (on the android side, our target devices are the latest Nexus and Samsung devices).

**Comment by alimoeeny** [comment]
I am actually more concerned with the order of things, 
I guess I should `DeactivateReactiveSystems` the `ClearReactiveSystems` then the all systems to `null` then `Pools.pool.ClearComponentPools()` and finally `Pools.pool = null` ?

**Comment by sschmid** [comment]
I'll try to answer soon. In the meantime you can read #82, maybe this contains valuable info already.

**Comment by MoritzVossKing** [comment]
I solved this "restart" problem by:

`      
        pool.DestroyAllEntities();
        pool.ResetCreationIndex();
        systems.TearDown();                
`

followed at an appropriate location by

`      
        systems.Initialize();
        //...
`
