### ISSUE TITLE
Rename IDeinitializeSystem

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#164]
I recently added IDeninitializeSystem to do final cleanup before destroying / resetting a system. Basically the opposite of IInitializeSystem.

Deinitialize is not really a word. Any ideas?

**Comment by alimoeeny** [comment]
WindDown, shutdown, halt, CloseAndClean, SunSet, break, destroy, destruct, dismantle, disengage :)

**Comment by cloudjubei** [comment]
ITearDownSystem

**Comment by JuDelCo** [comment]
Shutdown, Destroy and Reset are my favourites

**Comment by sschmid** [comment]
My favorites so far
IResetSystem
ITearDownSystem

**Comment by cloudjubei** [comment]
I generally like the word Reset (dunno why???) but in this context I don't think it works - if you reset something you should be able to use it anew soon. Whereas destroying something obviously has a different implication - I cannot use it anymore. So which behaviour do you want :)?

**Comment by sschmid** [comment]
ITearDownSystem it is then ;)

**Comment by VirtualMaestro** [comment]
IDisposeSystem
