### ISSUE TITLE
[Entitas:] Add pool.DisableEvents()

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#166]
In some cases you want to perform lots of calculations in an algorithm, but you actually don't want to trigger any groups or systems.

Idea:

```
pool.Sleep();

// Do calculations, add / replace / remove components

pool.Resume();
```

While sleeping, no events will be dispatched when creating / changing / destroying entities

Any ideas how I should call these methods?

Sleep, Wake
Pause, Resume
Mute, Unmute

**Comment by JuDelCo** [comment]
.DisableEvents()
.EnableEvents()

(a more verbose choice)

**Comment by sschmid** [comment]
Will close. Not planned anymore.
