### ISSUE TITLE
Rename GroupObserver

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#168]
I found, people often talk about group observer, but they are actually talking about

```csharp
group.OnEntityAdded += ...
```

not the class GroupObserver.

I suggest renaming it to sth like Collector / EntityCollector.

Any other sugestions?

**Comment by DanijelC** [comment]
EntityCollector better describes the intention of class than GroupObserver.

It observes one or more groups and collect entities by GroupEventType/s, so I agree.
