### ISSUE TITLE
Pool attribute name is not very descriptive

### ISSUE THREAD

**Issue by chrischu** [sschmid/Entitas-CSharp#17]
In my opinion the generated attributes that associate a component with a pool is not very descriptive. Imagine I have a pool called "Core", then the attribute will also be called "Core".

I think it would be better to have a PoolAttribute that takes an enum value and those enum values are generated by the code generator.

i.e. instead of having an attribute [Core] it would be an attribute [Pool(Pools.Core)].

**Comment by chrischu** [comment]
I just tried it and realised that enums cannot be partial, so instead of an enum a class with integer ids could be used like this:
    public class PoolIds {
        public const int Core = 1;
    }

**Comment by sschmid** [comment]
Sounds like a good idea! I'll give it a try.

**Comment by sschmid** [comment]
I agree,  [Pool(Pools.Core)] is more descriptive. On the other hand these attributes are used for a very specific case and only in entitas components. It's a little less code to write with the current impl. which is nice, if you're writing this over and over again.
```cs
[Meta, UI, SingleEntity]
public class MyComponent {}
```

**Comment by sschmid** [comment]
If you don't mind, I'd just leave it like it is for now.
