### ISSUE TITLE
Source Control

### ISSUE THREAD

**Issue by alimoeeny** [sschmid/Entitas-CSharp#171]
This is a minor thing,
Is `/Generated` meant to be kept under source control?
I don't see a way around it, and I currently do keep it under source control, but I find it just a bit uncomfortable that `ComponentIds.cs` gets changed all over because of reordering the `ComponenetIds` each time I add or remove a new Component. 

Had nothing better to complain about, and needed my daily does :) 
Just wanted to make sure I am doing it right.

**Comment by sschmid** [comment]
:)
Yes, `Generated` has to be in version control.

... but, when we have the roslyn generator - some day - we could ignore the generated folder.
