### ISSUE TITLE
Clone entity, e.Clone()

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#178]
Provide a method to clone an entity like e.Clone() and make sure both the entity and all components are using the internal object pool to reduce memory allocation.

Suggestion
```csharp
var clone = pool.CreateEntity();

var components = entity.GetComponents();
var indices = entity.GetComponentIndices();

foreach(var index in indices) {
    var component = entity.GetComponent(index);
    var newComponent = clone.CreateComponent(index, component.GetType());
    component.CopyPublicMemberValues(newComponent);
    clone.AddComponent(index, newComponent);
}
```

**Comment by echeg** [comment]
Maybe even add the ability to specify a list of components like 
```
e.Clone(Component[])
or
e.Clone(Component)
```
For example, to create a copy, but not copy something unnecessary. Especially it can be helpful when several people work on the project.

**Comment by JuDelCo** [comment]
It's worth mentioning that a SingleEntity should not be cloned
