### ISSUE TITLE
Repository does not contain VS projects for Entitas.Unity.* projects

### ISSUE THREAD

**Issue by chrischu** [sschmid/Entitas-CSharp#18]
This is particularly problematic if someone wants to contribute to the project and does use Visual Studio instead of MonoDevelop (because then the projects cannot be generated by Unity).

In general I feel it would be better if anyone that forks/checks out the repository could immediately start working with ALL the projects in any given development environment.

Maybe I am just not thinking about all the cases, but I don't think there would even be a big negative side effect with including the VS projects in the repository, right?

**Comment by sschmid** [comment]
The project files are in the [.gitignore](https://github.com/sschmid/Entitas-CSharp/blob/develop/.gitignore#L7) because they are and can be generated by Unity. Unity generates these files every time you select "Assets/Sync MonoDevelop Project"

**Comment by sschmid** [comment]
They will probably be comitted in the next release

**Comment by sschmid** [comment]
Hey, sorry but I'll remove the project files again in the next release. Unity will overwrite them anyway.
