### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by alimoeeny** [sschmid/Entitas-CSharp#181]
One of the big reasons I am so excited about Entitas is being able to actually test my unity code, using a CI service like TravisCI or drone.io or similar. 

May I ask if you can give me some pointers to get started? 
Specifically, 
I imagine I need to mock all the Unity related stuff, like `Time` and `gameObject` and `Debug` and `Camera` and things of that nature. I imagine you've done so already to test your stuff but I cannot find them in the repo, is there another place to look for them? 

Or am I going about it the wrong way?

**Comment by sschmid** [comment]
I write unit tests for the game logic, so basically most of the tests are testing systems. I use [nspec](http://nspec.org) which I run either within the IDE or with [runTests.sh](https://github.com/sschmid/Entitas-Shmup/blob/develop/runTests.sh).
[Entitas Shmup tests](https://github.com/sschmid/Entitas-Shmup/tree/develop/Assets/Tests/Editor)

My systems almost never use any unity stuff. E.g. I try to use [IViewController](https://github.com/sschmid/Entitas-Shmup/tree/develop/Assets/Scripts/View/ViewController) exclusively which are hiding the gameObject. I use my own logging [NLog](https://github.com/sschmid/NLog) which is more flexible than plain Debug.Log which also enables having logs in systems. If you use Debug.Log (or any other unity api) you cannot run the tests like I do anymore.
In the chat we already had a few discussion why that makes sense (running code on a server).

Sometimes I want to test features that actually use unity api. In those cases I use Unity Test Tools, see [EntityLinkTests.cs](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Tests/Editor/Unity/EntityLinkTests.cs)

**Comment by alimoeeny** [comment]
@sschmid what about `Time` ? do you also have a time library like `NLog` ?

**Comment by sschmid** [comment]
I haven't had a project so far that relies on time. All my games are tick-based.

**Comment by alimoeeny** [comment]
So, I must be missing something fundamental here, 
I need to create/initialize my pools for my tests to run, 
when I call `Pools.sharedInstance.SetAllPools();` somewhere Entitas wants to check with Unity to see if `Application.isPlaying`, and I get: 
```
...
Exception executing context: nspec. FLStateMachine test. stateMachine Setup test
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Attempted to access a missing method.
  at (wrapper managed-to-native) UnityEngine.Application:get_isPlaying ()
  at Entitas.Pools.CreatePool (System.String poolName, System.Int32 totalComponents, System.String[] componentNames, System.Type[] componentTypes) [0x00011] in <f71a8dc78d85453eb4d3e86bc895dad1>:0
  at Entitas.Pools.CreatePool () [0x00001] in <f71a8dc78d85453eb4d3e86bc895dad1>:0
  at Entitas.Pools.SetAllPools () [0x00001] in <f71a8dc78d85453eb4d3e86bc895dad1>:0
  at FLStateMachine_test.stateMachine_Setup_test () [0x00006] in <109973244a17496590ea7711e15e974f>:0
...
```
Is there a way to tell Entitas not to look for `Application` or is there way to pretend that that Application is actually running when running headless tests? 

Or am I missing something very important all together?

**Comment by sschmid** [comment]
You'll see `Attempted to access a missing method` every time you're accessing Unity api which cannot work without unity running.

For tests, I create pool manually like this
[TestHelper.cs](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Tests/Editor/TestHelper.cs)
