### ISSUE TITLE
Set arbitrary pool

### ISSUE THREAD

**Issue by DanijelC** [sschmid/Entitas-CSharp#191]
In some cases (scenes) I want just to operate on some pools not all.

The idea is to auto generated method like:
```
 public void SetPools (bool setCore, bool setInput, ... ) { 
     if (setCore) 
           core = CreateCorePool ();
     if (setInput) 
           input = CreateInputPool();
     ...
 }
```
Instead of setting every pool like:
```
Pools.sharedInstanced.core = Pools.CreateCorePool();
Pools.sharedInstanced.input = Pools.CreateInputPool();
...
```

**Comment by sschmid** [comment]
`Pools` is a partial class, so you can basically implement as many methods that make sense for you as you like.
The code generator is very flexible. You can duplicate the existing PoolsGenerator and modify it to your liking and select it in the Entitas Preferences.

**Comment by sschmid** [comment]
I'd suggest you create your own version of PoolsGenerator and make it generate your suggested code
