### ISSUE TITLE
Method name of IStartSystem could lead to conflicts when used on a MonoBehaviour

### ISSUE THREAD

**Issue by chrischu** [sschmid/Entitas-CSharp#20]
In my application it makes sense to manifest some systems in form of a MonoBehaviour on a GameObject (for example when I want to configure them through the editor, like giving them a reference to another GameObject that is relevant to them).

However since the method in IStartSystem is called Start, Unity thinks this method is actually the MonoBehaviour Start method that is used by Unity to initialize stuff. 

Maybe it would be better to rename IStartSystem.Start to IInitializeSystem.Initialize.

Beside from fixing the problem described I also think it would nicely illustrate the distinguish between the Unity Start/Update concepts and the Entitas Initialize/Execute concepts.

**Comment by sschmid** [comment]
Merged :)
