### ISSUE TITLE
I did an Entitas talk at my local meetup

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#200]
https://www.youtube.com/watch?v=jQEXETwgPDs

Excuse any quality problems, this was our first time recording the meetup and we ended up going with the feed I directly recorded on my laptop because it was the best quality.

**Comment by sschmid** [comment]
Great talk! I love it!
Great to see how your systems doing one single thing and comparing it to the Player script.
You seem to fully get the Entitas way :) Turning off systems for debugging rocks!

Keep it up!

**Comment by sschmid** [comment]
I'll create a new section in the readme or wiki to link your talk if you din't mind

**Comment by JamesMcMahon** [comment]
That sounds great, thanks Simon.

**Comment by sschmid** [comment]
Added to the wiki
https://github.com/sschmid/Entitas-CSharp/wiki#video-tutorials
