### ISSUE TITLE
Links to download Entitas not working

### ISSUE THREAD

**Issue by ChaosHelme** [sschmid/Entitas-CSharp#201]
The two links under the section "[Download Entitas](https://github.com/sschmid/Entitas-CSharp#download-entitas)" are not working.

Also I wanted to thank you. I listened to your talk about Entitas at the Games Academy in Berlin yesterday.

For me it always was a bit tricky to apply the common design patterns every software developer knows to a game. Surely everybody knows how important these patterns are for not ending in a big coding mess.
Your talk helped me to connect the last bit I needed to understand how to apply a really good pattern to games development.

**Comment by sschmid** [comment]
Thanks, I updated the links!
I'm glad I could share some useful information with you guys!
