### ISSUE TITLE
[Entitas:] Rename ICleanupSystem

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#202]
We currently have

`IInitializeSystem` -> `ITearDownSystem`

TearDown is the opposite of Initialize. It's supposed to remove components it added or entities it created.

`IExecuteSystem` -> `ICleanupSystem`
Cleanup is supposed to potentially cleanup every frame.

Is there a better word than cleanup? Does Cleanup make sense to you?

**Comment by sschmid** [comment]
Example:
[InputSystem.cs](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Sources/Features/Input/InputSystem.cs)

[GameController.cs](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Scripts/GameController.cs#L38-L39)

**Comment by DanijelC** [comment]
Maybe RecycleSystem, because useless entities are not only cleaned, they are returned back to pool to be reused again.
