### ISSUE TITLE
C# code generation problem

### ISSUE THREAD

**Issue by grumpyoldman1066** [sschmid/Entitas-CSharp#205]
I'm having problems generating code using straight C# and the console utility suggested.

In the autogenerated file pools.cs, 

>public static Pool CreateCorePool() {
>    return CreatePool("Core", CoreComponentIds.TotalComponents, CoreComponentIds.componentNames, CoreComponentIds.componentTypes);
>}

gives the error "CreatePool does not exist in the current context" even though it appears to exist in correct form in the non-generated partial class pool.cs provided with Entitas.

In addition, Component generated code never appears to generate.  Components marked with the [Core] attribute never appear listed in the generated file CoreComponentIds.cs.

**Comment by sschmid** [comment]
I updated the wiki [Install-Entitas-and-first-steps](https://github.com/sschmid/Entitas-CSharp/wiki/Install-Entitas-and-first-steps#first-steps).

I created a simple C# project for you with the code generator already set up.
This should help you getting started.

https://github.com/sschmid/EntitasPure

Have fun! :)

**Comment by sschmid** [comment]
Duplicate #50
