### ISSUE TITLE
Forced location of Blueprints/Blueprint asset

### ISSUE THREAD

**Issue by WoLfulus** [sschmid/Entitas-CSharp#206]
Creating a new Blueprints or Blueprint object (from the context menu) creates the asset on the root (Assets) folder, which is kinda annoying.

From my tests, changing

`[CreateAssetMenu(menuName = "Entitas/Blueprint", fileName = "Assets/New Blueprint.asset")]`

to

`[CreateAssetMenu(menuName = "Entitas/Blueprint", fileName = "New Blueprint.asset")]`

gives a better behavior.

**Comment by sschmid** [comment]
Makes sense. Will be in in a future version. Thanks
