### ISSUE TITLE
Documentation errors in Unity

### ISSUE THREAD

**Issue by oxysoft** [sschmid/Entitas-CSharp#207]
About to try out Entitas and Unity seems to be complaining about the documentation

![](http://i.imgur.com/1WsXUBS.png)

**Comment by sschmid** [comment]
Hi, documentation should not be part of your unity project or source code. Only copy the Entitas sources to Unity. That will fix it.

**Comment by oxysoft** [comment]
np, I kind of had that feeling, it's just that the wiki instructs you to copy the whole content of the zip into your assets folder so perhaps it should be updated for clarity
