### ISSUE TITLE
Method overload for system execute with single entity

### ISSUE THREAD

**Issue by oxysoft** [sschmid/Entitas-CSharp#208]
Currently reading up on Entitas and trying to wrap my head around ECS because it obviously far superior for large projects. It seems like you have to iterate yourself over the entities in all of your systems but it seems redundant to me when it's the case 99% of the time.

Would it be possible to have an overload with a single entity parameter where the iteration is already done behind the scene and it calls Execute for all the entities?

**Comment by KumoKairo** [comment]
The question is not very clear to me. You don't have to iterate over all of the entities, you can track changes and respond only to those you're interested in. What is an overload with a "single entity parameter", can you provide an example?

**Comment by sschmid** [comment]
@oxysoft I think you mean sth like in [RenderPositionSystem](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Sources/Features/Position/RenderPositionSystem.cs)
```csharp
public void Execute(List<Entity> entities) {
    foreach(var e in entities) {
        e.view.controller.position = e.position.value;
    }
}
```
and you don't want to do `foreach(var e in entities)`

As in many other cases, Entitas provides the foundation to work with your data in a way that I think is the fastest way. You can extend Entitas in any way you like, and if it makes sense to you and you're fine with the additional method call, you can create your own system with Execute(Entity e) and use that instead.
You can create your own base system which implements IReactiveSystem and calls a custom Execute(Entity e) for each entity. Other systems would subclass this base system. I personally wouldn't do it, but there's nothing technically that will stop you.
