### ISSUE TITLE
Deleting a component creates big problems

### ISSUE THREAD

**Issue by oxysoft** [sschmid/Entitas-CSharp#209]
When you delete a component, the generated code for that component errors out since it is now referencing a class that doesn't exist, and you are stuck in an endless loop unless you go down the tree and delete all of the generated code related to that class. You cannot simply rerun the code generator either because it seems like it operates on the previously compiled binary.

So is it possible to delete components without creating these issues or is it just a downside that we have to deal with?

**Comment by JuDelCo** [comment]
https://github.com/sschmid/Entitas-CSharp/wiki/Code-Generator

At the bottom of the page, there are a FAQ about those questions

**Comment by oxysoft** [comment]
Ah, I kind of figured there wouldn't really be a good fix for this. Correct me if I'm wrong, but there was some discussion about using Roslyn for the code generator instead of precompiled binaries, I believe it would resolve these issues?

**Comment by sschmid** [comment]
Yes, the planned roslyn code generator will fix these issues.
