### ISSUE TITLE
Event-Listeners Systems

### ISSUE THREAD

**Issue by aqaddoumi** [sschmid/Entitas-CSharp#211]
I'm starting a new project and would like to fix some systems I've used for Clowny Rain, my previous project. One of the major pain points was the event-listener system I've built. I would like to explain how it works and see if we can make it better or maybe replace it all together but provide the same functionality.

This is a long question so bear with me but I think it's a very beneficial system to have in Entitas. It helped me solve a lot my UI problems and I think it can be done more elegantly.

The scenario:
- You have two buttons one for options menu and one for shop menu.
- You press the options button, an OptionsTrigger event is triggered, the two buttons move outside the screen and the options menu appears.
- You press the shop button, a ShopTrigger event is triggered and the two buttons move outside the screen and the Shop menu appears
- Imagine you have dozens of these events and a lot more stuff happening for each event.

What I'm trying to do is create an Enum and assign it to a component, so that when it's added to the pool, some entities which can listen to this event and be retrieved in a system and make each entity do something different.

Here's how I approached it.

Components:
(1) ListenersDictionaryComponent:
A SingleEntity component which is dictionary of dictionaries that can be accessed from anywhere.

``` C#
[SingleEntity]
public class ListenersDictionaryComponent : IComponent {

    public Dictionary <TriggerEnum, Dictionary <string, Entity>> ListenersDictionary =
    new Dictionary <TriggerEnum, Dictionary<string, Entity>>();
}
```

(2) ListenToComponent:
An array added to the entity which has all the triggers the entity wants to listen to.

``` C#
public class ListenToComponent : IComponent {

    public TriggerEnum[] listenTo;
}
```

(3) TriggerComponent:
An enum that's added to a created entity choose the right dictionary from the parent dictionary.

``` C#
public class TriggerComponent : IComponent {

    public TriggerEnum trigger;
}
```

(4) ActiveListenersComponent:
A listeners dictionary chosen from the parent dictionary and added to an entity to trigger different systems.

``` C#
public class ActiveListenersComponent : IComponent {

    public TriggerEnum triggerKey;
    public Dictionary<string, Entity> activeListeners = new Dictionary<string, Entity>();
}
```

The Systems:
(1) CreateListenersDictionarySystem:
This Creates a global single entity with the ListenersDictionary component which is a dictionary of dictionaries.

``` C#
public class CreateListenersDictionarySystem : IInitializeSystem, ISetPool {

    public void Initialize () {
        Dictionary <TriggerEnum, Dictionary <string, Entity>> ListenersDictionary =
        new Dictionary <TriggerEnum, Dictionary<string, Entity>>();

        _pool.CreateEntity()
            .AddListenersDictionary(ListenersDictionary);
    }
}
```

(2) AddListenersToDictionarySystem:
This system loops through each entity with the ListenToComponent array and creates a child dictionary if the TriggerKey is not found in the parent dictionary and then add the entity to the each child dictionary.

``` C#
public class AddListenersToDictionarySystem : IReactiveSystem, ISetPool {

    public TriggerOnEvent trigger { get { return Matcher.AllOf(Matcher.ListenTo).OnEntityAdded(); } }

    public void Execute (List<Entity> entities) {

        foreach (var e in entities) {

            for (int i = 0; i < e.listenTo.listenTo.Length; i++) {

                if (!_pool.listenersDictionary.ListenersDictionary.ContainsKey(e.listenTo.listenTo[i])) {

                    Dictionary <string, Entity> dictionary = new Dictionary<string, Entity>();
                    _pool.listenersDictionary.ListenersDictionary.Add(e.listenTo.listenTo[i], dictionary);
                }

                Dictionary <string, Entity> listener = _pool.listenersDictionary.ListenersDictionary[e.listenTo.listenTo[i]];
                listener.Add(e.name.name, e);
            }
        }
    }
}
```

(3) TriggerActiveListenersSystem:
This system is triggered when a TriggerComponent is added. Then it looks through the Parent dictionary for the key and chooses the right listeners dictionary and adds it into the ActiveListeners component of a new entity.

``` C#
public class TriggerActiveListenersSystem : IReactiveSystem, ISetPool
{
    public TriggerOnEvent trigger { get { return Matcher.AllOf(Matcher.Trigger).OnEntityAdded(); } }

    public void Execute (List<Entity> entities) {

        foreach (var e in entities) {

            Dictionary <string, Entity> activeDic =
                _pool.listenersDictionary.ListenersDictionary[e.trigger.trigger];

            _pool.CreateEntity()
                .AddActiveListeners(e.trigger.trigger, activeDic)
                .IsDestroy(true);
        }
    }
}
```

(4) TriggerOptionsSystem, TriggerShopSystem, etc
I have dozens of systems like this one and they are triggered when the ActiveListeners is added and if it has the same TriggerEnum they want, the code runs.

``` C#
public class TriggerOptionsUiSystem : IReactiveSystem 
{
    public TriggerOnEvent trigger { get { return Matcher.AllOf(Matcher.ActiveListeners, Matcher.Destroy).OnEntityAdded(); } }

    public void Execute (List<Entity> entities) {

        foreach (var e in entities) {

            if (e.hasActiveListeners) {

                if (e.activeListeners.triggerKey == TriggerEnum.OptionsButton) {

                    Entity optionsPanel = e.activeListeners.activeListeners[DataNames.OptionsPanelName];
                    optionsPanel.ReplaceExampleComponent(1)

                    Entity shopButton = e.activeListeners.activeListeners[DataName.ShopButtonName];
                    shopButton.ReplaceExampleComponenet(2)
                }
            }
        }
    }
}
```

These systems work fine but I think there is better way to approach this than I did.
Pros:
- I don't have to create a new component for each event firing.
- It provides a structured way to trigger all events.
- I can access entities directly to make each one listening do something different.
- I think if I did each behaviour in a different system I would end up with even more systems and components.

Cons:
- All system like (4) TriggerOptionsSystem, TriggerShopSystem, etc. fire when an ActiveListener is created, but I only need one so I don't run them through an if statement.
- You have a huge dictionary of dictionary which can be accessed globally.
- Entities are referenced by strings in their name component which I don't know if it's a good idea.
- Any new trigger has to be added to TriggerEnum file.
- Sometimes you forget to add TriggerEmum in each entity ListenTo Component.

Thanks you for reading this far :)

Entitas is great and very straightforward for game logic but I'm still looking for a better approach for the UI. I'm just looking for ideas to make it better and maybe even a totally different way but still achieve the same functionality.

So my questions really is, is this a good way to handle UI events? How can I make it better? or is there a better way that I'm not aware of?

**Comment by T2RKUS** [comment]
In my project what I did is create an event pool with an event component containing a layer:int, type:int and args:object[] variables. and when I create a new event I'd use a helper I made: Event.CreateEvent(0, EventType.OpenLevelUI, null); or something similar. That entity is added to the pool and I'd catch it using the OnEntityCreated callback in my systems. 

From the UI though; when I select my level and click load that UI closes and creates a new event in the event pool which gets picked up by the LoadLevelSystem etc. The UI would call something like: Event.CreateEvent(0, EventType.LoadLevel, "Map/Level1.dat");

At the end of all my other systems I'd run EventCleanupSystem which deletes all the entities in the pool.

**Comment by T2RKUS** [comment]
You could make a UI Manager script that contains references to UI prefabs so that when you call Event.CreateEvent(0, EventType.UI, UI.LevelMenu); The arguments match up to the index on the UI managers list of references and have that spawned up.

**Comment by aqaddoumi** [comment]
So the UI elements behaviour would be in the UI manager and not in Entitas systems?

**Comment by aqaddoumi** [comment]
This actually gave me an idea, I could create an EventPool and on intialization a system loops through each every entity with a ListenTo component then it creates a new entity for every EventTrigger that has listeners to in the EventPool. It adds a component with Dictionary <EventTrigger, Dictionary <StringName, Entity>> then it adds each entity with ListenTo to appropriate entity in the EventPool.

So what I would end up with is a Pools with multiple entities each have its own dictionary with its own listeners and I could access those entities when an event is triggered.

This would solve the huge parent dictionary I had and replace it with a pool.
I can add ListenTo to entities on RunTime.
I can create different event types with different arguments.

It doesn't solve all the systems listening to event from firing and then disabling them through if statements.
It doesn't solve accessing entities by strings which also have to be unique strings.

I don't know. maybe I'm thinking about this all wrong and maybe I shouldn't use a system like this but I can't find another way to achieve that in Entitas other than creating lots of components and systems like in [GitHub](https://github.com/mzaks/Entitas-ReactiveUI).

**Comment by T2RKUS** [comment]
"So the UI elements behaviour would be in the UI manager and not in Entitas systems?"

The UI elements are from the unity view, meaning they are monobehaviours, you just want to get the data from the UI to the systems and vice versa. The event pool tries to solve that problem.

And, I'm glad I could have helped somewhat.

**Comment by aqaddoumi** [comment]
Okay I understand what you're saying now.
Thanks for the help 👍 I'm still trying to figure it out, any ideas are welcome :)

**Comment by GreatVV** [comment]
@aqaddoumi I solved similar problem using UniRx (https://github.com/neuecc/UniRx)

My problem was that I have a long chain-like very specific multi-step scenarios which used the same core gameplay (it's a story-driven painting game for kids)
I will describe my case in more details. I have a simple story. For example You need to paint a chicken, then you need to paint an egg and then you need to put the chicken on the egg.
I have a basic drawing system in entitas. And I need to change pool state one time (e.g. change painting target from chicken to egg). 
So it's just one time operation with very specific data and for me creating system which listen only for one state seemed like a big overhead and it was very time consuming (i tried)
so I just created a unirx sequence with actions listened to specific states and now it looks awesome

I have utility class methods like this:

```` csharp
      public static IObservable<Entity> WaitToPaint(string name)
        {
            return Observable.Create<Entity>(observable =>
            {
                var characters = Pools.painting.GetGroup(PaintingMatcher.Name);
                var targetCharacter = characters.GetEntities().First(x => x.name.Name == name);
                targetCharacter.isCanBeEdited = true;
                Debug.Log("anim: "+targetCharacter.animator.Animator);
                Debug.Log("anim: "+targetCharacter.animator.Animator.name);
                targetCharacter.animator.Animator.SetTrigger(AnimatorConstants.StartdrawingTriggerName);
                Group.GroupChanged changed = (@group, entity, index, component) =>
                {
                    if (entity.name.Name == name)
                    {
                        Debug.LogFormat("{0} had drawn", name);
                        targetCharacter.isCanBeEdited = false;
                        targetCharacter.isEdit = false;
                        observable.OnCompleted();
                    }
                    else
                    {
                        Debug.LogFormat("It's not a {0} ", name);
                    }
                };

                var targetGroup =
                    Pools.painting.GetGroup(Matcher.AllOf(PaintingMatcher.RootCharacterController, PaintingMatcher.Edit,
                        PaintingMatcher.Animator, PaintingMatcher.ControlCamera));
                targetGroup.OnEntityRemoved += changed;

                var feature = PaintingUtility.AddPaintingSystems(Pools.painting, Pools.uI, Pools.storage);
                Debug.LogFormat("Start draw {0}", name);
                observable.OnNext(targetCharacter);

                return Disposable.Create(() =>
                {
                    feature.DeactivateReactiveSystems();
                    targetCharacter.isCanBeEdited = false;
                    targetCharacter.isEdit = false;
                    targetGroup.OnEntityRemoved -= changed;
                });
            });
        }
````

And steps itselfs like this
````csharp
protected override IObservable<Unit> Stage1()
        {
            return Observable.Concat(
                WaitForDrawChicken(),
                Observable.Empty<Unit>().DelayFrame(2),
                WaitForDrawEgg(),
                WaitForDragChickenToEgg(),
                WaitForEggShakeAnimation(),
                EggTapMiniGame()
                );
        }

      
        private IObservable<Unit> WaitForDrawEgg()
        {
            return StoryUtility.WaitToPaint(CharacterNames.Egg).Select(character => character.isEdit = true ).DoOnSubscribe(() =>
            {
                if (Pools.painting.hasEnviromentController && Pools.painting.enviromentController.Controller.Animator){
                    Pools.painting.enviromentController.Controller.Animator.SetTrigger(AnimatorConstants.StageCompleted);
                }
            }).DoOnCompleted(() =>
            {
                var egg = StoryUtility.GetByName(CharacterNames.Egg);
                egg.isDraggable = false;
            }).AsUnitObservable();
        }
````

Sorry for dirty code - it's a first version of code.

Of course, UniRx it's totally different from Entitas and I had some problem with such approach.
But code is still testable (not in this case of course)  and short

**Comment by aqaddoumi** [comment]
I have no experience in UniRX, actually it's the first time I hear about it. I don't think I fully understand your code, I'd have to see how UniRx actually works to fully get it. 

But It seems that if we can a make a parent system with multiple children systems and the parent system can trigger only one system we would get the same effect right? and the children systems can have a state or stages so only one part of it would run until the state changes and it moves to the next one.

I'm understanding this correctly? If yes, a good question would be, how can you make a system triggers only one it's children systems and not the others without creating different components for each system?

Thanks for you're long answer, I will look into it more thoroughly :)
