### ISSUE TITLE
{pool}ComponentIds.cs not right created

### ISSUE THREAD

**Issue by Smartis2812** [sschmid/Entitas-CSharp#212]
Hello,

I'm currently trying to work with the Version 0.35.0 in Unity3D and i came across an issue.

My CodeGenerator.ComponentIndicesGenerator generates incorrect Values for my {Pool}ComponentIds.cs Classes. But my ComponentIds.cs contains everything for adding Components.

Does anyone also has this issue?

My Workaround right now is to replace in the generated Pools.cs, the Pool specific Constants with the Basic ComponentIds ones.

-----------------------

Here my files:

### CoreComponentIds.cs

```
public static class CoreComponentIds {

    public const int TotalComponents = 0;

    public static readonly string[] componentNames = {
    };

    public static readonly System.Type[] componentTypes = {
    };
}
```

### ComponentIds.cs

```
public static class ComponentIds {

    public const int Point = 0;
    public const int Tile = 1;

    public const int TotalComponents = 2;

    public static readonly string[] componentNames = {
        "Point",
        "Tile"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(PointComponent),
        typeof(TileComponent)
    };
}
```

**Comment by sschmid** [comment]
From reading the code it looks like the is no attribute in the components
see https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Sources/Features/Position/PositionComponent.cs#L4

**Comment by sschmid** [comment]
PoolAttributes will tell the code generator in which pools the component should be available. If there is no PoolAttribute it'll end up in the default ComponentIds

**Comment by Smartis2812** [comment]
Of course, Makes sense.

Thanks!
