### ISSUE TITLE
CustomComponentName also for IComponent

### ISSUE THREAD

**Issue by Blucky87** [sschmid/Entitas-CSharp#214]
``` csharp
[Input]
[CustomComponentName("Button1", "Button2", "Button3", "Button4")]
public class JoypadButtonComponent : IComponent {
    public float durationPressed = 0.0f;
}
```

and 

``` csharp
[Input, CustomComponentName("Button1", "Button2", "Button3", "Button4")]
public class JoypadButtonComponent : IComponent {
    public float durationPressed = 0.0f;
}
```

Will only generate code to create a JoypadButtonComponent. According to wiki it should create 4 separate components: Button1Component, Button2Component, Button3Component, and Button4Component all in the Input pool.

Am I doing something wrong? Or is it currently inop?

**Comment by sschmid** [comment]
Hi, currently this Attribute only works for non IComponents, e.g.
```csharp
// This will automatically generate PositionComponent and VelocityComponent for you
[Pool, CustomComponentName("Position", "Velocity")]
public struct IntVector2 { // <-- Not IComponent
  public int x;
  public int y;
}
```
 But I think we can add this also for IComponents. Will tag this as a feature request.

**Comment by sschmid** [comment]
Fyi, I will be back in December, so this will take a while, I'm sorry. If you like you can also dig into the code generator code and do a pull request.

**Comment by sschmid** [comment]
For now, it will only work on non IComponent

**Comment by benzsuankularb** [comment]
@sschmid Currently CustomComponentName is obsoleted but ComponentName.

Can I use ComponentName with IComponent at this time?

**Comment by sschmid** [comment]
@benzsuankularb It only works on non IComponent.
