### ISSUE TITLE
Some game design questions

### ISSUE THREAD

**Issue by zmox** [sschmid/Entitas-CSharp#217]
When My "Model"(Game Logic part)  became very complex, should I Only use Entitas component or Systems?

for example:
  I have a Complex World. which solution is better:
    1.For everyone of World's parameters , I create a component. 
    2.Create World Class holding some world's parameters. and others used by systems should create as component.

I already create a World have many levels and some other features.  and now I want to Refactor code using Entitas. what is the best way to do?

---------------

other question:
How do I create GameSave(Serialization) Systems In Entitas.
such as, How I save my current level data to file and load level data form saved file

**Comment by sschmid** [comment]
Usually I suggest keeping components as small as possible. This can increase the reusability and will result in more fine-grained control for matchers, groups or reactive systems. But of course, this is totally up to you and to whatever makes more sense in your game design. If your WorldClass only contains configuration of the world, which will not be used by other entities or e.g. reactive systems, there is no need to split it up into many smaller components. Think of components as small reusable building blocks. Is your WorldClass made of many little building blocks? Yes? Split it up. No? Keep it as a big class of data and link it as a reference in an other component.

Other question, see #226

**Comment by zmox** [comment]
@sschmid  thank a lot.  I got it
