### ISSUE TITLE
Component with default value

### ISSUE THREAD

**Issue by Arpple** [sschmid/Entitas-CSharp#218]
is there anyway to create component with default value that you can optionally specify value when create
such as
```c#
public class Foo : IComponent
{
    int x = 1;
}

someEntity.AddFoo();  //will have Foo  component with x = 1
someEntity.AddFoo(2);  //will have Foo  component with x = 2
```

**Comment by WoLfulus** [comment]
I thought about this yesterday, but this can't be done right now, at least not this way.
It'll be easier to implement when roslyn branch arrives.

The only way I see this coming without Roslyn is by creating attributes and modifying the code generation templates. Something like:
`[DefaultValue(1)]
public int x;`

**Comment by Blucky87** [comment]
@WoLfulus would it not be possible to just add
 ```csharp
public Entity AddFoo(){
   return AddComponent(BarPoolComponentIds.Foo, CreateComponent<Foo>(BarPoolComponentIds.Foo);
}
```
to a new partial Entity class. Like what is autogenerated?

**Comment by WoLfulus** [comment]
@Blucky87 Yes, but you'll still need to make it manually. To auto-generate method overloads you'll still need access attributes of the field.

I can be wrong though.

We need to hear from @mzaks @sschmid

**Comment by mzaks** [comment]
From my personal experience, I know that there are always a hand full of components which are good candidates for default values or partial default values. However the main accent here is on __handful__ 😉. Adding own implementation for defaults will as @Blucky87 will take a developer a couple of minutes, it is quite a trivial task. Defining an abstraction which can represent defaults and make it work for different types, is a complex task, which makes maintainability of the project more complex.

In my opinion the cost/gain relation is very disproportional.

However as far as I know it is possible to write your own code generator and plug it in. This would be a perfect candidate for own generator, if you really feel like implementing those default methods.

**Comment by sschmid** [comment]
First few thought:

I think this can be achieved without any attributes.
```csharp
public class Foo : IComponent {
    public int x = 1;
}
```
should be enough for the code generator.

But:
```
e.AddFoo();
e.AddFoo(2);
```
doesn't work if you add int y and int z with default values, too.
AddFoo(int x = 1, int y = 2, int z = 3) might be a better solution. This requires a certain order of fields (or a smart way in the generator to rearrange them) given the case below
```csharp
public class Foo : IComponent {
    public int x = 1;
    public int y;
    public int z = 3;
}
```
AddFoo(int x = 1, int y, int z = 3) // will not compile

I'll think about it and about cost/gain as maxim called it ;)

**Comment by sschmid** [comment]
Feel free to re-open, when you think it's important. Unfortunately, for now it's not going to make it in.

**Comment by bit-chimp** [comment]
Is this possible with the new Roslyn plugin?

**Comment by sschmid** [comment]
Unfortunately, this feature request will not be implemented
