### ISSUE TITLE
Component delete issus.

### ISSUE THREAD

**Issue by luochuanyuewu** [sschmid/Entitas-CSharp#220]
I have a component class named "DestoryLine.cs",   public class DestoryLine:IComponent{};
Then i delete this file "DestoryLine.cs", then i delete all generated code and regenerate again. 
this problem is, after i deleted the component file. the generated ComponentIds.cs still has "public const int DestoryLine = 0",  and still generate file named "DestoryLineGeneratedExtension".
Seems like i deleted a component, and the code generator are not aware of this.
Any idea?

... sorry about my English. :)

**Comment by luochuanyuewu** [comment]
So, if i deleted DestoryLineGeneratedExtension.cs, and remove related code about "DestoryLine" in ComponentIds.cs, then i can regenerate code correctly.

**Comment by cloudjubei** [comment]
Yes - you have to remember to remove the generated code (i.e. the {your class name}GeneratedExtension.cs + the const inside ComponentIds.cs)
So far not many people find this process problematic - but if this is really an issue I guess we should think of a solution to make it easier - probably something along the lines of making a MonoDevelop + VisualStudio button/option to delete a component by name.

**Comment by WoLfulus** [comment]
@cloudjubei I find it quite problematic :P so I'm playing with an external generator. It's made only for Unity yet. 

https://github.com/WoLfulus/Spirit

**Comment by luochuanyuewu** [comment]
@WoLfulus 
I have noticed your repo few days ago. but i din't find any information on how to use it. adding a readme or something like that is much appreciated!

**Comment by WoLfulus** [comment]
Sorry about that. I'm moving so it will take a while to get back to PC. I'm still working on it, but I'll be adding a readme ASAP.

**Comment by luochuanyuewu** [comment]
@WoLfulus 
Oh, thanks, glad to hear that.

**Comment by cloudjubei** [comment]
@WoLfulus Once Simon comes back from Australia I think we'll defo have to talk about this :) So if you will have a solution ready - we would definitely look at it!

**Comment by sschmid** [comment]
@luochuanyuewu is it a pure c# project or a unity project? I'm asking, because in a unity project usually deleting the component + the generated code should be enough.
