### ISSUE TITLE
Community Contribution to Documentation 

### ISSUE THREAD

**Issue by alimoeeny** [sschmid/Entitas-CSharp#221]
Hi @sschmid , 
I think there are enough members of the Entitas community that would be happy to contribute to the docs if you create a list of things that needs to be done and let people claim them.
For example, you can start by api docs with an automated tool and ask people to choose files to document, and you can review them and have the automated tool generate the docs. 
Or if you don't think that is effective, create a table of contents for the doc and let people write content under each title and review them before merging. 
I for one would be glad to help.
The lack of docs is a significant barrier to entry in MHO.

**Comment by sschmid** [comment]
Hey, that's a good idea. All classes considered public api already have basic documentation. [Doxygen](http://www.stack.nl/~dimitri/doxygen/) is used to generate the docs found here
- [Entitas.docset.tgz](https://github.com/sschmid/Entitas-CSharp/blob/develop/Build/deploy/Entitas.docset.tgz)
- http://sschmid.github.io/Entitas-CSharp/
- Also available for [Dash](https://kapeli.com/dash)

Run `./Scripts/docs` to regenerate the docs. This will generate the Entitas.docset.tgz and create the ./docs folder which will be shown when opening http://sschmid.github.io/Entitas-CSharp/

**Comment by sschmid** [comment]
I think a step by step guide would also be really helpful. This might go hand in hand with #227 (Video Tutorials)

**Comment by sschmid** [comment]
Will move to #333 and close
