### ISSUE TITLE
Ignore readonly properties on components

### ISSUE THREAD

**Issue by alimoeeny** [sschmid/Entitas-CSharp#224]
Hi @sschmid ,
I have this component, which inherits from a class `parent` which in turn has a readonly property. Something like: 
``` csharp
public class parent {
    public readonly string myId;
    public parent() {
        myId = "some random id";
    } 
}

public class mycomponent:parent {
    public mycomponent():base("some id") {
      // maybe some other initialization
    }
}
```

when Entitas tries to `Generate` the extensions for `mycomponent`, it does not ignore the readonly and does not use the provided constructor, and as a result tried to assign to the readonly properties and of course fails to compile.

**Questions:**
1- Is there a way to fix this? to have entitas use provided constructors and ignore the readonly properties?
2- I need these mycomponent to be part of entitas only because I want them to use my "TickSystem" to control game progress and synchronize entitas systems with these components derived from `parent`. Does that make sense? 

Thanks,
Ali

**Comment by Arpple** [comment]
it's not the same but I think it is similar to my question here #218
you can't do that with current code generator now
but you can do it manually

**Comment by sschmid** [comment]
I could update the the code generator to ignore read-only fields and properties. Would that help?

Could you give a little bit more context about your use case, maybe there are better ways instead of having a parent component.
