### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by Ziboo** [sschmid/Entitas-CSharp#227]
Hello,

Does anyone experimented in Entitas for Unity would be very kind to makes a series of video tutorial ?

I have been looking at the examples projects, but it's a lot to take in.

Would be awesome to follow the dev of a little project done with Entitas.

Thanks

**Comment by sschmid** [comment]
I'd love to do some video tutorials, unfortunately I'm not quite sure when I can spare some time. If anyone makes videos, let me know. I'll link them in the wiki

**Comment by sschmid** [comment]
And of course I'll let all of you know whenever I'll start working on video tutorials

**Comment by sschmid** [comment]
Will move to #333 and close
