### ISSUE TITLE
ITypeDrawer not compatible with Unity Attribute

### ISSUE THREAD

**Issue by zmox** [sschmid/Entitas-CSharp#230]
Entitas can show Component property on inspector by using ITypeDrawer. 
such as, IntTypeDrawer...
but this not compatible with  Unity Attribute very well.
for example:
```
 public class TestComponent : IComponent{
     [Range(1,10)]
     public int value; 
 }
```
the “Range” Attribute will not effect。

So, is there any way to make UnityAttribute Effect?

**Comment by sschmid** [comment]
Try implementing [IComponentDrawer](https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas.Unity/Assets/Entitas/Unity/VisualDebugging/Entity/Editor/IComponentDrawer.cs)

Example:
[AssetComponentDrawer.cs](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Sources/Assets/Editor/AssetComponentDrawer.cs)

A `IComponentDrawer` will be used when matching the component type. This way you can draw your custom editors

**Comment by zmox** [comment]
oh, this is what I want. thanks a lot. @sschmid
