### ISSUE TITLE
GUI Architecture with Entitas

### ISSUE THREAD

**Issue by KumoKairo** [sschmid/Entitas-CSharp#232]
Hi! I've been using Entitas for a bit (since march 2016, made a few relatively simple part time projects with it). Both my examples and the examples from the other people use simple UI system with just several windows and buttons. I remembered your last talk on Unite where you (or your colleague) said that Entitas is a complete replacement of MVC pattern (no need to worry where to put the code, one can't go wrong with that because all the logic is in systems, and mostly I agree with that). But there's a pretty huge and complicated UI system in my current full time project. One thing that still bothers me (and still keeping me from adding Entitas straight into the project via refactoring) is that I don't see a good way of handling complicated UI interaction with Entitas. Usually it's something about adding components like ButtonInput or ScrollStop (something like adding PhysicsInput component to some singleton entity) that is handled by some system. But it's pretty easy to start doing some logic in the UI like checking which component to really add so the right system can kick right in. It will soon start to look like there's really two places with logic - both systems and UI windows themselves. How should one approach this complicated UI environment? 
A few examples to make my question clear:
-any "business clicker" game where the whole game is just a bunch of buttons that one can click (this one is easier though, as every button contains very little logic that can really be placed right inside the button itself)
-something like "hearthstone" where the whole game is just a really huge UI app where a lot of functionality that doesn't really overlaps with playing cards logic per se.
-really any game where there's a lot of nested windows and windows with layout elements.

Maybe you can shed some light on this problem.

And thanks for your work.

**Comment by ophilbinbriscoe** [comment]
I'm about to start on a project that will have some fairly involved UI. Story events that occur as pages with decisions buttons on them, user-driven placement and design of structures, as well as standard management elements for tracking resources and tweaking preferences.

All told, a lot of stuff, and I'm wrestling with some of the same questions as you seem to be.

It's been my experience with pretty much every library / system / architecture / tool that getting things to work as nicely in a large involved project as they do in the "toy examples" is almost impossible. That's not to say that good design is thrown out the window, it just tends to look a bit different or at least have some more layers and moving parts before you get everything playing nice together.

In some cases, it's helped me to shift my perspective a bit on where a given piece fits into the whole. Maybe (almost definitely) there is a way to do all of this "the Entitas way," but if that way isn't apparent to you, then maybe the best approach is to relegate the Entitas model to the region of your application that makes the most sense for your needs. What are Entitas' strengths as a tool for you as a developer working on this project? Where does adhering to its architecture start to become a pain point instead of a win? Find that line and you'll probably be well on your way to having your project structured (at least on a very high level).

I am still in the design phase, but for me, in this project, it seems like Entitas will shine and therefor be the design authority and driving force behind the simulation aspect. As for the heavy UI and procedural geometry aspects, these will certainly consume and provide data from and to that simulation when appropriate, but they will really be their own systems.

I could be inadvertently showing my inexperience with this approach / reply, but it's what makes the most sense to right now. I think it was as much a thought exercise for myself as it was an answer to your question, but there you have it.

Best of luck!

**Comment by T2RKUS** [comment]
The way I do my UI is have the UI coupled to the platform I'm using and have entitas completely decoupled from any one engine so if im using unity i'd use some UI framework asset or Unity UI and just react to the game. So I have something like this:
```
[Occurrence]
public class OccurrenceComponent : IComponent {

    /// <summary>
    /// Layer.
    /// </summary>
    public int Layer;

    /// <summary>
    /// Type. e.g. "System.UI.OpenDialog"
    /// </summary>
    public string Type;

    /// <summary>
    /// Argument(s). 
    /// </summary>
    public object[] Args;
}
```
And execute them like this
```
public class OccurrenceExecuteSystem : ISetPool, IExecuteSystem
{
    Pool _pool;

    public void SetPool(Pool pool)
    {
        _pool = pool;
    }

    public void Execute()
    {
        foreach (var e in _pool.GetEntities())
        {
            if (e.hasOccurrence)
            {
                Occurrence.Signal.CreateOccurrenceSignal(e.occurrence);
            }
        }
    }
}
```

```
public static class Occurrence
    {
        /// <summary>
        /// OnOccurrence Event.
        /// </summary>
        public static event Action<OccurrenceComponent> OnOccurrence;

        /// <summary>
        /// Signal Class.
        /// </summary>
        public static class Signal
        {
            /// <summary>
            /// Create Occurrence Signal Method.
            /// </summary>
            /// <param name="Occurrence">Occurrence.</param>
            public static void CreateOccurrenceSignal(OccurrenceComponent Occurrence)
            {
                if (OnOccurrence != null)
                {
                    OnOccurrence.Invoke(Occurrence);
                }
            }
        }

...
```

which calls a static event on Occurrence class.
that class also has helper methods for creating events as well such as Occurrence.UI.LoadLevelDialog(..);
etc. then from that Unity UI view I then call another event from there and close that dialog. As for cleaning up events I have a system which deletes any lingering events. I could even have a separate component for a timer e.g. timed events and encounters for an rpg or something. These events can also be picked up by mods through a mod interface and other systems to react to. For collecting more than one type of event for a system or cache them as they come then execute them when that its that systems turn.

**Comment by KumoKairo** [comment]
Thanks @ophilbinbriscoe. To answer your question: "What are Entitas' strengths as a tool for you as a developer working on this project? Where does adhering to its architecture start to become a pain point instead of a win?"

I see several advantages in Entitas over our current solution. 
It's (entitas) a lot about amazing separation of concerns and the ability to relatively quickly and painlessly add or remove some features (just delete the feature folder, regenerate and most likely you're already good to go). This quick and easy feature-oriented design is what really attracts me in Entitas. General MVC/MVVM approach tend to add a lot of abstraction layers just for the sake of those layers (in case the functionality will be handy at some point, or just in case this or that will be extended etc.) while ecs maintains the separation and testability without the need of lots of boilerplate code. And as this approach tend to have pretty weak dependencies, those dependencies are still there which is not the case in ecs.
What you did in your answer is just pushed me a bit to looking for a specific solution rather than trying to deal with everything in my head all at once.

@T2RKUS Thank you for the answer, it's rather descriptive. As I can see there's no actual way to deal with it without another layer of concern (which is why I've written this question in the first place).

I consider this an answer:
"Yes, you'll need some other layer of concern that will handle UI interactions differently and actual implementation depends on your project". 

I will let this "issue" hang here for a few more days just in case

**Comment by Elzean** [comment]
It shouldn't matter however you represent your game, same as an MVC pattern. Can be UI or 3d object does not really matter. Everything that show up in Unity is part of your view, It shouldn't hold any game logic, but nothing stop you from hooking you view to Entitas data with a monobehavior.
Entitas will manipulate the data of your game / app and put it in a new state. Once that happen your views react to the data, not necessarily with events, just the fact that data are different is already enough to show something different.
Closing / opening window of UI doesn't change anything to the data of your game, it's usually not important to know if a window is open or not that can just be handle in Unity (the view) and Entitas doesn't need to know about it.
In case pressing a UI button act on the game it's exactly the same as killing an enemy or picking up an object, you can then create a new entity for example (inside a monobehavior) and init it, Entitas will naturally react to that newly existing Entity, Systems will manipulate it and change game data if needs to be.
A game like Eve Online, very heavy on UI, it's just a bunch of window that represent portion of their uge Database, no matter how they design those windows and how they are nested. Again you shouldn't make a difference between a UI and 3d object, you can always represent your game character as a window with a bunch of info (position, health, name etc) and a button for each of his actions (attack, run, jump...) it's the same :p

**Comment by JuDelCo** [comment]
Why the thumbs down? @KumoKairo

**Comment by KumoKairo** [comment]
It's a pretty useless answer. General things that are known and are pretty easy to explain with abstract things, but which are not really applicable to a real project as-is (tell me that). Most likely @Elzean didn't even fully read my question or any of the answers, though I bet he will try to prove the opposite (I can guarantee it).

**Comment by Elzean** [comment]
Hmm, i didnt mean to give you a "useless" answer. From your question i felt like you just needed direction on how to handle the UI with Entitas, my point was that it's no different than other element of your Application / Game. I was trying to help, no need to sound so negative :p

So from your previous message i guess you want something a bit more concrete.

There is various ways to implement UI, in my project i have an ApplicationStateComponent. The UI listen for a "stateChanged" from it. Depending on the result the UI will show something different. When clicking a button i generate "CommandComponents" that are catch by an Entitas ReactiveSystem and handle the command that was ask by the UI (but the command itself could be generate from something else too). The system change the data, for example right now it fetch data of the player from the server and fill the information. Again UI simply react to the change and display the information.

For other smaller UI interaction that happen within a state and doesnt act on the data of the game this is handle within the UI, like close/open a nested window, change tab etc.

Sorry if this still doesn't help you, i read your question but i probably don't get it (which is kind of worse XD).
