### ISSUE TITLE
[Entitas:] Add mechanism to filter entities based on component values in a reactive system

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#234]
This issue attempts to provide a solution for #165 
History:
PR #189 added filter condition to matchers
After implementing a solution I removed it in a future version, see #190 
> [...] It's very convenient, but it has an overall negative effect on performance [...]

Suggestion:
Add a new interface, e.g. `IFilterEntities` which can be implemented by reactive systems

**Comment by sschmid** [comment]
Hi, I added [IFilterEntities ](https://github.com/sschmid/Entitas-CSharp/blob/feature/%23234-filter-entities/Entitas/Entitas/Interfaces/IReactiveSystem.cs#L53-L55)

Initially, this should enable us to filter entites based on component values, e.g.
```csharp
public class KillSystem : IReactiveSystem, IFilterEntities {

    public TriggerOnEvent trigger { get { return CoreMatcher.Health.OnEntityAdded(); } }

    public bool filter(Entity entity) {
        return entity.health.value <= 0;
    }

    public void Execute(List<Entity> entities) {
        foreach(var e in entities) {
            // no need to check for health here anymore, yay
            e.flagDestroy = true;
        }
    }
}
```

Basically, `IFilterEntities` can now potentially replace the other existing interfaces `IEnsureComponents` and `IExcludeComponents`, since we can now express that in one simple `filter(entity)` method. This will also simplify the internal implementation of ReactiveSystem since we only have to check on single method now.

I'm thinking of deprecating `IEnsureComponents` and `IExcludeComponents` in favour of `IFilterEntities`.

What do you guys think?

**Comment by MoritzVossKing** [comment]
If this O(n) filter implementation scales equally well as IEnsureComponents did, sure!

In a recent gamejam project, I actually had to create an "Impassible" negative entity because IEnsureComponents couldn't reliably filter based on some external rules (a boolean array containing a collision map).
