### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by JRSerjeant** [sschmid/Entitas-CSharp#236]
Hello All, 

I have been looking at Entitas for my next Unity Project. It looks great so far I can really see how it can utilised in my project. I'm getting my head around the concepts and how things all tie together. 

However, I have been looking at the available examples and information in the wiki to setup a simple test project. I'm trying to create System to load prefab  a into the Unity scene then from there I have a base to create more components and systems. 

The issue is that all the examples seems to approach this in a different way and this is causing confusion. 

Is anyone of the examples considered best practice or does anyone have a simple example?

A couple of simple "Hello World" style examples with instructions would be very useful to get started. 

Thanks 

J

**Comment by Zammy** [comment]
Have you checked this page https://github.com/sschmid/Entitas-CSharp/wiki/Games-and-Examples?

**Comment by JRSerjeant** [comment]
@Zammy Yes these are the examples I'm referring to. I have read almost all of the wiki at this point.

**Comment by JRSerjeant** [comment]
After a bit more hacking on my lunch today I have managed to get what I wanted working.

I will try and find time this weekend to tidy up the project and post it to GitHub with some comments/instructions.

**Comment by JRSerjeant** [comment]
Evening All, I have uploaded my basic example to [here](https://github.com/JRSerjeant/Entitas-MostBasicGameObject). I will add more explanation as comments in the code and in the Git ReadMe soon. 

But some feedback on what I have implemented would be great. What about this is and is not considered to be good practice?

As a learning exercise I'm hoping to set up a few different examples to show the basic building blocks required for Entitas.

**Comment by JRSerjeant** [comment]
Hello Again all, 

I have updated the [example projects Wiki](https://github.com/JRSerjeant/Entitas-MostBasicGameObject/wiki) to provide some explanation. Any feedback would be great. 

Next I'm going to add some comments into the code for those that don't find the Wiki. Once done I'll move onto another example. I'm thinking moving the game object will be a nice next example. But if anyone has any idea for examples please let me know.

**Comment by sschmid** [comment]
On a related note

@FNGgames was kind enough to also provide a step by step Hello World Tutorial
[Wiki - Unity-Tutorial-Hello-World](https://github.com/sschmid/Entitas-CSharp/wiki/Unity-Tutorial-Hello-World)

Also feel free to update the Wiki with your Tutorial (ref #333)
