### ISSUE TITLE
Separate Index/Array for SingleEntity Components

### ISSUE THREAD

**Issue by mzaks** [sschmid/Entitas-CSharp#238]
This issue is slightly related to https://github.com/sschmid/Entitas-CSharp/issues/112
An entity stores components in an array. As SingleEntity component is stored only in one entity, it is wasteful to have a space for them in Entity component array. Instead we could have separate array for SingleEntity components, which would contain the component and the reference to the entity which is associated with this component. This way we can keep the API:

```
e.AddResources(resources);
```

Internally however it would not store the resources in the entities component array.

This improvement would reduce entity memory size.

**Comment by sschmid** [comment]
Currently, SingleEntity is just enforced by the generated code. You can still manually add a component that is market with [SingleEntity] to as many entities you like.

Until now [SingleEntity] was considered api sugar, so the question is should we actually enforce this by entitas. Otherwise we cannot get rid of the slot in the array

**Comment by mzaks** [comment]
We do throw `GroupSingleEntityException` when we ask for single entity and find two entities in the pool. It would be much better if we would already throw when we add the component so that we know where the bug is.

**Comment by mzaks** [comment]
Here is a Sketch of what we would need to have to implement it.

First we need an interface for unique component:

```csharp
interface IUniqueComponent {}
```

than we need a simple tuple which represents association of Component and an Entity.

```csharp
class ComponentEntityAssociaton {
  public IUniqueComponent component;
  public Entity entity;
}
```

Than we need a `IUniqueComponentLookup`. 
```csharp
interface IUniqueComponentLookup {
  public ComponentEntityAssociaton Get(int uniqueComponentId);
  public void Add(int uniqueComponentId, Component, Entity entity);
  public void Remove(int uniqueComponentId);
}
```

This interface should be implemented by `Context`. `Entity` class should have a reference to instance of such interface and we need to add  methods for `Get-`, `Add-`, `Remove-`, `Replace-`, `HasUniqueComponent`.

Than the Code Generator should generate separate component index for unique and non unique components. And finally we need to change the code generator to use described facilities.

The good news is, it can be non braking change for the users. As the generated public API can stay the same. It reduces the footprint of an entity and it let us throw an exception not when we asking for a unique component/entity but when we breaking the rule of uniqueness.

Bad news, it is a lot of work :)

**Comment by mzaks** [comment]
In my previous comment I forgot about one more thing - the matcher. They also has to be separated for unique components.

And second consideration. If we already separating the indexes and trying to make Entitas more memory efficient. It would be also good if we separate the flag components. Flag components do not has to be stored in components array as well. We could have a flag buffer where every flag component is just a bit field.

**Comment by FNGgames** [comment]
Was this closed because the suggestion was implemented? Or because it is no longer being thought about?

**Comment by sschmid** [comment]
Hi, no, it's not implemented. I talked to Maxim a few times, but I never felt like implementing it. There always seem to be tasks with a higher prio, so I probably will never do it, and since it's over a year old, I just closed it. I hesitate to introduce more complexity... things like e.GetComponents() and other areas have to be updated, but I don't think it's a problem right now.

**Comment by FNGgames** [comment]
Fair enough. It's one of those niggles that doesn't really affect how you use entitas much, so we can certainly live without it.
