### ISSUE TITLE
Remove IMatcher and use lambda instead

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#239]
`pool.GetGroup(Matcher.Health)` can also be expressed with
`pool.GetGroup(e => e.hasHealth)`

At the same time using a lambda expression makes it more flexible, too.
`pool.GetGroup(e => e.hasHealth && e.health.value > 0)`

This will kind of address #189

**Comment by sschmid** [comment]
Pools.cs
```csharp
        readonly Dictionary<IMatcher, Group> _groups =
            new Dictionary<IMatcher, Group>();
```

For the sake of reusing existing groups, that might not be a good idea.
Currently we can retrieve existing groups by comparing the matcher

**Comment by sschmid** [comment]
Creating new classes (like Nodes in Ash) could help, but who wants to write more classes... 👎

**Comment by Noshire** [comment]
Despite this being closed, I think it's definitely worth some further investigation.
I'm by no means experienced with how delegates and lambdas work under the hood exactly, but I found a few threads about caching lambda expressions, for example:
[Creating, combining and caching lambda expressions](http://stackoverflow.com/questions/23862302/creating-combining-and-caching-lambda-expressions)

Optimally we'd have the best of both worlds - auto-generated matchers to check for the existence for each component, as well as the ability to use lambdas (which may or may not get cached) to do finer checks.

In the end, though, don't sweat it - it's perfectly fine to retrieve components and filter them in a second pass manually.

**Comment by bddckr** [comment]
I agree with @Noshire. Entitas already handles "saving" lambdas: `EntityIndex` does it by referencing them by a name.
