### ISSUE TITLE
Does not correctly generate component when a member type is changed

### ISSUE THREAD

**Issue by Zammy** [sschmid/Entitas-CSharp#241]
Using Entitas 0.35.0 on Mac OS X 10.11.6 with Unity 5.5.0.

Steps:
*Create a component with a member
*Generate code for component
*Change member type
*Generate code for component

Expected (at least for me):
*To change the type on the field in generated code

Result:
*Does not change the type of generated code for component

Deleting the generated folder seems to solve the problem but it is annoying.

**Comment by sschmid** [comment]
If you change the member type the generated code will have compiler errors. You cannot regenerate while having compile errors.
But I have to check if this guard still works with Unity 5.5. Haven't tried yet. But sounds like it just regenerates based on the previous dll which includes the component with the old member type...

**Comment by sschmid** [comment]
I just check with Unity 5.5, the guard still works
```
Exception: Cannot generate because Unity is still compiling. Please wait...
```

When you change the member type your project most likely has compiler errors. This prevents the current code generator from regenerating (based on reflection and generates based on the last compiled dll). Unfortunately, you have to manually fix the compile errors in the generated code first. I usually just delete the affected lines and regenerate.

We're currently working on an alternative code generator to fix this issue.
