### ISSUE TITLE
Entitas tutorials

### ISSUE THREAD

**Issue by jony100200** [sschmid/Entitas-CSharp#246]
No tutorial on how to set it up. It is very confusing to use Entitas. Thanks for making it public btw.

**Comment by sschmid** [comment]
Currently I don't have time to do this. I'd love to do more tutorials as soon as I can find the time. I'm currently focusing on releasing the next version of Entitas which comes with lots of improvements. I hope that once I'm done with that I can make some tutorials.

In the meantime check out the [example projects](https://github.com/sschmid/Entitas-CSharp/wiki/Example-projects) and make sure you watched the [presentations](https://github.com/sschmid/Entitas-CSharp/wiki#video-tutorials)


Are you using Unity?

Look at the [GameController](https://github.com/sschmid/Match-One/blob/master/Assets/Scripts/GameController.cs) which contains all the logic you need to set Entitas up.

It's basically just creating a new pool and the list of systems. That's pretty much all you need to get started.

I hope that helps.

**Comment by JRSerjeant** [comment]
@jony100200 
Although I'm no expert and still learning myself I step up [this project](https://github.com/JRSerjeant/Entitas-MostBasicGameObject) in a attempt to show the basic structure of an Entitas Unity project. 

Check the wiki for some [explanation](https://github.com/JRSerjeant/Entitas-MostBasicGameObject/wiki)

Hope it helps and I welcome any feedback.

**Comment by T2RKUS** [comment]
I don't suppose there is much point making new Entitas tutorials right now being as a new (major) version of Entitas is just around the corner.

**Comment by JRSerjeant** [comment]
@T2RKUS  True, I'll update my example once the new version is released.

**Comment by sschmid** [comment]
@JRSerjeant I'll try to wrap up performance tests with the new version tomorrow. If there aren't any major performance draw backs with the generic type-safe version I will continue updating the code generator and visual debugging. If we're going this way this will be a major breaking change. It will also contain multiple other breaking changes that are recently made (no IEnsure, IExclude, etc). I hope I will be done within the next 2 weeks.
I try to post a sneak peek tomorrow of what the code could look like to get some early feedback.

**Comment by JuDelCo** [comment]
Sooo, I think the next thing to do is update the wiki with all the new changes in 0.36, right now without examples may be a bit difficult to start to play with

**Comment by sschmid** [comment]
@JuDelCo That is true. My current roadmap is to ship the in-between version before the type-safety / DSL version (see 0.36.0). Once the type-safety version is out and I upgraded my production codebase to prove that it works, there should be a wiki rewrite

**Comment by sschmid** [comment]
... with tutorials and FAQs ;)

**Comment by alimoeeny** [comment]
@sschmid does this mean we should not upgrade an wait?

**Comment by sschmid** [comment]
@alimoeeny I think you can wait
