### ISSUE TITLE
Entitas + package management

### ISSUE THREAD

**Issue by ophilbinbriscoe** [sschmid/Entitas-CSharp#249]
I have been working a bit with Node.js, and have been astounded by how quickly I can get things done by simply installing packages using npm and adding simple hooks to get things running.

Looking at many of the example projects, similar patterns seem to arise (sometimes verbatim). This seems to be especially true for Components + Systems responsible for interfacing with external behaviors (ex: input handling, creating / updating view objects, UI, etc.). I have also seen some neat features showcased at Unite or other talks (ex: journaling, time-travel, turn-based execution, etc.) that are fairly unopinionated and would be easy to use as a jumping-off point for many different applications.

Being able to package these and efficiently distribute + re-use them not only saves time, but helps to ensure that everyone is using a well-deigned, well-tested, and up-to-date solution to a given design problem. Not to mention that it could further lower the barrier to entry for newer developers.

For the time being I'm curious to know what thoughts of the authors and frequent users of Entitas are on this subject. Would any new code be required, or would it simply be a matter of getting the ecosystem off the ground?

The Asset Store has a dependency and update system, IIRC, so perhaps an Entitas package could simply be an asset. Removing an installed package from a project tends to be a bit messy, though, and there may be other considerations vis-a-vis generated code, etc.. Perhaps a bit of code to extend Entitas and the Unity editor to allow efficient finding, installing, updating, and uninstalling of packages.

Once the .dll version is out and the API becomes less prone to breaking changes (not complaining!) this is something that I could investigate in earnest. My workload is quite heavy until May, anyway.

**Comment by T2RKUS** [comment]
That sounds very useful, I've also used node.js before as well and love the package manager. It would be cool if it Entitas had one as well or used a pre-existing one out there.

**Comment by sschmid** [comment]
@ophilbinbriscoe Deep down on my to-do list I have this task :) I think it would be a very convenient thing to just click a button and Entitas updates itself. Personally, I love using package managers. Looking at my current work load and planned tasks, I probably won't be able to implement sth like this anytime soon. It's on my list, but the prio is very low. But I'm happy to discuss pull requests ;)

**Comment by sschmid** [comment]
I'm happy to accept PR ;)

**Comment by sschmid** [comment]
With the changes from #244 we just got one step closer...

**Comment by sschmid** [comment]
Duplicate #52
