### ISSUE TITLE
[Entitas:] New ReactiveSystem to process only one entity

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#251]
The current ReactiveSystem passes in a list of entities and you probably end up writing code like this
```csharp
public override void Execute(List<Entity> entities) {
    foreach(var e in entities) {
        // Do sth
    }
}
```

The idea of having another ReactiveSystem like the following came up again
```csharp
public override void Execute(Entity entity) {
    // Do sth
}
```

Any thoughts? Would you use that?

**Comment by JuDelCo** [comment]
Will do the second example execute the method for each entity anyway? If so, it's fine for me, but optional, not as a replacement (because the List is useful in some cases, count, or store it in somewhere)

**Comment by edgar1SI** [comment]
I would definitely use that all the time. In fact, it was something I was wondering why it didn't exist before, since there are many cases where you know you have a ReactiveSystem that reacts to a SingleEntity. Of course, it would be cool to keep both options available 👍

**Comment by sschmid** [comment]
@JuDelCo It would be an addition, not a replacement. The list approach is the most flexible and fits well with the Entitas idea of aggregation. The other approach on the other is a veeery common use-case I guess.

**Comment by pderuiter77** [comment]
If you make the method with the foreach virtual, we have the choice of overriding that if needed, or just use the Execute(Entity) if that suffices

**Comment by sschmid** [comment]
@pderuiter77  Yes, but this would mean you can override both methods, which can lead to confusion plus in a normal case you always have the overhead of a method call.

**Comment by pderuiter77** [comment]
You do have the DoExecute(entity) call. personally i would have had that call anyways :)
If you make it abstract it's clear what you must do.

**Comment by parandice** [comment]
In my understood, Execute(entities) in ReactiveSystem is enough and correct to the Entitas idea.
When I use ReactiveSystem, I don't care about what each entity in entities is. They are just matched to trigger. ReactiveSystem processing them. That's all.
But If there are Execute(entity) in ReactiveSystem, I should care about entity and trigger.
If there are plural entities matched to trigger, what is the one for execute? First one?
If so, how to processing other entities?
If use for SingleEntity only with other name that is not just ReactiveSystem, that's simple to understand.

**Comment by parandice** [comment]
In my understood, Execute(entities) in ReactiveSystem is enough and correct to the Entitas idea.
When I use ReactiveSystem, I don't care about what each entity in entities is. They are just matched to trigger. ReactiveSystem processing them. That's all.
But If there are Execute(entity) in ReactiveSystem, I should care about entity and trigger.
If there are plural entities matched to trigger, what is the one for execute? First one?
If so, how to processing other entities?
If use for SingleEntity only with other name that is not just ReactiveSystem, that's simple to understand.

**Comment by boscohyun** [comment]
In my understood, Execute(entities) in ReactiveSystem is enough and correct to the Entitas idea.
When I use ReactiveSystem, I don't care about what each entity in entities is. They are just matched to trigger. ReactiveSystem processing them. That's all.
But If there are Execute(entity) in ReactiveSystem, I should care about entity and trigger.
If there are plural entities matched to trigger, what is the one for execute? First one?
If so, how to processing other entities?
If use for SingleEntity only with other name that is not just ReactiveSystem, that's simple to understand.

**Comment by VirtualMaestro** [comment]
Don't forget that adding new API also brings complexity. Is new API really valuable or it is only a sugar?

**Comment by FNGgames** [comment]
Could it be a separate system altogether (e.g. SingleEntityReactiveSystem)? Rather than being mixed in with the current RS.

**Comment by sschmid** [comment]
It would be a separat system. Another reason to add this new system is performance. Currently you iterate once to filter, than you iterate to execute. With a single entity system we could save 1x iteration which might be noticeable when having thousands of systems.

**Comment by sschmid** [comment]
Won't happen for now... will close
