### ISSUE TITLE
[Entitas:] Add e.Destroy() and remove context.DestroyEntity()

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#254]
This is the way you have to destroy entities currently:
```csharp
context.DestroyEntity(entity);
```

It's more convenient to write
```csharp
entity.Destroy();
```

I always try that the entity doesn't know its context and doesn't have a reference to it.
@mzaks idea is that `entity.Destroy();` dispatches an event and the context subscribes to it and cleans up.

**Comment by JuDelCo** [comment]
Good idea !

**Comment by T2RKUS** [comment]
The new term 'Context' is starting catch onto me as well, actually im starting to prefer it to pool now when I think about the types of 'contexts' I want to use entities for. e.g. The terrain context (to handle all terrain entities/behaviour), DynamicObject Context (e.g. for NPC, Items, Players, monsters, things that exist on the terrain)... starting to make more sense.
