### ISSUE TITLE
A possible solution to compilation errors leading to hell

### ISSUE THREAD

**Issue by bwohaha** [sschmid/Entitas-CSharp#256]
Hey there, guys!
First of all, I want to say that I really appreciate the work you do.
Despite more than 6 years of experience with Unity and more than 10 at coding and making games, I'm rather new to Entitas and ECS. I still have much to figure out, but I'm already fascinated by it enough to use it in my home indie-games attempts. Mostly thanks to your awesome Unite presentations. If it wasn't for them, I don't think I would go for it: ECS seems weird in a lot of ways and not really applicable to bigger projects from where I'm at right now. I hope my views will change as I progress.
I'll try to do my part, as test-driven development is where I put all of my free time to and this new way of programming seems to hold a lot of promise.

My main issue with Entitas so far seems to be compilation hell after code generation. I'm used to first dive right in without reading much documentation, so after an hour or so of trying to imitate your example projects I have found myself lost when I figured out I didn't understand what got generated, how it got generated and how come trying to regenerate it seems to give me the same code with the same errors even after I've fixed the differences between my attempts and your examples. After reading though your wiki, I saw what things are required for generation and (my biggest foe) that you need everything to compile correctly before you can generate code.

Two days in, that last bit seems rather frustrating so far. I know I can get used to writing components without errors as they are very simple and understandable and my code generation will work fine at least 90% of the time, but the idea of refactoring it at some point in the future: deleting some of them, renaming, etc kinda scares me.

I saw that you are working on different approaches at code generation: you have Roslyn based code generator, for example. I didn't try it yet since it seems to be a year old and I didn't find any documenation on how to integrate it, so I've decided against it for now. I believe you've decided against integrating it into entitas due to it not working on platforms other than Windows.
I also saw that you are working on an alternative solution to this problem, although I believe it is far from ready at this point.
Am I right about all of this, or do you have a solution for this problem already, and I've just missed it? If so, please, let me know.

Anyways, just in case, I thought a little bit about the whole thing and then this idea hit me: what if we made another assembly just for code generation? Let me explain.
For code generation you need:
1) the component files and the data classes inside of them that (if I undestood ECS correctly) cannot be systems, pools or anything else, but raw data;
2) also you need the Entitas settings: pools, etc,- but those, I believe, should work fine even with compilation errors in unity project.

So basically, you can create another manual assembly before code generation that only includes files with "magical" names in the project like "<ComponentName>Component" and <ComponentDataName>Data. In other words, we make a naming convention for everything that is required for code generation so that we can manually create another assembly before code generation and then code generate based on that assembly only.
This way we can make sure that the probability of compilation errors is minimal and your ability to fix those compilation errors is huge.

The idea seems simple enough to work out of the box on any platform without changing much in your code generator. What do you think?

Of course, if you already have another solution in the works or maybe even up and working, I'm all ears. Otherwise, this might be a good workaround for the moment as this compile hell seems rather frustrating to me.

Regards,
Eugene.

**Comment by sschmid** [comment]
Hi Eugene, great to hear that you're giving Entitas a try. I always try to make working with Entities fun and seamless. The current code generator is our biggest complaint atm and we are well aware of that. After researching and prototyping different alternatives to fix that issue we finally made some really good progress. I plan to test our next-gen code generator this week, maybe even on a big project I'm working on. The solution we're striving or is our custom DSL. it will look sth like this:
```
comp Position in Core
    x: float
    y: float
    z: float

comp Resources unique in Meta
    coins: int
    gems: int
```

Based on the DSL we can generate code at any time, no matter if your game compiles or not. But there is way more than just that, I think the DSL has much potential and we can have really cool features in the future. We're also trying to generate systems and blueprints for you. It is really promising :) As I said, I plan to test all this this week and let all of you guys know about the results.

**Comment by JuDelCo** [comment]
The only concern maybe will be that the generated code from the DSL won't update your code using that generated code, so when you need to refactor something you will need to change the DSL and your code as well. Maybe i am wrong.

**Comment by T2RKUS** [comment]
I also want to know whether I can change the DSL code templates to fit into my code base better. e.g. rather than a pools/contexts class being generated I want to create them through a different method like service attached to di container.

**Comment by sschmid** [comment]
@JuDelCo true

**Comment by sschmid** [comment]
@T2RKUS That sound like a good feature. Entitas will always ship with the current default code generator, so it will be easy to implement custom generators.

**Comment by sschmid** [comment]
@T2RKUS with #265 you will be able to generate exactly what you need
