### ISSUE TITLE
Does entitas has a forum or at least a thread somewhere?

### ISSUE THREAD

**Issue by bwohaha** [sschmid/Entitas-CSharp#258]
Hey, guys.

Long story short - we need a place where we can share experience with each other to solidify the community: at the very least a thread for common dumb questions(F.A.Q.) and a thread to talk about specifics. Preferably a forum. If you have one, then, please, send me the link and/or put it in the noticable place(because if there is one, I couldn't find it through google or by looking through this git).

And now for the reasons as to why.
Yesterday I was finally able to write something that should've worked, but for some reason it didn't.
I wanted to ask someone a quick question or google on it, but found no forum or, quite frankly, anything on Entitas.

I'd prefer not to write to you about trivial and probably common matters(as what I encountered was completely game breaking, so I believe it should be due to a stupid mistake on my part somewhere). But at the same time I feel pressured to write to you about it, since there is no one else I can discuss this framework with.
If you don't want to drown in common and stupid questions, we(the people, who are trying to and working with entitas) need a place to communicate and ways to find each other.

Regards,
Eugene.

**Comment by bddckr** [comment]
We're all on Gitter, like the little badge on the Readme says :)
<a href="https://gitter.im/sschmid/Entitas-CSharp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge">
        <img src="https://img.shields.io/badge/chat-on%20gitter-brightgreen.svg" alt="Join the chat at https://gitter.im/sschmid/Entitas-CSharp"></a>

**Comment by bwohaha** [comment]
Oh! Great to know! Thanks.
