### ISSUE TITLE
How to make prefabs link to blueprints?

### ISSUE THREAD

**Issue by shophk** [sschmid/Entitas-CSharp#263]
I'm looking at the Entities-Shump-master sample projects.

I'm trying to load new prefabs into a blueprint. How do I do this?

After I create a blueprint, I switch to core, add components asset. 
![screen shot 2017-01-17 at 4 14 05 pm](https://cloud.githubusercontent.com/assets/15017456/22012629/0b4968e4-dcd0-11e6-80b3-44db1ba3530c.png)

In this screenshot, I added another prefab name Enemy1. How to I get this Enemy1 on the list in the previous screenshot?
![screen shot 2017-01-17 at 4 14 25 pm](https://cloud.githubusercontent.com/assets/15017456/22012689/6323a6c4-dcd0-11e6-9593-337a10127864.png)

**Comment by sschmid** [comment]
This file [Res.cs](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Sources/Assets/Res.cs) contains all available resource names. Usually I have a mechanism to generate them (either from resources or asset bundles). This is just a simple example, so I didn't provide the generator to generate this file. You can manually add them if you want, but for a proper game I suggest you have a different workflow and use asset bundles. For demo purposes I added [AssetComponentDrawer.cs](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Sources/Assets/Editor/AssetComponentDrawer.cs) to showcase, that you can render components as you want. This custom drawer inspects the Res.cs file and renders a dropdown with the contents.

**Comment by sschmid** [comment]
I could think of an AssetDrawer that inspects asset bundles or folders and also validates the names (in case you rename or move an asset)
