### ISSUE TITLE
[CodeGenerator:] More flexible architecture

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#265]
# Goal:
- simplify unit testing
- have modules for every feature
- enable simple extension
- enable simple integration for other types of parsers / data providers (json, ECSLang, etc)

# Suggestion:
Divide the whole generation process in 3 parts:

### Step 1: Input --> Model
Turn given input (e.g. *.cs, *.ecs, *.json files, etc) into an abstract model. Implementations of `ICodeGeneratorDataProvider ` emit `CodeGeneratorData` to build up the model by using reflection or parsing or any other technique. DataProviders should be really small and should just do one thing, e.g. provide `ComponentName` or `ContextNames` or `PublicMemberInfos`. This way every aspect of Step 1 can be unit tested easily. Future features can be added without modifying the existing code 👍 
The model is dynamic and new features can be added by any developer without modifying the library code.

```
                        Reflection /
                        Parsing
                     +---------------+
          input      |               |      output
     +-------------> |  Build Model  | +-------------+
     |               |               |               |
     +               +---------------+               v

+---------+                                     +---------+
|         |                                     |         |
|  Input  |                                     |  Model  |
|         |                                     |         |
+---------+                                     +---------+

 e.g *.cs                                    CodeGeneratorData[]

```

After this step there will be a complete model representation of the given input

```
+-------------------+
|                   |
|       Model       |
|                   |
+-------------------+
|                   |
|  Data             |
|           Data    |
|     Data          |
|                   |
+-------------------+
```
Again, `Data` can be anything, from component names, to contexts to attributes. Adding new features is as simple as plugging in a new data provider.

### Step 2: Model --> Code Generation
Implementations of `ICodeGenerator` get the model as an input and can query the model for anything the need. `ICodeGenerator` should also just do one thing, e.g. generate methods to extend the entity, generate methods to extend the context, generate ContextAttributes, etc. Each `ICodeGenerator` can be tested individually, which makes unit testing way easier. They emit one or more `CodeGenFile`.
New CodeGenerators can be added by any developer without modifying the library code.
```
                     +-------------------+
          input      |                   |      output
     +-------------> |  Code Generation  | +-------------+
     |               |                   |               |
     +               +-------------------+               v

+---------+                                      +-----------------+
|         |                                      |                 |
|  Model  |                                      |  CodeGenFile[]  |
|         |                                      |                 |
+---------+                                      +-----------------+
```

### Step 3: Post Process
Implementations of `ICodeGenFilePostProcessor` work on the `CodeGenFiles[]`. Again, they should only do one thing, which makes testing very easy. E.g. modify newlines for a given platform, add a file header or write file to disk.

```
                        +-------------------+
             input      |                   |
        +-------------> |  Post Processors  |
        |               |                   |
        +               +-------------------+

+-----------------+
|                 |
|  CodeGenFile[]  |
|                 |
+-----------------+
``` 

# Summary
This modular approach simplifies
- unit testing
- adding new features without modifying the library code
- adding new methods to parse input
- adding custom code generators for your special needs

```

          Step 1              Step 2            Step 3

      +------------+     +-------------+     +-----------+
      |            |     |             |     |           |
      |    Data    |     |    Code     |     |   Post    |
      |  Provider  |     |  Generator  |     |  Process  |
      |            |     |             |     |           |
      +-+---------++     ++-----------++     ++----------+
        ^         |       ^           |       ^
        |         V       |           V       |
+-------+-+      +--------++     +------------+----+
|         |      |         |     |                 |
|  Input  |      |  Model  |     |  CodeGenFile[]  |
|         |      |         |     |                 |
+---------+      +---------+     +-----------------+
```

**Comment by sschmid** [comment]
Closed by #266

**Comment by sschmid** [comment]
Unity support is missing...

**Comment by sschmid** [comment]
Not anymore ;)

<img width="408" alt="entitas-flexible-codegenerator" src="https://cloud.githubusercontent.com/assets/233700/22565925/478f2142-e98a-11e6-912d-1f0f9f338e75.png">

**Comment by vedun-z** [comment]
PublicMemberInfos seems not suitable for a custom data provider. It has reflection-based fields:
```
        public readonly Type type;
        public readonly string name;
        public readonly AttributeInfo[] attributes;

        readonly FieldInfo _fieldInfo;
        readonly PropertyInfo _propertyInfo;
```
My roslyn-based data provider just cannot create such classes.  Can you store strings  in PublicMemberInfos instead?

**Comment by vedun-z** [comment]
I've checked usage of PublicMemberInfos in Entitas, it seems that PublicMemberInfos should not used in CodeGeneration at all. I suggest to create another string based representation for public members.

**Comment by sschmid** [comment]
@vedun-z Agree, you're right, the code generator shouldn't use PublicMemberInfos. Can you create an issue for that?

**Comment by vedun-z** [comment]
@sschmid I've created https://github.com/sschmid/Entitas-CSharp/issues/280. If you don't mind I can try to make a patch with that changes.
