### ISSUE TITLE
Entitas, Perforce and Line Endings

### ISSUE THREAD

**Issue by vaudevillian** [sschmid/Entitas-CSharp#268]
Hi @sschmid,

first of all: thank you for developing such a promising ECS framework open source & free. I really like the ideas you (guys?) been following, since it tackles most of the issues I encountered myself while working with a self-written ECS system - in a very efficient way and an easy-to-read API. 👍 

But we're getting in trouble right now while working with Perforce for a few reasons:

- The CodeGenerator cant checkout the relevant files automatically (those in Generated folder as well as Entitas.properties). This is more of an inconvenience than a real problem, though. Yet combined with the following, it might be interesting to implement some kind of perforce support eventually.
- Merging files causes trouble. It can be troublesome if you're developing on some new components while someone else on the team is checking-in new components. Especially GameComponentIds might get in trouble then. We experienced a few times where the developers got caught in compiler hell, leading to revert everything he has done. In the meantime our developers know better how to handle those scenarios, yet it's always a certain amount of concentration necessary to not get lost. This might get improved significantly with your new DSL approach, though. Yet I'm not sure how it behaves with Perforce - we will check this out. Another way to avoid this could be - in case of an eventual perforce support - to automatically lock the auto-generated files.
- The main problem: Perforce automatically converts the coding of every file into the client's system. In case of Entitas this means: every Entitas file is in Windows (CR LF) and not Unix (LF). This leads to trouble with verbatim strings, as used in CodeGenerator for the AUTO_GENERATED_HEADER_FORMAT. Verbatim strings doesnt use "\r\n" by default, but instead the encoding of the source file, in this case the CodeGenerator encoded in Windows (CR LF). This again leads to replacing "\n" to "\r\n" (verbatim string compilation) and afterwards replacing "\r\n" to "\r\r\n" (CodeGenerator code replacing with Environment.NewLine). **This doesn't count for the perforce client who added Entitas**. Since this client still has Entitas files encoded in "Unix (LF)", until he force syncs all the files. At the beginning this lead to a lot of detected changes, since every Code Generation caused different files (although only the header was concerned). The fix might be simple: replace @"string" with "stringLine1\n" + "stringLine2\n". Or something like "stringLine1{0}stringLine2{0}, Environment.NewLine".
- At last something different: I would like to have control about where the (visual debugging) contexts  and systems game objects are placed in the hierarchy. Right now I achieve this with some work arounds (e.g. in Contexts the observer is no DontDestroyOnLoad anymore (its directly coupled with a scene) and becomes a member variable with a suitable getter). While this is working I would like to avoid "code augmentations" since its always troublesome to remember those on updates. If there are already any ideas to get access to those, I'd appreciate it seeing it in a future version. But it really isn't that important.

That's all, thanks again for all your efforts!

**Comment by sschmid** [comment]
Numer 1 and 2 will be improved when using Entitas-Lang or the roslyn code generator (coming soon):

Number 3 sounds like similar to #352 . Will take a closer look

Number 4. I added a new method for simplify getting the context observer:
```csharp
context.FindContextObserver()
```
