### ISSUE TITLE
Pool.cs not included in 3.6 release

### ISSUE THREAD

**Issue by Milambeer** [sschmid/Entitas-CSharp#269]
Hi, 
just entering in the project, which is awesome, and try to play with the library yesterday.

I was using the shmup project as reference and noticed that Pool.cs was not included in the release.
Is this an oversight or a new feature have been implemented?

Thanks for support!

**Comment by vladpazych** [comment]
Pool was renamed to Context since 0.36.0.
All changes listed in release page: https://github.com/sschmid/Entitas-CSharp/releases

**Comment by Milambeer** [comment]
Ok thank you! Didn't notice :)

**Comment by sschmid** [comment]
@Milambeer agree, will do some day. It's a recent change, so docs are not updated yet. Maybe I should only release when the docs are updated, too. Sorry for the confusion.
