### ISSUE TITLE
How to detect which gameobject(and Entity in Context) is clicked

### ISSUE THREAD

**Issue by Milambeer** [sschmid/Entitas-CSharp#272]
Hi everyone, continuing to play with with this awesome framework.

I am now trying to work with click trigger on entity and didn't found an easy way to do that.

I end up with this code (using raycast from camera on my IExecuteSystem) but i get the gameObject, and i do not know how to manage to get the entity attached to the gameobject clicked.

    public void Execute() {
        // Entity[] entities = _context.GetEntities();
        Camera camera = GameObject.Find("Camera").GetComponent<Camera>(); 
        if (Input.GetMouseButtonDown(0)) {
            Ray ray = camera.ScreenPointToRay(Input.mousePosition);
            RaycastHit hit;
            
            if(Physics.Raycast(ray, out hit, 100)) {
                GameObject gameObjectHit = hit.transform.gameObject;
                Debug.Log(gameObjectHit.GetInstanceID());
                hit.transform.Rotate(new Vector3(20,20,20));
            }
        }
    }

Thanks for your help!

**Comment by beck-daniel** [comment]
You could simply assign an entity for every clickable Unity game object, the shmup example [https://github.com/sschmid/Entitas-Shmup/blob/master/Assets/Scripts/View/EntityLink.cs](here) does exactly this, and then fetch the entity from returned game object.

**Comment by Milambeer** [comment]
Ok thank you, helped a lot.
Should be great in the future to be able to handle event like collision, input, etc directly in the entity or with a system without adding monobehaviour component to dispatch the entity.

**Comment by sschmid** [comment]
fyi, EntityLink will ship with the next release Entitas 0.37.0.
