### ISSUE TITLE
Entitas and Behaviour Trees

### ISSUE THREAD

**Issue by kdrzymala** [sschmid/Entitas-CSharp#278]
Hi!
We're currently developing one of our upcoming games in Entitas and loving it so far :) Hope to use it in all our future projects. Keep up the good work! :) 

Recently I came to a point when some behavior in this game would be nicely expressed with behavior trees and I'm wondering how to integrate that with Entitas. Did anyone tried to integrate Behaviour Designer or any other BT tools?
I'm not sure how to obey the rule that logic goes into systems and still have BT integrated. Any tips? How would you do it?
Thanks.

**Comment by sschmid** [comment]
iirc @mzaks wrote sth about this. Let's see if he can give an answer to this.

**Comment by mzaks** [comment]
I made small gist
https://gist.github.com/mzaks/3817c0e1a4e700aee4deb2607fa21eef

Basically you can have a System wich will hold a reference to a root node of a behaviour Tree and it will push the entities through the node. Haven't tried it on a real project, but conceptually should be fine :)

**Comment by kdrzymala** [comment]
Oh yeah, saw that one on google :) Didn't give it much thought though, because I don't want to write a tool from scratch ( looking forward to letting the designers tweak those trees in a visual manner).
Looking at it again I see that I could do pretty much the same with Behaviour Designer. I'll only need a component for the BT refrerence and the BT would need the reference for its entity. Nodes would operate directly on entities. I guess as long as the state is in components then I'm good, right?

**Comment by r3b00t5** [comment]
I realize this has been closed for a while, but has anyone been able to make this work? As I understand Behaviour Designer, each GameObject needs a behaviour tree attached to it so that it can run through its tree.
