### ISSUE TITLE
[Entitas:] EntityIndex with multiple key support

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#279]
Usually you generate one key for a given entity, e.g. `name : string`. In some cases it is helpful that one entity generates more than one key, e.g. a building on a map with position and size.
The building is at position(0,0) but because it has a size of (2,2) should also generate keys for all the other occupied positions.

**Comment by JuDelCo** [comment]
Like a spatial hash algorithm ? :smile:

**Comment by sschmid** [comment]
given:
a building with position(0,0) and size(2,2)

when:
added to an EntityIndex with multiple keys support

then:
it will be at
index.GetEntity(0, 0)
index.GetEntity(1, 0)
index.GetEntity(0, 1)
index.GetEntity(1, 1)

**Comment by sschmid** [comment]
this can be helpful for all sorts og games

**Comment by sschmid** [comment]
See [CustomEntityIndex](https://github.com/sschmid/Entitas-CSharp/blob/develop/Tests/Tests.Fixtures/Fixtures/CustomEntityIndex.cs) for a reference implementation

**Comment by jrmacgill** [comment]
The CustomEntityIndex link above not 404s

**Comment by FNGgames** [comment]
Oh no, that custom entity index page is really useful, it's dead now - we need a replacement

**Comment by sschmid** [comment]
There you go
https://github.com/sschmid/Entitas-CSharp/blob/develop/Tests/TestFixtures/Fixtures/CustomEntityIndex.cs

**Comment by FNGgames** [comment]
I dont know if other people have tried this but one thing i quite like to do for complex lookups use an intermediate string component with an entity index like this:

```csharp
public class ThingAComponent : IComponent {
    public ThingA value;
}

public class ThingBComponent : IComponent {
    public ThingB value;
}

public class ThingAThingBHashComponent : IComponent {
    [PrimaryEntityIndex] public string value;
}

public static string GetThingAThingBHash(ThingA a, ThingB b) {
    return string.Format("{0}_{1}", a, b);
}

var e = _context.GetEntityWithThingAThingBHash(GetThingAThingBHash(a, b));
```

**Comment by sschmid** [comment]
If you can represent this as an int, it would be great. Otherwise there's a risk to create lots of string and increase the gc pressure
