### ISSUE TITLE
[Entitas:] Format for CodeGeneratorData

### ISSUE THREAD

**Issue by vedun-z** [sschmid/Entitas-CSharp#280]
Now CodeGeneratorData is a dictionary that maps a string literal constant to an object. 
I suggest to replace a dictionary with arbitrary string keys to an ordinary class with fields. It would automatically define a format  for CodeGeneratorData, because now you should investigate CodeGeneratorDataProvider/CodeGenerator to understand what format it excepts. 

CodeGeneratorData format also includes PublicMethodInfos that contains Reflection-specific fields which obviously cannot be used by other data providers.  I suggest to replace it to ordinary class with string fields.

**Comment by sschmid** [comment]
The idea was that you can any kind of data to the dictionary. A class would be limiting for customisation. I agree, the PublicMemberInfos should be replaced with sth else in the first place, but the whole idea of the code generator refactoring was that you can add anything at any time.
This means, you can e.g. add a roslyn data provider that adds whatever you need to the dictionary. A custom code generator can read those values and produce any kind of code. In the Entitas Preferences Window you can select your data provider and code generator and everything should work. In this very case I understand it would be nicer if you only have to add a new data provider and use the existing code generator.

**Comment by sschmid** [comment]
You could duplicate the existing component generators and use your data instead of public member infos

**Comment by vedun-z** [comment]
> the whole idea of the code generator refactoring was that you can add anything at any time

You can have class fields for stable things like component public fields and an auxiliary dictionary for adding new features on the fly.  Anyway you have coupling between DataProvider and CodeGenerator and I think that an explicit declaration of common CodeGenerator requirements is a nicer than implicit.

**Comment by sschmid** [comment]
Btw, I was thinking about roslyn again. It's great that you do this. If there's ever a way we can invoke roslyn from within unity, I'd replace the reflection based one. I think that would be very powerful! I just started migrating a very big project today and we have some custom generators, but they're all based on reflection. Of course, there are lot of compiler errors and I cannot re-generate, but the dsl doesn't help either because those generators are custom. So roslyn would be very beneficial for those cases!

**Comment by vedun-z** [comment]
I've made a Roslyn-based data provider, you can check it out https://github.com/vedun-z/Entitas-CSharp/commits/develop . Now I have two separate commits. First commit introduces MemberInfosData for holding field/property info. The second one introduces Roslyn support. I've checked that my provider creates the same data for Tests.Fixtures project. Of Course, It has some bugs, bug reports welcome! :-D

I use nuget to install Rolsyn. It would work fine for windows, however, for mac/linux I except some troubles with msbuild. Roslyn uses msbuild to open solution/project files and  as far as I remember We've used custom build of msbuild and 4.6 runtime in mac/linux systems. So, If you have some ideas how to create multisystem Rolsyn distribution, please share them.
