### ISSUE TITLE
[Entitas] Generate attribute [Input]

### ISSUE THREAD

**Issue by zendorx** [sschmid/Entitas-CSharp#282]
Hi, i can't  get how to create Input attribute.  I'm trying to create match1 from scratch, but it's too hard without any tutorials. I see there must be generated file for this.

```
using Entitas;

[Input]
public sealed class InputComponent : IComponent {

    public int x;
    public int y;
}

```

**Comment by sschmid** [comment]
Common steps:
- start with an empty project
- define contexts in Entitas Preferences
- Generate (this will generate a few files including context attributes)
- create a new IComponent and use the generates context attribute (e.g. [Input])

**Comment by zendorx** [comment]
thanx!
