### ISSUE TITLE
ISetPool replacement?

### ISSUE THREAD

**Issue by senritsu** [sschmid/Entitas-CSharp#284]
My attempt to try out Entitas was cut quite short when i couldn't find how to bind the system to the Pool/Context. All documentation and examples implement `ISetPool` in addition to  `IXSystem` to get a `Group`, but i have no idea how that is supposed to work now. According to the latest release notes `ISetPool` was removed, but what is the replacement?

**Comment by sschmid** [comment]
Hey, yes with the last and the next release there are some major changes. See release notes
> Removed IEnsureComponents, IExcludeComponents, ISetPools, ISetPool, IReactiveSystem, IMultiReactiveSystem, IEntityCollectorSystem

The new version is almost done. After this I try to find time to update / rewrite the docs

**Comment by sschmid** [comment]
Check the example projects [Match-One](https://github.com/sschmid/Match-One)
or [Entitas-CSharp-Example](https://github.com/sschmid/Entitas-CSharp-Example).
Both of them have a GameController as an entry point. That might help

**Comment by senritsu** [comment]
Ok, so would you recommend waiting to try out Entitas until vNext is finished? How much of the existing concepts are obsoleted by the changes?

**Comment by sschmid** [comment]
The concepts stay all the same. The biggest new thing in the next versino is the type-safety.
See issue
https://github.com/sschmid/Entitas-CSharp/issues/257

see
Milestone
https://github.com/sschmid/Entitas-CSharp/milestone/7?closed=1

**Comment by senritsu** [comment]
So judging from the example and a quick look into the Entitas sources, the linking of `System` to `Context` is now done manually via constructor injection instead of method injection as before and there is no related interface or visible contract anymore. So if something needs the context, i have to handle that dependency myself, is that correct?

**Comment by sschmid** [comment]
that's correct. It's more explicit now. I usually pass in the contexts via ctor args

**Comment by senritsu** [comment]
Thanks for the insight. I think i will give it a try despite its current state, and see how far i get, now that i know there is at least an updated reference project to look at. 

One last tangential question, the `Feature` class used in the Match One example, am i correct in assuming it is just a wrapper around `Systems` solely for visual debugging purposes?

**Comment by sschmid** [comment]
Yes. The Feature class takes care of either subclassing from DebugSystems or normal systems. In the editor you'll get DebugSystems, in release mode you will get the faster Systems
