### ISSUE TITLE
Entity Creation Syntax

### ISSUE THREAD

**Issue by Xfer83** [sschmid/Entitas-CSharp#287]
![image](https://cloud.githubusercontent.com/assets/2735224/22982211/7814022e-f36c-11e6-91c9-32997baab51f.png)
(From the main page here.)

As of 0.37.0 this doesn't seem to work.  
I have to do something more like:
var e = _context.CreateEntity();
			e.AddAsset("ViewPrefab");
			e.AddText("Toast");

I'm interested in doing some tutorials / video work for beginners (as i am one, and am finding outdated examples confusing.  (the updated example projects are not outdated, but are somewhat complex and for a Unity user with no ECS experience its not 100% intutive where to look for the code that makes things work!)

**Comment by bddckr** [comment]
These "docs" are currently out of date but these two example projects have been updated:
https://github.com/sschmid/Match-One
https://github.com/sschmid/Entitas-CSharp-Example

**Comment by KumoKairo** [comment]
I'm working on a video step-by-step tutorial atm.

**Comment by sschmid** [comment]
yep all docs + wiki are not updated yet. Just released 0.37.0 and have to catch up with the docs...
