### ISSUE TITLE
[CodeGenerator:] Default Context

### ISSUE THREAD

**Issue by Xfer83** [sschmid/Entitas-CSharp#288]
Does a default context still exist? (There was a default pool at one time)
If so how do you access it?

**Comment by KumoKairo** [comment]
No, you have to create this "default" context by hand in the Entitas preferences. Every entity now needs to be assigned to some of the existing contexts.

**Comment by sschmid** [comment]
I'm thinking about adding sth like a default context again. Will probably just use the first declared context

**Comment by Xfer83** [comment]
I think this would be helpful for beginners.  Though after updating to 0.37.0 it took me some time to realize that i was obliged to declare a context at all, since by default there are none.

**Comment by sschmid** [comment]
Planned in 0.38.0
