### ISSUE TITLE
Does Entitas will support Unity 4.x in future?

### ISSUE THREAD

**Issue by KevinQiangK** [sschmid/Entitas-CSharp#29]
For history reason,my unity version is 4.5.5f1, when I building Match-One example scene,there have some errors as follow:
1. The unity(version < 4.6) doesn't has the NewUi (**UnityEngine.UI**);
2. In Entitas.Unity.VisualDebugging and demo script there using **Transform.SetParent** function which doesn't exist in older unity version.
thanks!

**Comment by sschmid** [comment]
I'll take a look and will update the Entitas sources to support Unity 4.5. I guess I will test the example projects only against the latest version of Unity.

**Comment by sschmid** [comment]
Could you please create a pull request with the updated Entitas sources to work with your Unity version? That would be great :)

**Comment by chrischu** [comment]
If I am not completely mistaken, Entitas does not have a UI and therefore does not utilize the new UI system from Unity 4.6, so that shouldn't be a problem.

**Comment by sschmid** [comment]
Yes, that's right. He was talking about the Match-One example

**Comment by sschmid** [comment]
@KevinQiangK I don't have Unity 4.5 atm, but feel free to create a pull request
