### ISSUE TITLE
[VisualDebugging:] Add search field to DictionaryType Drawer

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#299]
Add search field in case there many keys

**Comment by sschmid** [comment]
![entitas-dictionarytypedrawer](https://cloud.githubusercontent.com/assets/233700/23165453/74444f08-f83c-11e6-8051-150b58568f6f.png)

**Comment by trumpets** [comment]
@sschmid Man you are killing it lately ! Thank you for these, you support Entitas more than any OS framework I've ever used! :)

**Comment by sschmid** [comment]
❤️ ❤️ ❤️ 
Thanks, I really work hard trying to make Entitas a pleasure to work with.
