### ISSUE TITLE
Is an IExecuteSystem instanciated 2 times?

### ISSUE THREAD

**Issue by Milambeer** [sschmid/Entitas-CSharp#300]
When i create a system using IExecuteSystem with the following code:

```
    public void Execute() {
        if (Input.GetMouseButtonUp(0)){
            Debug.Log("Up");
        }
  }
```
after one click, the debug.log is called twice (and all other input detection). After searching in the unity docs, it seems that error occur when a script is attached twice in an object.

Thx!

**Comment by sschmid** [comment]
Try steeping through frames and also check, if you call Execute twice

**Comment by Milambeer** [comment]
Was a bug from my code and not from the framework!

**Comment by sschmid** [comment]
great :)
