### ISSUE TITLE
is there any idiomatic way to listen to the first 'add action'

### ISSUE THREAD

**Issue by 5alamander** [sschmid/Entitas-CSharp#302]
o(╯□╰)o  Hi~,  I am trying to use Entitas in a Card game, and I found it is strange when I update the value of 'Card' attribute.

for example:

IGroup<GameEntity> cards = game.GetGroup(GameMatcher.Card);

cards.OnEntityAdded += (g, e, i, c) => {
       // create a view of this entity
};
cards.OnEntityRemoved += (g, e, i, c) => {
       // destroy the view of this entity
};

When I update the card value, and this group will remove this entity, and re-add it at the same time.
😶 is there any idiomatic way to listen to the first 'add action' ?

**Comment by T2RKUS** [comment]
You would create a reactive system to do this:
```

	public class CreateViewSystem : ReactiveSystem<GameEntity>
    {
		protected readonly GameContext _Context;
	
		public CreateViewSystem(Contexts contexts) : base(contexts.game) {
			_Context = contexts.game;
		}
		public override Collector<GameEntity> GetTrigger(IContext<GameEntity> context) {
			return context.CreateCollector(GameMatcher.Card, GroupEvent.Added);
		}
		readonly IMatcher<GameEntity> filterMatcher = GameMatcher.Card;
		public override bool Filter(GameEntity entity) {
			return filterMatcher.Matches(entity);
		}
		public override void Execute(System.Collections.Generic.List<GameEntity> entities)
        {
            /* create views for entities. */
        }
	}
```
You would then add this system to your systems chain.
You can also have your system create a view by responding to the creation of an AssetComponent( assetName:string) and do then following (assuming you also have a component to hold the view)
```
	public class CreateViewSystem : ReactiveSystem<GameEntity>
    {
		protected readonly GameContext _Context;
	
		public CreateViewSystem(Contexts contexts) : base(contexts.game) {
			_Context = contexts.game;
		}
		public override Collector<GameEntity> GetTrigger(IContext<GameEntity> context) {
			return context.CreateCollector(GameMatcher.Asset, GroupEvent.Added);
		}

		public override bool Filter(GameEntity entity) {
			return entity.hasAsset && !entity.hasView;
		}
		public override void Execute(System.Collections.Generic.List<GameEntity> entities)
        {
            /* create views for entities. */
        }
	}
```

**Comment by 5alamander** [comment]
Thanks for reply. 😀

but I still wonder why the 'OnRemoved' and 'OnAdded' action are invoked when I just 'Replace' a component?

Is it possible to add an additional action of 'OnReplaced', to distinguish the first 'add action' and the 'replace action'   O__O ？

**Comment by T2RKUS** [comment]
When you "replace" a component what is happening under the hood is that the component is removed and a new component is requested from the component pool. Then the component values are copied from the old component the new component.
