### ISSUE TITLE
Spaces vs Tabs

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#304]
😱

**Comment by alimoeeny** [comment]
woot! Nooooooooooo

**Comment by sschmid** [comment]
:) Let the flame wars begin, haha

**Comment by sschmid** [comment]
Any vetos why not to do so are welcome btw

**Comment by kdrzymala** [comment]
Spaces FTW!

**Comment by bddckr** [comment]
This whole discussion was fixed for me 20 years ago because we have proper IDEs (And I'm not even 30 years old :wink:). 😛
I don't really care, as long as it's not changed all the time so my commits aren't just
> Letting Entitas change whitespaces again.
:wink:

**Comment by bddckr** [comment]
Make whitespace great again.

**Comment by alimoeeny** [comment]
At the end of the day, it is a matter of taste.
The only argument is tabs display differently in different editors, different displays. 
I am personally a "only use spaces" guy.

**Comment by sschmid** [comment]
I used to care a lot about details like this, but I stopped caring about it a year ago, because most of the time people argued based on personal preferences. I worked in different teams with different rules, and I'm convinced that everyone can adapt to anything. So I tried to approach this without personal preference but with logic, otherwise there will never be a consent.
What's probably more important, no matter which topic, consistency is king, especially when talking about whitespace and braces and all this rather unimportant things :)

I used spaces until now. My silly attempt to approach this with logic resulted in the following thoughts:
- Tabs is a character which only intent is to indent
- Space is a character which main intent is to separate
- you cannot "half indent" with tabs
- IDEs let you define the indent distance for tabs (e.g. 2 or 4)
- 1 tab character -> 4 spaces character

Well, couldn't find any advantages using spaces out of my head. Maybe I'm missing sth

**Comment by bddckr** [comment]
I hated tabs when doing line breaks and having the IDE indent the stuff then.

In Objective-C it was apparent all the time, in C# I still break long methods so each argument is on their own line, but all arguments are intended by the opening parenthesis.

**Comment by kdrzymala** [comment]
what @bddckr said.
That's why I prefer spaces. I know that if I break a long method and align it nicely, it'll look the same no matter the env settings.

**Comment by sschmid** [comment]
Haha, just check what VS for Mac does - it's cheating

![tabs spaces](https://cloud.githubusercontent.com/assets/233700/23218603/f0b22426-f91c-11e6-8ddf-ffc7d5591fa9.png)

**Comment by sschmid** [comment]
it's using spaces to align nicely

**Comment by JuDelCo** [comment]
If you need to put the parameters in different lines to read them then something is wrong.

As said, at the end the most important thing it's to be consistent (tabs or spaces, not both). I prefer Tabs, they are made for indenting (spaces no), allows each developer to see the size in theirs text editors as they prefer (i hate 2-spaces indenting for example) and you can't put 3/4 of a tab, as its only a character (not four)

https://softwareengineering.stackexchange.com/a/72

**Comment by basarsimitci** [comment]
I used to do tabs a (very) long time ago. Then I got sick of seeing my code garbled up when I opened in different editors / viewers and converted to spaces for good. While I acknowledge the argument that everyone can set the tab size to their liking, let's not forget that code is not only observed in editors that you can set the tab size, but also on web pages.
Also, frequently you need to align to non-tab-stop columns, as already mentioned.

**Comment by leinades** [comment]
Spaces because tabs are stupid.

**Comment by sschmid** [comment]
Lol, that's the best reason! Stupid tabs :D

**Comment by sschmid** [comment]
Ok, thanks for your input, always very much appreciated. Nothing will change, spaces will stay!
Hurray 🎉

**Comment by sschmid** [comment]
https://www.youtube.com/watch?v=SsoOG6ZeyUI

**Comment by FNGgames** [comment]
I was just about to post that :)
