### ISSUE TITLE
setters for component that trigger reactive systems

### ISSUE THREAD

**Issue by Milambeer** [sschmid/Entitas-CSharp#305]
Would be great to have accessors for component that trigger the reactive system on replacement.

For now, if you want to change only one property of your component but still trigger the reactive system, you have to set again all properties in the replacefunction of the component. The component.attribut = xxx doesn't trigger the reactive system listening on the component.

**Comment by T2RKUS** [comment]
You could create your own generator to do this for you when you call a method: entity.UpdatePosition(); for example. It would just copy all values to a new component and replace it internally triggering the change events.

to get this kind of syntax.
```
e.position.x = 10;
e.position.y = 10;
e.UpdatePosition();
```

**Comment by T2RKUS** [comment]
You could also use this solution: https://github.com/sschmid/Entitas-CSharp/pull/150

**Comment by sschmid** [comment]
Fyi, I strongly recommend not doing sth like this:
```csharp
e.position.x = 10;
e.position.y = 10;
```
In case you're planning to use the dsl, I enforced that you get a compiler error when writing sth like this.

@T2RKUS already found the issue with a suggestion how you could add your custom generator to solve this.

**Comment by sschmid** [comment]
You're welcome to do a PR so I can add it to Entitas
