### ISSUE TITLE
Code generation problem. Refreshed instructions

### ISSUE THREAD

**Issue by PanCotzky** [sschmid/Entitas-CSharp#308]
Tried Entitas 0.37 (clean install) and can't generate any components. I've set one context called "game". Then added a component PositionComponent derived from IComponent. Then pressed "Generate". It generated 5 files: GameAttribute, GameComponentsLookup, GameContext, GameEntity and Contexts. No files was generated for PositionComponent. I can't add it to a GameEntity either. Am I doing something wrong? I'm trying to debug the problem and no success so far. Can you update the instruction or check the release for bugs?

Thank you

**Comment by IDNoise** [comment]
Did you add [Game] attribute to position component? Now you need to specify what context\contexts component will be used in.

**Comment by sschmid** [comment]
Hi @PanCotzky , @IDNoise is right, in 0.37.0 you have to put a ContextAttribute to every IComponent like so [Match-One PositionComponent](https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Components/GameBoard/PositionComponent.cs#L3)

The next release has a "default context" feature, which means that all IComponts that don't have a ContextAttribute will automatically be linked to the first context specified in you Preferences. So with the new version your setup would already work.
