### ISSUE TITLE
[CodeGenerator] Auto generate (no Button press)

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#309]
In Unity, check on recompile if components were added / removed / or changed. If so automatically generate.

**Comment by sschmid** [comment]
Just an idea, not sure if it's worth the effort...

**Comment by bddckr** [comment]
The effort shouldn't be that big.

But if you add this make sure to let us disable it. I'm not using Entitas-Lang currently and therefore there will always be some changes where I don't want to regenerate just yet.

**Comment by sschmid** [comment]
Yes, sometimes you might not want to regenerate and get frustrated if it automatically does. I'll think about it, it's just an idea atm

**Comment by sschmid** [comment]
No seeing this happening right now... Will close

**Comment by sschmid** [comment]
It's coming 🤩
Please see #1005
