### ISSUE TITLE
Collision Script Help. 0.37.0

### ISSUE THREAD

**Issue by JRSerjeant** [sschmid/Entitas-CSharp#311]
Hello All, 

I'm trying to get collision  working with a Script Component but I having some issues. 

This is my Script Component attached to a collider . 

```c#
using UnityEngine;
using Entitas;

public class scr_manGroundCollider : MonoBehaviour
{
    public string targetTag;
    IGroup<GameEntity> _Group;
    GameContext _context;

    private void Start()
    {
        _context = Contexts.sharedInstance.game;
    }

    private void OnCollisionStay2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag(targetTag))
        {

        }
    }

    private void OnCollisionExit2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag(targetTag))
        {

        }
    }

    private void SetGroup()
    {
        _Group = _context.GetGroup(Matcher<GameEntity>.AllOf(GameMatcher.ManGroundCollider));
    }

    private void Update()
    {
        EntityLink el = gameObject.GetEntityLink();
        _context.CreateEntity().AddManExtraColliderCollision(el.entity);
    }
}
```
I current have nothing in the collision functions as I'm using Update to test for now.

Below is the System I have created. In side the foreach  I want to set a value of the colliderEntity. I have seen this in the Shmup example. However the auto complete in Visual Studio for me does not return a list of the the components. There is an image after the code showing this. 
````c#
using System;
using System.Collections.Generic;
using Entitas;
using UnityEngine;

class ManExtraColliderCollisionSystem : ReactiveSystem<GameEntity>
{
    public ManExtraColliderCollisionSystem(Contexts contexts) : base(contexts.game)
    {
    }

    protected override void Execute(List<GameEntity> entities)
    {
        foreach (var e in entities)
        {
            Debug.Log(e.manExtraColliderCollision.colliderEntity);
            e.manExtraColliderCollision.colliderEntity.
        }
    }

    protected override bool Filter(GameEntity entity)
    {
        return false;
    }

    protected override Collector<GameEntity> GetTrigger(IContext<GameEntity> context)
    {
        return context.CreateCollector(GameMatcher.ManExtraColliderCollision);
    }
}
`````

My Code without any Components in the intellisense drop down.
![Imgur](http://i.imgur.com/JdWUzPt.png)

Example from Shmup with the Components in the intellisense drop down.
![Imgur](http://i.imgur.com/n9elXOW.png)

I get the feeling that I'm just missing something simple here so any help would be much appreciated.

**Comment by sschmid** [comment]
Seems like your `ManExtraColliderCollisionComponent` has a member called `colliderEntity` of type `Entity` but should be of type ´GameEntity´ or should be casted like this
```csharp
((GameEntity)e.manExtraColliderCollision.colliderEntity).AwesomeCodeCompletion***
```

Btw, when it's only 1 matcher, don't use Matcher.AllOf to reuse the cached matcher
```
void SetGroup() {
        _Group = _context.GetGroup(GameMatcher.ManGroundCollider);
}
```

**Comment by JRSerjeant** [comment]
Evening Simon, 

Thank you for the quick response. Casting to GameEntity works perfectly. 

I will be able to sleep soundly tonight now, Cheers. :)

**Comment by sschmid** [comment]
:) You're welcome!  😴
