### ISSUE TITLE
[CodeGenerator:] Lazy default instantiation for IoC

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#314]
You can use Entitas to manage your dependencies, e.g.

```cs
[Game]
public class MyService {
    // ...
}
```

This will generate a `MyServiceComponent` and you can do
```cs
game.SetMyService(new MyService());

var service = game.myService.value;
```

which is similar to wiring up your context like in other IoC frameworks.
This is great for decoupling, mocking and testing. This also works for interfaces

```cs
[Game]
public class IService {
    // ...
}
```

# Suggestion

Add a convention or an Attribute to define the default value, so we don't have to set all dependencies ourselves. For unit testing we can still set mock services.

This means there will be no manual setup for us to do and we can write the following at any point of time and get a valid instance
```cs
// Will lazily instantiate a default instance if not set before
var service = game.myService.value;
```

**Comment by WoLfulus** [comment]
What about services that will be used on multiple pools but needs to have only one instance?

**Comment by sschmid** [comment]
You would wire up this instance to all contexts in the beginning and therefore the lazy instantiation wouldn't kick in

**Comment by WeslomPo** [comment]
I connect entitas to zenject and it work like a charm. Only SceneContext on scene before you hit play xD, and all dependencies in right place. Love it.

**Comment by sschmid** [comment]
The wave of closing issues doesn't stop here... Will close, focusing on more important features for now.
