### ISSUE TITLE
[CodeGenerator:] Cache static component index lookup into local var

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#316]
Example:

```csharp
// Before
public void AddPosition(IntVector2 newValue) {
    var component = CreateComponent<PositionComponent>(CoreComponentsLookup.Position);
    component.value = newValue;
    AddComponent(CoreComponentsLookup.Position, component);
}

// After
public void AddPosition(IntVector2 newValue) {
    var index = CoreComponentsLookup.Position;
    var component = CreateComponent<PositionComponent>(index);
    component.value = newValue;
    AddComponent(index, component);
}
```

**Comment by sschmid** [comment]
Welcome to the world of micro-optimizations

**Comment by T2RKUS** [comment]
Is that not the same thing? How is that faster?

**Comment by bddckr** [comment]
The difference is that the new variable `index` is used twice. The compiler won't reuse the same variable for that as it doesn't know what `CoreComponentsLookup.Position` does. It could have side effects for example.

**Comment by T2RKUS** [comment]
Ooh. Yes I know that. I overlooked the second use of the lookup variable lol. faster by 1 statement. 👍

**Comment by WoLfulus** [comment]
It'd be cool to see a benchmark and how those changes impact the performance :D

**Comment by sschmid** [comment]
Feel free to do one :)

**Comment by sschmid** [comment]
I don't expect any real life gains unless you call those methods reeeeeaaaly often
