### ISSUE TITLE
Have code generators check key exists (from data provider)

### ISSUE THREAD

**Issue by T2RKUS** [sschmid/Entitas-CSharp#318]
Currently, It seems that the generators assume that the keys it needs to function already exit and do not perform a check. This is problematic because it means that any custom component providers grouped together on their own wont work since they all go through to the same generators as well. Such as:

```csharp
using System;
using System.Reflection;
using Entitas;
using Entitas.CodeGenerator;

namespace T2.CodeGenerator.Persistence {

    public class PersistenceDataProvider : AbstractComponentDataProvider {

        public override string name { get { return "Persistent Components"; } }
        public override bool isEnabledByDefault { get { return false; } }

        public PersistenceDataProvider() : this(Assembly.GetAssembly(typeof(IEntity)).GetTypes()) {
        }

        public PersistenceDataProvider(Type[] types)
            : base(new IComponentDataProvider[] {
                new ComponentNameComponentDataProvider(),
                new PersistentComponentDataProvider(),
                new PersistentComponentMemberDataProvider(),
            }, types) {
        }
    }
}
```
It uses ```ComponentData``` so it is accepted by the code generators, but they assume their data exists.

**Comment by T2RKUS** [comment]
Example from ComponentGenerator
```csharp
        public CodeGenFile[] Generate(CodeGeneratorData[] data) {
            return data
                .OfType<ComponentData>()
                .Where(d => d.ShouldGenerateComponent())
                .Select(d => generateComponentClass(d))
                .ToArray();
        }
```

**Comment by T2RKUS** [comment]
I've realized I could also create my own AbstractComponentDataProvider but I'd be duplicating most of the code already there...

**Comment by sschmid** [comment]
I know what you mean, but this is intentional.
For this code generator to work, it needs certain information. If some keys don't exist, it cannot fully function. Checking for keys would mean it end up generating some things and would skip others. The shipped code generators work full or nothing. For customized solutions I recommend creating your own generators, even if this means duplicating an existing one and just changing a few little things.

**Comment by sschmid** [comment]
So I'd say it's ok to create your own `ComponentDataProvider` or `AbstractComponentDataProvider`. You can use ComponentData.

**Comment by T2RKUS** [comment]
I see. That makes sense. In that case I'll create my own, thank you.
