### ISSUE TITLE
Code generation for TypeDrawers and Defaults

### ISSUE THREAD

**Issue by leinades** [sschmid/Entitas-CSharp#327]
Creating type drawers (and defaults), even for simple components, is a very tedious and mechanical task. For simple components composed of only primitives this can be 100% automated. Components that include non-trivial components could be generated just as easily if the relevant type drawers exist.

I think automating this task could make Unity+Entitas much more accessible and fun to use. WDYT?

**Comment by sschmid** [comment]
Updated EntityDrawer to automatically draw all known types also for custom types. No code generation required. Entitas can draw nested known types recursively 👍 No need for simple custom TypeDrawers anymore like `IntVector2TypeDrawer`
