### ISSUE TITLE
[CodeGenerator:] Review and check for namespace awareness

### ISSUE THREAD

**Issue by Spy-Shifty** [sschmid/Entitas-CSharp#328]
Using code generator with following dataprovider settings:
Blueprint
Component (without namespaces)
Context
Entity Index

I have the following component:
```
namespace TileCore {
    [TileCore]
    public class PositionComponent : IComponent {
        [EntityIndex]
        public IntVector2 value;
    }
}
```

The code generator produce  the following lines of code in 
ContextsEntityIndices.cs

```
...
public partial class Contexts {

    public const string TileCorePosition = "TileCorePosition";

    [Entitas.CodeGenerator.Api.PostConstructor]
    public void InitializeEntityIndices() {
        tileCore.AddEntityIndex(TileCorePosition, new Entitas.EntityIndex<TileCoreEntity, IntVector2>(
            tileCore.GetGroup(TileCoreMatcher.TileCorePosition),
            (e, c) => { var component = c as TileCore.PositionComponent; return component != null ? component.value : e.position.value; }));
    }
}
...
```

But the correct Matcher id name should be:

`TileCoreMatcher.Position`

I change it manually at the moment.

Greate Frameworke by the way!!!

**Comment by sschmid** [comment]
Take a look #323 at, I just closed this issue with a commit. Component (without namespaces) is gone

**Comment by sschmid** [comment]
I will update all test fixtures to use namespace to have unit tests and make sure that all data providers and generators are namespace aware. Will rename issue

**Comment by sschmid** [comment]
Fixed in https://github.com/sschmid/Entitas-CSharp/releases/tag/0.39.0
