### ISSUE TITLE
Blueprints not persistent after changes to components.

### ISSUE THREAD

**Issue by Adjuvant** [sschmid/Entitas-CSharp#331]
First time saying hello, great work on the project! Starting to get my head around it...

Issue: individual Blueprint assets get wiped out when changing components. E.g.
Original Blueprint
- ButtonComponent
- NetworkComponent
- PositionComponent
- ResourceComponent

Changed the network component to remove it holding data to just become a flag i.e. (e.isNetwork). After this change the blueprint assets are wiped out for every component below the effected component e.g.

After change blueprint
- ButtonComponent

Is there a way of altering components after code generation that I'm missing?

Cheers!

**Comment by IDNoise** [comment]
I think problem here is in binary serialization, after change in network component serialization failed on 2nd component and all components below were wiped. I'm not sure, but possibly you can move component to the bottom of the list for each blueprint before changing it or wait\implement yourself json\yaml\xml serialization :)

**Comment by sschmid** [comment]
Good find. Fixed in latest commit. I was throwing an exception when attempting to set a field that does not exist. This stopped the deserialization. Works now as expected.
