### ISSUE TITLE
Explaine about Reactive System and Collector

### ISSUE THREAD

**Issue by AlexeyJKoshkin** [sschmid/Entitas-CSharp#334]
![image](https://cloud.githubusercontent.com/assets/3306190/23896802/b59393c6-08bb-11e7-8c88-5c8071f50517.png)
As you see this entity has no UpgradeBuildingComponent, but still inside Collector(AllOf(BuildingPawn, UpgradeBuilding).NoneOf(ConstucionCompete))

I thougth when entity lost some component it's shoud remove from collector. Am I right ?

**Comment by paraboxx** [comment]
No, it will be removed from the Group inside the collector, but not from the collector itself. Collectors keep the entity until the ReactiveSystem that owns the collector did its work on it.

**Comment by sschmid** [comment]
That's right. Collector collect / add entities, never remove them. This is why we use the `Filter()` method in ReactiveSystem. A trigger doesn't guarantee that the entity still matches.

**Comment by AlexeyJKoshkin** [comment]
Ok. My ReactiveSystem call Execute(List<BuildingEntity> eneities) method.
Because Inside this method I do `entities[i].RemoveUpfradeBuilding()`
But entity still in collector.
When entity will remove from collector ? Or entity will be inside forever ???

**Comment by sschmid** [comment]
ReactiveSystems automatically call collector.ClearCollectedEntites() once they are done. So yes, they will be removed automatically

**Comment by AlexeyJKoshkin** [comment]
but entity still in this collector :-) Even after calling `Execute(List<BuildingEntity> eneities)`.

**Comment by sschmid** [comment]
maybe the system triggers itself by changing components that are in the triger

**Comment by sschmid** [comment]
you're not calling `Execute(List<BuildingEntity> entities)` directly, right? (which would be wrong to do)

**Comment by AlexeyJKoshkin** [comment]
No, of course not :-)

I think you're right I'll try change my code.
> the system triggers itself by changing components

**Comment by sschmid** [comment]
If your ReactiveSystem triggers itself because you change components that are part of your trigger, you can also just call `Clear()` in the end of your execute which will clear collected entities for this reactive system
```csharp
    protected override void Execute(List<TestEntity> entities) {
        // do sth
        Clear();
    }

```

**Comment by sschmid** [comment]
It will only affect this system, all other reactive system will behave as expected

**Comment by AlexeyJKoshkin** [comment]
> If your ReactiveSystem triggers itself because you change components that are part of your trigger, you can also just call Clear() in the end of your execute which will clear collected entities for this reactive system

Thanks!. All working nice :-)
