### ISSUE TITLE
Add(Componnent) vs Replace(Component) vs Remove(Component)

### ISSUE THREAD

**Issue by Xfer83** [sschmid/Entitas-CSharp#335]
Can a reactive system distinguish between when a component is added vs  when a component is replaced?  
(It's my understanding that Replace(Component) removes the old component (if one exists) and then adds the new)

Also trying to figure out how to get this over to the new FAQ area.

**Comment by sschmid** [comment]
Hi, no, from the point of view of a reactive system there is no difference between a component being added or replaced.

That's definitely sth for the faq. I suggest having an issue with a catchy title and have the question including the answer (optionally some examples) in the description. I will add the faq label and move it to the faq project. Similar to the dummy issue #332
