### ISSUE TITLE
Nothing works ... 

### ISSUE THREAD

**Issue by cemkoker** [sschmid/Entitas-CSharp#336]
No documentation, no up-to-date videos ... so basically nothing works 'out of the box'. I wonder how a beginner like me can get started; there's no clear learning path to follow, everything is very obscure. Tried to do juste a simple game controller but I can't access 'Pool', which I 'suppose' has been renamed to something else, nothing, nowhere ... I find it very disappointing.

**Comment by trumpets** [comment]
check out this: https://github.com/sschmid/Match-One It is always up to date with the latest entitas

**Comment by cemkoker** [comment]
thanks for the reply ! I see this is 0.38 but entitas is 0.39; will it work ?

**Comment by trumpets** [comment]
Of course! It contains Entitas 0.38.0 bundled with it. 0.39.0 release just a couple of hours ago :) I am sure Simon will update the project. But the new changes are pretty under the hood, you won't notice them :)

**Comment by cemkoker** [comment]
ok thanks ! One thing that's very confusing is the 'Pool' actually ... The videos from Unite are very outdated and it's hard to 'get started' ... Hopefully someone will post a nice step by step video ! 👍

**Comment by sschmid** [comment]
Hello and welcome! I understand that it might be not as easy to get into at the moment. A few things changed recently and I'm busy to add more features and improvements which are important to the games I'm working on full time.
The good thing is all the concepts from the Unite Videos are still valid.
There are 2 changed that might be confusing after seeing the videos
1. Pool got renamed to Context
2. Entitas is type-safe now (more info see #257)

The best way to get into Entitas is by checking out Match-One
https://github.com/sschmid/Match-One

It's up to date (0.38.0) and I will update it to 0.39.0 which I just released today.

The GameController is the starting point of the game where all systems are added. Start exploring from there.

If you have questions you can either add new issues or ask in the chat
https://gitter.im/sschmid/Entitas-CSharp

**Comment by sschmid** [comment]
Match One is updated now

**Comment by sschmid** [comment]
Fell free to re-open or create new issues if you still have questions

**Comment by sschmid** [comment]
Added link to documentation in the readme
http://sschmid.github.io/Entitas-CSharp/

**Comment by FNGgames** [comment]
Introduction, overview and systems pages are up to date on the wiki now (0.39). Systems page has some more detail. https://github.com/sschmid/Entitas-CSharp/wiki/Systems

**Comment by discofever** [comment]
I'm sorry but it's not. I have still not a simple 'hello world' kind of example ... 
https://github.com/sschmid/Entitas-CSharp/wiki/Generate-your-first-component still speaking about pool ...

Why is it so hard for you guys to put yourself in the place of someone who has no clue on how this thing work ? There are just bits here and there and no clear path on how to build a simple example; I don't know like a simple button that makes a cube move, anything ... Please ! 

That was my 2cents comment ...

**Comment by FNGgames** [comment]
Hi, I've just updated the 'Generate Your First Component' page. This should be up to date for 0.39 now too. I intend to make a little step by step 'hello world' this weekend. As has been said before, please use MatchOne as your main reference example - this is always kept up to date along with new releases (give or take a few hours).

**Comment by discofever** [comment]
Ahhhhh finally ! Now I get a glimpse of how this 'thing' works. Thank you very much, and looking forward for a good tutorial.

**Comment by FNGgames** [comment]
Basics and Attributes page should be up to date now too.

**Comment by FNGgames** [comment]
I added [Hello World](https://github.com/sschmid/Entitas-CSharp/wiki/Unity-Tutorial---Hello-World) tutorial to the wiki. Should get you step by step from a blank Unity project to a set of working systems.
