### ISSUE TITLE
Support for Entitas in different assembly

### ISSUE THREAD

**Issue by WeslomPo** [sschmid/Entitas-CSharp#341]
Hi, I have an issue with Unity version. I have an habbit to save all extensions and other stuff that I don't need to recompile regularly in "Plugins" folder (some compile time improvement). And I place Entitas in here. For my surprise it won't worked any how, despite copy paste code from examples, i try different code from wiki, tricks and etc. To my fault, this habbit is so deep in my mind, that I did not even think to change the location of Entitas to regular path (also an assurance that the code will work in any folder do the think). After hour of investigations I made some research of source code and found that entitas code generator search for assembly by IEntity interface. Of course that interface lies in a plugins folder, with all entitas sources. And that brake all the thing. Plugins folder will placed in different assembly than generator needed, and code always return 0 components and contexts.

Cheers.

**Comment by sschmid** [comment]
Hi, yes, that's true. Starting with 0.37.0 I made some steps towards deploying Entitas as a dll which could also be placed in Plugins. I'm not quite there yet, as you found correctly, the Assembly is still hardcoded with `IEntity`. In the future I could imagine to specify a path to the assembly. You can try replacing `IEntity` with a type of your assembly. For now Entitas is only tested and supported in the Assets folder

**Comment by sschmid** [comment]
Added `assemblyPath` and `codeGeneratorAssemblyPath` to code generator config. You can now select `assemblyPath` and `codeGeneratorAssemblyPath` in the Entitas Preferences. When not selected already, navigate to `Library/ScriptAssemblies/` in your Unity project and select `Assembly-CSharp.dll` for the assembly and `Assembly-CSharp-Editor.dll` for the code generator assembly (or where ever you dlls are located)
