### ISSUE TITLE
I have lost the Debug Contexts game object

### ISSUE THREAD

**Issue by trumpets** [sschmid/Entitas-CSharp#347]
Heya,

After updating to 0.40.0 I don't see the context GO anywhere in my scene. Does any of you exhibit the same behavior?

Thanks!
/ivo

**Comment by GreatVV** [comment]
I had the same problem. I just rechecked "Enable Visual Debugging" checkbox in Entitas Preferences

**Comment by trumpets** [comment]
@GreatVV nope, does not do it for me :/ I also see that threshold value in preferences. It is set to 8 by default I guess. What does it do? Maybe it is somehow connected?

**Comment by sschmid** [comment]
Check your code generators, there's a new one called `Context Observer`. I decoupled it from the previous`Contexts` generator. Let me know if that fixes it:

**Comment by sschmid** [comment]
Btw, the `Entitas.Unity.VisualDebugging.SystemWarningThreshold` belongs to this feature [Added SystemWarningThreshold to visualize slow systems](7a3a333a6b98eac8a605dc3cd294c2a2d70b8b3c)

**Comment by trumpets** [comment]
@sschmid as always you are exactly right :) btw that issue leads to a 404 for me

**Comment by sschmid** [comment]
Thanks, updated comment
