### ISSUE TITLE
Entitas 0.40.0 for Unity, Code Clones Spotted!

### ISSUE THREAD

**Issue by CuriousHub** [sschmid/Entitas-CSharp#348]
Hi there,
I'm new to Entitas. I ran a quick Solution Analyze for Code Clones in Visual Studio 2015 and spotted a few Strong, Medium and Weak code clones in Entitas 0.40.0 for Unity that might be important and need refactoring.

**1- CodeGenerator.cs (Strong Code Clones Match, Count: 2)**
_Lines 30-62         |      Method name: DryRun()
Lines 69-101       |      Method name: Generate()_

**2- DebugSystemsInspector.cs (Strong Code Clones Match, Count: 2)**
_Lines 159-180     |      Method name: drawSystemList(DebugSystems systems)
Lines 183-204     |      Method name: drawSystemList(DebugSystems systems)_

**3- DebugSystems.cs (Medium Code Clones Match, Count: 2)**
_Lines 222-232     |      Method name: StepCleanup()
Lines 203-216     |      Method name: StepExecute()_

**3- ArrayTypeDrawer.cs (Weak Code Clones Match, Count: 2)**
_Lines 41-64         |      Method name: drawRank1(Array array, etc.)
Lines 19-42         |      Method name: DrawAndGetNewValue(Type memberType, etc.)_

Hope this helps.

**Comment by sschmid** [comment]
Haha, nice :) There are tools for everything nowadays... I'm aware of those code paths, I see what I can do. None of them are critical or important imo. Let's see

Thanks

**Comment by CuriousHub** [comment]
Oh, cool, just wanted share what I found.
Let Zack delete the extra lines though :)) He mentioned in the video that he loves to delete code whenever he can :D

**Comment by sschmid** [comment]
Haha, there will be no Entitas left once he gets started deleting code :D

**Comment by sschmid** [comment]
> 1- CodeGenerator.cs

just went away naturally :D

**Comment by sschmid** [comment]
The other parts will stay like this for now
