### ISSUE TITLE
best practice of different contexts

### ISSUE THREAD

**Issue by Spy-Shifty** [sschmid/Entitas-CSharp#351]
Hi, and sry if this isn't a real issue. But I struggle with this thing. 

What is the best practice for contexts?

I have a game that has a Tilemap with some tiles  (>10.000) and their components.
I have some kind of input and humans who run around and some economy stuff ;)

So now I have created 4 context like: Tile, Humanoid, Economy and Input. But I have also some dependencies between them.. Like tiles have costs to build them up or humans need to know on which tile they are and so on.

So my question is now: Is that a good practice? Or would a single "Game" context be a better choice?

I know this question isn't that clear and easy to answer. But maybe you have a interesst point of view or even experience with that, which could maybe help me to get a better solution or to confirm my concept.

Thank you in advance
Spy-Shifty

**Comment by T2RKUS** [comment]
Instead of 'Tile' context you could call it 'Terrain', and instead of Humanoid; "AI". If systems in the AI context need to know something about the Terrain context like cost you can create an entity index to get specific information on from your context without searching through a group a comparing data that way. 

For example. If you you want which tiles have a certain cost you could index your entities by the cost and get them by doing: 
```csharp
var tiles = _terrainContext.GetAllTilesByCost(3);
foreach (var item in tiles) {    }
 ```
 or
 ```csharp
var tile = _terrainContext.GetTileByPosition(10,10); 
int cost = tile.cost.value;
```
here is an example of an entity index which adds multiple index's of the same entity taking it's size into account so that with a tile of size: width(2), height(2) would span across four positions where it overlaps.
https://github.com/sschmid/Entitas-CSharp/blob/10f27c1e42c32ab72923baae31c71cc8644f697a/Tests/Tests.Fixtures/Fixtures/CustomEntityIndex.cs

**Comment by T2RKUS** [comment]
An example of an entity index which gets a blank tile from one surface of a 6 sided cube. From my puzzle game.

```csharp
using Entitas.CodeGenerator.Api;
using Entitas;
using System.Collections.Generic;

[CustomEntityIndex (typeof (GameContext))]
public class BlankTileEntityIndex : PrimaryEntityIndex<GameEntity, int> {

    public BlankTileEntityIndex (GameContext context): base (
        "BlankTileEntityIndex",
        context.GetGroup (Matcher<GameEntity> .AllOf (
            GameMatcher.Surface, GameMatcher.Tile, GameMatcher.Blank)), (e, c) => {
            var surface = c is SurfaceComponent ? (SurfaceComponent)c : e.surface;
            return surface.id;
        }) { }

    [EntityIndexGetMethod]
    public GameEntity GetBlankTileOfSurface (int surfaceId) {
        return GetEntity (surfaceId);
    }
}
```

**Comment by T2RKUS** [comment]
here I use a custom entity index to get all valid tiles per surface. I have a system which invalidates all tiles after movement and another which goes through each surface from the blank tile. mark the adjacent tiles as valid. Later when a tile is marked with a move component I use _context.GetValidTilesOfSurface(surfaceId) to see if the clicked tile is valid. If it is I can swap it with the blank tile by using _context. GetBlankTileOfSurface(surfaceId).
```csharp
using System.Collections.Generic;
using System;
using Entitas.CodeGenerator.Api;
using Entitas;

[CustomEntityIndex (typeof (GameContext))]
public class ValidTileEntityIndex : EntityIndex<GameEntity, int> {

    public ValidTileEntityIndex (GameContext context): base (
        "ValidTileEntityIndex",
        context.GetGroup (Matcher<GameEntity>
        .AllOf (GameMatcher.Surface, GameMatcher.Tile, GameMatcher.Valid)), (e, c) => {
            var surface = c is SurfaceComponent ? (SurfaceComponent)c : e.surface;
            return surface.id;
        }) { }
    
    [EntityIndexGetMethod]
    public HashSet<GameEntity> GetValidTilesOfSurface (int surfaceId) {
        return GetEntities (surfaceId);
    }
}
```

**Comment by T2RKUS** [comment]
Lastly, my most complex lookup so far. Each surface of my puzzle cube has tiles which have local positions. there would be 6 tiles of position 0,0 so when I want to lookup a tile I need to specify a surfaceId as well so I need a more complex type as my key. when I need to look up a tile directly I use: ```_context.GetTileWithPosition(new PositionIndex(1, 10,10)); // surface 2, tile position: x(10), y(10) ```
```csharp
using Entitas.CodeGenerator.Api;
using Entitas;

using System.Collections.Generic;
using System;

public struct PositionIndex : IEquatable<PositionIndex> {

    public int surfaceId;
    public float x;
    public float y;

    public PositionIndex(int surfaceId, float x, float y) {
        this.surfaceId = surfaceId;
        this.x = x;
        this.y = y;
    }

    public bool Equals(PositionIndex other) {
        return other.surfaceId == surfaceId && other.x == x && other.y == y;
    }

    public override bool Equals(object obj) {
        if(obj == null || obj.GetType() != GetType() || obj.GetHashCode() != GetHashCode()) {
            return false;
        }

        var other = (PositionIndex)obj;
        return other.surfaceId == surfaceId && other.x == x && other.y == y;
    }
}

[CustomEntityIndex (typeof (GameContext))]
public class TilePositionEntityIndex : PrimaryEntityIndex<GameEntity, PositionIndex> {

    public TilePositionEntityIndex (GameContext context): base (
        "TilePositionEntityIndex",
        context.GetGroup (Matcher<GameEntity> .AllOf (
            GameMatcher.Surface, GameMatcher.Tile, GameMatcher.Position)), (e, c) => {
            var position = c is PositionComponent ? (PositionComponent)c : e.position;
            var surface = c is SurfaceComponent ? (SurfaceComponent)c : e.surface;
            return new PositionIndex(surface.id, position.x, position.y);
        }) { }
    
    [EntityIndexGetMethod]
    public GameEntity GetTileWithPosition (PositionIndex Index) {
        return GetEntity (Index);
    }
}
```

**Comment by T2RKUS** [comment]
Do note that If you already have an entity indexed to a certain key already you will get an exception so you you should make sure there isn't an entity already indexed with the key. for example in my puzzle game I have to move my blank tile to position -1,-1 (invalid position but a blank tile isn't rendered anyway so it's fine). then move my non-blank tile to where it was. then move the blank tile to the position the other tile was at.

**Comment by Spy-Shifty** [comment]
Many thx for your deep explanation.
That helped me a lot! 

Maybe this could be a good starting point for newbies and a place for some more experence reports!

Thanks a lot!

**Comment by T2RKUS** [comment]
You're welcome. There is something I have forgot to mention. If you try to get an entity or entities with a key which doesn't exist it will simply return null and won't throw an exception.

**Comment by sschmid** [comment]
Will close, feel free to re-open if you have further questions.
Happy coding! :D
