### ISSUE TITLE
Code Generator: Windows New Lines

### ISSUE THREAD

**Issue by marczaku** [sschmid/Entitas-CSharp#352]
When compiling and using the Code Generator on Windows machines, there will be double new lines in the header.
I have not yet investigated what causes the issues, as the rest of the generated file is not affected by this (there are no empty lines there), but the problem seems to be that there are mixed line endings in the string already (`\r\n` and `\n`) and the `NewLinePostProcessor` simply replaces all `\n` by Environment.NewLine, which is `\r\n` on Windows machines. So all Windows line endings result in `\r\r\n`
A hacky workaround is to open `NewLinePostProcessor.cs` and replace
```
file.fileContent = file.fileContent.Replace("\n", Environment.NewLine);
```
by
```
file.fileContent = file.fileContent.Replace("\r\n", "\n");
file.fileContent = file.fileContent.Replace("\n", Environment.NewLine);
```

![header-newlines](https://cloud.githubusercontent.com/assets/7360266/24396090/4e16217c-13a2-11e7-867d-664ce78976e4.png)

**Comment by sschmid** [comment]
Cool, great, Will take a look! Thanks

**Comment by sschmid** [comment]
Can't see why this should happen. The file contains `\n` only

<img width="788" alt="generated header" src="https://cloud.githubusercontent.com/assets/233700/24839540/ed30c1b8-1d5c-11e7-89a0-82ec7c59e8e0.png">

and I'm calling `.ToUnixLineEndings()`

which will do

```csharp
public static string ToUnixLineEndings(this string str) {
    return str.Replace("\r\n", "\n").Replace("\r", "\n");
}
```

Did you open and save the file and therefore overwrite with `\r\n`?

**Comment by marczaku** [comment]
You call `.ToUnixLineEndings()` at:
`CodeGenFile.cs`-Constructor, which is only called for the initial `fileContent` value.
`UnityCodeGenerator.cs`, which does not have any effect, as `WriteToDiskPostProcessor` is called before you do so.
I don't know, why it happens. There are no changes to the `AddFileHeaderPostProcessor.cs`
But it happened to me again after forking your repo and then cloning it.
I made custom modifications to the `NewLinePostProcessor.cs` again to fix that issue for now.

I can do some further investigations in a few days.

**Comment by sschmid** [comment]
ah ok, `CodeGenFile` should maybe have a setter for `fileContent`and call `. ToUnixLineEndings ()`

**Comment by marczaku** [comment]
That's a nice solution. Although I would prefer a single line ending replace in the NewLinePostProcessor.

**Comment by marczaku** [comment]
whoops :'D

**Comment by sschmid** [comment]
I don't quite understand why it happens... if `AddFileHeaderPostProcessor.cs` didn't change everything should be fine, or am I missing sth?

**Comment by sschmid** [comment]
Added a setter to
[CodeGenFile](https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration/Entitas.CodeGeneration/CodeGeneration/CodeGenFile.cs#L8-L11)

Would be nice to know, if that fixes your issue

**Comment by sschmid** [comment]
Will close, see referenced commit. Feel free to re-open when still happening in the next release
