### ISSUE TITLE
Advanced Systems API

### ISSUE THREAD

**Issue by T2RKUS** [sschmid/Entitas-CSharp#356]
right now we can only Add systems to the Systems class but not query or deactivate/activate certain features. It would be nice if we can specify a name for the system so we can turn them off or on and find out which ones are active in the simulation. like
```
_Systems.Add(new MySystem(contexts), "Optional Name");
```
so we can deactivate/activate them like so:
```
_Systems.Activate("Name");
_Systems.Deactivate("Name");
```
and be able to query which systems are active 
```
var Names = _Systems.GetActiveSystemNames();
``` 

somekind of API like that.

**Comment by T2RKUS** [comment]
From Gitter:

> @T2RKUS Until now it’s part of the design that you cannot disable systems. Ideally, they should know when they have some work to. Managing and grouping systems with the Feature class can help. A parent system can also decide (based on components) if it should execute its child systems. This is basically a way to enable and disable systems

**Comment by sschmid** [comment]
Maybe sth like this?

```csharp
public class MySystems : Feature {

    public MySystems(Contexts contexts) {

        Add(new MySystem1(contexts));
        Add(new MySystem2(contexts));
        Add(new MySystem3(contexts));
    }

    public override void Execute() {
        if (contexts.isInBattleMode) {
            base.Execute();
        }
    }
}
```

MySystems will only execute its child systems when isInBattleMode

**Comment by FNGgames** [comment]
Got to say i like @T2RKUS's API suggestion too.
