### ISSUE TITLE
Complete step by step Entitas Tutorial

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#357]
Fyi everybody, since more and more people asked for it, I was working on documentation the lasts weeks. I did a very detailed step by step Entitas tutorial with best practises for a complete Clash of Clans clone including multiple scenes, UI, multiplayer, networking and 3D assets.

**Comment by sschmid** [comment]
1st April is almost over, so I can close this issue again :D 

Repost from the chat

> sorry everyone :) couldn’t resist. But on a serious note, I actually really started writing one yesterday. I will share it with you soon. It will by a step by step guide from downloading and installing Entitas to seeing moving cubes based on user input. I will push it to GitHub and every commit is a sub step where I add features etc. This tutorial should help getting people started. After doing the tutorial Match-One should be very obvious

**Comment by charlieamer** [comment]
This still got me :(
