### ISSUE TITLE
New Entitas Logo

### ISSUE THREAD

**Issue by IsaiahKelly** [sschmid/Entitas-CSharp#361]
Decided to experiment with creating a new logo for Entitas which I think is actually turning out really nice. It's of course totally up to @sschmid if he wants to use it or not when it's done, but this experiment has made me now wonder how exactly would you actually protect a trademark for an open source project such as this?

In other words, if I create a really awesome logo and Simon decides to use it, how do we allow it to be freely used within the project, while also preventing others from stealing or misusing it?

A quick google search for "protecting open source trademarks" offers a few results about the Apache license and it's trademark protection clause. Which makes me think I'll probably need to create a similar custom license for the logo itself if I want to protect it, but who exactly should be designated the owner of the trademark? Is the project technically owned / maintained by Wooga or Simon?

I understand this is a somewhat complex legal topic, but I'm hoping some folks here with maybe experience on the subject can offer some advice. Thanks!

**Comment by sschmid** [comment]
I'd love to see the icon :D I was thinking about having a new one anyway :)

I'm not expert with licensing atm, I hope to change that soon

**Comment by IsaiahKelly** [comment]
I'm not showing it off publicly just yet because it's a simple but very unique design and I'm afraid someone else could easily copy and clam the design for themselves before I figure out how best to do this. Yes, I'm being extremely paranoid here, but always better safe than sorry. 😄 

@sschmid Probably best to send you a draft of it directly to check out anyway. Do you have any noncorporate email or private message contact address I could send it to?

**Comment by IsaiahKelly** [comment]
Oh, I also thought it would be cool to create some "Made with Entitas" splash screens for people to use in in their projects. These could then be easily added to Unity's new splash screen player. However, I'm thinking it should probably exclude the words "made with" since this would seem repetitive and confusing if seen right after "Made with Unity". So it should probably just be the logo without a prefix or "and / powered by" or something like that instead.

**Comment by sschmid** [comment]
Sounds great!
I understand, it's better safe than sorry. If you join the chat you can pm me
https://gitter.im/sschmid/Entitas-CSharp

**Comment by T2RKUS** [comment]
It's tough for us guys with low level clearance.. lol Would love to see it one day.

**Comment by IsaiahKelly** [comment]
@T2RKUS Nothing personal dude. I just don't trust randos on the internet. You may be a spam bot for all I know. 😆 You shouldn't have to wait very long in any case. Just a few years or so. 😣  I kid I kid!

**Comment by WoLfulus** [comment]
Nothing personal, but I don't get all that fear for a logo...

I'd love to release all my stuff under IDGAF license, but meh... I'll keep using MIT just like entitas :P

**Comment by IsaiahKelly** [comment]
@WoLfulus Like I said before, I'm paranoid. 😄 This is because I think I've created something very special here and I don't want to accidentally just give it and all rights to it away (outside of the project itself). If this was just a generic logo I wouldn't care at all, but I think I've really got something unique here.

My plan right now is to write a simple custom license / guideline for use of the Entitas trademarks / logos, similar to [this one](https://opensource.org/trademark-guidelines). This should be good enough to at least give the project some basic intellectual property protection. 

I'll then show it to Simon and once he's okay with it, he can add it to a future release of Entitas with or without a new logo. The main purpose will just be to ensure we have IP protection in place for any current or future IP related content. Once that is all done I'll feel a little better about sharing the new logo design.

@sschmid is there anyone in the legal department at Wooga that you could ask for advice on this topic? If this is not possible or you're not comfortable doing so then that's fine. Just throwing out some ideas here.

**Comment by sschmid** [comment]
I guess there are people at Wooga who might know more about this topic, but would be great if you could do some research if you think it's important to you.
Will close, but we can stay in contact about this
Thanks
