### ISSUE TITLE
Unclear important points in Wiki

### ISSUE THREAD

**Issue by VladislavKostin** [sschmid/Entitas-CSharp#363]
I'm loving Entitas so far, but having some trouble with understanding some concepts, and I think that introductive documentation could be improved. There are some important points that probably should be addressed or clarified in the Wiki.

1) Groups. It is unclear if any query creates a group for that particular query specifically even if multiple matchers are used. Does it happen during code generation or during runtime? 

Sidenote: If groups are created automatically, then it would make more sense to me, to call them Queries instead. For me Intuitively groups are something that should be created by the user before being able to access them. I just don't understand yet. It seems to me that groups are created automatically, and GetEntities creates a group too, so I don't understand why groups are a thing, why aren't they just a Query object in the background. Maybe makes sense when you need to delete one?

2) The execution loop is unclear. I haven't found a clear explanation of the lifecycle of entities and components. Are changes aggregated and applied at the end of the frame, or immediately. It seems very important. It leads to lack of understanding of many other systems, like collectors in reactive systems.

3) Subscribing to group events. It is briefly mentioned that it's possible to subscribe to group events. Unclear what the use case and best practices are regarding this since all the examples I've found are using collectors.

4) The very first introduction, in my opinion, should make a clear point about what is the core philosophy of ECS or Entitas is and what are the benefits of this. This is what I needed to know for example something like this: 

"In OOP there are classes which contain logic and data and references to other objects and their data. This is bad because... something-something dependancies, something-something changes, something-something breaking everything, pain (in one or two sentences).

Entitas consists of Entities, Components, and Systems. Entities consist of Components that contain ONLY data. Systems contain ONLY logic. Everything is completely separated from each other horizontally, meaning that Systems are completely unaware of each other, and data blocks also never contain any references to one another or any systems. 

Next short explanation of Contexts (such an unintuitive naming for me :) ), Groups, querying, indexing.

Next the main loop. Immutability (I still don't know in what way it is implemented, and when changes are applied to entities).

Next couple of sentences about system types, especially reactive."

I think it would be good for the new users to see this all in one shot section before going into details about any particular concept.

5) Indexing. Very important! And seems completely absent, or I somehow missed it. The question is: how to get an entity with a specific property (like a particular position, or name), and I don't see the answer in the Wiki. 

I've been given an answer, but then it seems that I have found a completely different approach in an example project. Still not sure what to make of it. I need to revisit both, read docs, and probably do some testing.

6) Maybe some techniques I've found in the example projects are worth mentioning somewhere in the Wiki. Like using static classes for common logic between different systems. And maybe it should be mentioned that there are certain things that should not be done, like keeping state variables inside systems and stuff like that. Some basic do's and don'ts.

**Comment by VladislavKostin** [comment]
Nevermind the [1. Sidenote] I forgot about group events. But still a bit unintuitive that groups are created in the background when they are requested, and I would mention it in the Wiki. I mean you do say that they are cached, but maybe I'm too dumb to be sure what that means :)

**Comment by sschmid** [comment]
Hey, thanks for the feedback. These are all good points and I try to address all of them in the step-by-step tutorial I'm currently working on.

**Comment by VladislavKostin** [comment]
Awesome! Thanks. And one more:

7) Context separation. Also a big question. I see I'm not the only one who has that question, but I haven't found an explanation that gives an understanding necessary to be able to decide how many contexts to use and what are the implications of having multiple contexts. When should I separate them and when I should not?

**Comment by sschmid** [comment]
Jep, will all be part of the tutorial. In the meantime:
Multiple Contexts, an attempt to explain:
https://github.com/sschmid/Entitas-CSharp/issues/105#issuecomment-213925457

**Comment by VladislavKostin** [comment]
Cool. Thank you.
