### ISSUE TITLE
Entitas-lang "Connection to server got closed"

### ISSUE THREAD

**Issue by VladislavKostin** [sschmid/Entitas-CSharp#366]
Following instructions in the Wiki, I tried using Entitas-lang, twice, and I'm getting this when opening ".entitas" files:

[The Entitas Lang Server server crashed 5 times in the last 3 minutes. The server will not be restarted.]

[Info  - 12:16:28 PM] Connection to server got closed. Server will restart.
[Info  - 12:16:28 PM] Connection to server got closed. Server will restart.
[Info  - 12:16:28 PM] Connection to server got closed. Server will restart.
[Info  - 12:16:28 PM] Connection to server got closed. Server will restart.
[Error - 12:16:28 PM] Connection to server got closed. Server will not be restarted.

**Comment by AllanSamurai** [comment]
I think its java runtime requirement. if not installed install restart and try again?

**Comment by VladislavKostin** [comment]
Well, thank you, that did something because now I get:

`[Error - 1:53:41 PM] Server initialization failed.
  Message: java.lang.reflect.InvocationTargetException
  Code: -32603 `

**Comment by sschmid** [comment]
cc @mzaks

**Comment by mzaks** [comment]
@VladislavKostin can you post a sample `.entitas` file you get this crash on?

**Comment by VladislavKostin** [comment]
@mzaks Oops, sorry. When the first error was happening, I renamed the file, I don't remember why. Now I changed the name to what it's supposed to be, and it works.

Thank you for the quick response. 

Wiki probably needs to mention the java runtime requirement. At least there is a wrong link to VS extension installation instructions, so I just googled to find out how to install the .vsix file, and if java was mentioned on VS website, that's why I missed it.

**Comment by mzaks** [comment]
@VladislavKostin the requirement is directly from the AddOn no from VS so you are right we should add it to the wiki.

**Comment by mzaks** [comment]
Point 4 now describes the dependency on Java Runtime
https://github.com/sschmid/Entitas-CSharp/wiki/Tutorial-‐-Entitas‐lang#1-using-visual-studio-code

**Comment by VladislavKostin** [comment]
Cool. Note that point 3 link is wrong or redirects to: [http://code.visualstudio.com/docs/extensions/publish-extension
](http://code.visualstudio.com/docs/extensions/publish-extension
)

**Comment by mzaks** [comment]
Hm ... seems like they changed something on the VisualStudioCode side. Can you share the link which you used to get infos how to install the plugin?

**Comment by VladislavKostin** [comment]
That was a part of some random post somewhere. You can just give instruction to open the command line in VS Code (Ctrl+Shift+P) and type in: "install from VSIX" then locate the downloaded previously extension file.

**Comment by mzaks** [comment]
OK that's new :)
I will than write it this way in the Wiki

**Comment by VladislavKostin** [comment]
I'm totally nitpicking here, but I hate that my poor word selection is now in the Wiki, so I would better word it like this: "Open the command line in VS Code (Ctrl+Shift+P) and enter the following command: "install from VSIX" Then locate and select the downloaded extension file." 😄

**Comment by sschmid** [comment]
Hey, I will redirect you to the official Entitas-Lang GitHub repo which is maintained by @mzaks

https://github.com/mzaks/Entitas-Lang

If you have further questions, feel free to create an issue on this repo.
Thanks
