### ISSUE TITLE
non-Unity C# example

### ISSUE THREAD

**Issue by Serris** [sschmid/Entitas-CSharp#367]
all the examples in https://github.com/sschmid/Entitas-CSharp/wiki/Example-projects use Unity.

It would be helpful to have a non-Unity example there.

**Comment by sschmid** [comment]
Hi!

For c# only projects I only have a minimum project with one component here
https://github.com/sschmid/EntitasPure

But all the concepts are the same. Looking at the Unity projects should help you getting started with c# only, too, I hope.

**Comment by sschmid** [comment]
Fyi, a new command line code generator will come very soon. The EntitasPure example currently has a separate project for the code generator. This will go away in the future in favour of a standalone command line tool. Just to let you know

**Comment by sschmid** [comment]
The starting point in a c# project is the Main class. Take a look at the GameContoller.cs from the Unity projects, they are basically the entry point.

**Comment by Serris** [comment]
okay, thanks for the quick reply. I'm having some trouble setting up Entitas within Monogame, but i'll try the other way around, using that EntitasPure example and modify that to use Monogame.

**Comment by sschmid** [comment]
If you need further help, let me know.
If you have a basic project working, maybe you want to share it with the community. It might be helpful for other people using monogome, too. You can let me knoe

**Comment by anhle128** [comment]
hi, I'm try to add generate code to pure C# project, following by this tutorial : https://github.com/sschmid/Entitas-CSharp/wiki/Entitas-pure-C%23
But I don't find any Jenny.zip in Entitas release version 1.13.0 and 1.12.2
I wonder whether or not it will be removed in latest release version
Can u help me ?
Thank you

**Comment by sschmid** [comment]
@anhle128 Jenny.exe is currently only included in the Unity Asset Store version. But it works without Unity, too. 
http://u3d.as/NuJ
