### ISSUE TITLE
Refactoring tools

### ISSUE THREAD

**Issue by VladislavKostin** [sschmid/Entitas-CSharp#368]
Why not allow Entitas, if it's currently possible, or Entitas-lang to rename all the calls to generated classes?

People who are just starting to use ECS, and Entitas in particular, are going through the process of learning and establishing component-system organizing and naming practices, and that means a lot of renaming, and it is a pretty painful process to change all the calls to multiple different generated API elements for each component or system.

Also Entitas-lang seems to be not cleaning up the generated code for deleted components.

I think I missed something or got something wrong, but you get the idea.

**Comment by VladislavKostin** [comment]
Also, could Entitas-lang generate the System files automatically, so all I would have to do is to fill them in and maybe move?

Ideally of course Entitas-lang would have settings for directories and .entitas file names.

**Comment by T2RKUS** [comment]
Couldn't you just use the ctrl + R function in visual studio or the ctrl + f replace?

**Comment by sschmid** [comment]
@VladislavKostin You mean when `UserComponent`gets renamed to `PlayerComponent` you want that Entitas renames all occurrences of AddUser, ReplaceUser and RemoveUser to AddPlayer, etc, right? I was thinking about that for a while now. This is sth we can achieve with roslyn where we actually can do safe refactoring based on symbols. This would be an additional refactoring tool. It would definitely make sense.

**Comment by sschmid** [comment]
cc @mzaks dod you have an Entitas-Lang repo where we can add related issues?

**Comment by VladislavKostin** [comment]
@sschmid Yes.

@T2RKUS Yes, Ctrl+Shift+F works, when there are no name collisions. Then file names... 

Ideally working in Entitas-Lang there would be an F2 rename command, and it would do all the refactoring. And "Go To Definition" would send you to the implementation of the system, which, again would be generated automatically. 

Those quality-of-life features would save a lot of time and effort, especially to newbies like me.

**Comment by sschmid** [comment]
@VladislavKostin Agree, this feature is on my wish-list too :) Would be very convenient.

**Comment by sschmid** [comment]
I'd be happy to accept PRs :D While this feature is also on my wish list it's currently not planned. Will close, but might re-open at some point in the future.
