### ISSUE TITLE
Improved Blueprint Inspector

### ISSUE THREAD

**Issue by IsaiahKelly** [sschmid/Entitas-CSharp#369]
I'm currently working on updating the Entitas Blueprint inspector in Unity since I think there's plenty of room for improvements here.  I would also like to contribute a new Blueprint formatter eventually, but I don't understand the system well enough to do anything in that area yet. 

I can see someone already "stole" my idea of making the search field match Unity's search bar style, but there's still one other little detail missing from it that I will try to add before anyone else gets to it. 😄 

I'll post some screenshots here to show off the improvements soon and get feedback on certain changes. I personally don't like the component color coding and plan to add a new style closer to Unity's own component inspector, but I will keep the current style as an alternative for those who actually prefer it.

**Comment by IsaiahKelly** [comment]
Here's an idea: What if instead of expandable panels for each component, we had a dedicated area below the entire list of components that would show properties of the currently selected component only? This would function very much like Unity's Quality Settings levels inspector, and the list of components could be scroll-able to save space. 

Would this be an improvement or is there a real need to always be able to edit multiple components simultaneously?

**Comment by sschmid** [comment]
In my workflow I need to be able to see many components at a glance and often modify multiple components. That shouldn't change.

Any progress, otherwise feel free to close
Thanks

**Comment by IsaiahKelly** [comment]
I've made good progress on this, but I currently cant test any of my changes because I still haven't found a way to build and copy the DLLs into Unity on Windows.

**Comment by sschmid** [comment]
Wanna share screenshots to see if it's going in the right direction?

**Comment by IsaiahKelly** [comment]
I'm gonna close this issue for now. I'll reopen this if / when I fix my issues with the source code.
