### ISSUE TITLE
[Enhancement] Code Generator as DLL

### ISSUE THREAD

**Issue by gjroelofs** [sschmid/Entitas-CSharp#37]
I'd like to request that the Code Generator aspect of Entitas be packaged as a binary for consumption.

The reasoning behind this is to avoid cases where any automated tooling might break code within the Code Generator, as any crash during the code generation results in an uncompilable project.
I personally had this happen due to a careless mistake where Resharper wanted to refactor "Tag" into "EntityTag" and included one of the string matchers used in the Code Generator library.

Packaging the Code Generator as a binary should not be an issue as it's the part of the project that does not need to be altered during generation. The common consumers of the package don't need to alter the Code Generator, as they depend on its robustness.

**Comment by chrischu** [comment]
Good idea, but just as a general tip you should probably exclude generated code folders from ReSharper analysis.

**Comment by gjroelofs** [comment]
I completely agree, and it is standard practice in general.
However mistakes do happen, and the intent is to limit the damage that can be caused by them.

And the issue happened because the Code Generator code was altered, not the generated code. :-)
(Still, your point stands, obviously :+1)

**Comment by sschmid** [comment]
We plan to release the next version of the (probably roslyn based) code generator to be a precompiled executable. Thanks for your feedback!

**Comment by sschmid** [comment]
Hey, I plan to release the current reflection based code generator as a dll, too. Will be in the next release :+1:
