### ISSUE TITLE
Shortcuts for unique components

### ISSUE THREAD

**Issue by VladislavKostin** [sschmid/Entitas-CSharp#370]
[EDIT] Nevermind. Can anyone delete this issue?

Accessing unique components via shortcut methods in contexts like this:

```
var time = _gameStateContext.GetTimeSinceWaveStarted().value;

_gameStateContext.ReplaceCurrentLevelIndex(2);
```

Would make a lot of sense to me to be able to do that. Much like static methods in classes. 

When those methods are called if the component doesn't exist it could be created automatically on a new separate entity.

When I first read about unique components I thought that this is how they work. Feels weird to me to query for an entity which I know exist to get a list of them, only to get one component which I know exist or should exist.

Even if somebody doesn't like this API it could have its own attribute [Static] instead of [Unique].

**Comment by T2RKUS** [comment]
You can already do that.

**Comment by VladislavKostin** [comment]
Oh, I see... It must be that Entitas-Lang does not support it. That's a disappointment.. 

And I can't move just part of my code to Entitas, I'll have to abandon it if I want the unique components and index attributes.

**Comment by VladislavKostin** [comment]
Wait, not even that, I might be just using it wrong.

**Comment by VladislavKostin** [comment]
Turns I was using some wrong syntax when testing it.

**Comment by IsaiahKelly** [comment]
@VladislavKostin You should be able to close your own issue by clicking the "Close Issue" button at the bottom.

**Comment by VladislavKostin** [comment]
I see, thx.
