### ISSUE TITLE
Entitas-Lang: Support for entity indices

### ISSUE THREAD

**Issue by awalltoo** [sschmid/Entitas-CSharp#371]
Entitas 0.40 added support for the attributes [PrimaryEntityIndex] and [EntityIndex].  These are really handy for replacing a bunch of code that was previously needed to use to generate those indices.  However, as far as I can tell, Entitas-Lang does not have any way to add those attributes to fields in components.  Is this something that could be added to Entitas-Lang in the near future?

Thanks!

**Comment by sschmid** [comment]
cc @mzaks Did you push Entitas-Lang to a GitHub repo already where we can post related issues?

**Comment by sschmid** [comment]
Hey, I will redirect you to the official Entitas-Lang GitHub repo which is maintained by @mzaks

https://github.com/mzaks/Entitas-Lang

Please create an issue on this repo.
Thanks
