### ISSUE TITLE
Blueprints in Entitas-Lang

### ISSUE THREAD

**Issue by VladislavKostin** [sschmid/Entitas-CSharp#372]
So, blueprints currently are not supported in EntitasLang? 

They don't work and every time on compile I get this exception: 

NullReferenceException: Object reference not set to an instance of an object
Entitas.Unity.Blueprints.BinaryBlueprintInspector.<UpdateAllBinaryBlueprints>m__2 (IContext context) (at Assets/Libraries/Addons/Entitas.Unity.Blueprints/Editor/BinaryBlueprintInspector.cs:37)
System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[Entitas.IContext,System.String].MoveNext ()
System.Collections.Generic.List`1[System.String].AddEnumerable (IEnumerable`1 enumerable) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:128)
System.Collections.Generic.List`1[System.String]..ctor (IEnumerable`1 collection) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:65)
System.Linq.Enumerable.ToArray[String] (IEnumerable`1 source)
Entitas.Unity.Blueprints.BinaryBlueprintInspector.UpdateAllBinaryBlueprints () (at Assets/Libraries/Addons/Entitas.Unity.Blueprints/Editor/BinaryBlueprintInspector.cs:37)

I'm sure it's a known issue, and I'm currently not using blueprints anyway because of serialization issues, but I'm really looking forward to using Entitas-Lang with full set of Entitas features and reliable blueprints.

**Comment by sschmid** [comment]
Hey, I will redirect you to the official Entitas-Lang GitHub repo which is maintained by @mzaks 

https://github.com/mzaks/Entitas-Lang

Please create an issue on this repo.
Thanks
