### ISSUE TITLE
ScriptableObjects as Blueprints

### ISSUE THREAD

**Issue by VladislavKostin** [sschmid/Entitas-CSharp#373]
Why not just generate scriptable objects and use them as blueprints? I slapped together some example of a code that could be generated:

```
// Everything should be generated.
using UnityEngine;
using Entitas;

// Level is the name of the context.
[CreateAssetMenu(fileName = "LevelBlueprint", menuName = "Entitas/LevelBlueprints", order = 1)]
public class LevelBlueprint : ScriptableObject
{
    [SerializeField] [SomeDrawer] private bool isTile;
    [SerializeField] [SomeDrawer] private bool isPath;
    [SerializeField] [AnotherDrawer] private TilePosition tilePosition;
    [SerializeField] [ThirdDrawer] private Prefab prefab;

    public void Apply(LevelEntity entity)
    {
        entity.isTile = isTile;
        entity.isPath = isPath;
        if (tilePosition.exists)
        {
            entity.AddTilePosition(tilePosition.x, tilePosition.z);
        }
        else if (entity.hasPosition)
        {
            entity.RemovePosition();
        }
        if (prefab.exists)
        {
            entity.AddPrefab(prefab.value);
        }
        else if (entity.hasPrefab)
        {
            entity.RemovePrefab();
        }
    }

    public Entity CreateEntity()
    {
        LevelEntity entity = Contexts.sharedInstance.level.CreateEntity();
        Apply(entity);
        return entity;
    }

    // Generated from components.
    [System.SerializableAttribute]
    private struct TilePosition
    {
        public int x;
        public int z;
        public bool exists; // Added to indicate if it is "null" since it can't actually be null.
    }

    [System.SerializableAttribute]
    private struct Prefab
    {
        public GameObject value;
        public bool exists; // Added to indicate if it is "null" since it can't actually be null.
    }
}

// Original component.
// public sealed class TilePositionComponent : IComponent
// {
//     private int x;
//     private int z;
// }
``` 
This one actually works, just put property drawers on top and it seems to be a fully-functioning blueprint with Unity serialization. No problems. Right?.. 

![34t3](https://cloud.githubusercontent.com/assets/14858947/24831834/a725bb86-1caa-11e7-9734-f96b0dad0ebb.PNG)

**Comment by T2RKUS** [comment]
That's a good idea actually, If Blueprints are supposed to be a unity only thing but currently a blueprint is wrapped within a scriptableobject and draw using inspector code. This way you could load a blueprint from file and apply it that way as well.

**Comment by VladislavKostin** [comment]
You mean someone wants to use blueprints in non-Unity apps? If that is the case then current blueprints probably already work for them. In Unity, it is far better to have things serialized by Unity itself.

This one can be wrapped too, I imagine, but I would probably just implement this system this way for Unity as Entitas plugin. But I need help. I have no experience with reflection, so I think code generation will be hard for me.

Unless current blueprints can be as reliable and are easier to make work, and unless they also can serialize everything these can, I think this is a good way to go. These potentially support even refactoring with [FormerlySerializedAs].

**Comment by VladislavKostin** [comment]
Actually, game state saving and blueprint-integrated system seems pretty simple.

- Generate serializable versions of all components. 
- Generate a class like a blueprint in the initial post but not Unity-specific, use it as C# blueprint.
- Wrap one version of this class into ScriptableObject just like in the example above, for Unity blueprint.
- Have a system that would serialize and deserialize either version into a set of entities.
- Have a method that will serialize a list or a group of entities using these systems.
- This would make a very easy to use runtime serializer out of the blueprint system.

- Optionally, have a [SerializeComponent] or [DoNotSerializeComponent] attributes to mark components that you want to be serialized during runtime. But serialize all for the blueprints.

**Comment by IsaiahKelly** [comment]
I'm sure it has something to do with "portability" here, but I've been studying Blueprints lately and thought about doing something like this myself since I noticed Blueprints don't currently support Unity undo operations and switching context erases all blueprint components! 

This is really ridiculous and annoying, but I believe replacing the binary formatter should fix all that and I hope to help in this area eventually, but I still don't know enough about the system yet contribute anything. I have however at least been able to fix some aspects of the blueprint inspector already.

**Comment by VladislavKostin** [comment]
I think it can be portable by breaking down in 2-3 files and just using a ScriptableObject as a wrapper, but it might be easier to just generate Unity version separately. Internally they both would implement the same interface, so it is just a matter of one code generator addon for Unity. Blueprints are already pretty unity-specific at least partially.

**Comment by sschmid** [comment]
Fyi, due to #390 I cannot work on blueprint related issues. Blueprints can become a community supported feature.

**Comment by VladislavKostin** [comment]
I think I have read in the chat that someone was implementing something like this. Whoever it was, please respond here if you have some progress or have it working already :smile:

**Comment by pixeption** [comment]
@VladislavKostin Not sure but is it me or someone else?

**Comment by VladislavKostin** [comment]
@pixeption Idk, possibly, were you working on this, how is it going?

**Comment by VladislavKostin** [comment]
This would make a good Entitas Plus feature :)

**Comment by VladislavKostin** [comment]
It's not going anywhere for now. Should I close it? 😄

**Comment by Arpple** [comment]
I still want this to happen because I now use scriptableobject as blueprint by manually create it.
so it will be awesome if I can generate it instead.
I really want to help on this if I can :D

**Comment by pixeption** [comment]
@VladislavKostin sorry for late response

Actually I worked on something different, I don't want blueprint as scriptable object, I want to attach entitas components into GameObject (For example many game level require design on Editor for productivity). 

At the end I gave up (although it can run) since it is contained many cheat code & limited when using Unity serialization.

Writing code to generate scriptable object as blueprint is not hard, you can check how blueprint generate in source code and do the same thing. (actually I learn a lot of reflection and code generation via entitas)

**Comment by VladislavKostin** [comment]
@pixeption Isn't it the same code though? Mine and what you tried to achieve? Just change  ``` : ScriptableObject``` to ``` : MonoBehaviour``` and you can use it on game objects. And it is easy to implement yes. Problem is that for me it won't save any time doing so, but when someone will do this it will save time to a lot of people and improve workflow in the editor. Wink-wink nod-nod to @sschmid again :) It would be a great Plus/Pro/Delux feature.

**Comment by pixeption** [comment]
@VladislavKostin It's actually difference.
Blueprint is like a template and can't change (if we change, we change all object), prefab does. I want to add entitas component just like monobehaviour did and with each different object, the number of components and values are difference.

I succeed at serialize entitas component using Unity Serialization via many tricks.

Here is a demo but i don't think this is a good approach, maybe I'll think about another approach
<img width="378" alt="screen shot 2017-05-18 at 12 09 51 am" src="https://cloud.githubusercontent.com/assets/10240918/26166701/886ddc14-3b5e-11e7-8b54-bc7c0cafca2b.png">

**Comment by c0ffeeartc** [comment]
Had same idea was going to post it then saw this issue %)

The idea is Blueprint->Proto->Clone. Blueprint creates Entity Prototype, that can be Cloned.

Blueprint:ScriptableObject contains all Components of Context, and Flags field to filter display and creation.

Here is what I had in mind:
```
using System;
using System.Collections.Generic;
using Entitas;
using Entitas.Utils;
using UnityEngine;

namespace Assets.Custom.Scripts
{
    [CreateAssetMenu( menuName = "Custom/EntityBlueprint" )]
    public class EntityBlueprint: ScriptableObject
    {
        [SerializeField]
        private				List<Int32>				_componentFlags			= new List<Int32>(  );
        [SerializeField]
        private				HealthComp				_health					= new HealthComp(  );
        [SerializeField]
        private				PositionComp			_position				= new PositionComp(  );
        [SerializeField]
        private				ViewComp				_view					= new ViewComp(  );
        private				Entity					_proto;
        private				Entity					Proto
        {
            get
            {
                return _proto ?? ( _proto = CreateProto(  ) );
            }
        }

        public				Entity					CreateClone				(  )
        {
            return Contexts.sharedInstance.gameC.CloneEntity( Proto );
        }
        private				IComponent				GetComponent			( Int32 index )
        {
            switch ( index )
            {
                case 0: return _health;
                case 1: return _position;
            }
            return null;
        }
        private				Entity					CreateProto				(  )
        {
            var proto = Contexts.sharedInstance.gameC.CreateEntity(  );
            foreach ( var index in _componentFlags )
            {
                var component = GetComponent(index);
                var newComponent = proto.CreateComponent(index, component.GetType());
                component.CopyPublicMemberValues( newComponent );
                proto.AddComponent(index, newComponent);
            }
            return proto;
        }
    }
}
```
