### ISSUE TITLE
[CodeGenerator:] Use the new IConfigurable interface

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#376]
Entitas 0.41.1 introduced `IConfigurable` which enabled data providers, code generators and post processors to have additional configuration and additional optional keys in `Entitas.properties`.

E.g. you can now add `Entitas.CodeGeneration.Plugins.IgnoreNamespaces = true` in instruct the code generator to ignore namespaces.

Migrate all existing plugins to use `IConfigurable`

**Comment by kdrzymala** [comment]
How do you use Entitas.CodeGeneration.Plugins.IgnoreNamespaces = true ?
I just uprgaded to the 0.41.1 version, added that line to Entitas.properties file, hit generate but the generated components still contain the namespace.
I am clearly missing something here. Is there anything else I need to do first?

**Comment by sschmid** [comment]
Hey, I just check real quick, seems like I forgot to actually call `Configure` on the generators 🤦‍♂️ . Will fix it for the next version

**Comment by kdrzymala** [comment]
:)
Can I patch it myself somehow till the new version arrives?

**Comment by sschmid** [comment]
Yes, if you fork and and compile yourself. The easiest would be to change the default to `true`, meaning it should ignore namespaces

Search for `bool ignoreNamespaces { get`

https://github.com/sschmid/Entitas-CSharp/search?utf8=✓&q=%22bool+ignoreNamespaces+%7B+get%22&type=

and check against `false` instead of `true`

**Comment by sschmid** [comment]
I will make this more centralised and less duplicate code see #376

**Comment by kdrzymala** [comment]
awesome thanks, got it working this way 👍
