### ISSUE TITLE
Reorganize Wiki

### ISSUE THREAD

**Issue by VladislavKostin** [sschmid/Entitas-CSharp#377]
Currently, it is very inconvenient to look for a specific information in the Wiki, because it is fragmented and duplicated and incomplete as I've mentioned before. To find information about some elements I have to search for it in multiple categories of the Wiki with ambiguous names (and then load an example project and look there also). For example, Groups are in Introduction and The Basics. Collectors are in the Overview where they don't really belong in my opinion. Systems are not fully demonstrated on the Systems page, the complete use examples are given only in tutorials.

I suggest making Introduction very brief and explaining the core principle and advantages of Entitas. Then to have a separate page for every class or concept.

Introducing the Entitas
- Overview (core concepts, phylosophy, advantages)
- Core concepts (optional. very short version of the manual)
- Unity Integration

Manual
- Download and Installation
- Entities and Components
- Contexts
- Systems
- Groups
- Collectors
- Attributes
- Indexes

Tutorials and Projects
- "Hello World" Tutorial
- "Match One" Tutorial (would be nice to have that)
- "Advanced concepts tutorial" (possibly another tutorial covering anything that was left out)
- ExampleProjects

Additional (placeholder name)
- Addons
- Blueprints (beta)
- CodeGeneror (doesn't belong in introduction)
- Entitas-Lang (link leading to its repository)
- Roadmap

Video
- 1
- 2
- 3

**Comment by VladislavKostin** [comment]
Is there some sort of version control for the Wiki? I'd like to participate in reorganizing it, I'd make a general structure and fill it in with existing text or placeholders.

**Comment by sschmid** [comment]
@VladislavKostin Great, thanks. Yes the wiki is a git repo, too

**Comment by VladislavKostin** [comment]
This is the general structure. I want to get more experience working with Entitas first, then I might get my hands on the Wiki directly and submit some of my suggestions.

**Comment by sschmid** [comment]
Will close and gather docs / wiki related things here
#333
