### ISSUE TITLE
Components and namespace

### ISSUE THREAD

**Issue by zehreken** [sschmid/Entitas-CSharp#379]
I am checking v0.41 lately. After working a lot with v0.35, the new features are very welcome. I use namespaces as a convention. The problem is after generating components, the variable name for the component is the whole namespace combined with the component name. Is it intended or am I doing something wrong?
Example:
`namespace Name.Space.Test
{
	public class TestComponent : IComponent
	{
public int value;
}
}`
The generated name for this component is 'NameSpaceTestTest'.

**Comment by FNGgames** [comment]
See [Release 0.41.1](https://github.com/sschmid/Entitas-CSharp/releases). There's a new cfg variable that you can set to ignore namespaces when generating the API.

**Comment by sschmid** [comment]
@zehreken Added this feature in 0.41.1. Unfortunately I'm not calling the method to actually ignore the namespaces. Will fix this in the next release.
In the meantime checkout this comment for a workaround 
https://github.com/sschmid/Entitas-CSharp/issues/376#issuecomment-293275956

**Comment by sschmid** [comment]
Here's why the code generator includes namespace now
 #323
