### ISSUE TITLE
[Enhancement] Code Generator failure checks

### ISSUE THREAD

**Issue by gjroelofs** [sschmid/Entitas-CSharp#38]
AFAIK, at the moment the (Unity) code generation first deletes the generated code folder as it assumes that execution of the code generation will happen without faults or errors.

I suggest that we first write to a temporary folder and not replace/remove the code generated folder without confirmation of a successful execution of the Code Generator. (Exceptions / errors)

**Comment by sschmid** [comment]
That totally makes sense. I will definitely consider your idea in the new version of the code generator!
