### ISSUE TITLE
Code Generator freezes "[Dry Run] Creating Model"

### ISSUE THREAD

**Issue by Adjuvant** [sschmid/Entitas-CSharp#381]
Hello again! 

I'm using Entitas Unity 0.39.0, on OSX with Unity 5.5.2f1. Stuck with 39 as it was stable till now and my deadline put me off changing.

**Issue:** Reopened project, change a file, compiled ok, pressed generate on entitas and freezes. 
The freeze blocks out copy-paste unfortunately.
![screen shot 2017-04-13 at 13 57 42](https://cloud.githubusercontent.com/assets/5750541/25005541/418f5aac-2051-11e7-967f-0831acf532ff.png)
Subsequently I have: 
Force quit unity, restart, same issue. 
Tried updating to new version of entitas 0.41.1, same problem after untangling compile errors.
Moved to backup project, prior to any fault occurring (4days ago), same deal. 
Totally stuck with what to do now.

Is it issue with Code Generator accessing mono? Is it my Unity?

Any one had similar issues? Any ways to fix without cleaning out the whole of entitas and starting again? 

Thanks!

**Comment by sschmid** [comment]
Can you post your Entitas.properties file, it's in the root folder of your project.

Ok, I checked, seems weird:
Based on your exception `type.FullName` is null
https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas.Utils/Entitas.Utils/Utils/Extensions/TypeSerializationExtension.cs#L17

which I never saw before. Seems like it couldn't reflect the type correctly. Also seems like you're using a generic type for a component, is that correct? If so, that's not supported

**Comment by sschmid** [comment]
So my suggestion, check if you have generic components and remove them

**Comment by Adjuvant** [comment]
Amazing, thanks so much! Compiled, generated, built and run, successful! 

I did create a component with a generic, but it had a "DontGenerate" tag. That must have been ignored somehow. 

Owe you big! Anything on the wiki need done?

**Comment by sschmid** [comment]
:D Great to hear! Anything on the wiki is up for grabs :D
#333 

Hope everything works fine for you now! If you have further questions feel free to ask anytime.
