### ISSUE TITLE
InvalidOperationException in Blueprints

### ISSUE THREAD

**Issue by AlexeyJKoshkin** [sschmid/Entitas-CSharp#382]
I don't have any blueprints. I uncheck everything with them, but always after compiling project i have this message.
![image](https://cloud.githubusercontent.com/assets/3306190/25082932/84f90078-235c-11e7-8580-eb7b9cf4a71a.png)

**Comment by sschmid** [comment]
Hi, can you check your Entitas.properties and remove `Entitas.Blueprints.CodeGeneration.Plugins`

Are you using Unity?

**Comment by AlexeyJKoshkin** [comment]
Yes. It's unity 5.6.0.f3. I deleted Entitas.Blueprints.CodeGeneration.Plugins and still have this exception

**Comment by sschmid** [comment]
That's weird. Have you generate at least once? Is there at least one context?

**Comment by AlexeyJKoshkin** [comment]
Yes. I have several projects with different count of context. 1,3 and 6. And all this projects catch this exception.
And different unity version 5.6.0.f3 and 5.5.2.

**Comment by sschmid** [comment]
Just to make sure I understand:
You deleted `Entitas.Blueprints.CodeGeneration.Plugins`
Entitas.properties doesn't contain the plugin `Entitas.Blueprints.CodeGeneration.Plugins`
after Unity is done compiling it throws that error?

**Comment by AlexeyJKoshkin** [comment]
Yes :-) I did everything.
Some unity Magic ;-)

**Comment by sschmid** [comment]
Ok :D Since you're not using Blueprints anyway, you can just delete all Entitas.Blueprints.* dlls

**Comment by AlexeyJKoshkin** [comment]
heh :-) Everything working :-)

**Comment by sschmid** [comment]
Awesome! I leave this issue open so I can take a look at this later!
Happy coding :D

**Comment by sschmid** [comment]
Will close and check at some point. Binary Blueprints currently don't have a high prio unfortunately. See #267

**Comment by AlexeyJKoshkin** [comment]
Mark. When deleted blueprints libraries imposible to use codegenarator. "Couldn't load assembly ..."
I think it should be warning message or something like this.
