### ISSUE TITLE
Entity array index.

### ISSUE THREAD

**Issue by VladislavKostin** [sschmid/Entitas-CSharp#384]
Are entity indexes currently working only as dictionary lookups? In some cases, anything short of an array is pretty bad for performance. (Example: building game with 2D - 3D arrays of blocks, games with a lot of pathfinding or querying of tile grid data.) 

Can Entitas generate arrays of entities to allow querying them? 

Maybe syntax would look like that:

    [EntityArrayIndex(0)] 
    int x;
    [EntityArrayIndex(1)] 
    int y;

Or sometimes better like that:

    public sealed class PositionComponent : IComponent
    {
        [EntityArrayIndex3] 
        IntVector3 value;
    }

    public struct IntVector3 : IArrayIndex3
    {
        public int x, y, z;
        
        public GetArrayIndex3 (out x, out y, out z)
        {
            x = this.x; 
            y = this.y;
            z = this.z;
        }
    }

Which allows you to get 3D array index (in this case) from a component. Will generate method:

    var e = GetEntityWithPosition(x, y, z)  var e = GetEntityWithPosition(new IntVector3(x, y, z));

Maybe this is silly but here it is:

    public struct IntVector3 : IArrayIndex3
    {
        public int x, y, z;
        
        public Entity IArrayIndex3:GetEntityFromArray3 (Entity[,,] entities)
        {
            return entities[x, y, z]
        }
    }

Sometimes you want to have more than one entity with the same index (which is possible with the current lookup system, as far as I understand) so maybe in those cases, an array can internally be an array of lists of entities, but I'm not sure how to differentiate between the two in API.

    [ListArrayIndex(0)] vs [ArrayIndex(0)] (?)

**Comment by sschmid** [comment]
Yes, in performance critical areas that makes sense. Our indices used for pathfinding are also based on arrays. We implemented our custom array IEntityIndex and added a few custom EntityIndexAttributes to generate.
I currently can't squeeze in this feature though and would recommend implementing a custom solution.
As a start you can implement `IEntityIndex` and use the `CustomEntityIndex` attribute for generation.

**Comment by VladislavKostin** [comment]
Thank you. I'll look into it. I'm not actually gonna be using Entitas for a while until I finish my current game. I'm thinking about my next game, so I hope that maybe you'll find the time to implement this by then (prob 4 months at least).

**Comment by VladislavKostin** [comment]
But currently, Entitas supports that kind of thing via IEntityIndex? Just not as a single attribute? In that case that won't be a problem, as long as it is integrated with Entitas and I don't need to hack that kind of solution in.

**Comment by sschmid** [comment]
Will close, implement `IEntityIndex` and use [CustomEntityIndex] for custom entity indices.
