### ISSUE TITLE
Define Symbols: Requested build target group (27) doesn't exist

### ISSUE THREAD

**Issue by KumoKairo** [sschmid/Entitas-CSharp#385]
Entitas 0.41.1 (also happens on 0.40.0)
Unity 5.6.0f3

`PlayerSettings Validation: Requested build target group (27) doesn't exist; #define symbols for scripting won't be added.
UnityEditor.PlayerSettings:SetScriptingDefineSymbolsForGroup(BuildTargetGroup, String)
Entitas.Unity.Editor.ScriptingDefineSymbols:AddDefineSymbol(String)
Entitas.Unity.Editor.EntitasPreferencesDrawer:drawContent(Config)
Entitas.Unity.Editor.AbstractPreferencesDrawer:Draw(Config)
Entitas.Unity.Editor.PreferencesWindow:drawPreferencesDrawers()
Entitas.Unity.Editor.PreferencesWindow:OnGUI()`

Steps to reproduce - 
 - Got to Entitas -> Preferences
 - Change Automatic Entity Reference Counting to Fast and Unsafe (or back to Safe depending on a situation)

27 is Switch target, I'm looking to a way of fixing it right now

**Comment by bddckr** [comment]
It's a Unity bug that will be fixed in an upcoming release of 5.6.

I know this because we're bitten by it in [VRTK](https://github.com/thestonefox/VRTK), too, and one of our users had a discussion with one of the Unity engineers.

**Comment by KumoKairo** [comment]
Unity bug tracker issue https://issuetracker.unity3d.com/issues/playersettings-dot-setscriptingdefinesymbolsforgroup-doesnt-like-buildtargetgroup-dot-switch
