### ISSUE TITLE
Default Entitas.properties for Windows

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#394]
Entitas can produce a default Entitas.properties file with default values that work out-of-the-box on mac.
If you're on a Windows machine some paths have to be updated, e.g. searchPaths

```
C:/Program Files/Unity/Editor/Data/Managed,
C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity,
C:/Program Files/Unity/Editor/Data/UnityExtensions/Unity/GUISystem
```

Support generating default Entitas.properties for Windows, too.

Any other keys need modification, too? Let me know

**Comment by aefreedman** [comment]
I've found that the search paths is also problematic when collaborating, since the Unity asset selector window will return an absolute filepath specific to the user. You then need to edit the .properties file manually and make sure not to use the Entitas window.

**Comment by sschmid** [comment]
Any suggestions how to tackle this? An additional user.properties?

**Comment by aefreedman** [comment]
I think this might actually be ok in recent versions of the properties window now that the path fields only allow string entry. (Issue was Unity inputting absolute paths.)
