### ISSUE TITLE
Dll based workflow - unity visual debugging integration

### ISSUE THREAD

**Issue by T2RKUS** [sschmid/Entitas-CSharp#396]
It's really difficult to use the feature class in a dll based workflow because I don't want to depend on visual debugging. It would be nice if I could hook into it another way than deriving from Feature. I'd like to be able to just give the visual debugging addin my root Systems class and have it look through the structure of systems and enable visual debugging on unity that way or another.

At the moment I have a ProjectName.Runtime.dll with my simulation logic and a ProjectName.Runtime.Unity.dll where I integrate my simulation into unity but the problem is I also want to use visual debugging addin. The current implementation means I have to write two system chains. one in my dll and one in the unity editor using Feature (or not define it in the dll at all but I don't want to do that)

Is the a better way of doing this with the current implementation or am I pretty much stuck?

**Comment by T2RKUS** [comment]
Perhaps somekind of static event on Systems class so we can do:

```csharp
Systems.OnCreated += (SystemsCollection, Name) => new DebugSystems(SystemsCollection, Name); 
```

**Comment by sschmid** [comment]
Is `ProjectName.Runtime.dll ` also compiled by Unity or only `ProjectName.Runtime.Unity.dll`?

The Feature call only depends on VisualDebugging when you run it in the Unity Editor. When releasing or using c# only, the VisualDebugging part is stripped out, you don't depend on `Entitas.VisualDebugging.Unity`

**Comment by T2RKUS** [comment]
ProjectName.Runtime is pure c# no unity/client code but the simulation only where ProjectName.Runtime.Unity contains systems to integrate the simulation into unity3d though looking at this perhaps coding the unity integration side should be in the editor entirely

**Comment by sschmid** [comment]
So using Feature in the c# project will be fine and won't have a dependency to Entitas.VisualDebugging.Unity, since `UNITY_EDITOR` is not declared

**Comment by T2RKUS** [comment]
i think we should have a generator to create system chains. By appending an attribute to a system with a priority we can generate chains automatically. That would be less painful to develop a dll runtime and still use the feature class

**Comment by sschmid** [comment]
You can definitely write one :) It's super easy now ;)
