### ISSUE TITLE
How to define Contexts?

### ISSUE THREAD

**Issue by ophilbinbriscoe** [sschmid/Entitas-CSharp#397]
The context list appears to be absent from Entitas Preferences window in Unity in the most recent version. Is this intentional?

![image](https://cloud.githubusercontent.com/assets/7648855/25357533/26a4077e-290c-11e7-822e-2ddd8acccd91.png)

**Comment by sschmid** [comment]
Hi, you closed already, so I assume you found the 2nd text field named `Contexts`. It's a comma separated list of context names.

**Comment by ophilbinbriscoe** [comment]
Yeah, not my greatest moment, ahah. I was looking at the screenshot in the docs that used the ReorderableList GUI and felt crazy.
