### ISSUE TITLE
"First Steps" links to nonexistent page

### ISSUE THREAD

**Issue by aschuhardt** [sschmid/Entitas-CSharp#398]
See [this link](https://github.com/sschmid/Entitas-CSharp/wiki/Install-Entitas-and-first-steps).

Referred to in documentation but apparently doesn't exist.

**Comment by aefreedman** [comment]
What page is linking to that page?

**Comment by aschuhardt** [comment]
https://github.com/sschmid/Entitas-CSharp/wiki/Code-Generator

**Comment by aefreedman** [comment]
The link should be good now.
