### ISSUE TITLE
DestroyEntity & AddedOrRemoved group & removeEntitySilently 

### ISSUE THREAD

**Issue by vaudevillian** [sschmid/Entitas-CSharp#403]
Hi again,

if you destroy an entity the groups with "...OrRemoved" will get that entity in their list - since all components will be removed. But iterating through those entities will then cause an EntityIsNotEnabledException. 

There was a similar issue where the bug was fixed in addEntitySilently (https://github.com/sschmid/Entitas-CSharp/pull/193).

I could use "entity.isEnabled" filter in every ReactiveSystem, but I dont feel like that's the proper way to deal with it.
For me, the issues were fixed by returning "entity.isEnabled && removed;" in Group::removeEntitySilently. 

Is it intended to callback the removed component to the groups?

**Comment by sschmid** [comment]
Hi, I think we cannot change this, because this will skip reporting component removal when destroying entities.

I think adding a check like `entity.hasXyz` to the filter should help.

**Comment by vaudevillian** [comment]
Hey,

sure thing, I will copy & paste some code here. To the skipping: thats actually exactly what I want and I couldn't figure out a reason why a systems wants a list of disabled, pooled entities.

Here is the code:

```
public sealed class CalcOutlineSystem : ReactiveSystem<GameEntity>
{
    public CalcOutlineSystem( Contexts contexts ) : base( contexts.game )
    {
    }

    protected override Collector<GameEntity> GetTrigger( IContext<GameEntity> context )
    {
        return new Collector<GameEntity>(
            new[] {
                context.GetGroup(GameMatcher.ShipRoute),
                context.GetGroup(GameMatcher.View)
            },
            new[] {
                GroupEvent.AddedOrRemoved,
                GroupEvent.Added
            }
        );
    }

    protected override bool Filter( GameEntity entity )
    {
        return true;
    }

    protected override void Execute( List<GameEntity> entities )
    {
        foreach( var entity in entities )
        {
            if( entity.hasShipRoute )
            {
                if( HelperShips.IsLooping( entity ) )
                {
                    entity.ReplaceOutline( Color.green );
                }
                else
                {
                    entity.ReplaceOutline( Color.white );
                }
            }
            else
            {
                entity.ReplaceOutline( Color.red );
            }
        }
    }
}
```
Entities (Ships) may lose routes when they are cancelled. In this case, they should get a red outline. The entities are still intact. 
But if an entity is destroyed, the ShipRouteComponent will be removed during the destroying process, hence every system will react to the component removal. I could put everywhere a "is this entity still valid?" check, sure. But I was assuming that only valid entities gets forwarded to the Execute system.

**Comment by sschmid** [comment]
Ok, I see your Filter() is empty. Usually this is the place to do some checks, but I see why you return true.
Question:
At the moment you will replace the outline on any entity which had a change in ShipRoute. Is it possible to be more specific? E.g. in Filter() `entity.hasOutline`?
If you really want to apply this to any entity, entity.isEnabled seems to be the only way.

**Comment by FNGgames** [comment]
As a use case, you might want to increment a score system where any time an enemy is destroyed (i.e. Matcher.Enemy, GroupEvent.Removed) and add to a score board? There's something like this in MatchOne i think.

**Comment by sschmid** [comment]
The only information you get is how many entities have been changed. I think in your example it's valid to check for `isEnabled` since this is what this system is actually doing. You execute on removal but exclude destroyed entities.

**Comment by vaudevillian** [comment]
Okay, thanks for the help!
