### ISSUE TITLE
[Proposal] Provide way to create component libraries

### ISSUE THREAD

**Issue by yosadchyi** [sschmid/Entitas-CSharp#407]
As for now it looks like that Entitas has not to much ways to share components between projects, as well, looks like, there is no way to select some subset of components to be used by concrete project.

Major blockers for that are:

- Component indexes generated during code generation
- Using partial classes during code generation.

To enable this sort of functionality C# generic types can be employeed: every component can have generic type like ComponentType<TComponent> which holds information about component index.

As well extension methods can be used instead of partial classes. Only components using properties will require changes, regular components will mostly have the same API as before.

Believe adding such functionality can make Entitas better in terms of reusage and more generic in overall.

Just to illustrate idea I've created [gist](https://gist.github.com/yosadchyi/2c8560a996e2a08f83c238605d399e92) for quick demo.

**Comment by yosadchyi** [comment]
Played a bit with entitas and made sample implementation of generic API: https://github.com/yosadchyi/Entitas.Generic

**Comment by sschmid** [comment]
ref #307
