### ISSUE TITLE
[Entitas:] Remove entity cache in group.GetEntities()

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#408]
... and return the internal HasSet as `IEnumerable` to avoid memory alloc when group changes often.

Alternatively, make group enumerable like

```csharp
// look closely: no group.GetEntities() call
foreach (var e in group) {
    // ...
}
```

**Comment by optimisez** [comment]
When this optimization will be shipped? Will it totally avoid memory alloc and gc?

**Comment by T2RKUS** [comment]
Something tells me you're really into optimization @optimisez ;)

**Comment by sschmid** [comment]
@IDNoise I think you wanted sth like this too, right?

```csharp
foreach (var e in group) {
}
```

This will circumvent the caching and will reduce gc alloc

**Comment by sschmid** [comment]
But please be aware that you cannot change the group while iterating since you're actually iterating over the internal entity collection (for better performance and less gc alloc)

**Comment by IDNoise** [comment]
Right now i'm using these 2 options (mostly 1st):
1.  List<TEntity> _entityListCache = new List<TEntity>(64);

        public List<TEntity> GetEntitiesNonAlloc() {
            if (_entitiesCache == null) {
                _entityListCache.Clear();
                _entityListCache.AddRange(_entities);
            }
            return _entityListCache;
        }

2. public IEnumerable<TEntity> AsEnumerable => _entities;

Yeah, i know that 2nd has limitation of not changable during iteration :)

**Comment by rastlin86** [comment]
The proposed implementation for this feature still generates some garbage due to boxing. The best approach would be to remove IEnumerable interfaces just provide implementation without interface:
```
HashSet<TEntity>.Enumerator GetEnumerator();
```

**Comment by sschmid** [comment]
@rastlin86 Do you mean these 2 methods?

https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Group/Group.cs#L153-L159

**Comment by rastlin86** [comment]
Yes, the struct enumerator from HashSet is being boxed into IEnumerator causing GC.Alloc.

Adding the method I mentioned to IGroup interfaces resolves this
```
public interface IGroup<TEntity> : IGroup where TEntity : class, IEntity
    {
        HashSet<TEntity>.Enumerator GetEnumerator();
```
It might be also good to remove IEnumerable<TEntity> from IGroup to not encourage using the interface, which causes allocation, however this might have some compatibility issues for people using IGroup as IEnumerable.

**Comment by IDNoise** [comment]
@rastlin86 Did you measure it? How many bytes it allocs? 
As a thing to try is to create internal custom enumerator that will wrap hashset's struct enumerator inside, like here: https://gist.github.com/yuri-tikhomirov/6bb2cc1a04391451ba60, not gonna try it myself now, will do it when optimization interation will come :)

**Comment by rastlin86** [comment]
I did measure it, it's 40B per foreach.

It's pretty common situation with Unity and foreach. That's why it's advised to avoid Linq extensions, as they tend to allocate the memory.

There is already a HashSet enumerator available, that is being returned either way by current implementation and is alloc free. The allocation comes solely from the fact that it's wrapped with the interface.

**Comment by sschmid** [comment]
I also measured 40B.
As you already said, any linq methods will not work anymore.
I'll think about it, good find! 👍

**Comment by sschmid** [comment]
But I must admin, 0 gc alloc is very tempting :) Will probably go for it

**Comment by rastlin86** [comment]
Also, I'm planning to implement this in my copy of Entitas, but it's possible to completely remove memory allocation from the Group.

Current implementation has a cache of entities, which is invalidated each time the group is modified:
```cs
void removeEntity(TEntity entity, int index, IComponent component) {
	var removed = _entities.Remove(entity);
	if (removed) {
		_entitiesCache = null;
		_singleEntityCache = null;
		if (OnEntityRemoved != null) {
			OnEntityRemoved(this, entity, index, component);
		}
		entity.Release(this);
	}
}
```

The cache is created each time the GetEntities() is called if the modification occured:
```cs
public TEntity[] GetEntities() {
    if (_entitiesCache == null) {
        _entitiesCache = new TEntity[_entities.Count];
        _entities.CopyTo(_entitiesCache);
    }

    return _entitiesCache;
}
```
Each time the group is changed, it causes new managed array to be allocated.

The alternative, and more memory efficient approach is to switch the entities cache ownership to each System by providing new implementation of GetEntities:
```cs
public void GetEntities(List<TEntity> buffer) {
    buffer.Clear();
    foreach (var entity in entities) {
        buffer.Add(entity);
    } 

    return _entitiesCache;
}
```
This way each individual system would allocate his buffer only ONCE per it's lifetime essentially removing any memory allocation during execution - well unless the List would have to be expanded in the background due to number of entities. It can be worker around by profiling the application and choosing the buffer size accordingly, depending on usage.

If the Systems are executed sequentially all the time, one could get away with just a single buffer for all systems.

**Comment by sschmid** [comment]
@rastlin86 Thanks for the input. Sounds like a good idea for some scenarios!

**Comment by IDNoise** [comment]
Based on link i posted:
```csharp
        public IEnumerator<Entity> GetEnumerator()
        {
            return RetainEnumerator();
        }

        CustomEnumerator _enumerator;
        bool _isEnumeratorRetained;
        IEnumerator<Entity> RetainEnumerator()
        {
            if (_enumerator == null)
            {
                _enumerator = new CustomEnumerator(this, _entities);
                _isEnumeratorRetained = true;
                return _enumerator;
            }
            else
            {
                if (_isEnumeratorRetained)
                    return _entities.GetEnumerator(); //  _enumerator is retained, so would produce base enumerator
                else
                {
                    _isEnumeratorRetained = true; // not retained, so will just return an instance
                    _enumerator.MyReset(); // reset it with special public method
                    return _enumerator;
                }
            }
        }

        void ReleaseEnumerator(CustomEnumerator enumerator)
        {
            if (ReferenceEquals(enumerator, _enumerator))
            {
                // the reference equals, so it is ok to release
                _isEnumeratorRetained = false;
            }
        }

        public class CustomEnumerator : IEnumerator<Entity>, IEnumerator
        {
            private Group _group;
            private HashSet<Entity> _hashSet;
            private HashSet<Entity>.Enumerator _enumerator;

            public CustomEnumerator(Group group, HashSet<Entity> hashSet)
            {
                _group = group;
                _hashSet = hashSet;
                _enumerator = hashSet.GetEnumerator();
            }

            public void MyReset() => _enumerator = _hashSet.GetEnumerator();

            bool IEnumerator.MoveNext() => _enumerator.MoveNext();

            // can't access to private Reset() method, so just re-create base enumerator
            void IEnumerator.Reset() => _enumerator = _hashSet.GetEnumerator();

            object IEnumerator.Current => _enumerator.Current;

            Entity IEnumerator<Entity>.Current => _enumerator.Current;

            void IDisposable.Dispose()
            {
                // dispose base enumerator (actually, does nothing)
                _enumerator.Dispose();
                // tell the list it is released
                _group.ReleaseEnumerator(this);
            }
        }
```
This one generates 0 garbage (if you don't do foreach over group inside foreach over same group :) )

2nd approach i use is #1 from my comment before (GetEntitiesNonAlloc() with internal list cache)

I don't want to give away linq capabilities, i use it a lot and get rid\optimize only parts that really affect performance :)

**Comment by IDNoise** [comment]
Also garbage free solution (a bit hacky :) )
Group inherits from List<Entity> and we do this.Add(entity), this.Remove(entity) if add/remove entity to hashset succeeded.

```csharp
        bool AddEntitySilently(Entity entity)
        {
            if (entity.IsEnabled)
            {
                var added = _entities.Add(entity);
                if (added)
                {
                    >> this.Add(entity);
                    _doUpdateCache = true;
                    entity.Retain(this);
                }

                return added;
            }

            return false;
        }

        bool RemoveEntitySilently(Entity entity)
        {
            var removed = _entities.Remove(entity);
            if (removed)
            {
               >>  this.Remove(entity);
                _doUpdateCache = true;
                entity.Release(this);
            }

            return removed;
        }
```

**Comment by rastlin86** [comment]
The above will cause exception any time you modify the Entities which causes them to be added/removed from the group as long as you iterate over it.

Thats the reason you get a buffer copy on GetEntities() and only at this point.

**Comment by IDNoise** [comment]
Yes, there is no way to get rid of it, it was posted before. So you have to get a copy if such loop expected, my suggested getEntitiesNonAlloc does the trick (if you don't call it inside same foreach), it is always in group and you don't fill every system with buffer list field as you want in your solution,

**Comment by rastlin86** [comment]
Well your proposal of GetEntitiesNonAlloc() isn't thread safe unfortunately.

So it's just a matter of answering a question what performance characteristic you want to achieve. If you want zero-alloc, thread safe solution, one approach I can think of is to pollute your systems with a buffer for entities.

If you don't care about having minimal alloc or about thread safety, you can use either of your suggestions or current implementation.

**Comment by IDNoise** [comment]
Yes it isn't, didn't need it to be :) But it also don't stop you from having buffer inside threaded system and fill it yourself or have both solutions, just to reduce boilerplate.

**Comment by sschmid** [comment]
@rastlin86 what would you say to use an array buffer instead of a list buffer and use Array.Resize internally?

public void GetEntities(ref TEntity[] buffer)

**Comment by sschmid** [comment]
Nvm, that will produce garbage, too

**Comment by sschmid** [comment]
@rastlin86 Why do you have an if statement and don't use AddRange in both cases?

**Comment by sschmid** [comment]
my current impl:

```csharp
        public List<TEntity> GetEntities(List<TEntity> buffer) {
            buffer.Clear();
            buffer.AddRange(_entities);
            return buffer;
        }
```

**Comment by rastlin86** [comment]
AddRange always creates a new array internally regardless if the list needs to be resized or not, at leas in Microsoft implementation:

https://stackoverflow.com/questions/2123161/listt-addrange-implementation-suboptimal

Have not tested that, but I'm like 80% sure this is also the way it's implemented in mono.
