### ISSUE TITLE
CLI CodeGenerator fix subcommand should run recursively

### ISSUE THREAD

**Issue by danielbe1** [sschmid/Entitas-CSharp#409]
The `fix` option of the CLI code generator offers several possible fixes to the properties file. When plugins are offered to be added, they might require new keys to be added but since the utility does not run recursively they will be missing and the utility will not be able to run.

A good way to fix this is to run the fix utility recursively until no issues are found.

**Comment by sschmid** [comment]
Thanks, was already on my list :) Add this feature now (see commit). Will be in the next release! Will close
