### ISSUE TITLE
Unity: Windows Store build doesn't work

### ISSUE THREAD

**Issue by JGameCreation** [sschmid/Entitas-CSharp#41]
I really like the Entitas system for Unity (I use version 5.2.0f3), but when I try to build a project with Entitas for Windows Store (I tried 8.1 and 10), I get a lot of compiler errors caused by the code generator. I am sure this is caused by .NET for Windows Store apps (https://msdn.microsoft.com/en-US/library/windows/apps/br230232.aspx) that is missing some types that are present in the full .NET framework. As all issues are in the code generation part I wonder if it is possible to exlude this part of the project from the build, because it seems to be needed in the editor only.
To reproduce the problems just build the Match-One example project with the Windows Store build target.

Thanks in advance,

Jannis

Here is the editor log, I'm sorry that I can only provide it in German, but maybe it's still useful.

Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs(43,17): error CS0246: Der Typ- oder Namespacename 'FileInfo' konnte nicht gefunden werden. (Fehlt eine Using-Direktive oder ein Assemblyverweis?)
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs Line: 43)

Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs(43,59): error CS1061: 'System.IO.DirectoryInfo' enth�lt keine Definition f�r 'GetFiles', und es konnte keine Erweiterungsmethode 'GetFiles' gefunden werden, die ein erstes Argument vom Typ 'System.IO.DirectoryInfo' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs Line: 43)

Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs(43,76): error CS0103: Der Name 'SearchOption' ist im aktuellen Kontext nicht vorhanden.
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs Line: 43)

Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs(48,25): error CS0103: Der Name 'Console' ist im aktuellen Kontext nicht vorhanden.
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs Line: 48)

Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs(58,37): error CS1061: 'System.Type' enth�lt keine Definition f�r 'GetInterfaces', und es konnte keine Erweiterungsmethode 'GetInterfaces' gefunden werden, die ein erstes Argument vom Typ 'System.Type' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs Line: 58)

Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs(64,38): error CS1061: 'System.Type' enth�lt keine Definition f�r 'IsInterface', und es konnte keine Erweiterungsmethode 'IsInterface' gefunden werden, die ein erstes Argument vom Typ 'System.Type' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs Line: 64)

Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs(67,29): error CS1061: 'System.Type' enth�lt keine Definition f�r 'GetInterfaces', und es konnte keine Erweiterungsmethode 'GetInterfaces' gefunden werden, die ein erstes Argument vom Typ 'System.Type' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs Line: 67)

Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs(92,30): error CS0117: 'System.Attribute' enth�lt keine Definition f�r 'GetCustomAttributes'.
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\CodeGenerator.cs Line: 92)

Assets\Libraries\Entitas.CodeGenerator\Generators\ComponentExtensionsGenerator.cs(24,31): error CS0117: 'System.Attribute' enth�lt keine Definition f�r 'GetCustomAttributes'.
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\Generators\ComponentExtensionsGenerator.cs Line: 24)

Assets\Libraries\Entitas.CodeGenerator\Generators\ComponentExtensionsGenerator.cs(305,30): error CS0117: 'System.Attribute' enth�lt keine Definition f�r 'GetCustomAttributes'.
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\Generators\ComponentExtensionsGenerator.cs Line: 305)

Assets\Libraries\Entitas.CodeGenerator\Generators\ComponentExtensionsGenerator.cs(311,25): error CS1061: 'System.Type' enth�lt keine Definition f�r 'GetFields', und es konnte keine Erweiterungsmethode 'GetFields' gefunden werden, die ein erstes Argument vom Typ 'System.Type' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\Generators\ComponentExtensionsGenerator.cs Line: 311)

Assets\Libraries\Entitas.CodeGenerator\Generators\ComponentExtensionsGenerator.cs(333,25): error CS1061: 'System.Type' enth�lt keine Definition f�r 'GetFields', und es konnte keine Erweiterungsmethode 'GetFields' gefunden werden, die ein erstes Argument vom Typ 'System.Type' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\Generators\ComponentExtensionsGenerator.cs Line: 333)

Assets\Libraries\Entitas.CodeGenerator\Generators\IndicesLookupGenerator.cs(77,30): error CS0117: 'System.Attribute' enth�lt keine Definition f�r 'GetCustomAttributes'.
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\Generators\IndicesLookupGenerator.cs Line: 77)

Assets\Libraries\Entitas.CodeGenerator\Generators\SystemExtensionsGenerator.cs(21,41): error CS1061: 'System.Type' enth�lt keine Definition f�r 'GetConstructor', und es konnte keine Erweiterungsmethode 'GetConstructor' gefunden werden, die ein erstes Argument vom Typ 'System.Type' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\Generators\SystemExtensionsGenerator.cs Line: 21)

Assets\Libraries\Entitas.CodeGenerator\Generators\TypeGenerator.cs(30,22): error CS1061: 'System.Type' enth�lt keine Definition f�r 'IsGenericType', und es konnte keine Erweiterungsmethode 'IsGenericType' gefunden werden, die ein erstes Argument vom Typ 'System.Type' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\Generators\TypeGenerator.cs Line: 30)

Assets\Libraries\Entitas.CodeGenerator\Generators\TypeGenerator.cs(45,41): error CS1061: 'System.Type' enth�lt keine Definition f�r 'GetGenericArguments', und es konnte keine Erweiterungsmethode 'GetGenericArguments' gefunden werden, die ein erstes Argument vom Typ 'System.Type' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?).
 
(Filename: Assets\Libraries\Entitas.CodeGenerator\Generators\TypeGenerator.cs Line: 45)

**Comment by JGameCreation** [comment]
I solved the issue and sent a Pull request:
 Exclude scripts only needed in editor from build #42

**Comment by sschmid** [comment]
Hey, just a heads up:
New releases are published with Entitas-Unity.zip. This contains all files as usual, but the CodeGenerator is now moved into an Editor folder, which should solve your issue.
