### ISSUE TITLE
Make EntitasCache thread safe

### ISSUE THREAD

**Issue by paraboxx** [sschmid/Entitas-CSharp#410]
I'm running several instances of my game in parallel threads, completely separate from each other with each their own Contexts instance. EntitasCache is the only shared element between them that leads to problems.

I made a local modification for the EntitasCache._cache object to be [ThreadStatic]. But that requires manual instantiation of the cache on each thread since the constructor sadly doesn't get called automatically on all the threads but the first. So I added a call to EntitasCache.ThreadInit() into the generated Contexts.cs which works fine for me. But many of the tests in your test suite fail because they usually don't create Contexts. So now I'm not sure where best to ensure that EntitasCache is initialized before use.

An alternative would be to put locks around the code in all the methods in EntitasCache, but that would lead to unnecessary congestion, as there is no actual data being shared between the threads. It's just an object pool after all.

**Comment by sschmid** [comment]
Sounds good. A cache per thread makes sense. Do you want to submit a PR?

**Comment by paraboxx** [comment]
Do you know a good place to initialize the cache? Is Contexts constructor ok? Then we would need to manually initialize the cache for all tests that don't initialize a context.

**Comment by sschmid** [comment]
ref #325
