### ISSUE TITLE
Asset store version difference?

### ISSUE THREAD

**Issue by DTurley** [sschmid/Entitas-CSharp#411]
Just getting into Entitas and it looks fantastic. Wondering if there is any difference to the Unity Asset Store version and the one found here? Totally cool if it is just to support the developers, but if there is a difference it would be great to know some details so can make an informed decision :)

https://www.assetstore.unity3d.com/en/#!/content/87638

**Comment by sdarkwell** [comment]
I wonder that as well!

**Comment by jr69** [comment]
Seems like the Asset Store version is a scam, likely someone else impersonating Simon and trying to profit. There's no official word here of any paid version as far as I'm concerned

**Comment by sdarkwell** [comment]
@jr69: That was also a concern of mine. Might be worth confirming with Simon, though, just to ensure.

**Comment by sschmid** [comment]
Hey, I wrote an answer here #413.
