### ISSUE TITLE
Entitas Path Finding

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#416]
@cloudjubei just wrote in the chat:
> Simon just told me that some of you have been asking for incorporating PathFinding into your Entitas projects. As a matter of fact, I've written a PathFinding Service that is fully compatible with Entitas and has been pretty much battle tested for over 2 years. There's still plenty of optimisations that I could add to it, but as it is - it works pretty well on mobile especially (I remember we did some tests at the beginning and were even able to have hundreds of pathfindings happen every frame).
So I just wanted to see if people would be interested in something like that - cos then I could actually make it open source.

I'd love to see that happening, Would also be a great first Entitas Kit :)

Thumbs up if you want this!

**Comment by FNGgames** [comment]
Great idea

**Comment by andrewhickey** [comment]
@cloudjubei Did you decide to go ahead with this in the end? Any help needed?

**Comment by danielbe1** [comment]
Does it include local avoidance? What algorithms does it use?

**Comment by CypherEA** [comment]
Is this alive?

**Comment by sschmid** [comment]
@cloudjubei we still want this :)

**Comment by cloudjubei** [comment]
@sschmid I'm away from home this week, but next week I might finally have some 'quality' time :D

**Comment by CypherEA** [comment]
@sschmid @cloudjubei Any way you can also update the EntitasTanks to latest Entitas version - it's the only fully featured 3D example out there. With the pathfinding it will be even more important.

Also, using it to showcase best practices (code structure, step by step using generator etc') would be a tremendous help.
