### ISSUE TITLE
Visual Debugger List Type Drawer throws IndexOutOfRange on lists of custom class

### ISSUE THREAD

**Issue by aefreedman** [sschmid/Entitas-CSharp#418]
I imagine the Visual Debugger might be expecting an IComponentDrawer for this list/component? It might be better not to throw the exception but provide a warning? Being unable to draw the component in the debugger doesn't actually prevent the entity/component from working correctly.

Repro:

1. Create some custom class (`CustomData { public whatever whatever; }`)
1. Create a class that inherits from list of this custom class (` ListClass : List<CustomData>`)
1. Add an instance of this list to an Entitas component
1. Inspect the entity with the component
1. Get index out of range error

If you do the same thing but with a Dictionary, for example, the Visual Debugger draws the component without problems.

**Comment by sschmid** [comment]
Hi, sorry for the late reply. Yeah, that's true, my guess is, it's this
[ListTypeDrawer](https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.VisualDebugging.Unity.Editor/Entitas.VisualDebugging.Unity.Editor/Editor/Entity/TypeDrawer/ListTypeDrawer.cs#L18)

```csharp
var elementType = memberType.GetGenericArguments()[0];
```
... but I might also be wrong. The ListTypeDrawer is designed to draw generic lists. I recommend writing a custom `ITypeDrawer` for custom types if needed. See builtin [TypeDrawers](https://github.com/sschmid/Entitas-CSharp/tree/develop/Addons/Entitas.VisualDebugging.Unity.Editor/Entitas.VisualDebugging.Unity.Editor/Editor/Entity/TypeDrawer) for inspiration
