### ISSUE TITLE
Code Generator Caching Component Permanently Somehow

### ISSUE THREAD

**Issue by Eforen** [sschmid/Entitas-CSharp#419]
I created a component that I later decided I did not want (Lets call it foobar.cs) I deleted the entire Generated folder then ran entitas.exe gen and low and behold somehow even though the original file is totally deleted it generates a file named foobarComponent.cs

Where is it cashing this and how do I get it to not use the cache or delete the cache?

Am I just missing a step here in removing it that I am not aware of? Is it embedding something in the project file?

**Comment by sschmid** [comment]
Hey, oh yes, that's the behaviour of the current code generator. I'll explain:

- You add a component
- Unity will recompile and output Assembly-CSharp.dll which contains all of your code
- In the Entitas Preferences you most likely set the Assembly path to Assembly-CSharp.dll
- The code generator will use reflection on this dll and retrieve all the data it needs to generate

Now here's the tricky part: I f there are compile errors Unity cannot recompile a new dll. This means you changed your code but the changes are not in the dll. In fact, it's still the previous dll. This means if you generate, the code generator will retrieve outdated data.

To fix this, you have to get rid of all compile errors first. Deleting the generated folder will most likely result in compile errors, so please don't delete this folder.

I plan to release a new code generator this month which doesn't use reflection but actually parses your code. This way you can have compile errors and you're still able to generate. This will be very helpful

**Comment by shawn11ZX** [comment]
I sschmid, are there any progress on this issue?
