### ISSUE TITLE
Unity-Tutorial---Simple-Entity-View-and-Movement

### ISSUE THREAD

**Issue by JRSerjeant** [sschmid/Entitas-CSharp#422]
Hello, 

I noticed that in the [AddViewSystem](https://github.com/sschmid/Entitas-CSharp/wiki/Unity-Tutorial---Simple-Entity-View-and-Movement#addviewsystem) I get an error on the following line that Collector should be ICollector. 

```
    protected override Collector<GameEntity> GetTrigger(IContext<GameEntity> context)
    {
        return context.CreateCollector(GameMatcher.Sprite);
    }
```
![image](https://cloud.githubusercontent.com/assets/4333472/26129874/14ba2a90-3a8a-11e7-9745-302a592a3890.png)

Thanks 
J

**Comment by FNGgames** [comment]
Yeah, tut was made with an old version - feel free to update the tutorial page. I'll update the example project as soon as my PC comes back from the shop and I'm working on my game again.

**Comment by VladislavKostin** [comment]
Yeah, I ran into that myself in the Systems page before. Fixed this one too. Guess you can close this :)

**Comment by JRSerjeant** [comment]
Yeah I was just about to correct it myself and saw it had been done. 

Cheers. :)
