### ISSUE TITLE
Namespaces are not ignored in Entities objects names

### ISSUE THREAD

**Issue by Besjan** [sschmid/Entitas-CSharp#425]
Using Entitas 0.42.3

Not a big deal, but sometimes is faster to look at the entity names for current components.
And since the namespace is not ignored, the name of the entity becomes long.

Example:

`Entity_0(*1)(MyNamespace.MyFirstComponent, MyNamespace.MySecondComponent)`

**Comment by sschmid** [comment]
Hey, agree. Totally makes sense to skip the namespace for components. Btw, did you know that you can override ToString in components to get custom output like
`Entity_0(*1)(Health(100), Position(1,2,3)`

**Comment by Besjan** [comment]
Even better :) thanks for tip
