### ISSUE TITLE
Entitas Announcement (Simon & Wooga)

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#427]
# Entitas Announcement

**Hi community! How is it going? I hope you're doing all great!**

As you may have noticed I was a little bit quiet over the last 2 or 3 weeks. I wasn't as active in the chat as usual and didn't work on issues. But I'm so happy to see that you guys help each other out when someone has a question. Keep it up! :)

As always I try to be as transparent as possible, that's why I want to share a few things with you now and explain, why I was distracted from the chat and issues.

# Wooga and Entitas on the Unity Asset Store

In the issue #413 I shared my vision of Entitas on the Unity Asset Store. I'm really happy and thankful for the positive feedback and suggestions I got from you guys. That really helps a lot and you can help shaping the future of Entitas as well.

You can currently buy Entitas on the Unity Asset Store to support me and the development: https://www.assetstore.unity3d.com/#!/content/87638

This is the very same version you can also get for free in the [release section](https://github.com/sschmid/Entitas-CSharp/releases).

Unfortunately, my contract with Wooga doesn't allow to publish and sell Entitas on the Unity Asset Store or anywhere else. After I've released Entitas on the Unity Asset Store Wooga asked me to remove it again. I totally understand and respect their reasons.

**But here's the thing:** I see a lot of potential in Entitas and ECS in general. Entitas allowed others and me to write clean, robust, reusable and testable code which stays flexible even in big projects. As I mentioned in chat, I'm really excited to see that other big players in the industry like Blizzard use the same approach as we do with Entitas (See [GDC Talk - 'Overwatch' Gameplay Architecture and Netcode](http://www.gdcvault.com/play/1024001/-Overwatch-Gameplay-Architecture-and)). I've spend the last 3 years optimizing and maintaining Entitas after work and on weekends and I plan to continue doing so for years to come. I'm happy to see the great feedback from the growing community and the acceptance of this architecture.

I don't want to stop improving Entitas right now and as a consequence I cannot work at Wooga anymore. I had a great time in this awesome company and learned a lot but I decided to focus on Entitas full time now.

# What's next
Starting from 1st July 2017 I will focus on Entitas full time and I will not work at Wooga anymore. I'm more than happy to take this opportunity and will try my best to provide you a better experience when using Entitas. This is my current prio list:

- Complete Documentation + Complete Wiki
- Written Tutorials + Video Tutorials
- Entitas Plus on the Unity Asset Store
- Entitas website

I know that the biggest weakness of Entitas right now is the lack of documentation. I want to fix this so people will be able to learn Entitas quicker and easier. I thing it also makes sense to have Video Tutorials. I love Video Tutorials :) After that I think it's a great time to focus on selling Entitas Plus and see if I can find a way to maintain the future development of Entitas. I still have a few really cool ideas for great features to improve Entitas! :) In the meantime I guess I'm depend on [your donations more than ever](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=BTMLSDQULZ852) :)

If you're evaluating Entitas for your project or if you have any questions about the architecture, best practises or future plans you can always contact me and I can support you and try answering all your questions.

Happy coding everyone!

**Comment by WoLfulus** [comment]
This is awesome! We all love the work you put in Entitas and the whole architecture, and this is great news! 

I'm just waiting for roslyn stuff to really start working with entitas again (and get it from the store too). When you have only about an hour/day to work on little projects, that thing will help a lot!

Keep it up!  ;)

**Comment by AGeorgy** [comment]
Wow! So huge changes in your life! Well, good luck to you!

**Comment by chiuan** [comment]
i love the entitas project. and always support you! great work! 
by the way, i have spend my money on the Asset Store!

**Comment by pixeption** [comment]
Cool, hope the best for you and your team, I always support you.

**Comment by JamesMcMahon** [comment]
Congrats Simon and best of luck to you. Have you considered setting up a Patreon page?

Also, can you detail what your plans are for Entitas plus or are you still formulating your plans?

**Comment by WoLfulus** [comment]
A Patreon page will be awesome.

**Comment by WoLfulus** [comment]
A Patreon page will be awesome.

**Comment by IsaiahKelly** [comment]
Wow. You are undoubtedly very passionate and dedicated to this project. Thanks for all your hard work and best of luck with all this!

Yeah, I was just thinking of the possibility of setting up a Patreon or similar system of support too. You could entice people to support you on a monthly basis by offering early access to new builds / features and premium support, etc. 

This might work even better than a one-time fee because it means you could keep all features completely free and open. Supporters would just get them early. Something like this might also provide better longtime financial support, by giving you a steady stream of income over time rather than just a large lump sum upfront.

Nothing to lose in just trying something like this out anyway. It's always a good idea to investigate all your options. Never really know if it'll work until you try it.

**Comment by Tzelon** [comment]
Good luck mate. 
Just started to work with Entitas and I will be happy to contribute to the project. 
Just let me know how I can help.

**Comment by roygear** [comment]
Love your passion! Thanks for contributing this great tool. 
Good Luck!
