### ISSUE TITLE
Duplicate component generating in 0.36.0

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#428]
I'm upgrade my [example project](https://github.com/JamesMcMahon/entitas-2d-roguelike/) from 0.32.0 to the latest version of Entitas and I'm hitting a roadblock with 0.36.0.

For some reason some of my components are generating duplicate matchers with leads to this error,

>Assets/Sources/Generated/AudioAttackSourceComponentGeneratedExtension.cs(58,25): error CS0102: The type `PoolMatcher' already contains a definition for `_matcherAudioAttackSource'

Here is what the components look like,

AudioSourceComponents.cs
```csharp
[Pool]
public class AudioComponent : BaseAudioComponent
{
}

[Pool]
public class AudioAttackSourceComponent : BaseAudioComponent
{
}

[Pool]
public class AudioDeathSourceComponent : BaseAudioComponent
{
}

[Pool]
public class AudioPickupSourceComponent : BaseAudioComponent
{
}

[Pool]
public class AudioWalkSourceComponent : BaseAudioComponent
{
}
```
BaseAudioComponent.cs
```csharp
using Entitas;
using System.Linq;

public abstract class BaseAudioComponent : IComponent
{
    public Audio[] clips;
    public bool randomizePitch;

    public string[] clipNames
    {
        get { return clips.Select(i => i.ToString()).ToArray(); }
    }
}
```

I know this is an older version but it's a roadblock for me due to all the API changes. Any suggestions?

**Comment by KumoKairo** [comment]
This component inheritance thing looks very spooky. I would've gone with an 
`enum SourceComponentType
{
    Audio,
    Attack,
    Death,
    .... etc
}` 

and a `SourceComponentType` field inside of the `BaseAudioComponent` (which would be just an `AudioComponent`.
I can't tell you which steps of generation have gone wrong with 0.36, but I can definitely say that component inheritance is not the best practice for this type of the problem.

You have a great example project by the way, I started working with Entitas with your project (didn't go all the way to this audio components inheritance though)

**Comment by JamesMcMahon** [comment]
Thanks! One reasons I am hesitant to update the project is it's one of the first things I wrote in Entitas so some of the choices are a little odd. But people seem to find it useful so I wanted to see how much effort it would be to get it to 0.42. It hasn't been as straightforward as I would like so far.

I tried some more experiments tonight to see if I could rule something out. First, I got rid of the abstract class and just copy and pasted the code into each subclass to see if the generated with having trouble with class hierarchies, no luck. Second I moved a few of the components out into separate files, also no luck.

Here is what the generated code looks like for the matches,

``` csharp
    public partial class PoolMatcher {

        static IMatcher _matcherAudioWalkSource;

        public static IMatcher AudioWalkSource {
            get {
                if(_matcherAudioWalkSource == null) {
                    var matcher = (Matcher)Matcher.AllOf(PoolComponentIds.AudioWalkSource);
                    matcher.componentNames = PoolComponentIds.componentNames;
                    _matcherAudioWalkSource = matcher;
                }

                return _matcherAudioWalkSource;
            }
        }
    }

    public partial class PoolMatcher {

        static IMatcher _matcherAudioWalkSource;

        public static IMatcher AudioWalkSource {
            get {
                if(_matcherAudioWalkSource == null) {
                    var matcher = (Matcher)Matcher.AllOf(PoolComponentIds.AudioWalkSource);
                    matcher.componentNames = PoolComponentIds.componentNames;
                    _matcherAudioWalkSource = matcher;
                }

                return _matcherAudioWalkSource;
            }
        }
    }
```

For some reason the code generate is just duplicating those partial classes.

**Comment by JamesMcMahon** [comment]
I just ended up manually editing the generated code and deleting the duplicated code.

0.37.0 appears to fix the issue, so I am over the road block for now. Just wanted to make sure I didn't have something setup incorrectly.
