### ISSUE TITLE
[Feature] Excluding multiple components

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#43]
Excuse me if I am missing something but it looks like when using the `IExcludeComponents` interface there is no way to exclude multiple components. It looks like we need a `Matcher.AnyOf`, essentially the opposite of `Matcher.AllOf`, to allow this behavior.

Is this correct or am I missing something?

**Comment by sschmid** [comment]
You can exclude multiple components by passing them all into Matcher.AllOf()

**Comment by sschmid** [comment]
Any component contained in the Matcher.AllOf will be used to exclude entities having this component.

**Comment by sschmid** [comment]
Btw, AnyOf and NoneOf will be reintroduced in the next release

**Comment by JamesMcMahon** [comment]
Hmm, not sure why didn't work for me. I'll have to revisit. Good to here that additional matchers will be available soon.

**Comment by sschmid** [comment]
Sorry, I think I mixed sth up... You're right.
