### ISSUE TITLE
UNetWeaver issue when upgrading Unity

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#432]
I'm hitting an issue when upgrading Unity for [my example project](https://github.com/JamesMcMahon/entitas-2d-roguelike). It looks like the issues might be connected to Entitas 0.42.3 as I no longer see it if I downgrade Entitas and upgrade the project.

Post upgrade I see this error in the editor and it stops me from running the game,

> UNetWeaver error: Exception :System.NullReferenceException: Object reference not set to an instance of an object
  at Unity.UNetWeaver.Weaver.CheckSyncListStruct (Mono.Cecil.TypeDefinition td) [0x0004d] in /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/UNetWeaver.cs:1682 
  at Unity.UNetWeaver.Weaver.Weave (System.String assName, IEnumerable`1 dependencies, IAssemblyResolver assemblyResolver, System.String unityEngineDLLPath, System.String unityUNetDLLPath, System.String outputDir) [0x000bd] in /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/UNetWeaver.cs:1739 
UnityEngine.Debug:LogError(Object)
Unity.UNetWeaver.Log:Error(String) (at /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/Program.cs:20)
Unity.UNetWeaver.Weaver:WeaveAssemblies(IEnumerable`1, IEnumerable`1, IAssemblyResolver, String, String, String) (at /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/UNetWeaver.cs:1851)
Unity.UNetWeaver.Program:Process(String, String, String, String[], String[], IAssemblyResolver, Action`1, Action`1) (at /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/Program.cs:34)
UnityEditor.Scripting.Serialization.Weaver:WeaveUnetFromEditor(String, String, String, String, Boolean)

I've tested this on multiple operating systems and with both Unity 5.6.1 and 5.5.4. My theory is something in Entitas is attempting to use an outdated network call.

Anyone else hitting this issue?

**Comment by c0ffeeartc** [comment]
Look at https://github.com/sschmid/Entitas-CSharp/issues/430

**Comment by JamesMcMahon** [comment]
Thanks! I will try that out tomorrow.

Could have sworn I did a search in the issues here, oh well it's late and I'm tired.

**Comment by JamesMcMahon** [comment]
This worked. I ended up just deleting the CodeGenerator directory from Entitas-Unity.

I'm going to keep this issue open as it's something that could be improved in 0.42.3. My thought is the Documentation and CodeGenerator should be kept out of Entitas-Unity as they aren't needed if you are dragging the library into a Unity project.
