### ISSUE TITLE
Coming back to entitas since 0.36...

### ISSUE THREAD

**Issue by Milambeer** [sschmid/Entitas-CSharp#433]
Hey everyone,

Fisrt thing congratulation for your decision sschmid to work full time to entitas, i like this framework.

I am trying to update my code from 0.36 to 42.3 and i am an issue i can't manage to resolve. How we define the context with the new version? I used to go in the tool section in unity and create them from here, but after reading the documentation and example of  JamesMcMahon which is up to date, i didn't manage to solve this. I think i will have further question, in the coming days.

Thank you.

**Comment by JamesMcMahon** [comment]
Hey Milambeer,

I just went through this myself. I'd recommend go through it one release at a time. 0.37 is honestly the hardest one to upgrade, but if you go to that instead of going directly to 0.42.3 it will be easier.

If you have a specific question don't hesitate to ask, I'll try my best to answer.

**Comment by Milambeer** [comment]
Ok i managed to upgrade my project. I commented all my sources, added my contexts and deleted generated folder. The assembly dll was generated by unity. I generated entitas code to get my contexts generated code, then uncommented my components, then regenerated entitas code to get component generated. From there i just cleaned, updated the code with the upgrade guide to each version. And it worked! \o/

But i have a problem when you loose the game i print a ui menu to reload the game which reset all entity in each context whith this code:
 

			gameEventEntity.Destroy();
			_systems.DeactivateReactiveSystems();
			_systems.ClearReactiveSystems();
			_contexts.game.Reset();
			_contexts.gameEvent.Reset();
			_contexts.input.Reset();
 			SceneManager.LoadScene(SceneManager.GetActiveScene().name);

At this point i am getting this error when the game reach this code:

> ContextStillHasRetainedEntitiesException: 'Game' detected retained entities although all entities got destroyed!
Did you release all entities? Try calling systems.ClearReactiveSystems()before calling context.DestroyAllEntities() to avoid memory leaks.
Entitas.Context`1[TEntity].DestroyAllEntities ()
Entitas.Context`1[TEntity].Reset ()
GameController.Update () (at Assets/Scripts/GameController.cs:35)

It worked on 0.36.0 but i am not sure this is the proper way to reload the game. 

Any thoughts?

**Comment by JamesMcMahon** [comment]
I am on my phone right now so I can't look for in depth on anything but does this thread, https://github.com/sschmid/Entitas-CSharp/issues/82, help at all?

**Comment by Milambeer** [comment]
Ok i managed to fix it. The code
```` c#
    foreach (GameEntity e in entities) {
        if (e.hasView) {
            e.view.gameObject.Unlink();
            UnityEngine.Object.Destroy(e.view.gameObject);
        }
        e.Destroy();
    }
````

was called in another reactive system that wasn't executed before this code was called:

````c#
    gameEventEntity.Destroy();
    _systems.DeactivateReactiveSystems();
    _systems.ClearReactiveSystems();
    _contexts.game.Reset();
    _contexts.gameEvent.Reset();
    _contexts.input.Reset();
    SceneManager.LoadScene(SceneManager.GetActiveScene().name);
````
So i just waited that the system which clean gameobjects and unlink entities do its jobs and after it's ok just called:
````c#
    gameEventEntity.Destroy();
    SceneManager.LoadScene(SceneManager.GetActiveScene().name);
````

Since i am calling ` SceneManager.LoadScene(SceneManager.GetActiveScene().name); ` to reset the game, i could remove this ` UnityEngine.Object.Destroy(e.view.gameObject); ` but tohers part of the code use it (to remove projectile in the game). A refactor is needed to clean it :)

Thanks for your help!
