### ISSUE TITLE
[Bug][Unity] Exception thrown when inspecting System.Net.IPAddress in inspector

### ISSUE THREAD

**Issue by WeAthFoLD** [sschmid/Entitas-CSharp#436]
I'm currently experimenting on making a multiplayer game in Unity. I have some components like this:

```C#
using System.Net;
using Entitas;

[Network]
public class PingTestComponent : IComponent {
	public IPEndPoint target;

	public int testIntervalMsec = 1000;
	public float cooldown = 1.0f;
}
```

At runtime, when I try to see the content of an entity containing the above component in inspector, an exception pops up:

```
Exception: The attempted operation is not supported for the type of object referenced
System.Net.IPAddress.get_ScopeId ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MonoProperty.GetValue (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] index, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoProperty.cs:297)
System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoProperty.cs:283)
Entitas.Utils.PublicMemberInfo.GetValue (System.Object obj)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2 setValue)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2 setValue)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawComponent (System.Boolean[] unfoldedComponents, System.String[] componentMemberSearch, IContext context, IEntity entity, Int32 index, IComponent component)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawComponents (IContext context, IEntity entity)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawEntity (IContext context, IEntity entity)
Entitas.VisualDebugging.Unity.Editor.EntityInspector.OnInspectorGUI ()
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1229)
UnityEditor.DockArea:OnGUI()
```

The inspector looks like this (A different component, but also has IPEndPoint in it):
![image](https://user-images.githubusercontent.com/3516419/27513465-a4b77f48-5999-11e7-8bd9-7289f06d32a2.png)
The console:
![image](https://user-images.githubusercontent.com/3516419/27513467-c5ba0e54-5999-11e7-86fb-d9747e7cffab.png)

I think this happens because IPAddress somehow doesn't meet the criterion to be properly displayed in inspector. Under this situation, I think a warning shown on the inspector is preferred, then minimal information about this object can be displayed (e.g. using `ToString()`), but it's even better  if it can be displayed correctly.

BTW, would love to know a temp workaround to hide the field in the inspector! Thanks 🍻

**Comment by sschmid** [comment]
Hey, sorry for the late reply. The entity inspector tries to figure out how to draw unknown types. Most of the times that works, sometimes it doesn't. In those cases you have 2 options:
1. Implement your own `ITypeDrawer`
Implementing your own `ITypeDrawer` enables you to draw types the way you want. Take a look at the builtin type drawers to get inspired [TypeDrawers](https://github.com/sschmid/Entitas-CSharp/tree/develop/Addons/Entitas.VisualDebugging.Unity.Editor/Entitas.VisualDebugging.Unity.Editor/Editor/Entity/TypeDrawer)
Most of them are pretty simple.

2. Mark the component with `[DontDrawComponent]`
This will tell the entity inspector not to attempt to draw the type.

Option 1 is the better choice most of the time, because you can inspect and changes values while playing
