### ISSUE TITLE
Dll error when building an apk

### ISSUE THREAD

**Issue by Milambeer** [sschmid/Entitas-CSharp#437]
Hi, i am trying to generate an apk and run it into my phone, but within the process of generation, i get the following error: 

````
Found plugins with same names and architectures, Assets/Libraries/Entitas/Entitas/Entitas.Utils.dll () and Assets/Libraries/Entitas/Migration/Entitas.Utils.dll (). Assign different architectures or delete the duplicate.
UnityEditor.AndroidPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
````

Should i delete the migration folder?

**Comment by c0ffeeartc** [comment]
Move CodeGeneration and Migration folders outside Assets folder.
Entitas-Unity.zip/Entitas folder is used by unity project, and other folders contain separate command line tools.

**Comment by Milambeer** [comment]
Thank you, it worked!
