### ISSUE TITLE
Collector::~Collector was called from non-main thread

### ISSUE THREAD

**Issue by paraboxx** [sschmid/Entitas-CSharp#438]
I just had this once in the Unity Editor: The Collector destructor has apparently been called from a thread other than the Unity main thread. I do some multithreading in my app and maybe the GC got triggered from a background thread. Since it gets triggered by the GC, I don't think we have any control over which thread this call comes from?

In my specific case, the destructor called deactivate, which in turn released some entities which then got destroyed, which triggered an OnComponentRemoved callback which attempted to remove a unity gameobject in my code, which didn't work because GameObject manipulation is only allowed on the main thread.

**Comment by sschmid** [comment]
That's a good find!

The destructor deactivates the collector as a last resort to avoid leaks if the user didn't clean up.
Is it possible for you to clean up (deactivate) the collector manually at a controlled point of time from the mainthread instead?

**Comment by paraboxx** [comment]
That's the thing. It happened only once, in the Unity Editor. I have no clue which collector that was and why it didn't get cleaned up. I don't use collectors outside of the ones needed for reactive systems and I don't destroy/remove systems at all. Does the Visual Debugging code create additional collectors maybe?

I think the collector destructors should log an error and report a leak instead of silently cleaning up after the user in this case. The intention is good but Deactivating a collector undeterministically will eventually lead to other problems even outside of threading scenarios.

**Comment by sschmid** [comment]
Reminder and Note to myself:
Can reproduce sth similar in [Tests/Unity/VisualDebugging/Assets/Tests/Manual Tests/ReactiveSystem Destructor](https://github.com/sschmid/Entitas-CSharp/tree/develop/Tests/Unity/VisualDebugging/Assets/Tests/Manual%20Tests/ReactiveSystem%20Destructor)
```
get_gameObject can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.Component:get_gameObject()
Entitas.VisualDebugging.Unity.EntityBehaviour:onEntityReleased(IEntity)
Entitas.Entity:Release(Object)
Entitas.Collector`1:ClearCollectedEntities()
Entitas.Collector`1:Deactivate()
Entitas.ReactiveSystem`1:Deactivate()
Entitas.ReactiveSystem`1:Finalize()
```

**Comment by sschmid** [comment]
Will close, this can only happen in the Unity Editor but never in a release build.
