### ISSUE TITLE
Is ALL component designed to be sealed?

### ISSUE THREAD

**Issue by wuyin1985** [sschmid/Entitas-CSharp#439]
i known according to ecs rule: the component only has values,so it seem didn't need inherit.But sometime i think i need it to make quick functions.

**Comment by KumoKairo** [comment]
It may seem like a good quick solution, but resist the urge to do that. Don't add any functions to components _directly_ and don't use component inheritance. Any problem can be solved in many different ways. 
Keep in mind that there are no strict rules in programming. I encourage you to try different things and see if they work out for you. As for my experience - I've already tried something like you have described and it didn't work out for me at all. Cheers :)

**Comment by danielbe1** [comment]
It might not be a bad idea to add certain methods to components. It is good to add methods that help keep invariants for example, but remember that manipulating the components outside of the code generated by Entitas (Remove* Add* Replace*) might not be what you want. Personally I do add methods to components, I think using inheritance or static extension classes is fooling no one.
