### ISSUE TITLE
can i use this in mmorpg game development?

### ISSUE THREAD

**Issue by moto2002** [sschmid/Entitas-CSharp#440]
can i use this framework in unity3d mmorpg game development?

**Comment by joshbayley** [comment]
You can run entitas on a backend server and it could definately be used to simulate the world, entitas is not very implementation specific, its not going to do much of the work for you unfortunately. Also entitas dosn't support multithreading directly and load management is very important for an MMO so you would likely need to devise some way of utlizing threads with it.

You can definately utilize entitas for you're client though :)

The answer is yes you can use it, but it's not going to make it an easy task.

**Comment by moto2002** [comment]
ok,thanks very much
