### ISSUE TITLE
Template Files

### ISSUE THREAD

**Issue by Spy-Shifty** [sschmid/Entitas-CSharp#442]
Hi I don't know if this is the right place for it. 
But I want to share with you my Entitas Templatefiles for Unity!
[EntitasTemplates.zip](https://github.com/sschmid/Entitas-CSharp/files/1133119/EntitasTemplates.zip)

Just copy the files in the .zip to:
"Unity Install Directory"\Editor\Data\Resources\ScriptTemplates
(You need to restart Unity to load this files correctly)

Now you can create entitas Components/ Systems even faster, like Monobehaviour scripts!
![enitas context menu](https://user-images.githubusercontent.com/18166769/27987376-0a25b2be-640d-11e7-96e1-c0627045e087.png)

@sschmid 
Maby you can integrate this in your setup or migration tool or something!

Kind regards
Spy-Shifty

**Comment by sschmid** [comment]
Awesome! Thanks. I linked this issue here
[Wiki - Tools and Extensions](https://github.com/sschmid/Entitas-CSharp/wiki/Tools-and-Extensions)

so people can find it better.

**Comment by chuckbergeron** [comment]
Rad, thanks for this! If you're on Mac OSX here's some install instructions: 

Right-click your Unity.app and click `Show Package Contents` and copy / move the files to: `Contents/Resources/ScriptTemplates/*`

**Comment by gd2020** [comment]
https://github.com/gd2020/EntitasTemplates

I made it as a plugin so that it makes us possible to use this without setup.
