### ISSUE TITLE
Add Portable Code Library compatibility

### ISSUE THREAD

**Issue by ironicnet** [sschmid/Entitas-CSharp#446]
Right now, whenever i generate code for a Portable Code Library type of project, i get this error on the "Contexts.cs":

> error CS1061: 'Type' does not contain a definition for 'GetMethods' and no extension method 'GetMethods' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
> error CS0117: 'Attribute' does not contain a definition for 'IsDefined'
> error CS1579: foreach statement cannot operate on variables of type '?' because '?' does not contain a public definition for 'GetEnumerator'

I'll try to submit a PR with some flag for the ContextsGenerator.cs

**Comment by ironicnet** [comment]
Nowadays i'm replacing:

        ```
var postConstructors = System.Linq.Enumerable.Where(
            GetType(),
            method => System.Attribute.IsDefined(method, typeof(Entitas.CodeGeneration.Attributes.PostConstructorAttribute))
        );
```

With
```
 var postConstructors = System.Linq.Enumerable.Where(
                GetType().GetRuntimeMethods(),
                method => method.GetCustomAttribute(typeof(Entitas.CodeGeneration.Attributes.PostConstructorAttribute))!=null
            );

```

I really don't know if this is the best way to do it. but it seems to be working

**Comment by sschmid** [comment]
Take a look at [ContextsGenerator](https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration.Plugins/Entitas.CodeGeneration.Plugins/CodeGenerators/ContextsGenerator.cs)

It's possible to implement custom generators to change the default behaviour of the code generator.
