### ISSUE TITLE
ContextStillHasRetainedEntitiesException - Log all retained entities

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#448]
A common scenario you guys encountered is when resetting the contexts and changing scenes in Unity that you experience the `ContextStillHasRetainedEntitiesException`

```
ContextStillHasRetainedEntitiesException: 'Game' detected retained entities although all entities got destroyed!
Did you release all entities? Try calling systems.ClearReactiveSystems() before calling context.DestroyAllEntities() to avoid memory leaks.
```

You'll get this exception because some entities are still retained. Entities are usually retained by the context, groups, collectors and entity indices. When you destroy entities and therefore remove all its components, they will be removed from groups, entity indices and the context. They still might be retained by a collector that hasn't been cleared yet (e.g. a reactive system uses collectors, but the reactive system hasn't been executed yet). That's why `systems.ClearReactiveSystems()` often solves the problem.

If you manually created your own collectors or called `entity.Retain()` on entities you have to release the yourself. An easy way to detect objects that still retain entities is to select an entity in the hierarchy and see the retain section
![](https://raw.githubusercontent.com/sschmid/Entitas-CSharp/develop/Readme/Images/Entitas.Unity.VisualDebugging-Entity.png)

If you're using EntityLink for your views, you also have to unlink them before changing the scene.

Todo:
Log all retained entities in the error message to simplify detecting retained entities.

**Comment by sschmid** [comment]
This is what you'll get now
```
'Game' detected retained entities although all entities got destroyed!
Did you release all entities? Try calling systems.ClearReactiveSystems()before calling context.DestroyAllEntities() to avoid memory leaks.
Entity_0(*2)() - SomeObject, SomeOtherObject
Entity_1(*2)() - SomeObject, SomeOtherObject
```

**Comment by akoolenbourke** [comment]
I know this is old but I've just hit this problem and the solution doesn't seem obvious. I am using EntityLink but there seems to be an A/B problem here. If I unlink before killing gameobjects, it's possible that gameobjects might try and access EntityLink in their next Update before I get a chance to unload the scene, and therefore fail. If I unload the scene first, the game objects are gone and unlinked but how can I guarantee that my code can then be called at right at the end to DeactivateReactiveSystems and context.Reset()?
