### ISSUE TITLE
Destroyed Entity will be passed to Reactive Systems

### ISSUE THREAD

**Issue by patrickkulling** [sschmid/Entitas-CSharp#45]
Entities that are marked as _isEnabled = false should not be passed into an IReactiveSystem anymore.
You should be able to reproduce this behaviour with the following steps:

* Create 'Systems' with the 2 following systems:
* ```CreateEntitySystem : IInitializeSystem```
* ```ListenToAnyComponentSystem : IReactiveSystem```
* In ```CreateEntitySystem.Initialize()```: Add a AnyComponent to that Entity
* In ```CreateEntitySystem.Initialize()```: Destroy that entity immediately 
* In 'ListenToAnyComponentSystem' listen to ```Matcher.AnyComponent.OnEntityAdded()```
* Notice that the destroyed Entity is still passed in
* Any call to ```entity.AddComponent(...)``` will lead to: ```new EntityIsNotEnabledException("Cannot add component!")```

Expected behaviour: Destroyed entities shouldn't be passed into IReactiveSystems anymore

**Comment by sschmid** [comment]
Hi, this behaviour is expected for ReactiveSystems. ReactiveSystems are triggered by events like OnEntityAdded, OnEntityRemoved etc. and don't guarantee that that component that triggered the system is still present nor that the entity is not destroyed by the time it executes.
Generally, destroying entities in the middle of the systems chain is a bad idea. Destroying entities should be the last thing you do per frame, so every system has the chance to process these entities.
