### ISSUE TITLE
How to design a entitas ui system?

### ISSUE THREAD

**Issue by colourstar** [sschmid/Entitas-CSharp#453]
Hi everyone,i have a question about game ui design by ecs framework.
As you know,in general game design,ui system will designed as a node tree,and each ui will has a layout file to describe the ui,including position,texture,type,parent,and so on.and ui node,such as a button,will attach a callback function to implement what to do if the button clicked,or a slipbar draged and so on.
I read all the [https://github.com/cloudjubei/EntitasTanks](url) codes,that is brilliant,but the ui system is a little simple,my game will be a large system,which contains about 100 panels,and panel may have complicate ui layout and input events,so how to manage them in entitas is a problem that i have no idea.
My question is that how to design an entitas ui system,to implement show the ui,respond the input message,show the logic data,and so on?Or is there any examples to learn this issue?

**Comment by FNGgames** [comment]
For advanced ui the solution is to create interfaces e.g. IMenuItem then have monobehaviours which implement your interfaces. Then you can have a component e.g. MenuItemComponent with field item : IMenuItem. Your interfaces define the methods you want to use in your systems (e.g. OnClicked). If you build up your ui functionality that way you can make it as complex as you need, and plug into all the unity functionality through the monobehaviour. This has the advantage of requiring only that you re-implement your interfaces in the new engine should you want to switch engine later. Your systems code can then be completely engine-agnostic.

**Comment by colourstar** [comment]
@FNGgames Thanks a lot,i have some thinking about this issue,i dont know if you read this git
[https://github.com/mzaks/Entitas-ReactiveUI](url),which is same with your advise : component includes interfaces,which implement operations in detail.
