### ISSUE TITLE
Clearing all reactive systems but there are still retained entities

### ISSUE THREAD

**Issue by beck-daniel** [sschmid/Entitas-CSharp#458]
Using the latest Entitas release, after clearing all reactive systems, the following error is thrown:
`ContextStillHasRetainedEntitiesException: 'Character' detected retained entities although all entities got destroyed!
Did you release all entities? Try calling systems.ClearReactiveSystems() before calling context.DestroyAllEntities() to avoid memory leaks.`

This happens when I use a matcher that looks like this:
```
protected override ICollector<CharacterEntity> GetTrigger(IContext<CharacterEntity> context)
{
        return context.CreateCollector(
            CharacterMatcher.Speed.AddedOrRemoved(),
            CharacterMatcher.PathfindingTarget.AddedOrRemoved());
}
```

but not when I change that to:
```
protected override ICollector<CharacterEntity> GetTrigger(IContext<CharacterEntity> context)
{
        return context.CreateCollector(
            CharacterMatcher.PathfindingTarget.AddedOrRemoved());
}
```

**Comment by sschmid** [comment]
Hi! Can you click on the empty entity (will have a red `e` symbol) in the Unity hierarchy to see which objects are retaining this entity? This will give you a clue what went wrong

**Comment by sschmid** [comment]
Will look sth like this

<img width="379" alt="screen shot 2017-08-21 at 11 52 19" src="https://user-images.githubusercontent.com/233700/29513994-44450e00-8667-11e7-8c78-5550d4cb33ab.png">

<img width="445" alt="screen shot 2017-08-21 at 11 52 32" src="https://user-images.githubusercontent.com/233700/29513998-484b0496-8667-11e7-80e9-bf1b0ec12f3a.png">

**Comment by sschmid** [comment]
ref #448

**Comment by danielbe1** [comment]
The entity is retained by the collector (shown in the message above) of the reactive system I created the collector above for. I followed #448 and even after clearing all reactive systems the entity was still retained by that reactive system.

**Comment by sschmid** [comment]
Ah, I see, because you have a collector with AddedOrRemoved, it will collect an entity when a certain component got removed, which happens when destroying all entities. Call `systems.DeactivateReactiveSystems()` before you destroy all entities to avoid this as this will deactivate collecting entities until you call `systems.ActivateReactiveSystems()`, see [Systems.cs](https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Systems/Systems.cs)

**Comment by beck-daniel** [comment]
Awsome, that works, thanks!
