### ISSUE TITLE
How to dynamically activate/deactiavte any kind of system?

### ISSUE THREAD

**Issue by isbdnt** [sschmid/Entitas-CSharp#460]
A temporary way to achieve that is to use if/else in system code and this makes systems depend on specific options, but different scenes have different options, it turns out you have to add more judgement statements due to more different scenes. I think this logic code should be in controllers or managers, not systems, but if I do that, then I can not dynamically change options, that's why I need activating/deactiavting systems at runtime.

**Comment by isbdnt** [comment]
Temporarily way to achieve that is to use if/else in system code and this way makes systems depends on specific options, but different scenes have different options, it turns out you have to add lots of preprocessor directives due to more different scenes.

**Comment by KumoKairo** [comment]
We use different systems for different game states (i.e. Select Car state and Race state)
It can be either a scene-based controller (with all the states there) or a state-specific controller. Each state specific controller has a list of Systems which it executes, cleans up and tears down upon exit
Thus, you have a lot of options:
You can use specific managers to handle different game states
You can create "meta-systems" that check this "if/else" things and call other systems accordingly (this approach increases code dependency and not encouraged though)
etc.

Maybe you can provide your specific example with exact things you are facing now so it will be easier to provide and advice

**Comment by isbdnt** [comment]
My solution for this issue.
`
#if (!ENTITAS_DISABLE_VISUAL_DEBUGGING && UNITY_EDITOR)
    public class Processor : Feature
    {
        Dictionary<string, int> _executeSystemInfoIndices = new Dictionary<string, int>();
        Dictionary<string, int> _initializeSystemInfoIndices = new Dictionary<string, int>();

        public Processor this[string name]
        {
            get
            {
                return (Processor)executeSystemInfos[_executeSystemInfoIndices[name]].system;
            }
        }
        public override Systems Add(ISystem system)
        {
            base.Add(system);
            if (system is IExecuteSystem)
            {
                _executeSystemInfoIndices[system.GetType().Name] = _executeSystemInfoIndices.Count;
            }
            if (system is IInitializeSystem)
            {
                _initializeSystemInfoIndices[system.GetType().Name] = _initializeSystemInfoIndices.Count;
            }
            return this;
        }
        public Processor ActivateExecuteSystem(string name)
        {
            int index = _executeSystemInfoIndices[name];
            var info = executeSystemInfos[index];
            info.isActive = true;
            (info.system as IInitializeSystem)?.Initialize();
            return this;
        }
        public Processor DeactivateExecuteSystem(string name)
        {
            int index = _executeSystemInfoIndices[name];
            var info = executeSystemInfos[index];
            info.isActive = false;
            (info.system as ITearDownSystem)?.TearDown();
            return this;
        }
        public Processor ExecuteInitializeSystem(string name)
        {
            int index = _initializeSystemInfoIndices[name];
            var info = initializeSystemInfos[index];
            ((IInitializeSystem)info.system).Initialize();
            return this;
        }
        public Processor(string name) : base(name)
        {

        }
        public Processor()
        {

        }
    }

#else
        
    public class Processor : Feature
    {
        Dictionary<string, int> _executeSystemIndices = new Dictionary<string, int>();
        List<bool> _executeSystemActivities = new List<bool>();
        Dictionary<string, int> _initializeSystemIndices = new Dictionary<string, int>();

        public Processor this[string name]
        {
            get
            {
                return (Processor)_executeSystems[_executeSystemIndices[name]];
            }
        }
        public override void Execute()
        {
            for (int i = 0; i < _executeSystems.Count; i++)
            {
                if (_executeSystemActivities[i])
                {
                    _executeSystems[i].Execute();
                }
            }
        }
        public override Systems Add(ISystem system)
        {
            base.Add(system);
            if (system is IExecuteSystem)
            {
                _executeSystemIndices[system.GetType().Name] = _executeSystemIndices.Count;
                _executeSystemActivities.Add(true);
            }
            if (system is IInitializeSystem)
            {
                _initializeSystemIndices[system.GetType().Name] = _initializeSystemIndices.Count;
            }
            return this;
        }
        public Processor ActivateExecuteSystem(string name)
        {
            int index = _executeSystemIndices[name];
            var system = _executeSystems[index];
            _executeSystemActivities[index] = true;
            (system as IInitializeSystem)?.Initialize();
            return this;
        }
        public Processor DeactivateExecuteSystem(string name)
        {
            int index = _executeSystemIndices[name];
            var system = _executeSystems[index];
            _executeSystemActivities[index] = false;
            (system as ITearDownSystem)?.TearDown();
            return this;
        }
        public Processor ExecuteInitializeSystem(string name)
        {
            int index = _initializeSystemIndices[name];
            var system = _initializeSystems[index];
            system.Initialize();
            return this;
        }
        public Processor(string name) : base(name)
        {

        }
        public Processor()
        {

        }
    }
#endif
`

**Comment by isbdnt** [comment]
Then I can activate/deactivate some systems easily by editor or UI in game. Below is the inspector code snippet.
```csharp
bool isGod;
                if (asset.BoolPropertyField("isGod", out isGod))//return true if the field has changed.
                {
                    if (Application.isPlaying)
                    {
                        if (isGod)
                        {
                            Controller.processor
                                .DeactivateExecuteSystem("MainFighterWalkSystem")
                                .DeactivateExecuteSystem("ThirdPersonCameraProcessor");
                            Controller.processor
                                .ActivateExecuteSystem("CameraFlySystem")
                                .ActivateExecuteSystem("CameraWalkSystem")
                                .ActivateExecuteSystem("CameraLiftSystem")
                                .ActivateExecuteSystem("CameraFreeRotationSystem");
                        }
                        else
                        {
                            Controller.processor
                                .DeactivateExecuteSystem("CameraFlySystem")
                                .DeactivateExecuteSystem("CameraWalkSystem")
                                .DeactivateExecuteSystem("CameraLiftSystem")
                                .DeactivateExecuteSystem("CameraFreeRotationSystem");
                            Controller.processor
                                .ActivateExecuteSystem("MainFighterWalkSystem")
                                .ActivateExecuteSystem("ThirdPersonCameraProcessor");
                        }
                    }
                }
````
![image](https://user-images.githubusercontent.com/26591233/30008734-d319751a-9154-11e7-858a-a06cd1d7200b.png)
