### ISSUE TITLE
Suggestions required. Adding multiple identical components to the same entity

### ISSUE THREAD

**Issue by PanCotzky** [sschmid/Entitas-CSharp#462]
Hey!

Here's the deal. I have a certain functionality that needs to be shared between multiple components within the same entity. For example I have a character that has Health, Mana, Stamina, different skills. I can make each of them separate objects but they all can get bonuses, buffs, debuffs in other words they share a lot of functionality. So, it would be wise to combine them into a single component type and then create a feature that processes each of them with the same logic. But as I can imagine I can't add the same component to an entity multiple times.

At this time i'm trying to solve this problem by creating multiple "Property" entities and binding them to the same "Unit" entity via "UnitId" and then getting them like this:

```
Contexts.sharedInstance.gameState.GetEntitiesWithUnitOwner(entity.unit.Id)
                    .Where(e => e.hasProperty && e.property.name == "Health");

```
or

```
Contexts.sharedInstance.gameState.GetEntitiesWithProperty("Health")
                    .Where(e => e.hasUnitOwner && e.unitOwner ==entity.unit.Id);
```

As you can see both ways are clunky. I don't mind to adapt to them but may be I'm doing it the wrong way? Can you suggest more straight forward way?

Thank you!

**Comment by paraboxx** [comment]
You could implement your own index that reacts to entities with unit owners and properties and puts them in a like Dictionary<int, Dictionary<string, GameStateEntity>> for fast lookups. int would be the unit Id, string the property type, and GameStateEntity is the entity that contains the property.

Just look at the implementation for GetEntitiesWithUnitOwner() and roll your own that fits your usecase.

**Comment by sschmid** [comment]
Hi, having a separate entity for bonuses etc and binding them to the owner entity with id makes sense. When your processing your owner entity you can do `context.GetBonusesForEntity(e.id.value)` or sth like this.
