### ISSUE TITLE
More clear feedback on generating with present compiler errors

### ISSUE THREAD

**Issue by KumoKairo** [sschmid/Entitas-CSharp#463]
When generating code with compiler errors in the project, it looks like everything is working fine - there's a progress bar and other things, just like in a regular code generation. The problem is that there's only a small non-warning message in the console, saying that it will generate based on last compiled executable, which is not visible unless the console window is opened. There were a few cases already and it seems like a common problem when people using Entitas can't find the reason why generated components don't have newly added fields.
I guess this problem will go away with #77 and #104 once Roslyn generator is a default generating solution, but for now it will help just to add another dialog window saying that there are compiler errors in the project and it will generate code based on last successful build. Just like when you run a plan C#/C++ project in visual studio, it tells you that there are compiler errors and it asks you whether you want to run your last successful build. This way everything will become more transparent

**Comment by sschmid** [comment]
Agree. You will see this now

![entitas-codegenerator-compileerrorpopup](https://user-images.githubusercontent.com/233700/32519395-e8dccbdc-c40c-11e7-8a6c-08f176b23244.png)
