### ISSUE TITLE
EntityIndex - Operation is not valid due to current state of the object

### ISSUE THREAD

**Issue by kdrzymala** [sschmid/Entitas-CSharp#464]
Hey guys! I'm getting an error like described above when trying to generate this:

```csharp
[Meta]
public class UnlockedTrickComponent : IComponent {
        [PrimaryEntityIndex]
        public string trickId;
        [EntityIndex]
        public int trickHash;
}
```

But it generates fine when I remove one of the indexes. Am I not allowed to have multiple indexes on one component or did I miss something?

Thanks.

**Comment by aefreedman** [comment]
You are correct, you can only use one index per component.

**Comment by kdrzymala** [comment]
Ok, so a feature request :)
Let the error message tell the user what's the problem, took me too much time to figure this one out ;-)

**Comment by sschmid** [comment]
Hey, good find. Just added support for multiple indexed members per component!

**Comment by sschmid** [comment]
Reopen, needs some more adjustments...

**Comment by sschmid** [comment]
Updated generator, multiple entity indices are now supported! 👍
