### ISSUE TITLE
Could not find file Assembly-CSharp.csproj

### ISSUE THREAD

**Issue by jwvanderbeck** [sschmid/Entitas-CSharp#465]
I started a new project, added Entitas, and created one dummy script file so that Unity would compile.  I then opened the Entitas preferences, changed the generated path to be Source rather than Sources just out of personal preference and hit Generate.  I got an error from Entitas:
    
    Could not find file D:\Unity\TestProject\Assembly-CSharp.csproj

Looking in the Entitas preferences I see it has a setting "Project Path" which is not shown in the screenshots on the Wiki so I assume it is new? That says "Assembly-CSharp.csproj" so I assume that is why it is looking for this file.  This file however does not exist anywhere that I can see.

Is this correct? Should that be pointing to my actual project file, TestProject.csproj?

This is with latest Unity Beta, 2017.3b4

**Comment by jwvanderbeck** [comment]
Interestingly the exact same version of Entitas and the exact same version of Unity on my Mac does work and does have that file.  So it works on Mac, but does not work on Windows.

**Comment by FNGgames** [comment]
Yeah, point it to your MyProjectName.csproj file. This should be better documented.

**Comment by sschmid** [comment]
Hi, Unity has been changing this back and forth. It has been Assembly-CSharp.csproj for most of the time. I had a built where it was MyProjectName.csproj.

**Solution:**
Either deactivate the `Update .csproj` post processor (which is mainly useful when using the Code Generator CLI)

<img width="415" alt="entitas preferences" src="https://user-images.githubusercontent.com/233700/31048633-b7e053e0-a621-11e7-91fd-c1c2016dedc6.png">

or update your path to MyProjectName.csproj as @FNGgames already mentioned correctly

**Comment by jwvanderbeck** [comment]
The really strange thing is how on my Mac it does have Assembly-CSharp.csproj and it is the exact same version of Unity! 

I changed it to my project name on my Windows machine and now I can generate successfully.  If I go to Tool->Entitas->Generate it generates with no errors.

However if I go to Tools->Entititas->Preferences the click the Generate button there, I get an NRE in the console:

NullReferenceException: Object reference not set to an instance of an object
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:296)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7782)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7762)
UnityEditor.EditorGUILayout.LabelField (UnityEngine.GUIContent label, UnityEngine.GUIContent label2, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:6187)
UnityEditor.EditorGUILayout.LabelField (System.String label, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:6143)
Entitas.Unity.Editor.PreferencesWindow.drawException (System.Exception exception)
Entitas.Unity.Editor.PreferencesWindow.drawPreferencesDrawers ()
Entitas.Unity.Editor.PreferencesWindow.OnGUI ()
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:295)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:288)
UnityEditor.HostView.OldOnGUI () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:107)
UnityEngine.Experimental.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt) (at C:/buildslave/unity/build/Runtime/UIElements/Managed/IMGUIContainer.cs:179)
