### ISSUE TITLE
No Wiki documentation on TearDown systems

### ISSUE THREAD

**Issue by jwvanderbeck** [sschmid/Entitas-CSharp#466]
As I was reading the wiki page on Systems, I was thinking that it seemed there was something missing.  We have Initialize systems for startup, Execute systems for every frame and Cleanup systems for end of every frame.  What about shutdown I thought?

Then in Unity I noticed that in the SystemsDebugger there is indeed mention of a TearDown system which I assume is what I mentioned.  There is however nothing that I can find in the Wiki about this system, how to implement it, or how to call it.

**Comment by FNGgames** [comment]
GameController.cs

```csharp
void OnDestroy() {
    _systems.TearDown();
}
```

**Comment by jwvanderbeck** [comment]
Yeah I figured out how to use it from digging through the code, but the reason I opened the issue was to address the problem of the System's page on the Wiki which does not include this system.
