### ISSUE TITLE
[VisualDebugging] Cannot retain Systems game object after switching to new scene

### ISSUE THREAD

**Issue by optimisez** [sschmid/Entitas-CSharp#471]
When switching to whole new scene, the Systems game object will just getting destroyed as it does not call Object.DontDestroyOnLoad. I suggest make Systems game object still retain after switching to new scene or provide an API to do the setting. For now, I just use DontDestroyOnLoad(GameObject.Find("Root Systems")); to fix this issue but it's kind of ugly.

**Comment by KumoKairo** [comment]
The destruction of systems is an essential part of their usage. This is what we use `ITearDownSystem` for.
You basically use it to cleanup the current state of the game - unlink entities that have their GameObject views destroyed, etc.

If you need a notion of common systems that don't get destroyed for the whole lifetime of a game, you should create them from an already `DontDestroyOnLoad` object.
Systems themselves should know nothing about whether they are used from Unity or from pure C# code, it's just an unnecessary coupling.

**Comment by sschmid** [comment]
As every game is different, sometimes you want the the VisualDebugging Systems Object to be destroyed when changing scenes, sometimes not. I recommend using `DontDestroyOnLoad` as you suggested if your systems instance needs to stay alive.
