### ISSUE TITLE
Paid Roslyn Generator thoughts and suggestions

### ISSUE THREAD

**Issue by KumoKairo** [sschmid/Entitas-CSharp#472]
Just to keep in mind - the following message is just thoughts on paid/free Entitas versions and should not be treated as judging or whining or whatever, so please keep your mind open for a few following paragraphs. I decided to post a question here, rather than in the Gitter Chat, so it doesn't get lost in the history right away.

Anyways.
I personally think that making a new-Roslyn-generator only available in a paid version may not be as beneficial as it may seem. I've been gathering some feedback on Entitas lately and the only downside almost everyone has mentioned is the pain of working against The-Evil-Code-Generator, fixing compiler errors after changing components and all that stuff that this New-Glorious-Generator is going fix. Right now, after a few years of using Entitas, I already have a paid AssetStore version, but I'm concerned about how it will be treated by new Entitas users. In my mind it's like this - a new user comes to try Entitas, he sees two versions - free and paid, and decides to go with the free first (no way dude!). He starts developing things, trying to get acquainted with this new paradigm, and all is good except that generator that keeps making his life harder. The only possible solution will be to buy the full version, and this "buy to use" solution may seem like a forced purchase, making the whole thing look suspicious. Don't get me wrong, Simon *needs* to find a way to make money with Entitas, but there has to be another, maybe more profitable solution to this. Not just fixing the main paint-point of Entitas for money. 
Take Godot Engine for example. The creator has successfully opened a patreon page and is getting 4k$ + dollars a month just to keep developing the engine full time (https://www.patreon.com/godotengine). And the engine still has a hell lot of limitations and things-to-do. 
Maybe we need to help Simon sell some Entitas addons that are not as essential as the Roslyn Generator, but help boosting productivity a lot.
Maybe there's yet another way around this.

**Comment by WoLfulus** [comment]
Maybe a cool system/component marketplace? Or a set of ready to use stuff? A marketplace is a hell lot of work that should be put outside entitas itself, but could be an option for monetizing entitas in another way.

Still, I fully support simon's decision and I'll buy it myself when its out, but I do agree that this problem everyone has with the current code generator is a show stopper if you're trying to evaluate new stuff :(

**Comment by raincole** [comment]
I agree with @KumoKairo . It's an open source project after all, and while I'm willing to pay dozens of dollars to support it, I wouldn't like to see one of the core features become premium-only. Selling addons and books like "Best Entitas Practices" will be better options. Maybe a book about general ECS with examples written in Entitas? I bet there are thousands of programmers who are struggling getting ECS done right out there!

**Comment by KumoKairo** [comment]
We can create a visual node based editor for Entitas and present it to Simon to sell it on the assetstore. And in turn recieve a free Roslyn generator for the community.
I'll add more info on the upcoming Visual Entitas Jam #475 
Feel free to take part ;)
