### ISSUE TITLE
Poll: Unity Version

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#474]
The Unity version used to submit a package to the Unity Asset Store will define the minimum version for people how want to download the asset.

I'd like to get a feeling what you guys are using.

Please add a comment with the Unity version, and people with the same version can give it a thumbs up, so I can get an overview.

Thanks for commenting :)

**Comment by sschmid** [comment]
2017.2

**Comment by kdrzymala** [comment]
5.6.3.p4

**Comment by PencilBow** [comment]
2017.1.1f1, but moving to 2017.2 very soon

**Comment by jwvanderbeck** [comment]
You know you can submit multiple versions right?

We're currently using 2017.3 beta and almost always stay on the latest beta unless I run into show stopping issues.

**Comment by roygear** [comment]
2017.2

**Comment by Neikice** [comment]
2017.2

**Comment by Rybachello** [comment]
2017.1.2

**Comment by IsaiahKelly** [comment]
2017.2 

I'd suspect most users here like living on the cutting edge 😎 so the results will be skewed. A more actuate stat would be the [Unity version usage](https://forum.unity.com/threads/unity-version-usage-updates-now-in-publisher-forum.250891/page-3) data released by Unity themselves. You can get the very latest numbers for that in the private publisher forum, which you gain access to by [signing up for it here](https://support.unity3d.com/hc/en-us/articles/205930085-How-can-I-join-the-Unity-Publishers-Forum-). 

However, if you're only going to upload a single version the safest action would be to use the oldest supported version of Unity. Only upgrading when it's absolutely required. 

But Unity 2018.x will probably become the minimum required version anyway if you decide to integrate the new job system that's coming next year. ❓

**Comment by KumoKairo** [comment]
This is the editor usage statistics that is posted on Unity Publishers forum on 26th of July 2016. They publish new statistics every three months, so new stats should be coming soon.

**Methodology**:
* Medium-to-High users (excludes those who used Unity for a very short period of time during the period)
* Previous 30 days

**Current Major Versions**:
* 2017 - 13.5%
* 5.x - 83.9%
* 4.x - 2.5%
* 3.x - 0.1%

![image](https://user-images.githubusercontent.com/2943071/32266377-3e9b1278-bef8-11e7-90f2-ac5450af852e.png)

Targeting 5.5+ should be pretty safe, targeting most of the active users

**Comment by chiuan** [comment]
2017.2

**Comment by nbreum15** [comment]
2017.2
