### ISSUE TITLE
Does having a lot of entities (thousands) effect performance? 

### ISSUE THREAD

**Issue by haoRchen** [sschmid/Entitas-CSharp#479]
Hi all!

Just started using Entitas. I've built a world with 20 000 tiles created at runtime(indexed using 2D array) and the fps is around 100. Converting this world to be generated via Entitas caused the framerate to hit 0 despite having only 1600 tiles. This is after the tiles have all been created with a sprite and location.  I'm not too sure what is the main cause of this. 

The map is 40 x 40 tiles in size, this is the code in a class that initializes the map. 

```csharp
public void Initialize() {
    // Name of sprite to be loaded
    const string resourceName = "Floor";

    GameEntity map = _context.CreateEntity();
    map.AddMap(40, 40);

    // Map creation.
    for (int x = 1; x < _context.mapEntity.map.height; x++) {
        for (int y = 0; y < _context.mapEntity.map.width; y++) {
            GameEntity e = _context.CreateEntity();
            e.AddSprite(resourceName);
            e.AddPosition(new Vector2(x, y));
        }

    }
}
```
Any pointers would be much appreciated!

**Comment by sschmid** [comment]
I'd recommend using the Unity profiler. Creating lots of entities is not a problem, I could imagine that VisualDebugging drops the framerate. Try turning VisualDebugging off in the Entitas Preferences and check again

**Comment by sschmid** [comment]
VisualDebugging will only run in the Unity Editor. Whenever you make a release build all this related code is stripped out and the overhead is removed.

**Comment by haoRchen** [comment]
Thanks Simon. Turning off the visual debugging does bring the framerate to about 60.  I'll have a go profiling to see whats causing it.

**Comment by sschmid** [comment]
Do you have any interesting profiling results?

**Comment by haoRchen** [comment]
![entitasprofiler](https://user-images.githubusercontent.com/19397242/32526633-684cdf2a-c3f8-11e7-988b-5f123ff9fbb4.PNG)

A screenshot of a new project with the bare minimum required to create 10k tiles. Is it normal to have the majority of weight in entity behavior updates?

**Comment by haoRchen** [comment]
thats true. Since visual debugging thousands of entities can bottleneck the framerate, does entitas have a way for someone to selectively pick which entities to visual debug?
