### ISSUE TITLE
Roslyn code generation of multidimensional arrays

### ISSUE THREAD

**Issue by christianvoigt** [sschmid/Entitas-CSharp#481]
I have a GridComponent that has a multidimensional array as a property (`public int[,,] value`). In the generated partial component class the array is transformed into `ReplaceGrid(int[*,*,*] newValue)`.

**Comment by sschmid** [comment]
Yes, you are right. I just added a unit test to see how roslyn displays types. In this case roslyns way of doing that is not able to compile

```
describe ComponentDataProvider. when providing. special types. supports 3d array [,,].
Expected string length 7 but was 10. Strings differ at index 4.,
Expected: "int[,,]",
But was: "int[*,*,*]",
```

Will add custom fixes for those "special" types

**Comment by sschmid** [comment]
I added my own `ISymbol.ToCompilableString()` which catches those cases. Will be in the next release!
