### ISSUE TITLE
CLI Server/Client can't use custom properties file

### ISSUE THREAD

**Issue by jwvanderbeck** [sschmid/Entitas-CSharp#482]
It doesn't appear that you can specify to use a custom properties file when using the CLI server/client.  I tried to do so and it didn't work, and looking at the code it appears that the only params they take is the port number.

**Comment by sschmid** [comment]
Yes, you're right, thanks! The arguments were cut off and only the 1st arg was send as a command. Here's the fix https://github.com/sschmid/Entitas-CSharp/commit/24cc1db504685aa7cd6370a524c0cc23b02bec40

will be in the next release
