### ISSUE TITLE
How does Entitas compare to the (super early) ECS Unity previewed at Unite Austin?

### ISSUE THREAD

**Issue by darbotron** [sschmid/Entitas-CSharp#483]
Hi,

I have a few questions and I might possibly want to contribute too.

I assume you've seen the ECS that Unity announced at Unite Austin earlier in the year: https://www.youtube.com/watch?v=tGmnZdY5Y-E

Re: contributing, I was on the brink of starting my own ECS implementation when I found the Unity video I linked above and then when I saw it was WAAAY out (not even on the road-map page of the Unity site AFAIK) I started googling and found entitas; I'd potentially be interested in contributing to entitas rather than starting from scratch but that rather depends on what Entitas does of what I expect my code to do eventually.

To my questions, it looks like the Unity ECS has a high degree of interoperability with Unity in the native C++ layer which I assume Entitas can't have since it's all C#; for me this is one reason almost not to bother writing my own ECS now since I'll probably end up replacing it with Unity's one eventually anyway.

There were a couple of key features about their ECS which I'm interested to know if entitas does / how it does them without having to go through all the sourcecode:

1) it looks like their ECS is likely to integrate with the threaded job system they announced way earlier in the year at Unite Europe which is obviously pretty cool. I'm wondering if Entitas makes use of threads at all and whether you feel it's likely to work well if threaded? (this is important for me - I expect to be CPU bound on in the game I'm making and I am sure I'll have to use threads to run at 60fps on consoles since their CPUs are so much slower than average PCs)

2) the design of the Unity ECS also sounds like it uses struct-of-array rather than array-of-struct to provide iteration over contiguous arrays of components of the same type, maximising d-cache coherence. Obviously the ECS approach is inherently good for i-cache coherence, but I'd be interested to know if there's anything like this to help d-cache coherency in Entitas? 

I know these are big questions and I could answer them by reading the source code, but I thought I'd ask before diving into it :)

Cheers

Alex

**Comment by IsaiahKelly** [comment]
Don't know if you've seen them already, but the Untie Europe [2015](https://youtu.be/1wvMXur19M4) and [2016](https://youtu.be/lNTaC-JWmdI) talks about Entitas should help here you get a much better understanding of how Entitas works in comparison to the new native  Unity ECS. At least as much as is currently possible with the little knowledge we currently have about those new Unity features.

Simon is also already working on beginner tutorials at the moment which may further help you understand this. I don't have enough knowledge of Entitas myself to really help explain the exact differences, but in any case it's probably way too early to really know since the new Unity ECS and job system hasn't been released yet, so our understanding of them is very limited at the moment.

A followup/alternative question to yours for @sschmid right now might be how easily he thinks Entitas will integrate with these new Unity features and how difficult or easy it might be to transition from Entitas to this new native Unity ECS in the future and if using Entitas now is a good first step / substitute / preparation for these future features.

**Comment by darbotron** [comment]
Thanks Isiah, yeah I totally watched the unite videos already.

The questions I have aren't inherently limited by knowing what Unity's recemtly announced experimental ECS does...

My questions without any reference to Unity's ECS are in essence:

1) can entitas run on a thread other than the main thread, & if not is it in theory capable of doing so?

2) is there currently any way to control the memory layout of the components so that they're in contiguous allocations rather than just heap allocated wherever the new operator puts them?

Cheers,

Alex

**Comment by IsaiahKelly** [comment]
Yeah, I now see that in addressing the issue title I missed some important details.

1. Currently no, but multi thread support is something Simon wants to implement (#325) and the new job system should help him with that goal.

2. I don't know the answer to this myself, but asking this question in the [chat](https://gitter.im/sschmid/Entitas-CSharp) will probably get you an answer sooner then here. In fact, chat might be a better place for all these question. You can also just wait for Simon to stop by and hopefully answer these question way better than me. 😄

**Comment by darbotron** [comment]
cool, thanks :)

**Comment by sschmid** [comment]
I think it's a good time to also stress that not only Unity's ECS has been built with performance in mind, performance is also one of Entitas key pillars. I've basically built what Unity is building now a year ago, I might have shared some info here and there about it when I talked about my other ECS with components as structs and entity is an int. I critically compared Entitas to my other ECS which has the same performance as the Unity ECS and Entitas kept up so great that I decided not to further pursue a second ECS. Plus, Entitas has Reactive Systems and a lot of other goodies that make ECS even more fun to use and the generate API is hard to beat. Unity is probably ahead with multithreading.

**Comment by darbotron** [comment]
Thanks for getting back to me - I'd really like to say I'm not trying to make it a competition! I was just wondering whether it would be worth waiting for the Unity ECS.

I was planning to implement an ECS using structs which is how I found Entitas in the first place (always good to avoid reinventing the wheel, right?).

When you say Entitas has similar performance to the struct implementation I'd be interested to know how close the performance was & if you have any thoughts on why the performance was so close? 
I would have expected the contiguous memory you'd theoretically get from the struct approach would have been a big win from a cache PoV.
