### ISSUE TITLE
Entitas Lang compiles "trigger" to Collector instead ICollector

### ISSUE THREAD

**Issue by Synean** [sschmid/Entitas-CSharp#485]
Hi,

I have an Issue with Entitas Lang:

sys ProcessSpacebarInputSystem
    **trigger:**
        added(SpacebarInput)
        filter allOf(SpacebarInput)
    access:
        _gameContext : Game

Compiles to: 

protected override **Collector**<CharacterEntity> GetTrigger(IContext<CharacterEntity> context) {
		return context.CreateCollector(CharacterMatcher.SpacebarInput, GroupEvent.Added);
	}

It should be: **ICollector**

The Error Message in Unity:
_Assets/src-gen/systems/ProcessSpacebarInputSystem.cs(9,48): error CS0508: `AbstractProcessSpacebarInputSystem.GetTrigger(Entitas.IContext<GameEntity>)': return type must be `Entitas.ICollector<GameEntity>' to match overridden member `Entitas.ReactiveSystem<GameEntity>.GetTrigger(Entitas.IContext<GameEntity>)'_

**Comment by nbreum15** [comment]
The GitHub for Entitas-Lang is: https://github.com/mzaks/Entitas-Lang. Post the issue there 😃.

**Comment by Synean** [comment]
Thank you :-)
