### ISSUE TITLE
Entitas 0.45.0 cannot generate code 

### ISSUE THREAD

**Issue by optimisez** [sschmid/Entitas-CSharp#486]
After updated to version 0.45.0. I cannot generate code anymore. I also notice that the Code generator section at preference setting each option has been changed back to nothing and I not able to change to everything. 

![image](https://user-images.githubusercontent.com/7009368/32761749-128fbf16-c930-11e7-9fbb-4a407a8ae0a7.png)

**Comment by owengalenjones** [comment]
Same issue here.

**Comment by sschmid** [comment]
Hi, take a look at the [EntitasUpgradeGuide.md](https://github.com/sschmid/Entitas-CSharp/blob/develop/EntitasUpgradeGuide.md#entitas-0450-upgrade-guide).

- Use `MigrationAssistant.exe 0.45.0 path/to/project` 
- update the searchPath that points to the default plugins to from `CodeGenerator /Plugins/Default` to `CodeGenerator /Plugins/Entitas`

**Comment by sschmid** [comment]
Oh, I see, starting with a new project from scratch won't give you an option to select code generators. Will do a patch release

**Comment by optimisez** [comment]
Btw the I tried ur migration tools but seems like it does not work properly so I edit it manually.  For the searchPath I only see have this that I didn't see CodeGenerator/Plugins/Default

`CodeGenerator.SearchPaths = Assets/Libraries/Entitas, \
                            Assets/Libraries/Entitas/Editor, \
                            /Applications/Unity/Unity.app/Contents/Managed, \
                            /Applications/Unity/Unity.app/Contents/Mono/lib/mono/unity, \
                            /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/GUISystem`

**Comment by chiuan** [comment]
same issue

**Comment by sschmid** [comment]
I removed some default values for the code generator in this release, this is causing the issue. I will find another way to set them. In the meantime check Entitas.properties that the plugins are set so Unity can display them in the Preferences Window

sth like this (taken from Match One)
```
CodeGenerator.SearchPaths = CodeGenerator/Plugins/Entitas, \
                            Assets/Libraries/Entitas, \
                            Assets/Libraries/Entitas/Editor, \
                            ${user.unity}/Managed, \
                            ${user.unity}/Managed/UnityEngine, \
                            ${user.unity}/Mono/lib/mono/unity, \
                            ${user.unity}/UnityExtensions/Unity/GUISystem

CodeGenerator.Plugins = Entitas.CodeGeneration.Plugins, \
                        Entitas.VisualDebugging.CodeGeneration.Plugins
```

**Comment by sschmid** [comment]
you can also run
```
$ entitas auto-import
```

to automatically find and set all available plugins interactively.

**Comment by sschmid** [comment]
Next release will come with a convenient Auto Import Button. This will detect plugins, will set all defaults and automatically update Entitas.properties

<img width="449" alt="entitas-autoimportbutton" src="https://user-images.githubusercontent.com/233700/32833491-5381fc6c-c9ff-11e7-99ac-cccc60957596.png">

**Comment by sschmid** [comment]
Get the fix here

[Entitas 0.45.1](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.45.1)
