### ISSUE TITLE
Feature Request - Unity Entities Components

### ISSUE THREAD

**Issue by aqaddoumi** [sschmid/Entitas-CSharp#490]
Entitas is a great tool for building games but as it stands right now, it’s very hard to design games in it the “Unity Way”. Where you use the Unity Editor to set values and try different ideas, especially for game designers and non-programmers. Entitas fits very well for games with generated behavior but it doesn’t translate well for games with Levels, at least from my experience with Entitas. There were previous attempts like blue prints to tackle that but they didn’t work very well and soon were abandoned for different reasons. So here’s a new proposal that I think would work well but I might be wrong.

The main ideas is to use the code generator to generate Monobehaviours that you can attach to GameObjects in the Unity Editor. They have public variable based on the Entitas Component that game designers can change. When you press run there is a script that iterate through the scene hierarchy to check which GameObjects have these generated monobehaviours attached to it, it then creates new entities, add the appropriate entities components to it and then use EntityLink between the GameObject and the Entitas Entity. So basically you would create entities from Unity rather than the other way around. You could also create Prefabs with entity components. You could also attach multiple Unity Entitas Components to the same GameObject.

Here is my idea of implementation.

Step 1:

We create a new tag, lets call it [Unity] that the code generator would “understand” for example

```c#
using Entitas;

[Game, Unity]
public sealed class HealthComponent 
{
	public int health;
}
```

Step 2:

Press Generate and the code generator would generate a new MonoBehaviour script that look like that

```c#
 using UnityEngine;

  public class UnityHealthComponent : MonoBehaviour
{ 	
        public int health;
}
```

Step 3: 

We have a script let’s call it “UnityConext”, this is the first script you attach to any Unity GameObject that you want a related entity to be generated for it.

```c#
using UnityEngine;

  public class UnityContext : MonoBehaviour
{ 	
        public EntitasContexts context
} 
```

This is a public enum that have all the contexts currently in entitas. You choose from the editor which context you want your entity to be created.

Step 4:

You attach all the MonoBehaviour Components you want to that game object and when you press run there will be a script that loop through the hierarchy, checks if any game object have any of those generated monobehaviour components. It will create a new entity in the specified context, then add all the right components to that entity with the values specified by the designer in the Unity Editor. Plus it could use EntityLink to attach the GameObject with the newly created Entity.

Sorry but I don’t have a good implementation of how that code would work but it seems possible from my early tests.

I don’t have enough coding knowledge to implement this in a proper way, especially for the code generator but I don’t see any reason why it won’t be possible. I’m sure this approach have some cons and bad outcomes that I personally can’t see, but we can discuss that and see if it’s a good approach. 

One thing I can see that might cause problems is synchronizations between the Monobehaviours and the entities components. So what happens if you change a value in an entity, should the MonoBehaviour change it’s values too or should it just be used as an initialization pattern. This is something that can decided upon seeing the pros and cons of each implementation.

Thanks for the sticking this far with the post. If anyone have any better ideas or see this as a bad pattern or design, please tell me why. I can try to implement it if people point me to the right direction but I’m sure it won’t be optimized because the way I see it, I would have to use GetComponent a lot which is not very efficient so any volunteers would be appreciated.

**Comment by IDNoise** [comment]
There is bluepring functionality for this and it has problems now in case of component change.

There is one big cons: every time you want to change component stucture (combine, split, remove/replace) designer will need to fix all prefabs too. So it's better to have custom set of mono behaviours you give to your designer and you write own logic on how to translate this data into current set of components.

**Comment by kdrzymala** [comment]
I'd say coupling your entitas code to editor / unity like that isn't good. 
We did a level based game (didn't hit prod yet) and we were making custom mono behaviours for the designers with the params we allowed them to tweak :) 

Those MB's were creating entites / components based on the parameters set by designers - so if a breaking change/refactoring occurred - we managed to keep it all in code and unity scenes and prefabs weren't affected.

Generally - the less coupling you have, the better.

**Comment by aqaddoumi** [comment]
I guess those are very valid reasons not go this way. Maybe I'm just overthinking but it seems to me that there should be a generic elegant way to use Unity Editor and Entitas together and give the benefits of both instead of writing custom Mono Behaviours for each game, but I might be mistaken. Thanks 👍

**Comment by starikcetin** [comment]
@kdrzymala May you give a simple example of your approach?
