### ISSUE TITLE
Partial Component error

### ISSUE THREAD

**Issue by fayte0618** [sschmid/Entitas-CSharp#491]
So, I tried using the new roslyn generator and followed the guide using a fresh project (using Roslyn Generator from Asset store and 0.45.1 of Entitas) but I keep getting this "partial component" error. Here are my entitas settings and the error message:
![screenshot 2](https://user-images.githubusercontent.com/8073714/32967209-b8d04f50-cc17-11e7-8d98-677906a5a0ba.png)
![log](https://user-images.githubusercontent.com/8073714/32967089-46e85450-cc17-11e7-9085-e2d7e68677df.PNG)
![properties](https://user-images.githubusercontent.com/8073714/32967476-bce58f50-cc18-11e7-9166-c2d9ee8ad8a3.PNG)

![capture](https://user-images.githubusercontent.com/8073714/32967559-079cf1f0-cc19-11e7-9514-2f3de82637b7.PNG)
![component](https://user-images.githubusercontent.com/8073714/32967570-0cb6ed4e-cc19-11e7-96cc-e4113398d042.PNG)

**Comment by sschmid** [comment]
Ok, I see. So looking at you code generator output I see sth strange:

This is correct (marked with green)

```
Game/Components/GameFollowComponent.cs
```

But it also creates (marked with red)
```
Components/FollowComponent.cs
```

This usually only happens for objects that aren't `IComponent` but have an ContextAttribute like `[Game]`. In this case it will create a component for you. For some reason, it creates a FollowComponent for you, but this class is already an `IComponent.

![32967559-079cf1f0-cc19-11e7-9514-2f3de82637b7](https://user-images.githubusercontent.com/233700/32968168-81bca900-cbe0-11e7-8db6-af375f131418.PNG)


Try disabling `Entitas.CodeGeneration.Plugins.ComponentGenerator`

But actually, I think the error has to come from the Roslyn component data provider.

**Comment by sschmid** [comment]
Do you have 2 different .csproj files?

**Comment by fayte0618** [comment]
it creates copies
![capture](https://user-images.githubusercontent.com/8073714/32970147-b3a63be2-cc22-11e7-8c61-bdefbed509cb.PNG)

**Comment by nbreum15** [comment]
I think this is the same error i got. See #478. I didn't solve it by doing what was suggested in the issue. However, after switching to .NET 4.6 Experimental in Unity the problem was solved for me.

**Comment by fayte0618** [comment]
It's ok now. I changed runtime to .NET 4.6 then did a fresh setup and it works. The only problem i notice is whenever i regenerate components it displays this can't delete Assembly.dll error and compile erros appear. But, if i close and reopen Unity they disappear. I think it might have something do to do with the generator not allowing it to be deleted, since it deletes when I close it.
