### ISSUE TITLE
New Video Tutorial | Entitas - What's new - 0.45.1

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#492]
# Hi everyone,

I uploaded my very first Video Tutorial to YouTube. Please be easy on me guys :) I'll try to become better with every Video.
In this Video I compare the previous code generator with the new roslyn code generator. I show you how the new workflow can look like and how you can increase your productivity.

I will upload a new Video soon where I go more in depth with the code generator, so make sure to like & subscribe if you don't want to miss that.

### You can get [Entitas on the Unity Asset Store here](https://www.assetstore.unity3d.com/#!/content/87638)

---

### Entitas - What's new - 0.45.1
https://www.youtube.com/watch?v=LGKsqSg5FHg

![entitas - what s new - 0 45](https://user-images.githubusercontent.com/233700/33233967-21aa8678-d21f-11e7-8e20-15843964f926.jpeg)

**Comment by vasiliy-kuznetsov** [comment]
Thanks for great video.
The roslyn generator looks really great.

**Comment by sschmid** [comment]
Hey! I resolved the sound issues and uploaded an updated version of the video with better sound. Leave a like on the updated Video here
https://www.youtube.com/watch?v=LGKsqSg5FHg
