### ISSUE TITLE
0.45.1 Roslyn doesn't work on Windows

### ISSUE THREAD

**Issue by KumoKairo** [sschmid/Entitas-CSharp#495]
We're experiencing this problem for a few days. Launching `Entitas gen` drops with a NRE:
```
CodeGenerator\Entitas.exe gen -v
AppDomain load: Entitas.CodeGeneration.Plugins
  - Loading: Entitas.CodeGeneration.Plugins
    - Resolved: Assets\Libraries\Entitas\Editor\Entitas.CodeGeneration.Plugins.dll
AppDomain load: Entitas.VisualDebugging.CodeGeneration.Plugins
  - Loading: Entitas.VisualDebugging.CodeGeneration.Plugins
    - Resolved: Assets\Libraries\Entitas\Editor\Entitas.VisualDebugging.CodeGeneration.Plugins.dll
AppDomain load: Entitas.Roslyn.CodeGeneration.Plugins
  - Loading: Entitas.Roslyn.CodeGeneration.Plugins
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Entitas.Roslyn.CodeGeneration.Plugins.dll
Creating model: Context (4%)
Creating model: Component (Roslyn) (8%)
Opening Assembly-CSharp.csproj
  - Loading: System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\System.Collections.Immutable.dll
  - Loading: SQLitePCLRaw.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1488e028ca7ab535
    - Could not resolve: SQLitePCLRaw.core.dll
  - Loading: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.dll
  - Loading: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Framework.dll
  - Loading: Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.dll
  - Loading: System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\System.IO.FileSystem.dll
  - Loading: System.IO.FileSystem.Primitives, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\System.IO.FileSystem.Primitives.dll
  - Loading: Microsoft.Build, Version=14.1.0.0, Culture=neutral
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.dll
  - Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  - Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  - Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  - Loading: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.resources.dll
  - Loading: Microsoft.Build.Tasks.Core.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.resources.dll
  - Loading: Microsoft.Build.Tasks.Core.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.resources.dll
  - Loading: Microsoft.Build.Tasks.Core.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.resources.dll
  - Loading: Microsoft.Build.Tasks.Core.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.resources.dll
  - Loading: System.Reflection.Metadata, Version=1.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\System.Reflection.Metadata.dll
  - Loading: System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\System.IO.FileSystem.dll
  - Loading: System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\System.IO.FileSystem.dll
  - Loading: System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Could not resolve: System.IO.MemoryMappedFiles.dll
  - Loading: System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Could not resolve: System.IO.MemoryMappedFiles.dll
  - Loading: System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Could not resolve: System.IO.MemoryMappedFiles.dll
  - Loading: System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Could not resolve: System.IO.MemoryMappedFiles.dll
  - Loading: System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Could not resolve: System.IO.MemoryMappedFiles.dll
  - Loading: System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Could not resolve: System.IO.MemoryMappedFiles.dll
  - Loading: System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Could not resolve: System.IO.MemoryMappedFiles.dll
  - Loading: System.IO.MemoryMappedFiles, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Could not resolve: System.IO.MemoryMappedFiles.dll
  - Loading: Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Utilities.Core.dll
  - Loading: Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Framework.dll
  - Loading: Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.Build.Tasks.Core.dll
  - Loading: Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.CodeAnalysis.CSharp.dll
  - Loading: Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\Microsoft.CodeAnalysis.dll
Opened Assembly-CSharp
Parsing Assembly-CSharp
  - Loading: System.Security.Cryptography.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    - Resolved: CodeGenerator\Plugins\Entitas.Roslyn\System.Security.Cryptography.Primitives.dll
Complete Assembly-CSharp
System.NullReferenceException: Object reference not set to an instance of an object.
   at Entitas.Roslyn.SymbolExtension.ToCompilableString(ISymbol symbol)
   at Entitas.Roslyn.CodeGeneration.Plugins.ContextsComponentDataProvider.GetContextNames(INamedTypeSymbol type)
   at Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider.hasContexts(INamedTypeSymbol type)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider.GetData()
   at Entitas.CodeGeneration.CodeGenerator.CodeGenerator.generate(String messagePrefix, ICodeGeneratorDataProvider[] dataProviders, ICodeGenerator[] codeGenerators, ICodeGenFilePostProcessor[] postProcessors)
   at Entitas.CodeGeneration.CodeGenerator.CLI.Generate.run()
   at Entitas.CodeGeneration.CodeGenerator.CLI.Program.Main(String[] args)
```

This is the same problem at least one person in chat has experienced. There doesn't seem to be any solution yet.

It worked ok for the initial assetstore Roslyn version.

It works OK for a non-Roslyn generator (Ctrl+Shift+G from the Unity Editor)

**Comment by sschmid** [comment]
Ok, I need to find out what's causing this. To my current knowledge it's roslyn not being able to resolve types for unknown reasons. Someone send a project to me already, it worked on a Mac, but not on Windows with the exact same error as yours. I don't quite remember how I solved, but I didn't really change anything related to Entitas. It was more like making Unity regenerating the solution again. If you could send me a sample project where I can reproduce it, I will take a look into it. You can also DM me if you want.

**Comment by KumoKairo** [comment]
Cool, I'll try to regenerate the solution and project files and will write back here with the results.

**Comment by sschmid** [comment]
If anyone could send me a failing windows project, that would be very helpful. I think @StormRene also had this error once.

**Comment by sschmid** [comment]
Still waiting :)
Btw, try to use `/` instead of `\` in all your paths, not sure if that is related, but I just thought of it, because `\` is actually a reserved symbol in the properties syntax for multiline declaration

**Comment by KumoKairo** [comment]
Now I can't send you the project because we have tried importing it again (a few days after we initially switched back to standard generator) and it worked. I just watched the video as it was in the last time, done everything exactly the same and strangely enough it worked this time

**Comment by sschmid** [comment]
Strangely enough, I've heard this from almost everyone with initial problems. It kine of resolved itself?!?! That's what I've also seen when someone sent me a project. I opened it and then it worked, sent it back, and it worked :) Yay.

Never mind warnings like `Could not resolve` as long as the doctor tells you that everything is ok in the end.

**Comment by KumoKairo** [comment]
Can this `could not resolve` possibly impact the generators performance? Is there a way to use an `-a` append command to be able to `generate again` using this new client-server generator? Generating from client still raises those warnings and still takes the same amount of time

**Comment by sschmid** [comment]
Once the project is loaded by roslyn, there shouldn't be any `could not resolve` warnings anymore when using `entitas client gen`. The client/server completely replaced `gen -a`, it's more flexible and can be easily send from anywhere (e.g. from IDE or Unity). In case you have issues with the client on windows, I'm currently rewriting the tcp sockets (used for communicating between client and server).

**Comment by KumoKairo** [comment]
I have no issues except these `could not resolve` errors every time I run `entitas client gen`. with a `entitas server` running locally

**Comment by KumoKairo** [comment]
After a few generation iterations I started getting 
```Could not load file or assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.```
error. Rolled back to old generator, sent the project to IM on gitter

**Comment by gabrjt** [comment]
I'm also having the "Could not load file or assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified." problem. 

But this occurs with me only if I have Components that store classes from the UnityEngine, like a GameObject for example (ViewComponent).

**Comment by optimisez** [comment]
The problem seems similar to #503

**Comment by sschmid** [comment]
@gabrjt looks like you're using the reflection-based code gen in the terminal. If so, you have to update your searchpaths to point to the Unity dlls
(taken from [Match One - Entitas.properties](https://github.com/sschmid/Match-One/blob/master/Entitas.properties))
```
${user.unity}/Managed, \
${user.unity}/Managed/UnityEngine, \
```

or even easier,  just generate in Unity.

If you're using roslyn, you will not have this issue

**Comment by optimisez** [comment]
Hi @sschmid, I think I found the root cause of the problem. As stated in issue #503, when you open the project the in Visual Studio it will generate<TargetFrameworkProfile>Unity Subset v3.5</TargetFrameworkProfile> in .csproj and cause the Roslyn code generator does not properly. When u open the project with Visual Studio, it will generate different .csproj file. Open with Visual will generate [Your project name].csproj mean while MonoDevelop will generate Assembly-CSharp.csproj. I'm using Unity 2017.2 and Visual Studio 2017. I attached that 2 .csproj files for you to inspect. 
[Unity Test Project.csproj.txt](https://github.com/sschmid/Entitas-CSharp/files/1541932/Unity.Test.Project.csproj.txt)
[Assembly-CSharp.csproj.txt](https://github.com/sschmid/Entitas-CSharp/files/1541933/Assembly-CSharp.csproj.txt)

**Comment by optimisez** [comment]
@sschmid I forget to mention. Try to switch external script editor at Unity to get the reproduce the issue.

![image](https://user-images.githubusercontent.com/7009368/33807212-121219f6-de0e-11e7-8b73-3a564709fdb3.png)

**Comment by jwvanderbeck** [comment]
Not sure if this is the same issue or not, but after fighting to even get Jenny to see my csproj, I finally did, only to be presented with the following:

    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.VisualDebugging.Unity.dll
    x Could not resolve: Entitas.VisualDebugging.Unity.dll
    x Could not resolve: Entitas.VisualDebugging.Unity.dll
    x Could not resolve: Entitas.VisualDebugging.Unity.dll
    x Could not resolve: Entitas.VisualDebugging.Unity.dll
    x Could not resolve: Entitas.VisualDebugging.Unity.dll
    x Could not resolve: Entitas.VisualDebugging.Unity.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.CodeGeneration.Attributes.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: UnityEngine.CoreModule.dll
    x Could not resolve: UnityEngine.CoreModule.dll
    x Could not resolve: UnityEngine.CoreModule.dll
    x Could not resolve: UnityEngine.CoreModule.dll
    x Could not resolve: UnityEngine.CoreModule.dll
    x Could not resolve: UnityEngine.CoreModule.dll
    x Could not resolve: UnityEngine.CoreModule.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
    x Could not resolve: Entitas.dll
Could not load file or assembly 'Entitas, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
