### ISSUE TITLE
Adding a Context in Unity alters the Entitas.properties, removing the Roslyn plugins

### ISSUE THREAD

**Issue by Pelmog** [sschmid/Entitas-CSharp#496]
Hi,

I have been working with Entitas for a little while, and after watching the recent video, I got the 'Roslyn' version from the Unity store.

All was well until I added a context in Unity, and then code generation stopped working in Visual Studio and Rider. 

Code Generation still worked alright in Unity, but was 'non-Roslyn', requiring lots of commenting out of unworking code to get generation working.

So I ran "Entitas auto-import" again from the command line (after much searching around) and re-added the Roslyn plugins, which had been removed.

Hey presto - all working again.

**Comment by sschmid** [comment]
Oh ok, I will take a look if the Unity preferences is trying to automatically clean up the properties a little bit to motivated ;)

**Comment by Pelmog** [comment]
Thank you for your outstanding work Simon! :)

**Comment by sschmid** [comment]
Fixed in 0.46.0
