### ISSUE TITLE
Entitas API for external callers

### ISSUE THREAD

**Issue by nbreum15** [sschmid/Entitas-CSharp#498]
Hello. Is there a way for external callers to invoke and run the code generator? 

What I am doing so far is to use the DLLs and call Entitas.Utils.CodeGeneratorUtil.CodeGeneratorFromPreferences(Preferences), but want a bit more control over it, and be sure that the API does not change in future versions of Entitas. 

Without altering the source code directly (and change it to my requirements), are there any public API that Entitas supplies?

**Comment by sschmid** [comment]
`CodeGeneratorUtil.CodeGeneratorFromPreferences()` is used most of the time and does the heavy lifting for you. Actually, the code generator doesn't really have any hard dependencies and I will extract  and decouple it completely in one of the following releases. Once that is done, there will also be a public API. In the meantime `Entitas.Utils.CodeGeneratorUtil` is your friend

**Comment by sschmid** [comment]
Btw, here are all the commands which basically can be considered the public api
https://github.com/sschmid/Entitas-CSharp/tree/develop/Addons/Entitas.CodeGeneration.CodeGenerator.CLI/Commands

**Comment by sschmid** [comment]
As part of #508 I can imagine exposing the code gen API where all commands from the cli can be used in code, too
