### ISSUE TITLE
Roslyn code generator bug

### ISSUE THREAD

**Issue by optimisez** [sschmid/Entitas-CSharp#501]
![rosyln](https://user-images.githubusercontent.com/7009368/33390843-1bcf0ec6-d572-11e7-97b9-9caf348af89f.png)

I found that Entitas.exe does not detect the Entitas.properties at root project instead it detect CodeGenerator folder itself to find Entitas.properties. Then, after I copy Entitas.properties and User.properties to CodeGenerator folderm I run entitas auto import again it gives me "Could not find a part of the path 'C:\Users\cs\Documents\Unity\Project YC\CodeGenerator\Assets\Libraries\Entitas'." error.

**Comment by sschmid** [comment]
Hi, your working directory should always be the same as where the Entitas.properties file is located, which is the root of your project by default. So `cd` into the root of your project first and then execute Entitas.exe like this
```
$ CodeGenerator/Entitas.exe
```

For now, also make sure that the path separators (`\`) are forward slashes (`/`). I haven't verified that yet, but other people reported it helped to resolve their issues. I will test this soon, but I can imagine it will cause problems, because `\` is a reserved keyword in the properties syntax for multiline declaration

**Comment by optimisez** [comment]
![image](https://user-images.githubusercontent.com/7009368/33412517-bf6d1218-d5c6-11e7-9d8c-e5774c17b75f.png)

Hi @sschmid. I get "'CodeGenerator' is not recognized as an internal or external command,
operable program or batch file." when I try to run "$ CodeGenerator/Entitas.exe"

**Comment by optimisez** [comment]
![image](https://user-images.githubusercontent.com/7009368/33412638-a4b2f6b2-d5c7-11e7-9093-99415d693d7c.png)

Seems like the folder naming cannot have space and for Windows command prompt it need to put the complete path.  Anyway when I run "Entitas.exe auto-import" I get "Could not find a part of the path 'C:\Applications\Unity\Unity.app\Contents\Managed'.". If not mistaken, it's the path for Mac OS. I think you need to do extra care to detect whether it's Windows or Mac OS and feed the correct path.

**Comment by optimisez** [comment]
Update 3:
I get it working by creating a new Unity project but generating code still have issue. The generated code in Roslyn seems different than old code generator. I just create a TestComponent and generate with Roslyn code generator, I get ```Assets/Sources/TestComponent.cs(11,21): error CS0260: Missing partial modifier on declaration of type `TestComponent'. Another partial declaration of this type exists``` error. I notice it creates a new additional weird TestComponent script.

![image](https://user-images.githubusercontent.com/7009368/33427636-f03e837e-d600-11e7-8c1a-8893398dd0fc.png)

**Comment by optimisez** [comment]
Refer #503. Close issue.
