### ISSUE TITLE
[DontGenerate] Attribute

### ISSUE THREAD

**Issue by cywil4** [sschmid/Entitas-CSharp#504]
Hi,
I realized  [DontGenerate] attribute can be handy when we want to delete component and indeed Generator remove all references. However component with the attribute is still put into Lookup class in given context (or first one if don't set any in attributte). Is this common behaviour?

Cheers

**Comment by sschmid** [comment]
Hi,

yes, that's expected. But you can use

```csharp
DontGenerate(false)
```

to ignore the component completely.

https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration.Attributes/Entitas.CodeGeneration.Attributes/Attributes/DontGenerateAttribute.cs#L10
