### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by heynemann** [sschmid/Entitas-CSharp#505]
Hi,

I searched for an issue that discussed what I want to propose, but couldn't find anywhere. I'm looking to create libraries for Entitas.

Say Locomotion, Input, Networking, etc... I do not wish to create those every time I start a new project. Might even be something that can be published to allow people to kick-start their project with Entitas.

I've tried to start this, but have not been very successful thus far.

One issue I found is that I do not know beforehand what contexts people will use in their game. Other issue is with the generated content. Let me exemplify.

The first component/system I'm trying to provide is the ObjectIdComponent and ObjectIdSystem. They are supposed to add IDs to all the entities that get created in all the contexts that have them.

The main issue here is that I want ALL contexts to have these. And since I don't know beforehand which contexts exist, I can't do that.

Maybe an [AllContexts] attribute?

Another issue is that I have to rely on generated code. I have to do:
```csharp
		private void AddId (IContext context, IEntity entity) {
			var ent = (entity as IObjectId);
			if (ent == null) {
				return;
			}
			if (ent.hasObjectId) {
				return;
			}
			ent.AddObjectId (entity.creationIndex);
		}
```

But IObjectId is an interface that only exists upon generation. This means that my library is not very portable. I think it should be 100% self-contained. There should be some way to plug into entitas lifecycle (there might be already and I just don't know, lol).

I'm an Entitas newbie, but I don't know how to proceed to create libraries for Entitas. And I firmly believe that the Entitas ecosystem would hugely benefit from this feature. I mean, creating libraries would make the framework a lot more popular. 

Instead of providing a tutorial on how to use Physx with Entitas, we can provide a library with the Components, Systems and Features required to do it. Why keep doing Input integration with Entitas again and again?

It gets even more interesting when you think of composite libraries. Imaging a game with a locomotion, physics and input entitas libraries. Now if I include the networking library, it can just watch over all the entities and components in game and network those that contain certain(s) component(s).

Anyways, there are two possibilities here:

a) We want entitas to have libraries as first-class citizens and must change some stuff in the framework (not sure what);
b) The framework is fine as it is and we do not want to support libraries.

Either way I would appreciate help on how to move forward. 

If (a), then please advise what should be changed and I'll do my best to get a PR. I will need some help in getting the environment up and running, since I'm on Windows (my mac is on the office and I'm changing jobs right now).

If (b), can someone help me monkey patch what must be monkey patched in order to get the AllContexts thing working? I just need to have libraries that can subscribe to all contexts when the code is generated.

Anyways, thanks for a GREAT ECS framework.

**Comment by KumoKairo** [comment]
I would suggest to stick to one context for now. It will become apparent which contexts you will need only at a later stage. Trying to separate your contexts beforehand is overthinking and may lead to more OOP-oriented design approach (people usually try making contexts as kind of Classes in OOP with fields as components)

As for the libraries - Simon has already done some work with it https://github.com/sschmid/Entitas-CSharp/issues/307

**Comment by heynemann** [comment]
Hmmm I hope it goes forward.. I should close this then...
