### ISSUE TITLE
Entitas Server Client mode, server crashes

### ISSUE THREAD

**Issue by Draugor** [sschmid/Entitas-CSharp#507]
Hello Simon,

there seems to be a bug/problem when entitas.exe runs as server.
It sometimes crashes with some exception after i execute the gen command from a client.
The first one was from within unity, but after trying a few times it didn't seem to pop up again:
![entitascrash](https://user-images.githubusercontent.com/6240419/33520168-e1fa895a-d7b5-11e7-9e7a-df1cacc5dcc1.png)

the next one i got two different times while trying to generate from a cmd client:
![entitasservercrash2](https://user-images.githubusercontent.com/6240419/33520178-15e4502a-d7b6-11e7-8b5b-776b0c7e951d.png)

both times the code generation seem to work fine (as far as i can tell) but of course after that i have to restart the Entitas Server if i want to generate code again.
I also added the project here 
[Entitas_Clean_Unity.zip](https://github.com/sschmid/Entitas-CSharp/files/1524305/Entitas_Clean_Unity.zip) if you want to take a look at it. 
I work on Windows 10 64bit with the Rosyln generator from the asset store.

otherwise i want to say i really like Entitas, after getting a bit into the ECS mindset behind it, it becomes really easy to work with, thanks for creating it and bringing it this far. :)

Cheers

**Comment by sschmid** [comment]
Hi, I'm glad you like it!
Concerning your issue: it looks like a duplicate to #489.
I will close this one.
