### ISSUE TITLE
Desperate Devs? 🤦‍♂️ Desperate Devs!

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#512]
# Hi

I create software. Some of it is open source. You might have heard of Entitas ;)
I initially created Entitas to help me getting the job done quickly, clean, testable and with great performance. As it turned out, Entitas also helped lots and lots of other people.
Besides Entitas I also created other tools to help me to getting the job done. Most of them are tools that I basically need in every project. By having a reliable set of unit tested and battle tested tools that I can reuse in every project I can focus on the actual tasks.

Entitas used some of those tools by some extend and they were all in the Entitas namespace. But actually, .NoneOf() them have anything to do with Entitas. It's the other way around: Entitas was built on top of those tools.

Starting with Entitas 0.46.0 and as announced in #508 I extracted all those tools into separate standalone projects. That's great because now I see and treat them a standalone projects. As a consequence I have to increase the focus on a public API that makes sense for all kinds of scenarios and therefore the API awesomeness and the reusability is increased. It also enables me and others to create new kinds of projects that use the same fundamental tools without the need to depend on Entitas completely.

The Entitas repository will be even more about ECS than ever without distractions on other tools as they're all considered external dependencies.

# Desperate Devs
Great, I have all these tools now, but I'm desperately looking for a name, a roof, a brand, a namespace under which I can share them with all of you guys.

Welcome to Desperate Devs.

This is the name. Tools from Desperate Devs will be unit tested, pushed through multiple profiling sessions, and I will personally make sure that the API and ease of use is hard to beat :)

But Desperate Devs isn't exclusively about tools only. I started a YouTube Channel where I plan to make more Videos about Entitas, ECS, but also other related topics that are all about software and game development. I'll probably also show off some of the tools that I think are essential for every game.
It's a fresh channel that is just about to get started, but make sure to subscribe if you don't want to miss any future videos.

https://www.youtube.com/channel/UC2q7q7tcrwWHu5GSGyt_JEQ

![desperate-devs](https://user-images.githubusercontent.com/233700/33527251-c762a1b6-d84d-11e7-8666-ed3fb4e69a32.png)

Stay tuned, and as always

Happy coding :)

**Comment by Redwan13** [comment]
So, where is the source code of these assemblies? Will it be published?

**Comment by sschmid** [comment]
For now there are no plans to open source Desperate Devs, but you never know... :)
