### ISSUE TITLE
game architecture questing

### ISSUE THREAD

**Issue by Leonidos** [sschmid/Entitas-CSharp#516]
Hi,
Thanks for great framework.
I have a question on game architecture.

There are several buildings in a game and I can upgrade them, so I created a component:

```
public class UpgradableBuildingComponent : IComponent {	
	[PrimaryEntityIndex]
	public Building id;
	public int state;
	public int maxState;
	public bool isMaxState() {
		return state == maxState;
	}
}
```

It's ok and it works. 

I have an ui dialog. In that dialog I should check if I can upgrade it and if yes and player wants it - increment state for some money. I have a player entity with Account component.
```
public class AccountComponent : IComponent {	
	public int balance;
}
```

So in dialog I should get player and building entity. Check balance, upgrade price, building state. Update dialog UI state (show message If I low on balance, hide upgrade button, etc). And then if everything is ok - increment building state and decrement balance.

Should I pack this logic to System and create some kind of UpgradeBuildingRequestComponent. And then add it and the system will check everything and do the calculations? But I need this logic outside System to check states and update/create UI. 
I can put all UI states to entitas too... but I think It's not a really good idea, because I don't want to always calculate all ui flags, maybe I won't even need them (player won't open a dialog at all)

**Comment by KumoKairo** [comment]
> But I need this logic outside System to check states and update/create UI.

No, you actually don't. UI is mere view which does nothing but reflects the underlying data. Putting logic in UI may look like an easy way, but it will backfire badly on the long run. If UI state can be inferred from data - there's no need to store it anywhere. If UI state only depends on itself, like animation state or something - we don't need to store it anywhere except the component itself. Using UI buttons with Entitas implies that those buttons have some kind of command emitters like
`
component ButtonPress:
    string buttonId
`

Buttons just emit those entities into Contexts and some systems pick those up and process them (it may be one system or it can be a set of systems). UI then reacts to underlying changes that has come from systems in a form of changed state. It looks a bit like Commands in PureMVC framework.

If you need UI logic - create a separate set of systems that merely work with UI and nothing else. But please don't put any "business" logic outside the systems scope.

**Comment by Leonidos** [comment]
Thanks for advice. I will try )
