### ISSUE TITLE
Don't generate component properties

### ISSUE THREAD

**Issue by cywil4** [sschmid/Entitas-CSharp#517]
Hi,
Is there a way to do not generate properties in components? I would to use getter/setter in my components to data serialization/deserialization  for save games. I can still use public methods but properties looks more "convinienve".

BTW, Entitas is really great piece of work!:)

Cheers, Cywil

**Comment by sschmid** [comment]
Hi! I'm glad that you like Entitas :) I love it too!

Atm you can only mark components to be ignored by the generator
```csharp
[DontGenerate]
public sealed class MyComponent : IComponent {}

// also don't generate indices
[DontGenerate(false)]
public sealed class MyComponent : IComponent {}
```

see all available Attributes here:
[Entitas.CodeGeneration.Attributes](https://github.com/sschmid/Entitas-CSharp/tree/develop/Addons/Entitas.CodeGeneration.Attributes/Entitas.CodeGeneration.Attributes)

Unfortunately, there's nothing to ignore fields or properties. But fyi:
Static properties, readonly properties or nonpublic properties will not be generated. Only public fields and public properties get; set; will be generated.

C# extensions might do the trick:
```csharp
public sealed class MyComponent : IComponent {

    public float value;
}

public static class MyComponentExtension {

    public static string Serialize(this MyComponent component) {
        // ...
    }

    public static MyComponent Deserialize(this string str) {
        // ...
        return component;
    }
} 

```

Hope that helps

**Comment by cywil4** [comment]
Thanks! Right now I use non-static methods and it works just like a static one as well. But yes, extensions are more handy here.
Best!
