### ISSUE TITLE
Entitas 0.46.1 Setup Quick Guide

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#519]
Hi,

I'm currently working on the next Video where I explain more about the code generator. I'd like to already share some best practices how to quickly set up the code generator.

Before that, I make 2 assumptions:
1. When you don't use the Entitas.Roslyn plugin you generate in Unity only, because there's no reason to setup the Standalone code generator
2. When you use the Entitas.Roslyn you don't generate in Unity but only the standalone code generator, because Unity doesn't support the new .NET libs yet

Fyi:
By convention, code generator plugins end with `x.Plugins.dll`. Plugins that use Unity API and therefore ONLY work in Unity are called `x.Unity.Plugins.dll` by convention. E.g. The `DebugLogPostProcessor` uses Unity API `Debug.Log` and therefore cannot run without Unity. If using the standalone code generator, you should remove plugins that contain `Unity.Plugins.dll`

Note - How to run the Code Generator (called Jenny since 0.46.0):

on Windows:
```
CodeGenerator/Jenny.exe
```

on Mac
```
mono CodeGenerator/Jenny.exe
```

For simplicity I will only write
```
jenny
```

e.g.

```
jenny gen
```

### no Roslyn (GitHub version):
- Open `Tools/Entitas/Entitas/Preferences...`
- Click the Auto-Import button
- Done

### With Roslyn (Asset Store Version):
- Extract the contents of the CodeGenerator.zip to the root of your project
- run `jenny auto-import` and confirm everything with `y`
- if for any reason there are errors run `jenny fix`. After that, try again
- when plugin collisions are detected, press the number with the roslyn plugin

---
UPDATE:
Starting with 0.46.2, the following steps are obsolete, since the plugins will automatically resolve this issue for you.
---
`jenny auto-import` also finds `x.Unity.Plugins.dll`. As mentioned above, please don't add them, or if already added, remove them from your properties. The easiest way is to remove `DesperateDevs.CodeGeneration.Unity.Plugins` from the key `CodeGenerator.Plugins` and run `jenny fix`. Jenny will then offer you remove the unavailable post processor `DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor`

- Done

If you encounter any problems you can run `jenny doctor -v` and create a new issue. `-v` will result in verbose output which helps me identifying the problem.

**Comment by sschmid** [comment]
I will work on further improving the initial experience, so that in the future there's no need for a quick guide ;) Thanks for going through this with me.

**Comment by bwohaha** [comment]
Hey, Simon.
Was really looking forward to Roslyn, bought the plugin on the asset store, but I''m having issue trying to hook it up. The same problem as I got in 0.45.1.
https://clip2net.com/s/3QmeQ2h
Using Unity and Visual studio enterprise, if that means anything to you.
I'd appreciate any help I can get on this one.

**Comment by bwohaha** [comment]
after entering the path to the solution, the problem changed, but I still can't generate:
http://clip2net.com/s/3Qmfgxg

**Comment by sschmid** [comment]
@bwohaha can you translate the red error message for me please? Btw, the yellow warning can be ignored as long `jenny doctor` says everything is alright

**Comment by bwohaha** [comment]
The error says "Could not load a file or an assembly "UnityEngine, Version=0.0.0.0..." or one of its dependencies. Could not find the specified file.

jenny doctor result:
https://clip2net.com/s/3QmfvQy

**Comment by sschmid** [comment]
can you check you gitter, I send you a message

**Comment by sschmid** [comment]
Solved.

For anyone interested:
The properties file still contained  `DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor`.  As mentioned above, this is  a `x.Unity.Plugins.dll` plugin and won't work in the standalone code generator

**Comment by sschmid** [comment]
I think I found a nice solution for future versions: I added `IDoctor` so plugins can not only contain data providers, code generators and post processors, but also doctors that can diagnose if the plugin is supported in the current environment

![jenny-doctor](https://user-images.githubusercontent.com/233700/34020709-0135b4e6-e136-11e7-803f-0ba222097c44.png)


In this case the DebugLog PostProcessor implements `IDoctor` and checks if you attempt to run it with the standalone code generator and will complain if you do so.

**Comment by jwvanderbeck** [comment]
> run jenny auto-import and confirm everything with y
```
PS D:\Unity Projects\seti\Assets\Entitas> .\CodeGenerator\Jenny.exe auto-import
The given key was not present in the dictionary.
```

**Comment by jwvanderbeck** [comment]
The path it looks for the csproj in appears to be unaffected by the path in the properties file, and instead influenced by the pwd when you run jenny.exe.  However, if I switch to the directory where the .csproj is located and then run jenny from there, it gets all messed up and suddenly tries to find the csproj in the root of the drive!

`Could not find file 'D:\Assembly-CSharp.csproj'.`

**Comment by jwvanderbeck** [comment]
I thought despite the error it was still working but after adding some new components, I can see that it isn't.

**Comment by sschmid** [comment]
> Ok got that fixed by running jenny fix first, so maybe that should just always be run first?

Yes, when the properties file was created by Unity first (by opening the Entitas Preferences Window) you should run the `fix` command to prepare the properties file for jenny.

>  I'm basically just spamming "y"

I will probably add a new command that will just add everything without asking, that should already reduce the confusion. I do this already in Unity where all available plugins are automatically set by default (you see checkmarks in front of the names of the dropdown menus)

For some Unity version the default project name is `Assembly-CSharp.csproj` and for others it's `MyProjectName.csproj`. Make sure to set the correct project name for the key `DesperateDevs.CodeGeneration.Plugins.ProjectPath` in your properties file.

`cd` into the same folder where the .properties file is located because I assume all paths are usually specified to be relative and not absolute. When you make changes to the properties file you should also restart the server just to ensure that all changes are picked up correctly.

**Comment by Brainshack** [comment]
What seems to be missing here, is that you apprently have to add some unity directories to the search paths, or otherwise it will not find all DLLs. Here is how it looks for me:

```
CodeGenerator.SearchPaths = CodeGenerator/Plugins, \
                            CodeGenerator\Plugins\Entitas, \
                            CodeGenerator\Plugins\Entitas.Roslyn, \
                            CodeGenerator\Plugins\Jenny, \
                            C:/Program Files/Unity/Editor/Data/Managed, \
                            C:/Program Files/Unity/Editor/Data/Managed/UnityEngine, \
                            C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity, \
                            C:/Program Files/Unity/Editor/Data/UnityExtensions/Unity/GUISystem
```

However. Running on Windows 10 i still dont get the generator to work:

```C:\Users\brain\Documents\Unity Projects\LetsCreateJam\LetsCreateJam>CodeGenerator\Jenny.exe doctor
??  Available: Entitas.CodeGeneration.Plugins.ComponentDataProvider
??  Available: Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor
    × Could not resolve: SQLitePCLRaw.core.dll
    × Could not resolve: SQLitePCLRaw.core.dll
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.```

I must agree: Setting up the roslyn compiler makes absolutely no sense to someone that just wants to use it. Especially when you are migrating from an older Entitas Version that didnt have it. What I would kie to see would be a simple button inside Unity that does all the necessary setup for me. Considering the Roslyn Compiler is the main selling point for the Asset Store Version it really needs a better UX.

**Comment by Brainshack** [comment]
So just a little update: It works in a clean new project. So there might be some issues when using it inside a project that was using an older version of entitas before.

**Comment by ethankennerly** [comment]
1. Is there an up-to-date instruction for installing and upgrading Entitas Roslyn generator from the Asset Store?  
1. Are there step-by-step instructions for editing the properties file?

I have been advocating the adoption of Entitas, yet yesterday when I purchased, I ran into a lot of hassles, many of those mentioned here and in other issues.  https://github.com/sschmid/Entitas-CSharp/issues/477 https://github.com/sschmid/Entitas-CSharp/issues/521

Through trial and error, and following the breadcrumbs in miscellaneous issues like this one, I got it working. For example, during the Jenny diagnosis and fixing steps, Jenny gets confused.  I guess between the reflection-based generator and the compiler-based generator (Roslyn-based, from the asset store).  I kept only the references to Roslyn, yet Jenny asks me if I want to add back the reflection libraries.  When I add them back, Jenny has a conflict.

**Comment by jwvanderbeck** [comment]
What I found is that for a brand new project, with a fresh Entitas install the setup is a lot simpler.  `jenny auto-import` and spam Y.  Then edit the properties file to point to the correct path where you want generated to be, and in my case I also set Ignore Namespaces to true (which I thought used to be the default?).  Done.

That can be improved by removing the need to spam Y to stuff you don't understand anyway.

Where the real nightmare comes in though is migrating an existing project and I think that is where most of us had the issues, and jenny just makes a real mess of things when you already have an existing properties file.

**Comment by sschmid** [comment]
I think the main problem is the lack of docs because as you said, most of you probably don't know what the jenny messages actually mean. I'm currently working on (hopefully) one of the last version before 1.0 (will submit to the Asset Store tonight) and then I hope I there are less issues and more time for docs

**Comment by kdrzymala** [comment]
I was holding off with Rolsyn reading here that people had issues. I think I waited long enough and tried it today on a new project (latest asset store entitas, Unity 2017.3.0p1) with this result: 

`C:\Repo\Slippy\Implementacja\Slippy>Jenny\jenny doctor
???  Unused key: Preferences.Entitas
???  Unused key: Entitas.VisualDebugging.Unity.Editor.SystemWarningThreshold
???  Unused key: Entitas.VisualDebugging.Unity.Editor.DefaultInstanceCreatorFolderPath
???  Unused key: Entitas.VisualDebugging.Unity.Editor.TypeDrawerFolderPath
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor
?????  Symptoms: Entitas.CodeGeneration.Plugins.ComponentDataProvider loads and reflects Library/ScriptAssemblies/Assembly-CSharp.dll and therefore doesn't support server mode!
??  Treatment: Don't use the code generator in server mode with Entitas.CodeGeneration.Plugins.ComponentDataProvider
?????  Symptoms: Entitas.CodeGeneration.Plugins.EntityIndexDataProvider loads and reflects Library/ScriptAssemblies/Assembly-CSharp.dll and therefore doesn't support server mode!
??  Treatment: Don't use the code generator in server mode with Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
Nie można załadować pliku lub zestawu 'Entitas, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' lub jednej z jego zależności. Nie można odnaleźć określonego pliku.

C:\Repo\Slippy\Implementacja\Slippy>Jenny\jenny fix
?  Add available post processor: 'DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor' ? (y / n)
Added: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor
?  Remove unused key: 'Preferences.Entitas' ? (y / n / (i)gnore)
Removed: Preferences.Entitas
?  Remove unused key: 'Entitas.VisualDebugging.Unity.Editor.SystemWarningThreshold' ? (y / n / (i)gnore)
Removed: Entitas.VisualDebugging.Unity.Editor.SystemWarningThreshold
?  Remove unused key: 'Entitas.VisualDebugging.Unity.Editor.DefaultInstanceCreatorFolderPath' ? (y / n / (i)gnore)
Removed: Entitas.VisualDebugging.Unity.Editor.DefaultInstanceCreatorFolderPath
?  Remove unused key: 'Entitas.VisualDebugging.Unity.Editor.TypeDrawerFolderPath' ? (y / n / (i)gnore)
Removed: Entitas.VisualDebugging.Unity.Editor.TypeDrawerFolderPath
??  Apply fix: Remove DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor from CodeGenerator.PostProcessors
to treat symptoms: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor uses Unity APIs but is used outside of Unity! ? (y / n)

C:\Repo\Slippy\Implementacja\Slippy>Jenny\jenny auto-import
Podana nazwa zestawu lub ścieżka bazowa kodu jest niepoprawna. (Wyjątek od HRESULT: 0x80131047)

C:\Repo\Slippy\Implementacja\Slippy>`

Sorry for errors in Polish, not my fault, it's Windows' I guess ;-)

Not sure what to do next, as the docs are pretty fragmented and related to different versions of Entitas. Someone here said that Zenject is a great example for how documentation should be done. I second that :)

**Comment by sschmid** [comment]
Dang, Asset Store is 0.47.7... this is fixed in [0.47.8](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.47.8)

New release should hit the Asset Store this week

**Comment by kkohno** [comment]
do step by step for roslyn and have an error
![7eef10974227176e0975369ea09f30ae](https://user-images.githubusercontent.com/17728172/44148551-04c69b00-a0c3-11e8-947b-5b04010fed5c.png)

**Comment by sschmid** [comment]
Looks like your folder doesn't contain any properties file.
When opening the Entitas Preferences in Unity, a new properties file will be generated automatically. Alternatively use `jenny new MyProperties.properties` to create one in the terminal

**Comment by kkohno** [comment]
@sschmid thanks, it seems that *.properties files was executed by default by another soft on my computer

**Comment by xiatianjin** [comment]
Could not find file 'Assembly-CSharp.csproj'
Press "Assets -> Open C# Project" to create the project and make sure that "Project Path" is set to the created *.csproj.
