### ISSUE TITLE
Unexpected char

### ISSUE THREAD

**Issue by npoguca** [sschmid/Entitas-CSharp#520]
Hi, console says there are issues after copying all files into my Unity project.

Assets/Entitas/Documentation/dynsection.js(3,13); BCE0044: unexpected char: '&'.
Any idea?
Thanks.

I have an idea / suggestion / found a bug / have question / want to contribute.

![333](https://user-images.githubusercontent.com/11585179/34062718-2fdc01a0-e1ff-11e7-9a93-b37f4766dacb.PNG)

**Comment by c0ffeeartc** [comment]
Hi, remove documentation folder or move outside Assets folder

**Comment by sschmid** [comment]
Correct. Only import the Entitas folder into Unity. Don't import other folders like Documentation or CodeGenerator
