### ISSUE TITLE
Please correct the installation Manual

### ISSUE THREAD

**Issue by npoguca** [sschmid/Entitas-CSharp#522]
Hi,
idk if it's platform-related or version-related but on Windows there's no menu called "Entitas" on the toolbar. It's under "Tools". I know it's not a big deal but I was still confused for a while thinking there was some kind of an error.  And just generally the installation process is very vague and missing a few steps.
Thank you

**Comment by sschmid** [comment]
Who volunteers to update the wiki :)

**Comment by npoguca** [comment]
I'm talking specifically about the "tutorials" section of wiki.

**Comment by sschmid** [comment]
But yes, you're right. Entitas used to be a top level menu item. Unity requires asset store menus to be under `Tools`, so I changed it to `Tools/Entitas`

**Comment by sschmid** [comment]
Btw, feel free to update sections in the wiki that are not correct or outdated.

**Comment by npoguca** [comment]
Updated the tutorials section.

**Comment by IsaiahKelly** [comment]
I replaced the installation section of that tutorial entirely with link to the new dedicated step-by-step guide I made over a week ago. This new page rendered that section unnecessary and repetitive. I also moved the troubleshooting section to FAQ page and plan to update the install guide to cover that issue as well.

**Comment by sschmid** [comment]
Very nice :)

**Comment by IsaiahKelly** [comment]
Okay, I just spent way too much time updating the step-by-step guide to address both project path and script assemblies issues, but it should be pretty comprehensive now. Still have no idea why I'm spending so much time updating the docs for a framework I don't even use! 😆 😕 I think I might be broken or something.

**Comment by Skybladev2** [comment]
Hi folks,

Thanks for awesome extension, but I had some problems with installing it.

Can you please add [step-by-step install guide](https://github.com/sschmid/Entitas-CSharp/wiki/Using-Entitas-with-Unity) link to the main page (Readme.md)?

**Comment by IsaiahKelly** [comment]
@Skybladev2 Did my step-by-step guide solve all your problems? If not, please let me know what I can do to improve it. Guide is on the main wiki page, but unfortunately only Simon can update the `Readme.md` (@sschmid 😉😉 *nudge, nudge*), but I'll see what I can do about updating the other tutorials. That whole section really needs to be completely redone, but my time is limited. Also please remember that anyone can help edit the wiki.

**Comment by Skybladev2** [comment]
@IsaiahKelly  Yes. The problem was that I was afraid to press `Generate` button the first time until I read your tutorial.
