### ISSUE TITLE
custom index name in Contexts with a namespace prefix, ignore namespaces=true doesn't work

### ISSUE THREAD

**Issue by wallpap3r** [sschmid/Entitas-CSharp#524]
Hi,

I've created custom entity index within a namespace
```csharp
using Entitas;

namespace xxx 
{
    [game]
    public class AgentId : IComponent{
        public long val;
    }

    [CustomEntityIndex(typeof(GameEntity))]
    public class AgentEntityIndex : PrimaryEntityIndex(GameEntity, long){
        public AgentEntityIndex(GameContext ctx):base(
              "AgentEntityIndex",
             ctx.GetGroup(GameMatcher.AgentId),
             (e,c) => { xxxxx;})
 }

    []
    public GameEntity GetAgentsById(long id)
    {
        return GetEntity(id);
    }
}
```

but the codeGenerator create a contexts file having the the namespace as prefix:
```csharp
public partial class Contexts {

    public const string xxxAgentEntityIndex = "xxxAgentEntityIndex";
...
```

I have to move the AgentEntityIndex out of the namespace to make the index key equal with each other. 
I was set ```Entitas.CodeGeneration.Plugins.IgnoreNamespaces = true```
Did I miss something?

**Comment by sschmid** [comment]
I will take a look. Sounds like the EntityIndexGenerator is not yet using the `IgnoreNamespaces` config.

**Comment by sschmid** [comment]
Hi, so just check. All good. So there's no generated api which contains the namespace of your custom index. The code you're referring to is only used internally, and if you're creating classes in a namespace, it needs to respect that namespace
