### ISSUE TITLE
Collected entites sorting

### ISSUE THREAD

**Issue by cywil4** [sschmid/Entitas-CSharp#528]
Hi,
I have question about position of entity grabbed by Collector. Are they sorted always same way? Right now it`s relevant to Add/ReplaceComponenet queue. Is there probability it can change in the future? It is very important for creating hierarchy in Unity (parents have to be created before children).

Cheers, Cywil

**Comment by sschmid** [comment]
Hi, entities are not sorted for performance and design reasons, but you can sort them manually if needed when you retrieve them from the collector

**Comment by cywil4** [comment]
My question was inaccurate, sorry my fault. I would to know if an order of entities in collection depends always on the order of adding/updating of components. I tested and it looks like in code below but I have to make sure.

```csharp
context.CreateEntity().AddPosition(0);
context.CreateEntity().AddPosition(1);
context.CreateEntity().AddPosition(2);

//and then in reactive system

void Execute(IEntity[] entites)
foreach (e in entites)
{
Debug.Log (e.position.value);
}
//output:
//0
//1
//2
```

**Comment by sschmid** [comment]
The order is not guaranteed and you cannot depend on it. See [Collector](https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Collector/Collector.cs#L19)

Collected entities are stored in a hashset, so order should be considered random. Deterministic, but random :)
But again, to ensure a certain order you can sort the entities first in the reactive system.

**Comment by cywil4** [comment]
Ok, I can see it now. Thank's a lot:)
Best andFröhliche Weihnachten:D

**Comment by sschmid** [comment]
Danke, fröhliche Weihnachten zurück :)
