### ISSUE TITLE
Add Namespace to Code Generator

### ISSUE THREAD

**Issue by aaronmell** [sschmid/Entitas-CSharp#53]
When using the Code Generator outside of unity, it would help to be able to specify the namespace of each generated file. Otherwise each time I regenerate the files, i will have to fix my code manually.

**Comment by aaronmell** [comment]
The namespace issue might be problematic, since it uses partials on the entity class for the extension methods.  I think that could be fixed though, instead of using a partial, why not turn the partials into true extension methods that operate on the Entity and Matcher objects? I might be missing something though, since I am unfamiliar with Unity.

**Comment by sschmid** [comment]
Generated components are in the Entitas namespace. Why do you have to fix the namespace? They are optional afaik and don't nessecarily have to match the folder structure. That should be fine.

Extension methods are very limited and can only use the public api of an object. With partial classes we can achieve sth like e.position.x, which isn't possible with extension methods.

**Comment by aaronmell** [comment]
Its probably just my experience as as business developer peeking through and being pedantic. It bugs me that resharper complains about the namespaces not matching the folder structure in the project.

**Comment by chrischu** [comment]
If that bugs you, you can just change that in ReSharper: Select the a folder in the solution explorer, open/show its properties (F4) and change the setting for "NamespaceProvider" to false.

This is necessary anyhow if you don't want your namespaces to include "Assets" etc. :).

**Comment by sschmid** [comment]
For now most of the generated extensions have to be in the Entitas namespace, so I think I cannot change that. Sorry.
