### ISSUE TITLE
[Discussion] I find my workflow has suffered since the addition of Rosyln

### ISSUE THREAD

**Issue by jwvanderbeck** [sschmid/Entitas-CSharp#530]
I just wanted to start a discussion here about the new(ish) Rosyln code generator

I was one of the first to jump on this new generator when it was made available, but over time I found myself drifting BACK to the old one despite the problems it has.  

Why?  Workflow.

When I work with external tools in Unity, I want them to just work with as little effort as possible on my part.  Early on the setup was very convoluted, but that was understandable given it was a new feature in development.  Over time that smoothed out a lot, and I see in the latest version it looks like there is *almost* no setup at all which is great.  However for me the elephant in the room is still the need to externally run the Entitas server.  I know its silly (but this is **my** feedback :p) but I find that to just be an annoying workflow.  Having to open a command line and open that process up whenever I want to work. Why can't Entitas itself spin up this process from Unity?

The workflow I want ideally is the workflow I had in the past.  I modify some code in my IDE, alt-tab into Unity and press Generate.  If this now requires a separate process, then have Entitas in Unity spin up the process, do the generate, and then close it down.  And/Or have an option to spin the server process up when I start Unity and close it when I close Unity.

**Comment by roygear** [comment]
My workflow is this:
0. Open Jenny-server, and pretend it not there
1. Change Entitas code
2. Use Hotkey of IDE to execute "client gen", wait 1 to 2 seconds
3. Go back Unity and wait a few seconds
4. Do something must do in Unity Editor

and repeat step 1~4

**Comment by jwvanderbeck** [comment]
What you have described is twice the number of steps each iteration and 33% more "applications" open, or arguably 50% more if you consider having to first run Terminal or Powershell/cmd.  Each time you want to work.  As opposed to running Unity, and letting Unity open your IDE at the first edit.

Also, the setup process which I thought had gotten better really hasn't.  I just thought it had but then I found out that it wasn't actually working, so now I've spent the last day trying desperately to even get the external generator to work, as opposed to again the one in Unity that literally just works out of the box.

I bought the asset store version specifically for this better generator and it has given me nothing but trouble to the point where I would be better off with the free version, which isn't great for the long term health of Entitas.

**Comment by roygear** [comment]
The setup process of 0.46.3 is easier than old version. 
I guess you are a VS user. Yes, it do have more trouble than Rider. 
For example, you have to use the extra IPreProcessor which a new function of 0.46.3. Otherwise, Roslyn not work.

**Comment by Brainshack** [comment]
I dont get the point of this issue to be honest. Afaik the old way of working has never been removed? If you really think that starting a single script is to much to ask of you, you can always return back to the old ways. And also return to slow compilations and sometimes hard to fix catch 22 issues that appear when you need to change components that would break unities code compilation. For me, having to run a single command before starting work is really worth the amounts of time and headaches it safes me.

**Comment by Draugor** [comment]
i wrote a script for my unity project that starts the jenny server when i open my unity project (or restarts the server after it crashes) 
[RunEntitasServerOnEditorStartup.txt](https://github.com/sschmid/Entitas-CSharp/files/1591942/RunEntitasServerOnEditorStartup.txt)

if your project isn't using the new .net 4.6 environment you probably need to comment-out or change the "Debug.Log" lines.

so after using that i just open my project in unity, Jenny starts automatically, i open the c# project from unity and start "happy coding" :D

**Comment by jwvanderbeck** [comment]
See that's what Entitas should be doing!
