### ISSUE TITLE
Reload assembly called from managed code directly

### ISSUE THREAD

**Issue by jwvanderbeck** [sschmid/Entitas-CSharp#531]
Seeing this error with the latest version of Entitas when I generate inside Unity (Tools -> Jenny -< Generate)

```
Reload Assembly called from managed code directly. This will cause a crash. You should never refresh assets in synchronous mode or enter playmode synchronously from script code.
UnityEditor.EditorUtility:ClearProgressBar()
DesperateDevs.CodeGeneration.CodeGenerator.Unity.Editor.UnityCodeGenerator:Generate()
```
It appears the code is still being generated despite the error, but that is a rather scary error :)

**Comment by sschmid** [comment]
Does this happen for you all the time or was this a one time thing?

**Comment by jwvanderbeck** [comment]
I don't see it EVERY generation, but I am seeing it more than just the once.  Not sure if there is a pattern, but let me see if I can find one.

**Comment by sschmid** [comment]
Is this still a thing? Unfortunately, I wasn't able to reproduce. Do you know how I can reproduce? Otherwise feel free to close

**Comment by FNGgames** [comment]
I get this when i go through the reflection generator procedure for renaming and refactoring components in existing projects. Only when re-generating the contexts and feature classes, and then only when adding components back, but it does happen consistently every time. I've just ignored so far and it has never caused a crash.
