### ISSUE TITLE
WrapperComponent not supported by Jenny?

### ISSUE THREAD

**Issue by jwvanderbeck** [sschmid/Entitas-CSharp#532]
In previous projects, with the old code generator, I was using this amazing add-on https://github.com/sschmid/Entitas-CSharp/pull/88/files

Support was added as part of Entitas core in this commit:
https://github.com/sschmid/Entitas-CSharp/commit/f17bd30e7af6956933a48ffd96eaf8aa5ef338ec

However this no longer appears to work, as components built using WrapperComponent are not getting proper code generated for them.  The generated code is the same as that of Flag Components rather that of Data components as they should.

This worked for me before, so I am making the assumption here that it somehow got lost in the split up of the code base maybe and Jenny just needs to be fixed to ignore the Abstract class like before?

**Comment by sschmid** [comment]
I see, roslyn is lacking support as it is not recognizing the public field of the inherited class.

**Comment by sschmid** [comment]
I just added support for subclassing components in roslyn which will enable the WrapperComponent. I see you've read my concerns about the WrapperComponent and that you are aware and fine with that :)

**Comment by jwvanderbeck** [comment]
Yeah I abhor the use of var when at all possible and much prefer explicit types, so I am ok with the implicit conversion which simplifies the overall API.

Certainly good to have the option for those who want it and I loved using it in the old generator :)

**Comment by jwvanderbeck** [comment]
Any idea when this update will hit the Asset Store or is there some other way to obtain the fix?

**Comment by sschmid** [comment]
Sorry, got sick. Will release this week

**Comment by sschmid** [comment]
Hi, fixed in [Entitas 0.47.0](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.47.0)
