### ISSUE TITLE
[Suggestion] have "Assets" folder inside unity release archives

### ISSUE THREAD

**Issue by c0ffeeartc** [sschmid/Entitas-CSharp#535]
Hello,
It's common thing for newcomers to deal with errors after importing Entitas into Unity.
I think adding "Assets" folder into Unity release archive and keeping everything unneeded or error-prone outside this folder would help a lot when starting.
What do you think?

**Comment by sschmid** [comment]
Sounds like a good idea

**Comment by sschmid** [comment]
Hi, fixed in [Entitas 0.47.0](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.47.0)
