### ISSUE TITLE
Performance problem with huge amount of Entities(10000!)

### ISSUE THREAD

**Issue by raveneer** [sschmid/Entitas-CSharp#539]
Hello, I'm making tilemap simulation game.

my game have 250*250 tiles, some tile could have Plants (flowers, trees, etc)

and my plants grow with time. (or tick)

someplace like the jungle, plants amount could be 10000 over.

I simulated this scenario with Entitas and got performance issue.

when 10000 plants-entities grow, 2.5MGC happen and process time was 190ms.

this is unacceptable slow... 
(currently, my project using the c# class, and 10000 plants update is under 0.2ms)

sure I know Unity's GameObject are slower than entities. if I made 10000 GO, the editor has clashed...

I think the component system could make emergence in simulation games.

have any idea?

https://gist.github.com/raveneer/f738be84346c5550aefc37ff7a8c2df7

https://gist.github.com/raveneer/918e3a7109d7baae1fe66599a4b21c2a

![supergc](https://user-images.githubusercontent.com/19799411/34566268-43e23212-f1a1-11e7-826d-dc5f295cd650.png)

**Comment by sschmid** [comment]
Hi, by default VisualDebugging is activated which adds some overhead to integrate Entitas nicely into Unity. This code will be stripped out when you build a release version. To turn VisualDebugging off in the Unity Editor open EntitasPreferences and disable VisualDebugging. This will already make a huge difference in your case

**Comment by raveneer** [comment]
Thank you. 
After off visualDebugging: 10000 entity with damage dealt per tick : 180ms -> 2ms!

**Comment by bddckr** [comment]
I'd bet most of the time is spent because of that huge GC Alloc. Maybe there's a way to reduce the allocations?

**Comment by ShadeSlider** [comment]
Don't forget, that VisualDebugging creates/removes GameObject in the Hierarchy for EACH entity. So yeah, if you create 10k entities, you create 10k GO as a result.
