### ISSUE TITLE
Bug? Unity / visual debugging / Set Toggle  not work 

### ISSUE THREAD

**Issue by raveneer** [sschmid/Entitas-CSharp#540]
can't set to false.
after auto compile of unity, it turns on!

https://www.youtube.com/watch?v=SjCDNnx3HfQ

**Comment by sschmid** [comment]
That's weird. As a workaround for now try
Edit > Project Settings > Player > Other Settings

and add to Scripting Define Symbols:
`ENTITAS_DISABLE_VISUAL_DEBUGGING `

**Comment by sschmid** [comment]
Explanation:

The Visual Debugging toggle adds or removes this compiler flag to all build targets. If for any reason it couldn't apply to all of them, the checkmark turns on again

**Comment by raveneer** [comment]
it's working but can't understand.
I can't explain this symptom. plz, look at the video...

https://www.youtube.com/watch?v=LYol1VNixtI

**Comment by optimisez** [comment]
I also have the same issue but adding ```ENTITAS_DISABLE_VISUAL_DEBUGGING``` manually at Scripting Define Symbols solve the problem. I wonder whether the Scripting Define Symbol that I create myself affects it. 
![image](https://user-images.githubusercontent.com/7009368/34704174-595bc40c-f532-11e7-9def-9757c367f526.png)

**Comment by raincole** [comment]
This bug still happens to me in Entitas 1.4.1. Could you reopen this? The workaround works tho.

**Comment by sschmid** [comment]
Can't reproduce with 1.4.1. Are there any exceptions in the console?

**Comment by raincole** [comment]
No, but I created a fresh new project and imported Entitas, and then the bug didn't happen there. Guess the problem is on my own side.
