### ISSUE TITLE
Check Replace Component Even ?

### ISSUE THREAD

**Issue by qkhuyit** [sschmid/Entitas-CSharp#541]
How to call method when replace component ?
Love all <3

**Comment by KumoKairo** [comment]
This is what Reactive Systems are for

**Comment by qkhuyit** [comment]
how to check Replace component even ?
I used BattleMatcher.PlayAnimation.Added(), but not successful

**Comment by KumoKairo** [comment]
You should go take a look at project examples like https://github.com/sschmid/Match-One/ and other inside of the examples page - https://github.com/sschmid/Entitas-CSharp/wiki/Example-projects

**Comment by sschmid** [comment]
A good example is probably
[Match One - AnimatePositionSystem](https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Logic/View/Systems/AnimatePositionSystem.cs)

When a position is replaced on entities, this system will do its things when systems.Execute() is called
