### ISSUE TITLE
Entity Templete Save Loader v0.1

### ISSUE THREAD

**Issue by raveneer** [sschmid/Entitas-CSharp#543]
I made simple Save/load entity template utility.

https://github.com/raveneer/EntitasSaveLoader

https://www.youtube.com/watch?v=w8IwLh8ct50&feature=youtu.be

thank you!

**Comment by sschmid** [comment]
Nice! Thanks for sharing. Looks like JSON Blueprints, great :)

**Comment by sschmid** [comment]
Hi can you or someone else add this in the wiki to the other community contributions? Thanks

**Comment by IsaiahKelly** [comment]
Added it to the wiki extensions pages. You're welcome 😃

**Comment by sschmid** [comment]
You're the best :) Thanks!
