### ISSUE TITLE
Scene management in Entitas

### ISSUE THREAD

**Issue by AVAVT** [sschmid/Entitas-CSharp#544]
There's so little info about this. Everyone on gitter keeps telling me to *not* use multiple scenes at all.

But real games are not only "gameplay". There are nested menus, cutscenes, tutorials, big BUY THIS DLC button that we hope everyone would click, etc etc.

All of my games have visual-novel style cutscene with narration and dialogues (see Disgaea). They're completely different from the rest of the game. Actually, they're like a second game working parallel with the main game, and I'm struggling to find a way to do this with Entitas. I have tried both fitting everything in 1 scene and enforcing hard reset for multiple scenes; both of them feel unnatural and forcing.

Maybe it's about structure, maybe I'm just lazy and not disciplined enough, but it feels like Entitas actively work *against* anything that's not a mobile endless runner.

None of the current example projects is giving me any hint on this at all. Any help? 😭

**Comment by c0ffeeartc** [comment]
A guess - add scene component to an entity, when unloading scene manage entities(destroy, etc)

**Comment by KumoKairo** [comment]
Common patter is to have several scenes to manage game state
When entering a scene, `Initialize` all the systems and `TearDown` on leaving a scene (`Start` and `OnDestroy`) methods
This is where `TearDown` came from - it's used to cleanup current state-specific data (transient entities)

**Comment by AVAVT** [comment]
Thank you @KumoKairo, after taking your suggestions I got the cutscenes going well now 😸
