### ISSUE TITLE
How to group through multiple contexts?

### ISSUE THREAD

**Issue by sesky4** [sschmid/Entitas-CSharp#545]
Hi,

I have question want to ask.

How to create a group that tracks entities in multiple contexts having a specific component ?

Here's my problem:
I'm implmenting a collisionNotifySystem which triggers all entities(may live in different contexts) that has a collisionListener component.

It seems that this system need two ReactiveSystems: 

One listens to Event context and check if there is a collision event raised.

Another is a multiReactiveSystem listens to all contexts that collisionListenerComponent may exist.Collect them into an array and trigger them when a collision event raised.

If there is multiGroup that can collect all entity that has a collisionListenerComponent across all contexts, things would be much easier.

Or is there a more ECS way to do that?

Thanks!

**Comment by FNGgames** [comment]
You can create multiple groups, one for each entity, then when you go to process them, cast them to a common interface as you do in the multiReactiveSystem.

```csharp
readonly IGroup<GameEntity> _gameGroup;
readonly IGroup<InputEntity> _inputGroup;
// etc ...

public void Execute() {
     foreach (var e in _gameGroup.GetEntities()) Process(e);
}

void Process(ICollidableEntity e) {
    // do stuff
}
```

**Comment by sesky4** [comment]
@FNGgames Thanks. It seems a good idea to have a MultiGroup.

**Comment by wallpap3r** [comment]
It seems that dividing entities to multiple context is not necessary in ECS way. If you find you need multiple context to describe some kind of entity, you should put them together.
"To divide" means "should not combine", in my opinion.
In my project, I only have those two default context. Some times entites are passed between systems of different contexts.

**Comment by FNGgames** [comment]
@wallpap3r your point of view would also make MultiReactiveSystems a bit of an antipattern. Given that they exist, it seems logical that multi-groups should also exist.

**Comment by sesky4** [comment]
@wallpap3r Sounds real neat to work with.But it may lead to worse performance and more memory consumption.
Here's a related article.
https://medium.com/@icex33/why-components-need-different-context-types-in-entitas-csharp-e12e0aee9a67

**Comment by wallpap3r** [comment]
@sesky4 yes, a huge entity will cost unnecessary memory. I prefer to divide when it is clear as Input vs Game, or lobby vs battle, it's due to we are not familiar with ECS way.
Still, some of the components are doing the same thing, such as LoadingProgressComponent vs TaskProgressComponent. May be it's better to leave them duplicated.

**Comment by wallpap3r** [comment]
@FNGgames I'm not quite follow your point. But I do think ECS is anti-inheritance, but use combination to implement Polymorphism.
Return to the topic, I prefer to put all the entities which can be notified by collision events within an context...
But I have the same confuse that how can I pass entites from context A to systems of context B. It seems we can only use CustomEntityIndex.

**Comment by FNGgames** [comment]
@wallpap3r there's no inheritance in my example, and in fact no real polymorphism (`gameEntity.AddCollisionListener` does essentially the same thing as `inputEntity.AddCollisionListener`). 

Basically i think we need to be able to createa group as an IGroup<ISomeMultiContextEntity> using a method that takes an array of Matchers from different contexts, whose entities implement the ISomeMultiContextEntity interface.

**Comment by wallpap3r** [comment]
@FNGgames I see... I think it's the strong type dividing the contexts so that you cannot group the entities with diffrent ```Type```.
May be it's better to divide the entity index with other solution but not with template specialization.

**Comment by FNGgames** [comment]
We have the interface `IMatcher<TEntity>` and  `IContext<TEntity>`. Seems like most of the abstraction is done already. 

If you know that a `GameEntity` implements `ISomethingEntity`, you therefore also know that `GameContext` has a method called `CreateEntity()` that returns something that can be cast to `ISomethingEntity`. All of that is guaranteed, but currently it's not enforced in code.
