### ISSUE TITLE
"Jenny.exe client gen" command never completes

### ISSUE THREAD

**Issue by sdarkwell** [sschmid/Entitas-CSharp#546]
**Hello,**

I am having an issue using the Jenny.exe server to generate code.

After running the command "Jenny.exe client gen -v", I see the following output:
> Client is connecting to 127.0.0.1:3333...
> Client connected to 127.0.0.1:3333
> Sending 6 bytes via 127.0.0.1:3333

Beyond this, it never completes.

Jenny server IS open in the background. It states:
> Server is listening on port 3333...

When using the Unity command "Tools>Jenny>Generate with external Code Generator", it successfully proceeds through all of the steps (Connecting..., Connected, Generating..., Generated, Disconnected).

**Thank you and be well!**
- S.

**Comment by sschmid** [comment]
Hi, there are some fixes in [Entitas 0.47.0](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.47.0). Hopefully it helps with the issue you had. Feel free to reopen, if it doesn't (you might have to wait a few days for the Asset Store version update)

**Comment by sschmid** [comment]
Does it finish when you wait 10+ secs or does it hang forever?

**Comment by sdarkwell** [comment]
@sschmid: It hangs for at least 10 minutes.

**Comment by sschmid** [comment]
Ok, I just added a potential fix for that. Will be in the next release

**Comment by sdarkwell** [comment]
@sschmid: Thank you, sir!
