### ISSUE TITLE
Run Jenny server with optional configs, same as gen

### ISSUE THREAD

**Issue by ethankennerly** [sschmid/Entitas-CSharp#550]
Thanks for supporting:
```Jenny.exe gen Roslyn.properties```

Would you have time to add this?
```Jenny.exe server Roslyn.properties```

Without this the ALT+CMD+G keyboard shortcuts don't work.  

Or the editor freezes when pressing SHIFT+CMD+G.

Alternatively, would you have time to remove the reflection-based shortcut?  Otherwise pressing SHIFT+CMD+G freezes the editor, as you mentioned in https://github.com/sschmid/Entitas-CSharp/issues/476

Or move the tools menu and shortcut configuration out of a DLL and into a C# file so that the end-user can remove the broken commands?

**Comment by sschmid** [comment]
External generate will now send the selected properties path with `client gen`

<img width="449" alt="entitas-multiple-properties" src="https://user-images.githubusercontent.com/233700/34898724-d0caa3c2-f7f4-11e7-891b-bb16b807bc74.png">

You can select the desired properties with the new Switch Button.

Will be in the next release
