### ISSUE TITLE
Systems profiling does not work properly at editor mode

### ISSUE THREAD

**Issue by optimisez** [sschmid/Entitas-CSharp#554]
I dunno why it does not work properly when I run the profiler at editor but it's working when I build a player build with development build enabled to profile the systems. 
![image](https://user-images.githubusercontent.com/7009368/34907044-7cdbc678-f8b3-11e7-8c32-814278c3e4f0.png)

**Comment by sschmid** [comment]
Use deep profiling in the editor.
It's called "DeviceDeepProfiling", so only affects development builds
see [FeatureClassGenerator](https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.VisualDebugging.CodeGeneration.Plugins/Entitas.VisualDebugging.CodeGeneration.Plugins/FeatureClassGenerator.cs#L12)

**Comment by optimisez** [comment]
Can you make the profiler able to profile systems without the need of toggling DeviceDeepProfiling too?There are a lot of unnecessary information pops up at there.

**Comment by KumoKairo** [comment]
This feature was written by me a month back. 
And it's only needed for the devices as the built-in Unity's deep profiler provides much more detailed info than this custom on-device profiler. 
It also conflicts with the built-in Visual Debugging tool that also captures the systems timings, so you currently can't run both things at once.

**Comment by optimisez** [comment]
@KumoKairo How can I enable DeviceDeepProfiling on device? I only know enabling Deep Profiling in the editor.
![image](https://user-images.githubusercontent.com/7009368/34913051-5bd5e510-f92d-11e7-8fc9-5c1c39269cef.png)

**Comment by KumoKairo** [comment]
Editor - Deep Profile
Device - DeviceDeepProfiling (Entitas-only feature)

You can't enable Deep Profile on a device, this is why we made this feature

**Comment by optimisez** [comment]
@KumoKairo, do u mean this is DeviceDeepProfiling ?

![image](https://user-images.githubusercontent.com/7009368/34914270-38d92e6a-f94a-11e7-86ca-78199db562c9.png)

**Comment by KumoKairo** [comment]
Yes, it means that it's turned on. Build your game with a **"Development Build"** tick and it connect the Unity profiler to see profiling data
