### ISSUE TITLE
Auto-Import doesn't work when folder's name contains space(s)

### ISSUE THREAD

**Issue by sdarkwell** [sschmid/Entitas-CSharp#555]
**Hello,**

After importing Entitas v0.47.6 into a new Unity project, navigating to Tools > Entitas > Preferences..., clicking the "Auto Import" button, then finally clicking the "Continue and Overwrite" button in the "Jenny - Auto Import" dialog box, the dialog box closes, but nothing else appears to happen. Unity's console displays no errors.

**Unity Version:** 2018.1.0b2
**Operating System:** Windows 10 Pro

The issue seems to occur when there are spaces in the project folder's name.

**Comment by sdarkwell** [comment]
It appears this issue only occurs when the project folder's name has a number that is separated from surrounding text with a space.

**Comment by sschmid** [comment]
I see, the paths are escaped uri strings...
`My%20Unity%20Project` 

Will fix this. Thanks for reporting!

**Comment by sdarkwell** [comment]
My pleasure. Glad that I could help!

**Comment by sschmid** [comment]
Fixed in [Entitas 0.47.7](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.47.7)
