### ISSUE TITLE
Is this kind of ReactiveSystem.Filter surplus? [question]

### ISSUE THREAD

**Issue by yuchting** [sschmid/Entitas-CSharp#556]
Hi,

I am read the Match-One sample project and Entitas least released source code, but I found some surplus code, I am not sure:

```csharp
    protected override ICollector<GameEntity> GetTrigger(IContext<GameEntity> context) {
        return context.CreateCollector(GameMatcher.Position);
    }

    protected override bool Filter(GameEntity entity) {
        return entity.hasView && entity.hasPosition;
    }
```

```csharp
    protected override ICollector<GameEntity> GetTrigger(IContext<GameEntity> context) {
        return context.CreateCollector(GameMatcher.GameBoard);
    }

    protected override bool Filter(GameEntity entity) {
        return entity.hasGameBoard;
    }
```

_ReactiveSystem<>.GetTrigger_ will return a collector to catch all GameEntity which matched, but filter return the same condition, so, could I delete the _entity.hasPosition;_ and change the "_return entity.hasGameBoard;_" to "_return true;_"?

Cheers

**Comment by FNGgames** [comment]
@yuchting The filter conditions are there to prevent stale entities from being processed. Having a reactive system react to `GameMatcher.Position` does not guarantee that `entity.hasPosition == true` in the filter method. 

Here is a contrived example with two systems:

```csharp
// run this code in the first system to execute
var e = _context.CreateEntity();
e.AddGameBoard(xSize, ySize); // fires GameMatcher.GameBoard.Added() event
e.RemoveGameBoard(); // removes the component but group has been triggered, so the next system will process this entity regardless

// second system reacts to GameMatcher.GameBoard.Added()
// put this in exec method
Debug.Log(e.gameBoard.xSize + " " + e.gameBoard.ySize); 
// ENTITY DOES NOT HAVE COMPONENT EXECEPTION
```

**Comment by yuchting** [comment]
@FNGgames 
 Thanks! I know what you meaning, if some system add component and delete it again in one frame, the collector may catch the adding behaviour, but pass it to Execute method, but it hasn't the added component.

So the GetTigger is for action, but the Filter is for current game entity status.

I got, thanks so much! :smile:

**Comment by FNGgames** [comment]
That's correct, you're welcome.
