### ISSUE TITLE
Cannot support Unity assembly definition files properly

### ISSUE THREAD

**Issue by optimisez** [sschmid/Entitas-CSharp#557]
Starting from Unity 2017.3.0, assembly definition files has been introduced to separate project scripts into multiple assemblies. I already tried everything I can but still not able to make it work properly. Seems like Entitas needs to modify something to make it works.

**Comment by T2RKUS** [comment]
Doesn't it generate a new .csproj with that name too? If you have an asmdef in Assets/Generated.Source/ and have it generate code in Assets/Generated.Source/Generated with the components one level up does it work then? With the generated .csproj in your properties. Or are you trying to separate components into their own asmdef?

**Comment by optimisez** [comment]
Ya. I tried to make Components, Systems and Generated as individual assembly file but not working properly. So, now I only Libraries.asmdef and Sources.asmdef  for now. 

Btw I found the issue that Jenny code generator does not gen code properly after setting up assembly definition file. All the generated code went missing. It seems like Jenny not able to scan the component file and gen the code properly.

**Comment by sschmid** [comment]
You said in the chat you managed to get it working?

**Comment by optimisez** [comment]
Ya. ```Sources.asmdef``` is already working. Now let see whether I can further split out the generated code.

**Comment by optimisez** [comment]
Since generated code has dependency to Components, Systems and vice versa that Unity will complain cyclic reference error. I think it's not possible to split out generated code as a separate assembly.

**Comment by sschmid** [comment]
Don't overthink it. Don't separate things that belong together :)

**Comment by huhund** [comment]
Hello Wizards, I stumbled on this same issue using asmdef file in source folder. Code generation does not happen if I add a asmdef file at the root of my source files. I'm using Unity 2019.2.9f1 and Entitas 1.13.0 (paid version).

Do I understand correctly that the work around is to delete the asmdef file while generating? If possible, this is something that I would prefer not to do. Or is folks getting this to work without deleting it?

Best, Hu

**Comment by huhund** [comment]
Thanks, I got it to work! 

I added my asmdef to "Assets/Source/Source.asmdef" and change "Porject Path" in Jenny settings from "Assembly-CSharp.csproj" to "Sources.csproj".

Best, Hu
