### ISSUE TITLE
Entitas-unity 0.4.7.7 doesn't work

### ISSUE THREAD

**Issue by xmzyl** [sschmid/Entitas-CSharp#560]
Hi,
     I upgrade Entitas 0.4.7.7,  then perform jenny gen , show a error message:
Failed to load file or assembly "Entitas, Version = 0.0.0.0, Culture = neutral, PublicKeyTok
en = null "or one of its dependencies. The system can not find the file specified.

Cheers

**Comment by chiuan** [comment]
i got this with new properties file....
![image](https://user-images.githubusercontent.com/1845859/35024899-0803dc60-fb7d-11e7-853a-790169e73eae.png)

**Comment by sschmid** [comment]
@xmzyl Pleas open the properties and check if all your paths are still valid. E.g. The folder CodeGenerator has been renamed to Jenny. Make sure all the paths specified in the searchPaths are still valid. Also take a look at #561 , I already made a fix for windows

**Comment by sschmid** [comment]
When in doubt, you can delete the properties and open the Entitas Preferences and click auto-import, this will create a new one which should work

**Comment by xmzyl** [comment]
thank @sschmid ,  this Issue is the same #561 。
