### ISSUE TITLE
Project Path and File Name Issues

### ISSUE THREAD

**Issue by IsaiahKelly** [sschmid/Entitas-CSharp#563]
By default the project path in Entitas Preference is set to `Assembly-CSharp.csproj` However, on Windows 10 this is not always correct. Sometimes the project file is actually named after the Unity project itself. So if your Unity project is named "My Game" the project file might actually be `My Game.csproj`, but what exactly determines the project file name is something of a mystery at the moment. So I hope to use this topic to investigate the cause of the issue and hopefully come up with a _solution_, no pun intended. 

First of all, the file naming convention seems to be directly related to the script editor you're using with Unity. For example, MonoDevelop seems to always generate `Assembly-CSharp.csproj` while Visual Studio can produce either `Assembly-CSharp.csproj` or `<Project Name>.csproj`, seemingly at random!

So for starters I decided to take a look at the solution (.sln) files generated by each script editor on Windows.

### Visual Studio Solution File
```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 2017
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```

### MonoDevelop Solution File
```
Microsoft Visual Studio Solution File, Format Version 11.00
# Visual Studio 2010

Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution

	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(MonoDevelopProperties) = preSolution
		StartupItem = Assembly-CSharp.csproj
	EndGlobalSection
EndGlobal
```

As you can see, MonoDevelop is using file format v11 here and includes an extra section that defines:

**StartupItem = Assembly-CSharp.csproj**

This would seem to explain why MonoDevelop always generates `Assembly-CSharp.csproj`, but we still are left to wonder why Visual Studio can generate either type. It also turns out that adding that extra definition to the Visual Studio file doesn't seem to fix it and is removed automatically. 

**_To be continued_**

**Comment by sschmid** [comment]
Added ValidateProjectPathPreProcessor to throw an error which will hint to the solution
