### ISSUE TITLE
[Question] Example Entitas Scene demonstrating subsystem and UnityEngine data types/objects

### ISSUE THREAD

**Issue by miketon** [sschmid/Entitas-CSharp#57]
Hey y'all,

Can I get a pointer to an example scene that demonstrates how subsystems are setup.  As well as array of example interaction with all UnityEngine datatypes (GameObject, Vector3...etc).  I stumbled on it an existing example scene in one of the projects available here a week ago, but for the life of my are unable to locate that scene again.  Thanks for your attention and consideration.

**Comment by sschmid** [comment]
Do you mean this?
https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas.Unity.VisualDebugging/Assets/Tests/Game%20Scene.unity

<img width="594" alt="entitas-entity-inspector" src="https://cloud.githubusercontent.com/assets/233700/12380363/5689f4a6-bd71-11e5-9c98-7bbe214658a6.png">

**Comment by miketon** [comment]
Yes!  I spent ~3 hours stepping through the repo available looking for this.  Thanks for the pointer, and taking the time to answer this.  I really appreciate the work y'all are putting in to Entitas.  It's a very different approach to code than I'm familiar with, and are loving it so far.

**Comment by sschmid** [comment]
You're more than welcome! :)
I'm happy to hear that you like it, and thanks for your support, I really appreciate it.
