### ISSUE TITLE
EntityLink exceptions is thrown on inactive GameObjects when quitting application.

### ISSUE THREAD

**Issue by AVAVT** [sschmid/Entitas-CSharp#570]
I'm getting this exception thrown on all GameObjects in my object pool:
```
EntitasException: EntityLink got destroyed but is still linked to Entity_14(*10)( ... )!
```
It seems OnApplicationQuit() is not called on inactive MonoBehaviors.

Currently I have to add this to `GameController` to turn off the error messages:
```
void OnApplicationQuit()
{
    foreach (EntityLink links in Resources.FindObjectsOfTypeAll(typeof(EntityLink)))
    {
      if (!links.gameObject.activeInHierarchy)
      {
        links.Unlink();
      }
    }
}
```

**Comment by sschmid** [comment]
Maybe I should consider to remove this behaviour again. This is [the code](https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.Unity/Entitas.Unity/EntityLink.cs#L35-L46) I added recently. Main goal was to inform the user that he forgot to unlink gameObjects. Doing this in OnDestroy might not be the best idea...

**Comment by AVAVT** [comment]
Do you think this is a bug on Unity side? The doc says it is called on all GameObjects but apparently it's only called on active GameObjects.

I think the warning is helpful and should not be removed.

**Comment by sschmid** [comment]
Is this still an issue for you? What's your use case having inactive gameObjects that are still linked to active entities?

**Comment by AVAVT** [comment]
Well a simple use case is an object pool (projectiles).
It's no longer a bug, but an issue in the sense that it's yet another thing I have to remember to do manually in every new scene.

**Comment by sschmid** [comment]
If you are using them for object pools, you should definitely unlink them.

**Comment by AVAVT** [comment]
I see. I'm currently pooling entities along with their gameobjects, so I never unlink object during the game. Anyway, it's no longer a problem so I'll close the issue.

**Comment by sschmid** [comment]
Ok. Btw, all entities are already automatically object pooled, so you don't need to do that.
