### ISSUE TITLE
How can I use the Roslyn Plugin with source code?

### ISSUE THREAD

**Issue by yuchting** [sschmid/Entitas-CSharp#571]
Hi,

I have a question want to ask, if I use Entitas via source code instead of dll, and I move the source code folder to another place of Asset of unity, how can I use Roslyn plugin?

It say "cannot find Entitas/Editor folder", if I move source code to the same folder(Assets/Entitas), it will report a lot of error.

And another question for Roslyn, what is this meaning? Although my Roslyn work OK with dll.
![image](https://user-images.githubusercontent.com/1817716/35181799-8f755ef2-fe03-11e7-9a54-9629afd05a72.png)

**Comment by roygear** [comment]
To use Entitas and Roslyn generator properly, particular folder placement is needed! You cannot move them to anywhere.

That SQLitePCLRaw error can be ignored. It will disappear in latest version of Entitas.

**Comment by yuchting** [comment]
@roygear thanks for your quick reply.
Could you explain more about Roslyn plugin do for Entitias code? I find the Entitas.exe file has been changed into Jenny.exe, I run this exe file, it show a lot of command:

> usage:
> jenny add key value          - Add a value to a key
> jenny auto-import            - Find and import all plugins
> jenny client command         - Start client mode
> jenny doctor                 - Check the config for potential problems
> jenny dry                    - Run the code generator in dry mode
> jenny dump                   - List all config keys and values
> jenny edit                   - Open config files with default editor
> .....

I just know a little usage via [Entitas introduce video](https://www.youtube.com/watch?v=LGKsqSg5FHg),  any wiki/example/note to let me know more about those commands? And what did Jenny do for my C# code by xxxx.csproj file while I "jenny gen"? How can I custom a code generator?

Thanks!

**Comment by roygear** [comment]
The "Roslyn" is a new code generator which is aim to replace the old code generator of Github version.
Compare to the old one, Roslyn generator mainly have 2 advantages: 
	- faster code generation time via client-server mode
	- code can be generated even there are code errors


"jenny fix", "jenny auto-import" used for first time setup.
"jenny doctor" to check whether the setup good or not.
After successful setup, we only use command "jenny client gen" in daily workflow. 

For other commands, I personally never used. 

For custom code generation, there is no detailed DOC in wiki. 
You can get inspiration from Entitas' source code:
https://github.com/sschmid/Entitas-CSharp/tree/develop/Addons/Entitas.CodeGeneration.Plugins

**Comment by sschmid** [comment]
Thanks @roygear, I couldn't have said it better :)

**Comment by yuchting** [comment]
@roygear Thanks a lot!
So I cannot use Roslyn with source code, but I was newbie in Entitas, how can I debug my project code and see the Entitas code too? Because I step follow the code, cannot enter the Entitas.dll.

@sschmid any idea?

**Comment by roygear** [comment]
Which IDE is used for your project? Something like Visual Studio or Rider can decompile the DLL file and then source code will be shown. If you just like to see the source code some time rather than changing them, use DLL version of Entitas is fine.

**Comment by sschmid** [comment]
@yuchting the Entitas dlls are optimized release builds and therefore don't contain any debug information. That's usually the case for precompiled 3rd party libraries. You can fork Entitas and compile debug dlls if you want (see [CONTRIBUTING.md](https://github.com/sschmid/Entitas-CSharp/blob/develop/CONTRIBUTING.md)) to step through the code. Not quite sure if that's desirable though if you want to debug 'your' code.

**Comment by yuchting** [comment]
@roygear @sschmid 
Thank you! As a newbie of Entitas, I have always a lot of problems, thanks for your patience and help :)
