### ISSUE TITLE
Error on generate in new project

### ISSUE THREAD

**Issue by c0ffeeartc** [sschmid/Entitas-CSharp#572]
Hi, getting this error on hitting generate in empty project, Entitas 0.47.9, Unity 2017.1.2f1
```
Could not find file "/..../TestEntitas/Assembly-CSharp.csproj".
```
In Entitas 0.42.3 it was possible to avoid this error by unchecking `Update .csproj` in `Tools->Entitas->Preferences->PostProcessors`. Unchecking this option in new Entitas versions doesn't help

Is this error expected behaviour for new Entitas versions or a regression?

Error gets fixed by opening any .cs file in IDE which generates csproj file

**Comment by FNGgames** [comment]
Try changing the entry in the entitas preferences menu to target <your-project-name>.csproj and see if that fixes it. I.e. the .csproj file that unity generates in the top level of your project folder.

**Comment by c0ffeeartc** [comment]
There is no csproj file in new Unity project

**Comment by sschmid** [comment]
As soon as you open the c# project the very first time (Assets > Open C# Project), Unity will create a project for you. I think Unity should create this by default, but it doesn't. But that's not really a problem. Usually Unity will create `Assembly-CSharp.csproj`, in some cases users reported that the project is called differently, e.g. `<MyProjectName>.csproj`. Adjust the Entitas preferences accordingly

**Comment by sschmid** [comment]
Also see Video at 2:59
https://youtu.be/LGKsqSg5FHg?t=2m59s

**Comment by optimisez** [comment]
@sschmid Maybe you can do auto search .csproj for Unity and Jenny code gen and also manual setup .csproj function or Jenny although u can just directly edit properties file directly.

**Comment by c0ffeeartc** [comment]
Error message should be more descriptive, something like:
```
Could not find file "/pathToYouProject/Assembly-CSharp.csproj".
Press "Assets->Open C# Project" in Unity's menu to create it.
If error remains check name of created *.csproj, and write it into Entitas preferences.
```

**Comment by IsaiahKelly** [comment]
@c0ffeeartc I'd say "Could not find file" is pretty self explanatory. It's also supposed to be an error message, not a tutorial 😛. However, the wiki [FAQ](https://github.com/sschmid/Entitas-CSharp/wiki/FAQ#csproj-missing) page already explains how to fix this and other common errors in detail.

**Comment by c0ffeeartc** [comment]
Sorry, do not agree. Error message should point to solution when possible IMHO

**Comment by IsaiahKelly** [comment]
Yes, that's a standard error message. 

It would probably be ideal if @sschmid could somehow automatically open the C# project whenever you run **Auto Import** or **Generate** and Entitas detects that the project file and/or script assemblies are missing, or at least upon first run.

Not sure if we can actually detect project file naming issues, but adding a **More Info** or **Help** button to the error message itself, that links to the FAQ or other documentation, would be a very helpful too.

**Comment by CreativeWarlock** [comment]
Glad I had a look into the issues section of this repository. When I went through the installation steps I got the same daunting error. I can only agree to @c0ffeeartc that error messages should always point to some solutions.

**Comment by sschmid** [comment]
Added ValidateProjectPathPreProcessor to throw an error which will hint to the solution
