### ISSUE TITLE
Entity being retained by trigger

### ISSUE THREAD

**Issue by mrobaczyk** [sschmid/Entitas-CSharp#575]
Hi,

Firstly, Im sorry if I posted my question in wrong place, but I couldn't find any other way to do it.

I have a question.

I work with Unity and I have many features and systems in my project. My application has 3 main modes. I have split my features so that every feature works only on their corresponding application mode. (I dont want to use CPU for systems' updates that aren't needed).

I have some problems with entities being retained by systems from other app mode. It seems like a trigger from a system is being cached and thats why my entity which I want to delete is being retained. It says: 

Retained by (1)
Collector(Group(AllOf(View))).

View is my Component for storing Unity gameobject for an entity.

My problem is that I don't know hot to release the entity. One idea is to change the trigger so that it gets triggered on View.Added but when entity has View and has Base component. Currently it is  
```csharp
    protected override ICollector<CoreEntity> GetTrigger(IContext<CoreEntity> context)
    {
        return context.CreateCollector(CoreMatcher.View.Added()); 
    }
```
and I would like to add to it that it has BaseComponent but it's impossible to merge Added event with component check. is it?

I would like to do something like this:
```csharp
    protected override ICollector<CoreEntity> GetTrigger(IContext<CoreEntity> context)
    {
        return context.CreateCollector(CoreMatcher.AllOf(CoreMatcher.View.Added(), CoreMatcher.Base); 
    }
```
but this is not compiling.

Furthermore I have some simple quick questions:
Is there any difference between CoreMatcher.AllOf(CoreMatcher.View.Added() and CoreMatcher.AllOf(CoreMatcher.View ? It seems to me that there is not.

How can I react only on entity being added to group?

Does ReplaceComponent trigger Component.Removed, Component.Added?

How does this work:
```csharp
CoreMatcher.AllOf(CoreMatcher.View, CoreMatcher.Base).Added()
```
Thank you for any help. 
Michael

**Comment by charlieamer** [comment]
Hello guys,

I think I encountered a similar bug (or not, I don't really know). My bug was that after destroying all entities (i wanted to load a new level basically), in teardown even though I called `_systems.ClearReactiveSystems();` I still got error `ContextStillHasRetainedEntitiesException: 'Game' detected retained entities although all entities got destroyed!
Did you release all entities? Try calling systems.ClearReactiveSystems()before calling context.DestroyAllEntities() to avoid memory leaks.`

I noticed all entities that didn't want to clean up were retained by collector of velocity system, so here is the old collector code which caused the problem:
```c#
return context.CreateCollector(GameMatcher.Velocity.Added(), GameMatcher.Move.Removed());
```

I replaced the code with the following code:
```c#
return context.CreateCollector(GameMatcher.AllOf(GameMatcher.Velocity).NoneOf(GameMatcher.Move));
```
and my problem was solved. So I guess in your case you can solve your problem by using
```c#
return context.CreateCollector(CoreMatcher.View);  // without added() function. You can additionally check if view exists in filter.
```

**Comment by sschmid** [comment]
> I have some problems with entities being retained by systems from other app mode

When you deactivate an app mode, consider calling `systems.DeactivateReactiveSystems()`. This will pause them until you activate them again and also releases any retained entities.

> and I would like to add to it that it has BaseComponent

use Filter() to filter entities.
To react to both View and Base use
`context.CreateCollector(CoreMatcher.View.Added(), CoreMatcher.Base.Added());`

To react to a group with view and base use
`context.CreateCollector(CoreMatcher.AllOf(CoreMatcher.View, CoreMatcher.Base);`

> Is there any difference between CoreMatcher.AllOf(CoreMatcher.View.Added()

CoreMatcher.View.Added() is not a matcher and this code won't compile
*.Added() return TriggerOnEvent

> Does ReplaceComponent trigger Component.Removed, Component.Added

Replace will trigger group added

> CoreMatcher.AllOf(CoreMatcher.View, CoreMatcher.Base)

it creates a group with view and base. if an entity has both, it's added, otherwise not

Hope that helps ;)

**Comment by mrobaczyk** [comment]
systems.DeactivateReactiveSystems() this helped! Thanks a lot!
