### ISSUE TITLE
Asteroids example - Live Streaming ~February 18th

### ISSUE THREAD

**Issue by KumoKairo** [sschmid/Entitas-CSharp#576]
Hi,

Students from the local University's gamedev club are very interested in ECS and Entitas, so I have decided to make a local stream on a full how-to with Asteroids example in one shot.
I will be streaming from that University (or from home if WiFi there will turn out to be not really fast) on Youtube so you'll be able to connect and take part in it.

![image](https://user-images.githubusercontent.com/2943071/35379761-3b50ef12-01c8-11e8-84e2-24b30ec6970e.png)

Approximate date - February 18th, 
Time - 1 P.M. (GMT +3)

I just wanted to check on the most appropriate time for the international viewers.
Is 1 P.M. (GMT +3) OK?

Cheers

**Comment by sschmid** [comment]
Awesome! Sounds great! Do you also record to share it later or is it streaming only?

**Comment by KumoKairo** [comment]
Sure, it will be shared after the stream :)

**Comment by KumoKairo** [comment]
https://youtu.be/tQa-LMEl0nE streaming is live

**Comment by KumoKairo** [comment]
https://youtu.be/1qh6fTHeb5E
Recording. Links included

**Comment by sschmid** [comment]
Thanks for sharing!
