### ISSUE TITLE
Jenny doesn't work if Entitas is in a Subdirectory with Spaces

### ISSUE THREAD

**Issue by thygrrr** [sschmid/Entitas-CSharp#579]
Hi,

I have a practice of placing 3rd Party modules in "Assets\3rd Party". This causes Jenny to fail. 

Workaround: If I place Entitas in Assets directly, or rename the subdirectory "3rdParty", this works.

```
C:\Projects\Demo>\Jenny\Jenny\jenny gen
Game\GameComponentsLookup.cs - Entitas.CodeGeneration.Plugins.ComponentsLookupGenerator
Input\InputComponentsLookup.cs - Entitas.CodeGeneration.Plugins.ComponentsLookupGenerator
Game\GameAttribute.cs - Entitas.CodeGeneration.Plugins.ContextAttributeGenerator
Input\InputAttribute.cs - Entitas.CodeGeneration.Plugins.ContextAttributeGenerator
Game\GameContext.cs - Entitas.CodeGeneration.Plugins.ContextGenerator
Input\InputContext.cs - Entitas.CodeGeneration.Plugins.ContextGenerator
Game\GameMatcher.cs - Entitas.CodeGeneration.Plugins.ContextMatcherGenerator
Input\InputMatcher.cs - Entitas.CodeGeneration.Plugins.ContextMatcherGenerator
Contexts.cs - Entitas.CodeGeneration.Plugins.ContextsGenerator, Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator
Game\GameEntity.cs - Entitas.CodeGeneration.Plugins.EntityGenerator
Input\InputEntity.cs - Entitas.CodeGeneration.Plugins.EntityGenerator
Feature.cs - Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator

Could not load file or assembly 'Entitas, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
```

This is using the Asset Store version 1.0.0.

**Comment by thygrrr** [comment]
Actually, a whole lot of things may or may not be glitching out if Entitas is not in the root of Assets. :(

**Comment by FNGgames** [comment]
From my point of view, this would be a killer - i will flat-out refuse to use any asset that won't let me tidy it away in a Assets/Libraries/... folder.

**Comment by thygrrr** [comment]
Not sure what exactly is going wrong here, actually. The Jenny server batch also doesn't work unless it's in the root of your project, but I guess that's easily remedied.

(I mean you also can't call \Jenn\Jenny-Server and expect that to work because the batch is written in a way that it only runs if there is a Jenny directory with Jenny.exe in the current Directory)

**Comment by sschmid** [comment]
You can place Entitas and Jenny in any folder you want. I guess @FNGgames is happy to hear that ;)

You posted another issue #581. So I guess there went something wrong with you setup.

Can you share your properties file?

**Comment by FNGgames** [comment]
Goodo. I'm super OCD about tidy folders :)

**Comment by roygear** [comment]
@sschmid I think it is just OK for Mac.
For Windows, I still have to put Jenny's content like this to make it work.
![entitaswindow](https://user-images.githubusercontent.com/30362268/35467507-1eeff98e-034a-11e8-9474-15229627f654.jpg)

**Comment by sschmid** [comment]
Hi, I uploaded a Video Tutorial on how to set up Entitas. Let me know if it helps you
See #585 

It it helps you can close this issue

**Comment by thygrrr** [comment]
Can no longer reproduce. 

I did the steps from the tutorial video and it works.

Thank you VERY much for helping out with this, I'm a little embarrassed this bug report turned more into a customer service ticket in the end. :)
