### ISSUE TITLE
Return removed components to the component pool

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#58]
As a performance optimization the Code Generator creates component pool for each generated component type (https://github.com/sschmid/Entitas-CSharp/blob/develop/Tests/Tests/Entitas.CodeGenerator/Fixtures/PersonComponent.cs#L15)

When you replace or remove components, the old component gets pushed to the component pool.

However, neither e.RemoveAllComponents() nor pool.DestroyEntity() will make use of the component pool and won't push them back.

That should be fixed...

**Comment by sschmid** [comment]
Once we add a component using a generated method like `e.AddHealth(42)` we could add an event handler for `OnComponentRemoved`. This handler could check if the component index is the same and push the component to the component pool. This way it would work for both cases  `e.RemoveAllComponents()` and `pool.DestroyEntity()`

What do you think?
I also have unity project for performance testing where I could check if the added event handler has a negative effect on the performance.

**Comment by sschmid** [comment]
Also, I think it's time to also add tests for the actual logic of the generated output, not only tests for the expected output of the generator. I'd like to add tests for the four component types (standard, flag, single std, single flag)

**Comment by sschmid** [comment]
First tests revealed it adds 104 byte per component even with cached event handlers
<img width="815" alt="entitas component pool" src="https://cloud.githubusercontent.com/assets/233700/12434024/7977f820-bf04-11e5-9c7b-7129d0e5182e.png">

**Comment by sschmid** [comment]
Creating new components would be cheaper...

**Comment by trumpets** [comment]
I see... The issue I stumbled upon, and thus discovering this intricacy, was that my object count was increasing a lot, I had a lot of entities which were being destroyed and created, and the GC was turning on once in ~10 secs and that was stuttering my game :/

I am tinkering with the code right now, trying to figure out another way...

**Comment by sschmid** [comment]
91%, to be precise :)
<img width="808" alt="entitas new component" src="https://cloud.githubusercontent.com/assets/233700/12434216/abed178a-bf05-11e5-925a-42aa318cab21.png">

**Comment by sschmid** [comment]
Here's my test, if you're interested:

**Comment by sschmid** [comment]
```
using System.Collections.Generic;

namespace Entitas {
    public partial class Entity {
        public PositionComponent position { get { return (PositionComponent)GetComponent(ComponentIds.Position); } }

        public bool hasPosition { get { return HasComponent(ComponentIds.Position); } }

        static readonly Stack<PositionComponent> _positionComponentPool = new Stack<PositionComponent>();

        public static void ClearPositionComponentPool() {
            _positionComponentPool.Clear();
        }

        EntityChanged cachedOnComponentRemoved {
            get {
                if (_cachedOnComponentRemoved == null) {
                    _cachedOnComponentRemoved = onComponentRemoved;
                }

                return _cachedOnComponentRemoved;
            }
        }

        EntityChanged _cachedOnComponentRemoved;

        public Entity AddPosition(float newX, float newY, float newZ) {
            OnComponentRemoved += cachedOnComponentRemoved;
            var component = _positionComponentPool.Count > 0 ? _positionComponentPool.Pop() : new PositionComponent();
            component.x = newX;
            component.y = newY;
            component.z = newZ;
            return AddComponent(ComponentIds.Position, component);
        }

        public Entity ReplacePosition(float newX, float newY, float newZ) {
//            var previousComponent = hasPosition ? position : null;
            var component = _positionComponentPool.Count > 0 ? _positionComponentPool.Pop() : new PositionComponent();
            component.x = newX;
            component.y = newY;
            component.z = newZ;
            ReplaceComponent(ComponentIds.Position, component);
//            if (previousComponent != null) {
//                _positionComponentPool.Push(previousComponent);
//            }
            return this;
        }

        public Entity RemovePosition() {
//            var component = position;
            RemoveComponent(ComponentIds.Position);
//            _positionComponentPool.Push(component);
            return this;
        }

        void onComponentRemoved(Entity entity, int index, IComponent component) {
            OnComponentRemoved -= cachedOnComponentRemoved;
            if (index == ComponentIds.Position) {
                _positionComponentPool.Push((PositionComponent)component);
            }
        }
    }

    public partial class Matcher {
        static IMatcher _matcherPosition;

        public static IMatcher Position {
            get {
                if (_matcherPosition == null) {
                    var matcher = (Matcher)Matcher.AllOf(ComponentIds.Position);
                    matcher.componentNames = ComponentIds.componentNames;
                    _matcherPosition = matcher;
                }

                return _matcherPosition;
            }
        }
    }
}
```

**Comment by sschmid** [comment]
added `onComponentRemoved`

**Comment by trumpets** [comment]
I found this article summarizing some garbage tests with events and delegates: http://jacksondunstan.com/articles/3264#comments and they confirm your findings. 104 bytes for creating a delegate and then another 208 bytes when adding that delegate to an event if it is the second+.

**Comment by sschmid** [comment]
I could try writing a custom event system for Entitas. Might be (or not be) more efficient

**Comment by sschmid** [comment]
I have an idea which works completely without events. An entity could have an array of stacks (similar to the array which holds the components). When removing a component it will get the stack at index and push the component. Done. If not stack exists, it doesn't (which means we're using entitas without the code generator)
I'll give it a try

**Comment by sschmid** [comment]
fyi, I started writing tests for the existing generated component extensions. After that I will implement my idea test driven.

**Comment by sschmid** [comment]
Ok, I found a way which works without events.
See PR #60

**Comment by sschmid** [comment]
@trumpets @SvDvorak
If you like, you can test the latest version. Here are the zip files
https://github.com/sschmid/Entitas-CSharp/commit/fbfc99e5e0061b93b4f6017b18c6fb21c1bf22db

I'd be interested if it solves your issues. Let me know, if it works better now

**Comment by sschmid** [comment]
See #60

**Comment by SvDvorak** [comment]
A bit late but I checked through your solution, smart moving up the pools and creating a function to retrieve the correct one. Nicely done!

**Comment by sschmid** [comment]
Thanks :)
