### ISSUE TITLE
Jenny gives errors unless using the default Windows terminal

### ISSUE THREAD

**Issue by thygrrr** [sschmid/Entitas-CSharp#580]
Jenny's input functions don't work if the input is redirected, or you're using a non-standard terminal such as MinTTY on Windows (ships with Cygwin and Git for Windows). 

This happens with both cmd and (Cygwin or GfW) bash. Haven't tried anything from Windows Linux Subsystem yet.

```
$ jenny auto-import
??  Will add missing key: 'Jenny.Ignore.Keys' (press any key)
Cannot read keys when either application does not have a console or when console
input has been redirected from a file. Try Console.Read.
```
This is using 1.0.0 asset store.

**Comment by sschmid** [comment]
I'm using `Console.ReadKey(true)` to prompt user input. Do you know a way that works with your terminal as well?

**Comment by sschmid** [comment]
Btw, you can use `jenny auto-import -s`. `-s` is for silent mode. You will get way less prompts.

**Comment by sschmid** [comment]
You need to do the setup only once per project. Consider using the default terminal for that as shown here #585

**Comment by thygrrr** [comment]
I'd suggest the read key commands to be omitted; as that could also interfere with automated project setup, etc.

Other than that, I can live with using the default terminal.
