### ISSUE TITLE
Frequent Unity Error on Generate

### ISSUE THREAD

**Issue by thygrrr** [sschmid/Entitas-CSharp#582]
Hi,
after generating by pressing the button in the Entitas Preferences menu, I get (about 80% of the time) the following error on Unity 2017.3.0f3 Windows using Entitas 1.0.0 Asset Store

```
Reload Assembly called from managed code directly. This will cause a crash. You should never refresh assets in synchronous mode or enter playmode synchronously from script code.
UnityEditor.EditorUtility:ClearProgressBar()
DesperateDevs.CodeGeneration.CodeGenerator.Unity.Editor.UnityCodeGenerator:Generate()
```

Cheers

**Comment by sschmid** [comment]
After a quick google I read "strange regression in Unity for Windows specifically".

That's what my gut feeling tells me too (though I might be wrong). I'm just using the Unity API `UnityEditor.EditorUtility:ClearProgressBar()` as usual. Starting with 2017.3 I discovered multiple other Unity GUI bugs. Seems like they changing quite a bit here and there but it's not quite ready yet.

But to get back to you issue: that message can be ignored and won't affect the functionality.
As mentioned in other Unity GUI related issues, I will ignore them for now and hope Unity fixes them as I don't think I can do anything about it.

**Comment by sschmid** [comment]
Created a new issue to collect all those issues. Will close and redirect to #583
