### ISSUE TITLE
Jenny: Visual Studio freezing when generating code

### ISSUE THREAD

**Issue by optimisez** [sschmid/Entitas-CSharp#588]
When generating code with Jenny, my Visual Studio 2017 will freeze awhile and need to wait the gen process to complete before I continue using Visual Studio. It would be better to improve the experience that won't freeze the Visual Studio when gen code. I think there are something related to refresh .csproj file.

**Comment by sschmid** [comment]
Do you experience the same issue when you manually edit a source file outside of VS and go back to VS?

**Comment by optimisez** [comment]
Nope. No freezing issue when manually edit a source file outside of VS and go back to VS

**Comment by sschmid** [comment]
Ok sorry, I actually meant modifying the project file. If you have a suggestion how to improve this for VS please let me know. With my current knowledge it's a short coming from VS and there's nothing I can do about it other than recommending another IDE such as Rider. Maybe there are settings in VS to change this behaviour?

**Comment by buihuuloc** [comment]
@sschmid 
I'm having the same issue here.
I'm using Iterm2. The Jenny server is really slow. It takes more just 2 minutes to generate the code when using: 
``` jenny client gen```

Any ideas??

**Comment by sschmid** [comment]
@buihuuloc Your issue is a different thing. This issue is about Visual Studio not handling external project modification well.

Could you please create a new issue and tell me more about your setup. Is it any different to what I explained in this video? see #585

**Comment by sschmid** [comment]
I'm afraid, but I don't think I can do anything about how Visual Studio 2017 handles changes made to the project.
