### ISSUE TITLE
A question about visual debugging

### ISSUE THREAD

**Issue by 000hahaha000** [sschmid/Entitas-CSharp#589]
Hi,

I have have a question about visual debugging 
It is an error when i click GameObject named Systems

InvalidOperationException: Operation is not valid due to the current state of the object
System.Collections.Generic.Stack`1[System.Boolean].Pop ()
UnityEditor.EditorGUI.EndDisabledGroup () (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:211)
Entitas.VisualDebugging.Unity.Editor.DebugSystemsInspector.drawSystemInfos (Entitas.VisualDebugging.Unity.DebugSystems systems, SystemInterfaceFlags type)
Entitas.VisualDebugging.Unity.Editor.DebugSystemsInspector.drawSystemInfos (Entitas.VisualDebugging.Unity.DebugSystems systems, SystemInterfaceFlags type)
Entitas.VisualDebugging.Unity.Editor.DebugSystemsInspector.drawSystemList (Entitas.VisualDebugging.Unity.DebugSystems systems)
Entitas.VisualDebugging.Unity.Editor.DebugSystemsInspector.OnInspectorGUI ()
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1231)
UnityEditor.DockArea:OnGUI()

InvalidOperationException: Operation is not valid due to the current state of the object
System.Collections.Generic.Stack`1[System.Boolean].Pop ()
UnityEditor.EditorGUI.EndDisabledGroup () (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:211)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1254)
UnityEditor.InspectorWindow.DrawEditors (UnityEditor.Editor[] editors) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1028)
UnityEditor.InspectorWindow.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:352)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Here's some code

How can I resolve this problem ?

thank you!

**Comment by sschmid** [comment]
Hi, unfortunately I cannot tell from the error message. I would need more information about the system setup and if you're doing anything special. Can you identify which system causes this issue?

**Comment by ethankennerly** [comment]
If it's relevant, I've seen this error preceded by another error:

Visual debugging sometimes crashes when switching windows.

Steps:
1. Mac laptop.
1. Play in editor.
1. Switch window away from Unity.
1. Edit an asset file.
1. Switch back to Unity. 
1. Sometimes an error appears:

        NullReferenceException: Object reference not set to an instance of an object
        Entitas.VisualDebugging.Unity.ContextObserverBehaviour.OnDestroy () (at <7a3e32b56db949119387854a500d7000>:0)

After this, I might also see a GUI sort of like the one above, but I seem to recall the stack trace was different.

**Comment by sschmid** [comment]
I haven't got any feedback so far, so I assume the issue is resolved? Feel free to re-open otherwise.
