### ISSUE TITLE
Jenny : install in windows fail

### ISSUE THREAD

**Issue by raveneer** [sschmid/Entitas-CSharp#590]
followed this video, but not works. 

maybe path different? 

my symptom: https://www.youtube.com/watch?v=BToRuJgniLI&feature=youtu.be

**Comment by sschmid** [comment]
Hi, please `cd` into the folder where the properties file is located. You were in the wrong folder

**Comment by raveneer** [comment]
https://youtu.be/gzB17VH9CU8

I tried in project folder too...

**Comment by sschmid** [comment]
try `cd` into the folder where the properties file is and run
```
$ Jenny/Jenny.exe fix
$ Jenny/Jenny.exe auto-import
```

**Comment by raveneer** [comment]
thank you. fix worked me.
