### ISSUE TITLE
Question about DestroyAllEntities mechanism

### ISSUE THREAD

**Issue by hegi25** [sschmid/Entitas-CSharp#594]
Hi,

I have question about using DestroyAllEntities. 
When you call this method its checks collectors for retained entities and asks you to clear active reactive systems. Why not clearing the attached reactive systems itself? Is there any scenario when you want to destroy all entities in a context (for example reload the game) without resetting the reactive systems? Currently i'm using a workaround for this problem right now to keep reactive systems collected by contexts and call contexts.game.ClearReactiveSystems(); before destroying entites.

```csharp
public class Processor : Feature
{
    public bool Enabled = true;
    private readonly IContext _context;

    public override void Execute()
    {
        if (Enabled)
            base.Execute();
    }

    public Processor(IContext context, string name) : base(name)
    {
        _context = context;
        _context.AddSystem(this);
    }

    ~Processor()
    {
        _context.RemoveSystem(this);
    }
}

public static class IContextExtension
{
    private static readonly Dictionary<IContext, List<Processor>> Dictionary = new Dictionary<IContext, List<Processor>>();

    public static void AddSystem(this IContext context, Processor processor)
    {
        List<Processor> list;
        if (!Dictionary.TryGetValue(context, out list))
        {
            list = new List<Processor>();
            Dictionary.Add(context, list);
        }

        list.Add(processor);
    }

    public static void RemoveSystem(this IContext context, Processor processor)
    {
        Dictionary[context].Remove(processor);
    }

    public static void ClearReactiveSystems(this IContext context)
    {
        List<Processor> list;
        if (Dictionary.TryGetValue(context, out list))
        {
            foreach (var processor in list)
            {
                processor.ClearReactiveSystems();
            }
        }
    }
}
```

Cheers

**Comment by sschmid** [comment]
Hi, in Entitas you always have full control of all your systems. Contexts are not aware of systems and will never execute or clear anything for you. Entitas throws an exception when using `context. DestroyAllEntities()` and there are still retained entities. I do this to enforce cleaning up first which will prevent any unintended follow-up bugs that are harder to track down otherwise. In those cases you have to decide what makes the most sense for you application, sometime clearing reactive systems makes sense, sometime other steps like processing all retained entities might be more desirable. This is totally up to you. Hope this helps

**Comment by hegi25** [comment]
Thanks for the reply. 

I agree that contexts are not aware of systems so i revoke my suggestion above.
But i still think that something is not working correctly here.

My main problem is with the working style of the Collector and Filter.
When using a collector with .Removed() matcher it will trigger when i call DestroyAllEntities(). There is no problem at all. But after these collectors will retain these entities even if the filter will never match. Its like warning me even if there are no reactive systems to process any entity. My suggestion here is to check the validity of the retained entities after the collectors update with reactive systems filter or something like.

For Example:
Collector: context.CreateCollector(GameMatcher.BatchingIsVisible.Removed());
Filter: return entity.hasView && !entity.isBatchingIsVisible;

1.DestroyAllEntities()
2.BatchingIsVisible component is removed (also View component)

How currently work: The collector will retain my entity but the filter is not matching. (No reactive system will ever process these entities)
How should it work: The collector will not retain the entity, because the filter is not matching.


Workaround 1:
1.Add a WillBeDestroyed component to all entities
2.DestroyAllEntities()
3.context.CreateCollector(GameMatcher.AllOf(GameMatcher.BatchingIsVisible).NoneOf(GameMatcher.WillBeDestroyed).Removed();
4. Not working, still retaining (I thought BatchingIsVisible component will be removed first because of alphabet, but collector still retaining)

Workaround 2:
1.Add a WillBeDestroyed component to all entities
2.context.CreateCollector(GameMatcher.BatchingIsVisible.Removed(), GameMatcher.WillBeDestroyed.Added()); (i have to remove the BatchingIsVisible component manually here, or the collector will trigger again)
3. DestroyAllEntities()
4. Actually this one works, but its too complicated compared to my original suggestion.

Thanks!

**Comment by hegi25** [comment]
New idea!

What about Collectors not collecting disabled entities. This tweak would solve all my problems. 
Is there any situation when you want to execute disabled entities in a reactive system? My short answer is no, because you cannot Add/Remove/Replace any component on a disabled entity, so there is no reason to retain them.

Thanks!

**Comment by sschmid** [comment]
Hi, sorry for the late answer. Before calling context.DestroyAllEntities() you should call systems.DeactivateReactiveSystems(). This will deactivate and clear all collectors and release retained entities.

> How currently work: The collector will retain my entity but the filter is not matching

Entities are not retained when not passing the filter. The collector releases all entities after executing the reactive system, see [ReactiveSystem](https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Systems/ReactiveSystem.cs#L65)

I think the problem you mean is when a collector in the reactive systems collected entities but you never execute the system and the call context.DestroyAllEntities().

This is what the exception should suggest
see [ContextStillHasRetainedEntitiesException](https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Context/Exceptions/ContextStillHasRetainedEntitiesException.cs#L10-L11)

**Comment by hegi25** [comment]
Hi, sorry but i cannot agree with you. 
If i have a ReactiveSystem with trigger like: `context.CreateCollector(GameMatcher.Asset.Removed());` this will retain any entity is destroyed (and has AssetComponent of course). But this should only retain entities if the AssetComponent has been removed. Why should a reactive system retain an entity if it is Destroyed (aka it has no components to work with). What could a reactive system execute on an empty entity? I still suggest to implement this filter into the Collector  
```
private void addEntity(IGroup<TEntity> group, TEntity entity, int index, IComponent component)
    {
      if (!entity.isEnabled || !this._collectedEntities.Add(entity))
        return;
      entity.Retain((object) this);
    }
```

Thanks
