### ISSUE TITLE
Question regarding component design

### ISSUE THREAD

**Issue by bit-chimp** [sschmid/Entitas-CSharp#596]
Hey,

I'm stumped on how to design components, here's an example of what I mean:

I've got a VelocityComponent because I want entities to be able to move, accelerate and decelerate. 

Should my VelocityComponent contain these variables:
````
namespace Assets.Sources.Core.Position.Components
{
    public sealed class VelocityComponent : Entitas.IComponent
    {
        public float x;
        public float y;
        public float maxSpeed;
        public float accelerationSpeed;
        public float decelerationSpeed;
    }
}
````

Or would it be a better approach to have VelocityComponent, SpeedComponent, AccelerationComponent and DecelerationComponent?

````
namespace Assets.Sources.Core.Position.Components
{
    public sealed class VelocityComponent : Entitas.IComponent
    {
        public float x;
        public float y;
    }
}
````
````
namespace Assets.Sources.Core.Position.Components
{
    public sealed class AccelerationComponent : Entitas.IComponent
    {
        public float speed;
    }
}
````
````
namespace Assets.Sources.Core.Position.Components
{
    public sealed class DecelerationComponent : Entitas.IComponent
    {
        public float speed;
    }
}
````
````
namespace Assets.Sources.Core.Position.Components
{
    public sealed class SpeedComponent : Entitas.IComponent
    {
        public float speed;
    }
}
````
My reason for asking is that if I use the 1st approach, when I come to ReplaceVelocity with the new values for x and y, I'll need to also add accelerationSpeed and decelerationSpeed, which I find a little annoying to be honest.

Maybe there is another approach which I haven't thought of, suggestions and advice appreciated :)

Cheers

**Comment by bit-chimp** [comment]
Tried to approach it differently and this is what I ended up with:

<img width="270" alt="screen shot 2018-02-04 at 08 00 56" src="https://user-images.githubusercontent.com/20213078/35775060-a6caece6-0981-11e8-8b74-aa32a5b58dd2.png">

I think that's a little complex for it since when I come to actually creating the entities I need to add all those components just for movement, what do you think?

**Comment by Lazersquid** [comment]
Short answer is that composing an entity of many small components is better than having few big components that might contain unneeded functionality. You can create static methods to create combinations of components that you need often, eg:
```C#
public static void AddVelocityComponents(GameEntity entity, float x, float y, float maxSpeed, ...)
{
    entity.AddPosition(x, y);
    entity.AddMaxSpeed(maxSpeed);
    ...
}
```

**Comment by sschmid** [comment]
I agree with @Lazersquid 
You will have benefits from splitting up components more granular. You can react to specific changes like velocity change, and you will more likely be able to reuse the code in different project.

**Comment by bit-chimp** [comment]
Thanks for your feedback guys. 

Regarding entity references, is it a bad practice to hold a List<GameEntity>? I've got an Ore Vein which creates Ore Branches for each miner that targets it, the Ore Vein needs to keep a reference to all it's branches to make sure they're removed when it's destroyed. So would a ParentComponent containing a List<GameEntity> be a bad idea?

**Comment by raveneer** [comment]
you don't need a list of entities, just make a group. Igroup<T>.getEntities() will return desired entities!

**Comment by bit-chimp** [comment]
I require the list because I need the entities that were created by another specific entity, I don't think a group will cut it unfortunately.

**Comment by bit-chimp** [comment]
For the SightTargets I decided to use a component with a List of Entity IDs, and for Targeting I've decided to use a static class with a method GetEntityTargets, which gets all entities with targets and crossmatches the ID. Seems to be a good approach for this issue.

**Comment by FNGgames** [comment]
@bit-chimp Lists are fine, you can do the following:
```csharp
// define this component
public class ListComponent : IComponent {
    public List<int> values;
} 

// now you can do any of the things below
// add fresh list
e.AddList(new List<int>()); 

// build a list then add
var list = new List<int>();
list.Add(1);
list.Add(2);
e.RepalceList(list);

// read an existing list from a comp, modify and save it back
var list = e.list.values;
list.Add(3);
e.ReplaceList(list);

// same but without the temp variable
e.list.values.Add(1);
e.ReplaceList(e.list.values); 
// important that you call replace, even though you already
// modified the list in-place - replace triggers reactive systems!
```

**Comment by FNGgames** [comment]
RE: getting entity targets - that sounds like a job for a Custom Entity Index. See #351 for an implentation of an entity index that lets you do "GetXWithY" lookups (e.g. GetTargetWithId(int id))

**Comment by bit-chimp** [comment]
That's exactly how I managed to work around it, thanks for the suggestion. Hopefully, this will help others with the same issue :)
