### ISSUE TITLE
Define order of Component removal? 

### ISSUE THREAD

**Issue by bit-chimp** [sschmid/Entitas-CSharp#598]
Hi,

I'm trying to use the Destroy All Entities on a context and one entity that is linked to a GameObject is not being unlinked due to my View component being removed before my Asset/Sprite. If the WillRemove event is added (reference to my previous issue posted) then I can utilise that, but if not, what would be the right approach to this?

Oh and I should thank you for Entitas, it's the greatest tool for ECS!

Cheers

**Comment by bit-chimp** [comment]
So after testing this some I found that adding these

````
         m_systems.DeactivateReactiveSystems();
         m_systems.ClearReactiveSystems();
         m_contexts.game.DestroyAllEntities();
````

instead of using Destroy All Entities gets the job done, so why doesn't Destroy All Entities use these methods and how can I get it to work without these calls? 

I hope you don't mind all these questions but I'm trying to learn by example and I can't seem to find this info in previous issues/wiki, so I'm hoping they will help others too.

**Comment by sschmid** [comment]
Hi, questions are always welcome, no problem.
Here's a recent issue about DestroyAllEntities where I already replied #594

I assume you heard about the common practice of using a DestroyedComponent and flagging entities with `e.isDestroyed = true` as in [Match One](https://github.com/sschmid/Match-One)

Destroying entities should always be the last step to avoid issue similar to what you experienced. So before you call context.DestroyAllEntities you have to clean up everything that has to been cleaned up, e.g views and unlinking views.

**Comment by bit-chimp** [comment]
So Contexts will not change anything from systems, good to know, thank you!
