### ISSUE TITLE
Bug: When stopping my game, it sometimes says that the gameObject has been destroyed

### ISSUE THREAD

**Issue by bit-chimp** [sschmid/Entitas-CSharp#600]
Hi,

I've encountered an issue, I'm using Entitas 1.0 asset store version.

These two screenshots are the same exact code run after each other, it sometimes throws that error, I'm assuming that Unity destroys it's game objects before Entitas runs TearDown?

<img width="1680" alt="screen shot 2018-02-05 at 03 29 07" src="https://user-images.githubusercontent.com/20213078/35786114-5008bfce-0a25-11e8-9308-091363e044aa.png">
<img width="1680" alt="screen shot 2018-02-05 at 03 28 55" src="https://user-images.githubusercontent.com/20213078/35786115-5025c772-0a25-11e8-9671-14d3e1b96cfb.png">

This is where the error is being thrown
````
private void RemoveView(GameEntity e)
        {
            Debug.Log("Destroy GO");
            var go = e.view.gameObject;
            go.Unlink();
            Object.Destroy(go);
            e.RemoveView();
        }

        public void TearDown()
        {
            Debug.Log("Tear down");
            foreach (var e in m_context.GetGroup(GameMatcher.View).GetEntities())
            {
                RemoveView(e);
            }
        }
````

Cheers

**Comment by sschmid** [comment]
Looks like it, yes. That's not an Entitas bug. There are multiple ways to solve this. If you need to keep the teardown this way I suggest checking Unity's execution order and set it up accordingly by placing this script above the default time.

**Comment by bit-chimp** [comment]
Great, thanks for your answer!
