### ISSUE TITLE
Changing Scene with ReactiveSystem cause ContextStillHasRetainedEntitiesException

### ISSUE THREAD

**Issue by AVAVT** [sschmid/Entitas-CSharp#602]
So I have managed to change scene through user input with no trouble, but when I change scene through a ReactiveSystem, the system retains an entity and cause the mentioned exception.

So I have a reactive system that is executed whenever a value reaches 0:

```
// GameOverSystem.cs
protected override bool Filter(GameEntity entity)
{
	return entity.hasGoldRepository && entity.goldRepository.value <= 0;
}

protected override void Execute(List<GameEntity> entities)
{
	GamePlayController.Instance.GameOver();
}
``` 

Within GamePlayController I have:
```
// GamePlayController.cs
public void GameOver()
{
	_systems.TearDown();
	_systems.DeactivateReactiveSystems();
	_systems.ClearReactiveSystems();
	_systems = new Feature();
	foreach (EntityLink links in Resources.FindObjectsOfTypeAll(typeof(EntityLink)))
	{
		links.Unlink();
	}
	_contexts.Reset();

	// ... Change to GameOver Scene
}
```

At `_contexts.Reset()` I always get this error:
```
ContextStillHasRetainedEntitiesException: 'Game' detected retained entities although all entities got destroyed!
Entity_10(*1)() - ReactiveSystem(GameOverSystem)
```

While I kinda know what causes the problem: `GamePlayController.GameOver()` is called within `GameOverSystem`'s `Execute()` so GameOverSystem is still retaining the `goldRepository` entity. But I don't know how to resolve it. Destroying or Releasing the entity only result in further exceptions.

**Any help?**

-----

Right now I'm using this workaround that, well, works, but looks terrible:
```
public void GameOver()
{
    _systems.TearDown();
    _systems.DeactivateReactiveSystems();
    _systems.ClearReactiveSystems();
    _systems = new Feature();
    foreach (EntityLink links in Resources.FindObjectsOfTypeAll(typeof(EntityLink)))
    {
      links.Unlink();
    }
    StartCoroutine(ChangeSceneNextFrame());
}

IEnumerator ChangeSceneNextFrame()
{
    // Wait 1 frame after all systems are deactivated so they no longer retains entities
    yield return null;
    _contexts.Reset();
    Camera.main.GetComponent<CameraMasker>().MaskChangeScene("GameOver");
}
```

**Comment by sschmid** [comment]
I usually have a unique `GameOverComponent` and a system like `DetectGameOverSystem`. As you already mentioned, you're basically calling teardown and reset in the middle of the execution phase. I recommend to only set the context.isGameOver and then act accordingly and do the teardown and reset in OnDestroy of the controller of the current scene
