### ISSUE TITLE
Entitas telemetry?

### ISSUE THREAD

**Issue by CCludts** [sschmid/Entitas-CSharp#604]
Hi,

I have a question. When I generate using roslyn compiler and -v flag, at the end it show me a uri:
`http://desperatedevs.com/a/entitas.php?u=<sensitive info goes here>`
Is the codegenerator sending my usage-statistics to a server?!

**Comment by KumoKairo** [comment]
Yes, you can check the compiled `DesperateDevs.Analytics.dll`. It doesn't send much - OS version and hadrware statistics. 
```
public UserTrackingData()
{
	base["u"] = Environment.UserName + "@" + Environment.MachineName;
	base["d"] = Environment.ProcessorCount + "@" + Environment.OSVersion;
}
```
But it bothers me too. It works with a built-in generator too, this `dll` is inside Unity package by default. We have rolled back to 0.45.1 for an "in production" project and use a completely custom Entitas version for our new projects.

**Comment by CCludts** [comment]
@KumoKairo thanks for the response. It's seems to more than just that though, it seems to also report information about the components.
It's unsetteling to me that my (potentially very sensitive) data is sent to some server without notifying/asking for permission, and the source-code is not public information. 
@sschmid would it be possible to have an option to disable this?

**Comment by WoLfulus** [comment]
quick solution:

Edit /etc/hosts or C:\Windows\System32\drivers\etc\hosts and add

127.0.0.1 desperatedevs.com

**Comment by sschmid** [comment]
You can turn off tracking by adding

Jenny.TrackHooks = false

to the properties file.

**Comment by KumoKairo** [comment]
We need a check mark in the GUI properties in Unity too
