### ISSUE TITLE
Enum auto-generation

### ISSUE THREAD

**Issue by CCludts** [sschmid/Entitas-CSharp#606]
Hi,

I have a suggestion. There's a case me (and others on my team) have run into multiple times now, and each time we ended up copy-pasting a bunch of code. 
I think codegeneration is a much more appropriate way of dealing with this, but I would like to hear from the community as well 👍 

```csharp
using System;
using System.Collections.Generic;
using Entitas;
using Entitas.CodeGeneration.Attributes;
using NUnit.Framework;
using UnityEngine;


// CodeGeneration flag
namespace Entitas.CodeGeneration.Attributes {
    
    public class EnumFlagAttribute : System.Attribute { 
        
    }
}


[Game][EnumFlag]
public class StatusComponent : IComponent { 
    public Status value;
}
public enum Status {
    On,
    StandBy,
    Off
}


public partial class Contexts {
    
    public void DemonstrateEnumFlag() {
        
        var e = game.CreateEntity();
        e.ReplaceStatus(Status.Off); // nothing new
        
        // under the hood, it ALSO uses flag components
        Assert.IsTrue (e.isStatusOff);
        Assert.IsFalse(e.isStatusOn);
        Assert.IsFalse(e.isStatusStandBy);
        
        
        e.ReplaceStatus(Status.On);
        Assert.IsTrue (e.isStatusOn);
        Assert.IsFalse(e.isStatusOff);
        Assert.IsFalse(e.isStatusStandBy);
        
        
        
        // this way, you can react to the flags being set
        var g = game.GetGroup(GameMatcher.StatusOn);
        g.OnEntityAdded += (_g, _e, _i, _c) => {
            Debug.Log("STATUS WAS TURNED ON");
        };
        
        
        // it's still a normal enum component, we did not remove any functionality
        var g2 = game.GetGroup(GameMatcher.Status);
        g2.OnEntityAdded += (_g, _e, _i, _c) => {
            Debug.Log("STATUS CHANGED: " + _e.status.value);
        };
    }
}
```

Cheers

**Comment by FNGgames** [comment]
Simon will tell you to write a custom code generator. I think the idea is really good though, and warrants consideration for being part of entitas.

I imagine that generating a flag component for each state of the enum is how you would have to do it for the custom matchers and groups. This could easily explode out into many many components, but that would be your decision when you add the attribute to your component right?

Many of the helper methods could be done without any extra flag components - you could have `e.isStatusOn`, `e.isStatusOff`, `e.isStatusStandby`, as a wrapper around a simple equality check -> under the hood it would be `e.status.value == Status.On`, no need for an actual new component generated for each enum state there.

**Comment by sdarkwell** [comment]
I like this idea as well!
\- S.

**Comment by CCludts** [comment]
@FNGgames Indeed, this could be supported without codegeneration, but that involves increasing the complexity by a large amount. 
Having read-only flags is by far the easiest way of implementing this, and the flags just get updates when you replace the component. 

Yes this will create more components, but it's by entitas' design that you can only react to component, not component values. I like this way of coding, it makes code simple. I would dislike this being implemented in any other way than through components.

That said, I'm glad that other people are also seeing the usecase for this :)

**Comment by FNGgames** [comment]
@CCludts all fair points for sure

**Comment by sschmid** [comment]
They way I usually deal with sth like this is a reactive system that reacts to StatusComponent and in the Filter() I filter for the desired enum value.

> Simon will probably tell you to write a custom code generator

@FNGgames knows me by now ;)

If it makes sense for you, you can look into creating a custom code generator for this and share it with us.
