### ISSUE TITLE
Adding partial keyword to Interfaces generated in ComponentEntityInterfaceGenerator

### ISSUE THREAD

**Issue by guitax** [sschmid/Entitas-CSharp#607]
Hi,

I'm currently using my own version of [`ComponentEntityInterfaceGenerator`](https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration.Plugins/Entitas.CodeGeneration.Plugins/CodeGenerators/ComponentEntityInterfaceGenerator.cs) class in which the only difference is that it generates a `partial` interface (so that I'm able to other custom generators).

Since I have to keep up with the possible changes (like the ones made with #591), could you maybe add the `partial` keyword to the official generator to increase the extensibility for everyone?

Thanks for this awesome ECS framework!

Cheers

**Comment by sschmid** [comment]
Just curious, what is your exact use case. With what do you extend the partial interface?

**Comment by guitax** [comment]
For now I'm using something like your code gen example in #451.
And I think that in general if your generated interfaces are partial, then we can have more "freedom" in creating custom code generators.
Besides what harm can it make? 😁

**Comment by sschmid** [comment]
OK :)
