### ISSUE TITLE
Can I use Entitas in dotnet core2?

### ISSUE THREAD

**Issue by vkyii** [sschmid/Entitas-CSharp#612]
Hi,

I have some game logic to do in server side which almost same with Unity client, my server code depends on .net core2, how can I use it correctly? especially the code generation.

Cheers.

**Comment by sschmid** [comment]
I have no experience with .NET core2, so I don't know if it works or not

**Comment by StormRene** [comment]
@vkyii 
Did a quick check about the topic and run the Api Port Analysis from Microsoft. Here's the result:
![image](https://user-images.githubusercontent.com/30431430/36664414-e5729d44-1ae4-11e8-8db5-bda41a1f74fa.png)

**Comment by xmzyl** [comment]
great!
