### ISSUE TITLE
Having a EnabledComponent interferes with Entitas internal logic

### ISSUE THREAD

**Issue by Draugor** [sschmid/Entitas-CSharp#614]
Hello, 

i just came across this interesting problem: some of my reactive system stopped triggering. (or so it seemed still not to sure where exactly this all goes wrong)
So after some testing and reverting code-changes i found the reason to be my newly added EnabledComponent, which is a simple component without any members.
For such a component the code generator produces an isEnabled property, but this property now "hides" the isEnabled property of the IEntity interface and the Entity Class, and thus destroys some internal logic.

Now i could think of an other name for that component or use the [UniquePrefix] attribute to circumvent that problem, but to prevent others from stumbling over this i suggest renaming the property in the IEntity interface and the Entity class.

Cheers
Draugor

**Comment by sschmid** [comment]
Hi. If renamed, the issue still exist. I suggest renaming EnableComponent because isEnabled is already taken. Maybe activated?
