### ISSUE TITLE
Generate systems hierarchy

### ISSUE THREAD

**Issue by mrobaczyk** [sschmid/Entitas-CSharp#619]
Hi,
could you provide some sample code to generate systems hierarchy grouped in features like in Unity debug view?

It would be very nice to have such hierarchy when debugging code.

I've been looking into Entitas code to get it done with methods already implemented in Entitas.VisualDebugging.Unity and Entitas.VisualDebugging.Unity.Editor, but there is a lot of code and I'm struggling with it...

Thanks in advance for any help.
Michael

**Comment by mrobaczyk** [comment]
Could you point me code in Entitas.VisualDebugging where you iterate over all Features and Systems and where you list them in they Unity inspector?

**Comment by sschmid** [comment]
[DebugSystemsInspector.cs](https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.VisualDebugging.Unity.Editor/Entitas.VisualDebugging.Unity.Editor/DebugSystems/DebugSystemsInspector.cs)

**Comment by sschmid** [comment]
Did this info help you? If so, you can close if you want

**Comment by mrobaczyk** [comment]
Yes thanks for help. Now i have to implement what I want.
