### ISSUE TITLE
Multiple listeners for a single component on a single entity

### ISSUE THREAD

**Issue by RomanZhu** [sschmid/Entitas-CSharp#621]
Hi,

Repost from @echeg
> Many cases when for one entity it is necessary to call simultaneously several changes in the UI.
For example, we have several units, each of them has health. And when it changes, this change needs to be shown in two+ different places(hp bar, card info, stats screen etc).

If anyone has suggestions on how it could be used or implemented - welcome :D

**Comment by StormRene** [comment]
I already proposed a solution in the issue of reactive ui and in the chat. Take a look here: https://github.com/sschmid/Entitas-CSharp/issues/591#issuecomment-365905791

**Comment by RomanZhu** [comment]
Yep, that's a good one
this issue was created to be dedicated for that separate feature, #591 is too broad

**Comment by sschmid** [comment]
Will change to List<IListener> and will add a generator for this

```csharp
public partial class GameEntity {

    public void AddColorListener(IColorListener value) {
        var listeners = hasColorListener
            ? colorListener.value
            : new System.Collections.Generic.List<IColorListener>();
        listeners.Add(value);
        ReplaceColorListener(listeners);
    }

    public void RemoveColorListener(IColorListener value) {
        var listeners = colorListener.value;
        listeners.Remove(value);
        if (listeners.Count == 0) {
            RemoveColorListener();
        } else {
            ReplaceColorListener(listeners);
        }
    }
}
```

**Comment by IDNoise** [comment]
You can also add to EntitasCache (if it's partial) new object pool entry per multicast event and get list from there on add and push on remove, because this api is already ready for it :)
