### ISSUE TITLE
Alloc free groups

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#624]
#see latest comments in #408

Make iterating over groups alloc free

**Comment by sschmid** [comment]
@rastlin86
see commit 9520928b62bcdee4c5c77aef738866135eaf0c00

**Comment by optimisez** [comment]
@sschmid Will anything break for this changes?

**Comment by sschmid** [comment]
Only if you used linq, e.g. group.Where().
But all foreach loops are unaffected

**Comment by optimisez** [comment]
> Only if you used linq, e.g. group.Where().
But all foreach loops are unaffected

@sschmid I see ur Match-One example project uses Linq. Have u thought about how to solve this breaking change? Something like: 

`foreach (var e in _contexts.game.GetEntitiesWithPosition(new IntVector2(input.x, input.y)).Where(e => e.isInteractive)) {
            e.isDestroyed = true;
        }
`

**Comment by sschmid** [comment]
that's not a group, so that will still work

**Comment by sschmid** [comment]
I should probably have a custom entity index that only get interactive entities and replace linq. But I probably won't :)

**Comment by optimisez** [comment]
@sschmid Actually dun use linq and make it as if statement check will be better. lol
`
foreach (var e in _contexts.game.GetEntitiesWithPosition(new IntVector2(input.x, input.y))) 
        {
            if (e.isInteractive)
                e.isDestroyed = true;
        }
`

**Comment by IDNoise** [comment]
According to this https://stackoverflow.com/questions/3679805/how-does-foreach-call-getenumerator-via-ienumerable-reference-or-via/3679993#3679993
you can still use IEnumerable interface (just implement it privately so there is no crossing between GetEnumerator that returns HashSet and the one that returns IEnumerator<T>). And for foreach it will be alloc free (because GetEnumerator that returns hashset.enumerator must be used first) and for linq there will be cast to ienumerable version. Didn't test myself, but thing to try :)

**Comment by rastlin86** [comment]
@sschmid Have you profiled the implementation?

According to MS reference source the AddRange always creates a temp table:
https://github.com/mono/mono/blob/27480ee50d6fe402b752da40653d7c6a38e517dd/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs#L735

I'm looking for how it's implemented in mono to confirm.

**Comment by optimisez** [comment]
@rastlin86 Should be. Even I switch to Api Compatability Level to .Net 4.6.

```
[__DynamicallyInvokable]
    public void InsertRange(int index, IEnumerable<T> collection)
    {
      if (collection == null)
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.collection);
      if ((uint) index > (uint) this._size)
        ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.index, ExceptionResource.ArgumentOutOfRange_Index);
      ICollection<T> objs = collection as ICollection<T>;
      if (objs != null)
      {
        int count = objs.Count;
        if (count > 0)
        {
          this.EnsureCapacity(this._size + count);
          if (index < this._size)
            Array.Copy((Array) this._items, index, (Array) this._items, index + count, this._size - index);
          if (this == objs)
          {
            Array.Copy((Array) this._items, 0, (Array) this._items, index, index);
            Array.Copy((Array) this._items, index + count, (Array) this._items, index * 2, this._size - index);
          }
          else
          {
            T[] array = new T[count];
            objs.CopyTo(array, 0);
            array.CopyTo((Array) this._items, index);
          }
          this._size += count;
        }
      }
      else
      {
        foreach (T obj in collection)
          this.Insert(index++, obj);
      }
      ++this._version;
    }
```

**Comment by sschmid** [comment]
@rastlin86 I added a new scene in the VisualDebugging project call Group Alloc
see PR https://github.com/sschmid/Entitas-CSharp/pull/625

The profiler said 0B gc alloc, so I'm happy.

**Comment by optimisez** [comment]
@sschmid I wonder what kind of use case will use `_group.GetEntities(_buffer)`? Only iterate _buffer entities?

**Comment by rastlin86** [comment]
It's nice to see that Unity optimised AddRange implementation. Good job with the testing scene!
