### ISSUE TITLE
Upgrading from 1.1 -> 1.3

### ISSUE THREAD

**Issue by SpellChucker** [sschmid/Entitas-CSharp#627]
I just tried to upgrade from v1.1 to v1.3 and now my components are not getting generated. I didn't change anything, just dropped the new version into my project at the same location v1.1 was in. v1.1 worked perfectly but v1.3 does not put anything in the generated folder. Any ideas?

**Comment by sschmid** [comment]
Yes, please use `auto-import` again to use the updated plugin names

**Comment by sschmid** [comment]
See [release notes](https://github.com/sschmid/Entitas-CSharp/releases)

**Comment by SpellChucker** [comment]
Ah sorry, I did see that but I did a generate before auto import. Thank you.

**Comment by sschmid** [comment]
No worries, happy coding :)
