### ISSUE TITLE
How would you approach nested Sprite Swapping?

### ISSUE THREAD

**Issue by bit-chimp** [sschmid/Entitas-CSharp#629]
Hi,

As the title suggests, I'm curious as to how you would handle nested sprite swapping? I've got humanoids with arms, legs, torso, head and weapon that can be swapped, how would you do this in an ECS? 

My approach is I create some sort of AnatomyComponent which holds a Dictionary<string,int> being BODY_PART_ID and Entity Index and then use that in a SpriteSwappingSystem?

Curious to see what you guys come up with!

Cheers

**Comment by StormRene** [comment]
What do you think about the following: 
`HumanComponent` identifies your humanoids.
`BodyPartComponent` has a reference to the Human. Like so
```
class BodyPartComponent : IComponent {
   [EntityIndex]
   public int creationIndex;
}
```
When you want to change parts of your humanoid you could do:
```
var bodyParts = context.GetEntitiesWithBodyPart(specificHuman.creationIndex);
foreach(var bodyPart in bodyParts) {
   //go for it
}
```

**Comment by bit-chimp** [comment]
HO, I totally disregarded the EntityIndex attribute! You're a genius, thanks man!

**Comment by StormRene** [comment]
You are welcome :)
