### ISSUE TITLE
Possible to define System execute order?

### ISSUE THREAD

**Issue by bit-chimp** [sschmid/Entitas-CSharp#630]
Hey!

I was wondering if would be possible to add the ability to define when a system is run, according to the hierarchy you posted, Init > Input > Execute > Events > Cleanup.

Would it be possible to add that somewhere so we define it in the System itself? 

````
public class ApplyPositionSystem  : IExecuteSystem
    {
        private Contexts m_contexts;
        private IGroup<GameEntity> m_group;

        public ApplyPositionSystem  (Contexts contexts)
        {
            m_contexts = contexts;
            m_group = contexts.game.GetGroup(GameMatcher.Position);
            contexts.SetSystemRuntime(SystemStructures.Execute);
        }

        public void Execute()
        {
            foreach (var e in m_group.GetEntities())
            {
            
            }
        }
    }
````

````
public class CreatePositionSystem : ReactiveSystem<GameEntity>
{
    private Contexts m_contexts;    

    public CreatePositionSystem (Contexts contexts) : base(contexts.game)
    {
        m_contexts = contexts;
        contexts.SetSystemRuntime(SystemStructures.Initialize);
    }

    protected override ICollector<GameEntity> GetTrigger(IContext<GameEntity> context)
    {
        return context.CreateCollector(GameMatcher.Prefab);
    }

    protected override bool Filter(GameEntity entity)
    {
        return entity.hasView == false;
    }

    protected override void Execute(List<GameEntity> entities)
    {
        foreach(var e in entities)
        {
            //Create View
        }
    }
}
````
That way I won't need to worry about how I organise them in features, because they will always run a specific order. This will also allow me to package Core Components and Systems than I can use on all my projects and simply add the CoreSystems Feature to my main game loop!

Cheers

**Comment by StormRene** [comment]
You know that you can nest Features? Like a `SystemStructuresExecuteFeature` in your `MainLoopFeature` and so on. 
If you really want that feature you could build it yourself in two ways:
1. Create your own generator and make a set of Attributes for your systems. 
2. The `Add(ISystem system)` in `Systems` is public therefore you could call it inside a System. For example deriver from `ReactiveSystem` implement your own technqiue how to add to `Systems` and finally deriver from that class all your regular systems.

**Comment by sschmid** [comment]
Atm, the system execution order is defined by the order you add them to the systems. You can implement your own strategies how you want to add systems in a specific order if that makes sense for you. I would advice not to put the  information about the system order in the system itself as it will become impossible to keep the overview and control ones you have lots of system.
Instead, I recommend having Feature classes like `InitSystems`, `ExecuteSystems`, `InputSystems`, etc and group your systems within those classes

**Comment by bit-chimp** [comment]
Defining the execution by use of nested features seems to be the best approach. I'll just use CoreInit, CoreExecute, CoreInput for my library then create MainInit and just add grouped features in there.

Thanks for your help :)
