### ISSUE TITLE
Index was outside the bounds of the array (Entitas v 1.4.1 w/patch)

### ISSUE THREAD

**Issue by fayte0618** [sschmid/Entitas-CSharp#633]
![capture](https://user-images.githubusercontent.com/8073714/36770422-299bcfc6-1c85-11e8-8877-8f20f537b468.PNG)

**Comment by roygear** [comment]
to fix this, check the last post  : https://github.com/sschmid/Entitas-CSharp/issues/628

**Comment by sschmid** [comment]
Hi, you are using 1.4.1? Did you update both, the Entitas folder in the Assets and Jenny outside of the Assets folder?

Can you show me the component with the event attribute, it seems like it couldn't get the priority

**Comment by sschmid** [comment]
I can only reproduce, if I don't pass a bool as the first argument (which of course will result in compiler error). Please check if you pass a bool like this [Event(true)] or [Event(false)]

**Comment by fayte0618** [comment]
^already fixed! Thanks I updated all my EventType.AddedOrRemoved.
