### ISSUE TITLE
MultiReactiveSystem throwing errors when upgrading from 1.0.0

### ISSUE THREAD

**Issue by AVAVT** [sschmid/Entitas-CSharp#635]
I have a MultiReactiveSystem following this wiki guide: https://github.com/sschmid/Entitas-CSharp/wiki/MultiReactiveSystem-Tutorial

This is how it looks like:

*IPoolableEntity.cs*
```
using Entitas;
using UnityEngine;

public interface IPoolableEntity : IEntity, IReusable, IView, IPoolable { }

public partial class GameEntity : IPoolableEntity { }
public partial class InputEntity : IPoolableEntity { }
public partial class SoundEntity : IPoolableEntity { }
```

*CleanUpPoolSystem.cs*
```
public class CleanUpPoolSystem :  MultiReactiveSystem<IPoolableEntity, Contexts>
{
  ...
}
```

Now after upgrading to 1.4.1, `jenny gen` has generated an IPoolableEntity a huge amount of errors show up:

```
The namespace '<global namespace>' already contains a definition for 'IPoolableEntity' [Assembly-CSharp]

The type or namespace name `IReusable' could not be found. Are you missing an assembly reference? // Same for IView & IPoolable
```

**Comment by sschmid** [comment]
looks like you updated Entitas but didn't unzip the new Jenny or ran auto-import.

**Comment by sschmid** [comment]
The new interfaces changed name and end with *Entity now

**Comment by AVAVT** [comment]
I see, so IPoolable is now IPoolableEntity?
But what do you suggest I name my previously named IPoolableEntity now?
I followed the lead and changed it to:
```
public interface ICrossContextPoolableEntity : IEntity, IReusableEntity, IViewEntity, IPoolableEntity { }

public partial class GameEntity : ICrossContextPoolableEntity { }
public partial class InputEntity : ICrossContextPoolableEntity { }
public partial class SoundEntity : ICrossContextPoolableEntity { }
```

it works now but the name is pretty cumbersome.

**Comment by sschmid** [comment]
`IPoolable`? :)

**Comment by sschmid** [comment]
Is that actual code from your game? Because, why input and sound is a IViewEntity?
I don't think you need multiple contexts and interfaces for that at all

**Comment by AVAVT** [comment]
Oh SoundEntities are mostly GameObjects with AudioSource that are pooled and move around (even attach themselves to other entities), so they have View.
For Input it's a relic from past mistakes, removed ^^'
