### ISSUE TITLE
Broken Code Generator Documentation Link

### ISSUE THREAD

**Issue by npruehs** [sschmid/Entitas-CSharp#64]
The wiki page Code Generator at https://github.com/sschmid/Entitas-CSharp/wiki/Code-Generator contains a broken link in the first paragraph:

"In a pure C# project, simply choose your generators like this."

I expected to find a reference implementation of how to fire up a code generator, but found none.

**Comment by sschmid** [comment]
Thanks!
Please see #62

**Comment by sschmid** [comment]
Updated the section with a code example
https://github.com/sschmid/Entitas-CSharp/wiki/Code-Generator

**Comment by npruehs** [comment]
Thank you!
