### ISSUE TITLE
Draw read-only properties in inspector

### ISSUE THREAD

**Issue by raincole** [sschmid/Entitas-CSharp#640]
It would make debugging easier if Entitas' inspector draws read-only properties of components in inspector, besides public fields and read-write properties. For example:

```
public class MovementComponent : IComponent {
    public Vector3 Velocity;
    public float Speed => Velocity.Magnitude
}
```

I don't want to make `Speed` writable, but I want to see its change in real time.

Specifically, this behavior is defined at https://github.com/sschmid/Entitas-Shmup/blob/master/Assets/Libraries/Entitas/Entitas/Serialization/PublicMemberInfo.cs#L91

That is a static method so I don't think there is an easy way to work around it without changing Entitas' code and work from source.

**Comment by sschmid** [comment]
@raincole by default, only public fields or properties are drawn.

However, you can customize this by implementing your own [IComponentDrawer](https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.VisualDebugging.Unity.Editor/Entitas.VisualDebugging.Unity.Editor/Entity/IComponentDrawer.cs)

Save the MovementComponentDrawer in a Editor folder and you can define how the component should be drawn.

Example:
https://github.com/sschmid/Entitas-CSharp/blob/develop/Tests/Unity/VisualDebugging/Assets/Examples/VisualDebugging/Editor/PersonComponentDrawer.cs

**Comment by raincole** [comment]
Got it. For future reference, this is how I implemented it:

https://gist.github.com/raincole/5943d5c68e045e785a742c5f85235cce

It's kinda ugly because I avoided changing current behavior. But hey it works.
