### ISSUE TITLE
How would you approach an RPG Stat system in Entitas?

### ISSUE THREAD

**Issue by bit-chimp** [sschmid/Entitas-CSharp#642]
Hi,

As the title implies, how would you do it?

My current thinking is to have a StatsComponent with a Dictionary<StatId, float> and a StatModifiersComponent with the same dictionary. Then use a ReactiveSystem to apply any changes to the StatsComponent when a modifier is added/removed or if the entity was damaged in the case of Health.

Or how about creating an entity for each StatModifier?
````
var healthModifier = Contexts.stat.CreateEntity();
healthModifier.AddStatBaseModifier(5);
healthModifier.AddStatMultiplierModifier(0.25);
healthModifier.AddStatId(Stats.Health);
healthModifier.AddStatModifierTarget(helmet);
````

**Comment by Djadavin** [comment]
Hello. I not a proffecional programer, but trying create RPG for fun.
My current aproach like whis:
I have a BaseStat class with float value and name. From BaseStat i have Primary, Secondary , Derived 
and Vital stat classes for progression stat like strenght, unchanging like mass, derived from others like HitChance and everchanging stats with cur/max values.
Stats are hold in simple wrap around Dictionary<string,BaseStat>.
For stat modifiers i have class with strings Stat, Layer(like armor, shield, total), and float value. And have component with StatModifier and ownerID added to entity for each modifier.
StatUpdateSystem gets StatCollection and all entities with StatModifiers fro each unit and calculates them.
I dont know if its good for your game, as im not prof.
I get inspiration from https://www.youtube.com/watch?v=wqEk5mzJB3M.
And for effects from https://www.youtube.com/watch?v=TIQlX2WPCAQ.

**Comment by bit-chimp** [comment]
I think the approach I proposed better maintains the principles of ECS, avoiding inheritance etc.

For dependant stats I think I would use a StatService with a method Calculate, and then have it call a HandleDerivedStats method or something which would have a bunch of if statements, if(statID == "critical") //depends on agility * strength / dexterity and returns a new value.

Honestly I think it'll be more manageable that way, but thank you for your input :)!
