### ISSUE TITLE
There is no method context.GetEntityWithId(id) but FAQ is saying so

### ISSUE THREAD

**Issue by mrobaczyk** [sschmid/Entitas-CSharp#644]
Hi,

how can I get entity by its id?

Mike

**Comment by c0ffeeartc** [comment]
Look at [IdComponent](https://github.com/sschmid/Entitas-CSharp/wiki/FAQ#q-should-i-store-references-to-entities-inside-components) example

**Comment by sschmid** [comment]
`context.GetEntityWithId(id) ` is a generated method when you use `PrimaryEntityIndex`

**Comment by sschmid** [comment]
Here's another example
[Match one - PositionComponent](https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Components/Game/PositionComponent.cs)

[Match One - GameBoardService](https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Services/GameBoardService.cs#L13)
