### ISSUE TITLE
MultiReactiveSystem of bug?

### ISSUE THREAD

**Issue by yika-aixi** [sschmid/Entitas-CSharp#646]
GetTrigger function carried out before the end of the ctor, which is odd, is a bug?
![image](https://user-images.githubusercontent.com/22412994/37151906-5f83bde0-2312-11e8-9753-06e9ee7ee242.png)
![image](https://user-images.githubusercontent.com/22412994/37151913-67e30086-2312-11e8-8cae-9af77d13232a.png)

Entitas versions:1.4.1

**Comment by sschmid** [comment]
Hi,

it's not a but. ReactiveSystem base calls GetTrigger()

https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Systems/ReactiveSystem.cs#L16-L17

**Comment by yika-aixi** [comment]
oh.
