### ISSUE TITLE
MultiReactiveSystem Execute error "Cannot cast from source type to destination type."

### ISSUE THREAD

**Issue by yika-aixi** [sschmid/Entitas-CSharp#648]
[extension set cs](https://github.com/sschmid/Entitas-CSharp/files/1796821/ttt.txt)

help me take a look at where I was using the wrong?

thank you

**Comment by yika-aixi** [comment]
[ttt.txt](https://github.com/sschmid/Entitas-CSharp/files/1796821/ttt.txt)

**Comment by FNGgames** [comment]
I believe this might be because the interfaces that get generated by entitias for multi-context components have been renamed.

What used to be called IDestroy is now IDestroyEntity. Unfortunately that was the name I used in the multi-reactive system tutorial for the interface I made, which now should be called something different.

```csharp

// this component
[Game, Input, State]
public class DestroyedComponent : IComponent { 
}

// generates an interface which is now called IDestroyEntity
// used to be called just IDestroy
public interface IDestroyEntity { 
    bool isDestroy;
}

// so now when you make your cross-context interfaces you need to name them differently:
public interface IDestroyable : IDestroyEntity, IEntity {}
public partial class GameEntity : IDestroyable {}
public partial class InputEntity : IDestroyable {}
public partial class StateEntity : IDestroyable {}
```

**Comment by yika-aixi** [comment]
Is still the same error

**Comment by yika-aixi** [comment]
You run the Game, and then in Game or Input to create an entity and the add DestroyedComponent you will see the error

**Comment by FNGgames** [comment]
I don't understand why you have the DestroyEntity class in there. There should be no such concrete class as a `DestroyEntity`. In our example you should only have a `GameEntity` and an `InputEntity`. These classes are both generated by entitas. I also cannot find the place where you say `public partial class GameEntity : IDestroyEntity {}`. You need to do this to be able cast from GameEntity to IDestroyEntity.

**Comment by FNGgames** [comment]
in your example file, `ttt` and `ttSystem` are both fine, but that DestroyEntity class should not exist.

**Comment by yika-aixi** [comment]
Now I deleted it and created
` ` public partial class GameEntity: IDestroy {} ` `
The and
` ` public partial class Inputntity: IDestroy {} ` `
But still the same mistakes, that I'm a little confused

Can you give me an example of can run?thank you!

[New](https://github.com/sschmid/Entitas-CSharp/files/1797655/ttt.txt)

**Comment by yika-aixi** [comment]
I suspend use MultiReactiveSystem, somewhat embarrassed
