### ISSUE TITLE
Extract Code Generator Utility Methods

### ISSUE THREAD

**Issue by npruehs** [sschmid/Entitas-CSharp#65]
Many of the methods of the class Entitas.CodeGenerator.ComponentsGenerator are incredibly useful for writing own code generators. Following methods could be extracted to be accessible from other generators:

- shouldGenerate
- getFieldInfos
- isSingletonComponent

**Comment by sschmid** [comment]
Please see #62.
Once I release the new version code generators only get ComponentInfo[]
https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas.CodeGenerator/Entitas.CodeGenerator/Intermediate/ComponentInfo.cs

This way you don't have to worry about if we use reflection, roslyn or anything else as a source.

**Comment by npruehs** [comment]
Neat! That should do the trick! :)
