### ISSUE TITLE
Unity Collider and Animator in entitas

### ISSUE THREAD

**Issue by VergilGao** [sschmid/Entitas-CSharp#655]
Hi,

I have a collider named AttackTrigger as a child gameobject of my actor, I wanna add it as a TriggerComponent the I can use Pysics2D to let my actor attack.
Can anyone give me some advice?

Cheers

**Comment by fayte0618** [comment]
dont let the triggerComponent have a direct reference to the unity trigger, but let it store data like a boolean to know it is triggered. Then, have a monobehaviour view that holds the collider AttackTrigger, and when it is triggered using the Mono methods (Ex. OnTriggerEnter). Then have the view create an input Entity or have it change the trigger data in your TriggerComponent and do your logic in your systems, then update your view again using EventListeners

**Comment by nashnie** [comment]
thanks@fayte0618

**Comment by nashnie** [comment]
@fayte0618 thanks.

**Comment by VergilGao** [comment]
@fayte0618 thank you.
