### ISSUE TITLE
Generate freezes with Roslyn plugin

### ISSUE THREAD

**Issue by reverso13** [sschmid/Entitas-CSharp#658]
Hi,

When I click generate (after configuring Roslyn plugin),  the editor completely freezes.
It gets stuck at the first stage called "[Dry Run] Creating model Component (Roslyn)".

The only way to make it work is by using the external generator.

I'm using Unity 2017.3.0p4

![](https://puu.sh/zKOPi/5d75ee493b.png)

**Comment by sschmid** [comment]
Roslyn is using new .NET code and can not be run in Unity, that's why there is the standalone generator (Jenny). Always use the Terminal, external Generate Button or other ways to generate with roslyn
