### ISSUE TITLE
Generate non-public pool access method

### ISSUE THREAD

**Issue by npruehs** [sschmid/Entitas-CSharp#66]
In generated Entity extension methods for all components, there's a duplicate for retrieving a component from the pool.

Example:

    var component = _positionComponentPool.Count > 0 ? _positionComponentPool.Pop() : new PositionComponent();

This line is used from Add and Replace extension methods (e.g. AddPosition and ReplacePosition), and might be useful for other generated extension methods as well. It could be extracted to a non-public method (e.g. AllocPosition).

**Comment by sschmid** [comment]
True. Atm it's intended, because this code is being generated and we can save a method call. If we start using it in more places, we can extract it to a method.

**Comment by npruehs** [comment]
Yeah, I had to copy it for my own implementation of IComponentCodeGenerator. Not a big deal, but other people might easily miss the pooling part by just calling the component constructor instead. Your decision :)

**Comment by sschmid** [comment]
In general extracting such a method would be nice. Not sure if it makes sense in this case. It's in a generated extension a should not be used from a different generated extension. Offering a generic method componentPool.GetComponent<Position> would work but since it's in a generated file I'd rather go for the better performance by writing new PositionComponent()

**Comment by sschmid** [comment]
Hi, a quick follow-up:
Just added entity.CreateComponent() which does all the pooling logic now. It's also used by the code generator now.
e641cf184a48691ed30454a880462a0f7b24e5ba

```csharp
public Entity AddPerson(int newAge, string newName) {
    var component = CreateComponent<PersonComponent>(ComponentIds.Person);
    component.age = newAge;
    component.name = newName;
    return AddComponent(ComponentIds.Person, component);
}

public Entity ReplacePerson(int newAge, string newName) {
    var component = CreateComponent<PersonComponent>(ComponentIds.Person);
    component.age = newAge;
    component.name = newName;
    ReplaceComponent(ComponentIds.Person, component);
    return this;
}
```

**Comment by npruehs** [comment]
Excellent :)
