### ISSUE TITLE
GC problem with Matcher

### ISSUE THREAD

**Issue by livingstonhan** [sschmid/Entitas-CSharp#661]
Hi,

I have an have question.

I enjoy using GetGroup method with Matcher like AllOf and AnyOf.  Easy to use and saves effort.

Like this :
 
```csharp

Contexts.sharedInstance.game.GetGroup(GameMatcher.AllOf(GameMatcher.Male, GameMatcher.Human).NoneOf(GameMatcher.CanFly));

```

But when I look into deep profile, It's cause amount of GC, like 0.5k to 1k per frame, Is that something I should be worried about? If It is, How could I avoid this? Stop using is last thing I want to do.

Cheers

**Comment by sschmid** [comment]
Can you tell me, what is causing the gc alloc?

Side notes, nice to know:
- "simple" Matchers like GameMatcher.Position are cached and only alloc once
- "Complex" matchers like AllOf().NoneOf are allocated new, but you can cache them manually if you use them often
- There's only ever 1 instance of a group per given matcher, so allocs only happen when requesting a group the first time

When profiling, make sure to turn of VisualDebugging to get more accurate results

**Comment by c0ffeeartc** [comment]
Also this might be helpful for group entities iteration https://github.com/sschmid/Entitas-CSharp/issues/624#issuecomment-368242397

**Comment by livingstonhan** [comment]
@sschmid  Thanks a lot, It's my mistake, I did not realize that matchers can be cached.
