### ISSUE TITLE
[Question]Jenny gen doesn't work on .net core 2.0?

### ISSUE THREAD

**Issue by xmzyl** [sschmid/Entitas-CSharp#663]
Hi,

I have  found a bug , Jenny doesn't gen code  exactly on .net core 2.0
 i create a .net core 2.0 project,  like below

![image](https://user-images.githubusercontent.com/1343477/37963550-2e6d2ac8-31f1-11e8-9e0c-cb279a353cfc.png)

I have added reference assembly, copied jenny to Project root path, then gen GameComponentsLookup.cs file, there 's TotalComponents field value is zero in code.

![image](https://user-images.githubusercontent.com/1343477/37964263-75bcbee6-31f3-11e8-8a59-6b246760f08a.png)

I uploaded my project [EntitasApp.zip](https://github.com/sschmid/Entitas-CSharp/files/1851662/EntitasApp.zip), help me please  @sschmid 

Here's code of components

```csharp
using Entitas;

namespace EntitasApp {
    [Game, Event(false)]
    public sealed class PositionComponent : IComponent {
        public int x;
        public int y;
    }

    [Game, Unique, Event(false)]
    public sealed class PauseComponent : IComponent {

    }

    [Game, Unique]
    [Event(false)]
    public sealed class SkipComponent : IComponent {
    }

    [Input]
    public sealed class InputComponent : IComponent {
    }
}
```

** here is Preferences.properties:**
Jenny.Ignore.Keys = 
Jenny.SearchPaths = Jenny\Plugins\DesperateDevs, \
                    Jenny\Plugins\Entitas, \
                    Jenny\Plugins\Entitas.Roslyn, \
                    Libraries

Jenny.Plugins = DesperateDevs.CodeGeneration.Plugins, \
                DesperateDevs.CodeGeneration.Unity.Plugins, \
                Entitas.CodeGeneration.Plugins, \
                Entitas.VisualDebugging.CodeGeneration.Plugins, \
                Entitas.Roslyn.CodeGeneration.Plugins

Jenny.PreProcessors = DesperateDevs.CodeGeneration.Plugins.ValidateProjectPathPreProcessor, \
                      DesperateDevs.CodeGeneration.Plugins.TargetFrameworkProfilePreProcessor

Jenny.DataProviders = Entitas.CodeGeneration.Plugins.ContextDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider, \
                      Entitas.CodeGeneration.Plugins.ComponentDataProvider, \
                      Entitas.CodeGeneration.Plugins.EntityIndexDataProvider

Jenny.CodeGenerators = Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentLookupGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextAttributeGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextMatcherGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextsGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityIndexGenerator, \
                       Entitas.CodeGeneration.Plugins.EventEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenerComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenertInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemsGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator

Jenny.PostProcessors = DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor

Jenny.Server.Port = 3333
Jenny.Client.Host = localhost
DesperateDevs.CodeGeneration.Plugins.ProjectPath = EntitasApp.csproj
Entitas.CodeGeneration.Plugins.Contexts = Game, \
                                          Input

Entitas.CodeGeneration.Plugins.IgnoreNamespaces = true
DesperateDevs.CodeGeneration.Plugins.TargetDirectory = EntitasApp/Sources
Entitas.CodeGeneration.Plugins.Assemblies = bin/Debug/netcoreapp2.0/EntitasApp.dll

Cheers

**Comment by StormRene** [comment]
What I'm seeing is: `DesperateDevs.CodeGeneration.Unity.Plugins` in `Jenny.Plugins`. That shouldn't work without Unity.
