### ISSUE TITLE
Unique Entity In Entitas

### ISSUE THREAD

**Issue by qkhuyit** [sschmid/Entitas-CSharp#664]
How to create Unique Entity in entitas ~ Unique Component

**Comment by Aslan85** [comment]
Add [Unique] before the declaration of your class.
You need to declare「using Entitas.CodeGeneration.Attributes;」

```
using Entitas;
using Entitas.CodeGeneration.Attributes;

[Unique]
public sealed class ScoreComponent : IComponent
{
    public int value;
}
```
