### ISSUE TITLE
Hi all, how to resolve component dependencies?

### ISSUE THREAD

**Issue by nomadfighter** [sschmid/Entitas-CSharp#665]
Hi,  this is my simple sample code

```csharp
using Entitas;

public sealed class ViewComponent : IComponent {
    // ....
}

public sealed class PositionComponent : IComponent {
}

public class LoadViewSystem : ReactiveSystem {
     // balabala...
     void LoadView() { // aysnc load asset
    }
}

var entity = CreateEntity();
entity.AddView(...);
entity.AddPosition(0,2,0); // problem here: entity position is (0,2,0), but entity's gameObject postion is
                             //(0,0,0), because when add position ,the gameObject is not load complete

// solution 1:
public sealed class LoadComplete : IComponent  {}
public class LoadCompleteSystem : ReactiveSystem {
      // has load complete
      void Execute() {
          if (e.hasPosition) e.ReplacePosition(e.position.x, e.position.y, e.position.z);
          // check other component
          // e.g.
          if (e.hasWeapon) e.ReplaceWeapon(...);
          if (e.hasEffect) e.ReplaceEffect(...);
          // ......
          // so terrible!!!
      }
}
```
Any suggestions?
Thanks

**Comment by StormRene** [comment]
I don't get your problem? Is it for you terrible to Replace all in one system? You could split it into different systems and add it under one feature. Something like a `LoadCompleteFeature` and `LoadCompleteReplacePositionSystem` etc.

**Comment by TheHacky** [comment]
It is a little bit difficult to give you an answer because we don't know your whole system.
But in most cases, Rene approach will be a good one. Another one is to capsulate gameObject instantiation from asset creation. So, first of all, create your gameObject and in features afterwards load the assets. Each for every component.

**Comment by FNGgames** [comment]
This might not be suitable for you, but the way i do this is to defer the entity setup to a script on the gameobject e.g. IConfig. If I want an asset i only need to know its name. I call `_context.CreateEntity().AddAsset("MyAssetName");`. This send the entity through my LoadAssetSystem.

In `LoadAssetSystem` I call IViewService.LoadAsset(name) - in my implementation of this, I look for IConfig on the gameobject and call `IConfig.Configure(IEntity e)`. When it's all configured I do `entity.isAssetLoaded = true;`

**Comment by nomadfighter** [comment]
thanks all , I used @StormRene solution
