### ISSUE TITLE
[Question] How to handle multiple games in same project?

### ISSUE THREAD

**Issue by dharmeshinitfusion** [sschmid/Entitas-CSharp#666]
Hi,

I am working on casino game which has around 3 to 4 games in the same project. And I want to use Entitas for my game. so I am a little bit confused how to use Entitas with the big game. In my game, there is an individual scene for each game. So my questions are how to handle multiple contexts? What happens when I switch scene?  how to restart InitializeSystem? Should I create multiple contexts for each game? eg. poker, blackjack.

Thanks.

**Comment by StormRene** [comment]
You could create a context for every individual game and a context for application. Like a top-level context. 
When switching the scene you could clean up the individual context of the game. I would control the scene change with entitas systems in the top-level context. So everything is prepared. Don't forget you can use `ITeardown` as a counter part to `IInitialize`.

**Comment by dharmeshinitfusion** [comment]
Can you please explain how to clean up the context. and how to use `ITeardown` and `IInitialize`.
Sorry, I am new to Entitas.

**Comment by StormRene** [comment]
https://github.com/sschmid/Entitas-CSharp/wiki/Systems
https://github.com/mzaks/EntitasCookBook/blob/master/chapters/1_ingredients/107_system.md
The Context can be resetted via the Method `context.Reset()` do clean all current entities if you don't need the data anymore.

**Comment by dharmeshinitfusion** [comment]
Thank you so much @StormRene. I will try with your solution...

**Comment by StormRene** [comment]
You are welcome 👍
