### ISSUE TITLE
code generation failed when component names duplicated

### ISSUE THREAD

**Issue by forsakenyang** [sschmid/Entitas-CSharp#668]
Hi,

I found that when I create two indexed components with same name in different namespaces, the code generator goes wrong:

```csharp
namespace DunkHeroes.Inputs.Components
{
    using Entitas;
    using Entitas.CodeGeneration.Attributes;

    [Input]
    public class PlayerIndexComponent : IComponent
    {
        [EntityIndex]
        public int value;
    }
}

namespace DunkHeroes.Game.Components
{
    using Entitas;
    using Entitas.CodeGeneration.Attributes;

    [Game]
    public class PlayerIndexComponent : IComponent
    {
        [PrimaryEntityIndex]
        public int value;
    }
}
```
![20180331213642](https://user-images.githubusercontent.com/2673696/38163858-7f58a162-352d-11e8-9fd9-1fd9e2145165.png)

PS:My Entitas version is 1.4.2

Cheers

**Comment by c0ffeeartc** [comment]
Hi,
Added your components code to project, generated result:
```
public partial class Contexts {

    public const string DunkHeroesGameComponentsPlayerIndex = "DunkHeroesGameComponentsPlayerIndex";
    public const string DunkHeroesInputsComponentsPlayerIndex = "DunkHeroesInputsComponentsPlayerIndex";

```
No compilation errors.
`Ignore Namespaces` is set to `false` in Entitas 1.4.2 preferences.
Generated by Unity generator(not jenny)

**Comment by forsakenyang** [comment]
thanks @c0ffeeartc ,after set ``Ignore Namespaces`` to ``false`` all errors are gone.

And then I get lots of loooong name components :(

Can I have it both ways?

**Comment by c0ffeeartc** [comment]
That's current solution. If you have better ideas propose it in new issue, @sschmid may take it or ask to write your own generator.

I don't use namespaces for components, and when name collision happens just come up with another name

**Comment by sschmid** [comment]
If you have classes with the same name, you have to use namespaces. If you use namespaces, the code generator must respect them and prefix all components. You have to choice by setting `Ignore Namespaces` in the Entitas preferences.
Personally, I only use namespaces for libraries. I don't use any namespace for the game logic
