### ISSUE TITLE
NullReferenceException in ContextObserverBehaviour.OnDestroy

### ISSUE THREAD

**Issue by ChessMax** [sschmid/Entitas-CSharp#671]
Hi,

Sometimes I have an error in the Unity console: 

> NullReferenceException: Object reference not set to an instance of an object
Entitas.VisualDebugging.Unity.ContextObserverBehaviour.OnDestroy () (at <26f6c548d34b4706bc95f64ea927764f>:0)

Usually it happens after switching from Unity to IDE or vice versa in play mode. And then nothing is working at all and I need to restart the game(. Unity version 2017.3.1f1, Entitas - 1.4.2. OS: Win10.

Cheers

**Comment by surferau** [comment]
If you update the game code while unity is in play mode then this is a normal behavior and not only with entitas.

**Comment by ChessMax** [comment]
So, the problem is code recompilation . Thanks.
