### ISSUE TITLE
[Issue] Jenny Generator error with new update

### ISSUE THREAD

**Issue by Cosmik11** [sschmid/Entitas-CSharp#672]
The new Entitas update 1.5.0 is giving me an error when I try to generate it reads as follows: "Jenny is configured to work only with the standalone code generator!". Generating with Entitas 1.4.2 causes no error. Why?

**Comment by sschmid** [comment]
As mentioned in the release notes, there's a new `EnsureStandalonePreProcessor` which will throw when generating in Unity. If you don't like this behaviour, you can disable it

**Comment by Cosmik11** [comment]
I apologize for not reading the notes Thank you

**Comment by sschmid** [comment]
No problem at all :)
