### ISSUE TITLE
Help Meeeeeee =.= 

### ISSUE THREAD

**Issue by qkhuyit** [sschmid/Entitas-CSharp#675]
> ContextStillHasRetainedEntitiesException: 'Battle' detected retained entities although all entities got destroyed!
Did you release all entities? Try calling systems.ClearReactiveSystems()before calling context.DestroyAllEntities() to avoid memory leaks.
Entity_1(*3)() - EntityLink(duongqua(Clone)), EntityLink(spirit(Clone)), Collector(Group(AllOf(Position)))
Entity_2(*3)() - EntityLink(thieulam(Clone)), EntityLink(spirit(Clone)), Collector(Group(AllOf(Position)))
Entity_3(*3)() - EntityLink(kimmaosuvuong(Clone)), EntityLink(spirit(Clone)), Collector(Group(AllOf(Position)))
Entity_4(*3)() - EntityLink(kimmaosuvuong(Clone)), EntityLink(spirit(Clone)), Collector(Group(AllOf(Position)))
Entity_5(*3)() - EntityLink(tieulongnu(Clone)), EntityLink(spirit(Clone)), Collector(Group(AllOf(Position)))
Entity_6(*3)() - EntityLink(hutruc(Clone)), EntityLink(spirit(Clone)), Collector(Group(AllOf(Position)))
Entitas.Context`1[TEntity].DestroyAllEntities ()
B18.B18Manager.EndBattle () (at Assets/Sources/B18Manager.cs:118)
B18.Battle.Manager.BattleManager._Close () (at Assets/Sources/Battle/Manager/BattleManager.cs:92)
B18.Battle.Behaviour.LoserController.OnPointerDown (UnityEngine.EventSystems.PointerEventData eventData) (at Assets/Sources/Battle/Behaviour/LoserController.cs:11)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerDownHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:36)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerDownHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at /Users/builduser/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()

My Code:
`_systems.ClearReactiveSystems();
  Contexts.sharedInstance.battle.DestroyAllEntities();`

**Comment by sschmid** [comment]
You should see entities in the hierarchy that are marked with a red entity logo. By selecting them you can see which objects are still retaining them. 
In your case it looks like the views (EntityLink) are still retaining them.

I assume you are using the pattern of `e.isDestroyed = true` in combination with a DestryoEntitySystem.

If so, make sure to destroy all entities like this before calling `battle.DestroyAllEntities();`, otherwise your cleanup systems (e.g. DestroyEntitySystem) won't get the chance to do their job.

**Comment by qkhuyit** [comment]
thank very much
