### ISSUE TITLE
Is it possible to apply getEntitiesWithId functionality on groups?

### ISSUE THREAD

**Issue by surferau** [sschmid/Entitas-CSharp#677]
Say i have

```
e1.isHand = true;
e1.AddBodyId(bodyId);

e2.isLeg = true;
e2.AddBodyId(bodyId);

IGroup legsGroup = _context.GetGroup(GameMatcher.AllOf(GameMatcher.Leg, GameMatcher.bodyId));
```

is there a way to do something like 

`legsGroup .GetEntitiesWithBodyId(10);`

or 

`legsGroup.where(e => e.bodyId.value == 10)`

the we have all legs belonging to bodyId with id 10

the way i do now is using something like 

```
foreach(var leg in legsGroup )
{
   if(leg.bodyId.value == 10)
       legs.Add(leg);
}
```

The other way i tried was
`var legs = _context.GetEntitiesWithBodyId(10).where(e => e.isLeg == true);`

but i got impression it was slower in situation say when there are many body parts but little of them are legs.

Probably something like this will do, but will require cycle over group elements each time

`legsGroup .GetEntities().Where(e => e.bodyId.value == 10)`

Is there a better way?

**Comment by FNGgames** [comment]
You can do this with custom entity indices - @T2RKUS shared his implementation in #351 

This allows queries like "Get (any) X With (specific) Y" or "Get (specific) X with (specific) Y" or "Get (any) X with (specific) Y *and* (specific) Z" etc.

**Comment by surferau** [comment]
Thank you. I will look into it.
