### ISSUE TITLE
DontDrawComponent for known types

### ISSUE THREAD

**Issue by vaudevillian** [sschmid/Entitas-CSharp#678]
Hi,

is there a way to make [DontDrawComponent] work for known type drawers also?
I have a component with a huge list of a generic type that freezes the UnityEditor as soon as the GameObject gets selected, yet I dont really need that information.
I could use a new class with an unknown type drawer, but I would assume that a component with [DontDrawComponent] attribute wont be drawn, regardless of the type drawers. What do you think?

Cheers

**Comment by sschmid** [comment]
Hi,
you're right, [DontDrawComponent] only applies for custom drawers. Sounds like a good idea to make it work for all types.
