### ISSUE TITLE
cant generate component suddenly using Jenny gen

### ISSUE THREAD

**Issue by tonypig1988** [sschmid/Entitas-CSharp#679]
Hi,

Everything is OK before. When I add a sub of contexts named [Battle] in Preferences.Properties.
Then I use Jenny gen.But it cant generate any new component.
Then I create a new project, and install Jenny,copy the scripts.it also dont work.

**Comment by sschmid** [comment]
Hi, can you show me the Preferences.properties?
Also try running `jenny gen -v` to get verbose output so I can see, what is going wrong

**Comment by tonypig1988** [comment]
Jenny.Ignore.Keys = Entitas.CodeGeneration.Plugins.Assemblies
Jenny.SearchPaths = Assets\Entitas\Editor\Plugins\DesperateDevs, \
                    Assets\Entitas\Editor\Plugins\Entitas, \
                    Jenny\Plugins\Entitas.Roslyn

Jenny.Plugins = DesperateDevs.CodeGeneration.Plugins, \
                DesperateDevs.CodeGeneration.Unity.Plugins, \
                Entitas.CodeGeneration.Plugins, \
                Entitas.VisualDebugging.CodeGeneration.Plugins, \
                Entitas.Roslyn.CodeGeneration.Plugins

Jenny.PreProcessors = DesperateDevs.CodeGeneration.Plugins.ValidateProjectPathPreProcessor, \
                      DesperateDevs.CodeGeneration.Plugins.TargetFrameworkProfilePreProcessor

Jenny.DataProviders = Entitas.CodeGeneration.Plugins.ContextDataProvider, \
                      Entitas.CodeGeneration.Plugins.ComponentDataProvider, \
                      Entitas.CodeGeneration.Plugins.EntityIndexDataProvider

Jenny.CodeGenerators = Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentLookupGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextAttributeGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextMatcherGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextsGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityIndexGenerator, \
                       Entitas.CodeGeneration.Plugins.EventEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenerComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenertInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemsGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator

Jenny.PostProcessors = DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor

Jenny.Server.Port = 3333
Jenny.Client.Host = localhost
DesperateDevs.CodeGeneration.Plugins.ProjectPath = TestDemo.CSharp.csproj
Entitas.CodeGeneration.Plugins.Contexts = Game, \
                                          Input

Entitas.CodeGeneration.Plugins.IgnoreNamespaces = false
DesperateDevs.CodeGeneration.Plugins.TargetDirectory = Assets/Sources
Entitas.CodeGeneration.Plugins.Assemblies = Library/ScriptAssemblies/Assembly-CSharp.dll

**Comment by tonypig1988** [comment]
D:\EntitasWork\TestDemo>.\Jenny\Jenny gen
Game\GameComponentsLookup.cs - Entitas.CodeGeneration.Plugins.ComponentLookupGen
erator
Input\InputComponentsLookup.cs - Entitas.CodeGeneration.Plugins.ComponentLookupG
enerator
Game\GameAttribute.cs - Entitas.CodeGeneration.Plugins.ContextAttributeGenerator

Input\InputAttribute.cs - Entitas.CodeGeneration.Plugins.ContextAttributeGenerat
or
Game\GameContext.cs - Entitas.CodeGeneration.Plugins.ContextGenerator
Input\InputContext.cs - Entitas.CodeGeneration.Plugins.ContextGenerator
Game\GameMatcher.cs - Entitas.CodeGeneration.Plugins.ContextMatcherGenerator
Input\InputMatcher.cs - Entitas.CodeGeneration.Plugins.ContextMatcherGenerator
Contexts.cs - Entitas.CodeGeneration.Plugins.ContextsGenerator, Entitas.VisualDe
bugging.CodeGeneration.Plugins.ContextObserverGenerator
Game\GameEntity.cs - Entitas.CodeGeneration.Plugins.EntityGenerator
Input\InputEntity.cs - Entitas.CodeGeneration.Plugins.EntityGenerator
Events\EventSystems.cs - Entitas.CodeGeneration.Plugins.EventSystemsGenerator
Feature.cs - Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerato
r

**Comment by tonypig1988** [comment]
I use Jenny doctor . it say      ?????  No problems detected. Happy coding :)

**Comment by tonypig1988** [comment]
first, I define the Battle context in the properties.but I cant generate BatlleComponent .and then I discovery I cant generate any Component. so I create a new project in unity .and install Entitas.copy the scripsts to new project.and delete Battle context .but I cant generate any component anymore.

**Comment by roygear** [comment]
Be careful about the format and symbol in properties file. It is easy to mess up at beginning. 

To add a new context in properties file, you should have this:
```
Entitas.CodeGeneration.Plugins.Contexts = Game, \
                                          Battle
```

For more safe way, we can use Unity's GUI like this:
![e](https://user-images.githubusercontent.com/30362268/38949752-e7ad86f0-4375-11e8-8885-fc74fb5b8b5c.jpg)

**Comment by tonypig1988** [comment]
I find my mistake .  when I auto import the Roysl is not always 2.    sorry for wasting your time

**Comment by tonypig1988** [comment]
D:\EntitasWork\TestDemo>.\Jenny\Jenny.exe auto-import -s
??  Potential plugin collision: ComponentDataProvider
0: Keep all (no changes)
1: Keep Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider
2: Keep Entitas.CodeGeneration.Plugins.ComponentDataProvider


this time it is 1.

**Comment by roygear** [comment]
yes, always select Roslyn if you are using asset store version

**Comment by sschmid** [comment]
Glad that it works now :)
