### ISSUE TITLE
System Configuration

### ISSUE THREAD

**Issue by npruehs** [sschmid/Entitas-CSharp#68]
Proposing a new feature for configuring Entitas game systems.

Some systems might need some configuration at initialization time - think difficulty level, game speed, mouse sensitivity. A good example is the GameBoardSystem of Match-One:

https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Features/GameBoard/GameBoardSystem.cs

Here, the probability of creating a piece over a blocker (91%) is hard-coded. While in some cases this is quite fine, because these values don't change too often, in other cases designers are forced to tweak these values on an hour-to-hour basis.

Passing systems an initial configuration would allow the game to read this configuration from a text data file (much like blueprints for entities), and reduce turn-around time.

**Comment by kicholen** [comment]
I don't know if this is necessary. You could create entity with settings component (filled with data from server/file) before calling initialization on systems than getting it from pool on Initialize.

**Comment by trumpets** [comment]
That's how I do it currently as well. But I could see how it would be useful :)

**Comment by npruehs** [comment]
Ah interesting, yeah I like that. Thinking about that, settings are no different than entities with components... Actually, I recall Blizzard do it like that in Hearthstone. Thanks for the pointer!

**Comment by sschmid** [comment]
Yes, settings is just data and should be stored in components. If really only needed in the system you could also pass it in as a constructor argument for the system (wouldn't recommend that though)
```
pool.CreateSystem(new GameBoardSystem(spawnChances));
```

Good example @npruehs with the 91% probability. In deed that should not be hardcoded and should be accessed sth like this:
```
if (Random.value < pool.blockerProbability.value) {
    _pool.CreateBlocker(column, row);
}
```
