### ISSUE TITLE
How to implement behavior like StartCoroutine by Entitas?

### ISSUE THREAD

**Issue by lai32290** [sschmid/Entitas-CSharp#681]
Hi there, I'm migrating my game to using Entitas, what I have now is `HitComponent` and my code rule is, when `entity.isHit = true` I need start a coroutine, waiting for 1 second and this coroutine's going to set `entity.isHit = false`.

Since my system is not extending `MonoBehavior`, I can't access `StartCoroutine` function, how can I do this by Entitas way?

**Comment by FNGgames** [comment]
You could try this: 

Give HitComponent a field (float cooldownTime) then do entity.AddHit(cooldownTime). Then have a HitCooldownSystem : IExecuteSystem that iterates through the group of entities with hit components, subtracting the delta time from the timer value. When this hits 0, remove the hit component.

 ```csharp
public class HitComponent : IComponent {
    public float cooldownTime;
}

public class HitCooldownSystem : IExecuteSystem {
    readonly IGroup<GameEntity> _hitGroup;

    public HitCooldownSystem(Contexts contexts) {
        _hitGroup = contexts.game.GetGroup(GameMatcher.Hit);
    }

    public override void Execute() {
        foreach (var e in _hitGroup.GetEntities()) {
            e.ReplaceHit(e.hit.cooldownTime - deltaTime);
            if (e.hit.cooldownTime <= 0) e.RemoveHit();
        }
    }
}

**Comment by FNGgames** [comment]
If you wanted it to be fully general you could have something like 

```csharp
public class DelayedActionComponent : IComponent {
    public int ownerId;
    public float delay;
    public Action<GameEntity> action;
}

// then you could do
e.isHit = true;

var action = _context.CreacteEntity();
action.AddDelayedAction(1, (e) => e.isHit = false);

// then in system
public class HitComponent : IComponent {
   public float cooldownTime;
}
```

then write a DelayedActionSystem that reacts to new delayedActionComponents, decrements their time value like before then when that hits 0 calls the the action you set in the component.

This breaks the "ONLY DATA IN COMPONENTS" rule though, and is a nightmare to serialize, so it's not recommended.

**Comment by lai32290** [comment]
Hi @FNGgames , about your first answer, is this way common been done using Entitas? I already did this way but I just not sure if it's the best/correct way to do.

Thank you so much, you answered my question

**Comment by FNGgames** [comment]
The first way is how I would do it. I think I have something very similar in my game

**Comment by sschmid** [comment]
@lai32290
@FNGgames summarized pretty good (as always ;)) first answer is a very common way to deal with timers and cooldowns.
I'm just commenting to emphasize not to do the 2nd solution. Technically it works, but you would basically hide logic in a component, which you should avoid.
