### ISSUE TITLE
StackOverflowException

### ISSUE THREAD

**Issue by thygrrr** [sschmid/Entitas-CSharp#687]
I get a stackoverflowexception in one of Entitas' typedrawers.

It is unclear what type this even is, the entities are pretty damn simple. It occurs at 80% of the starts.

It is aggravating, because it persists even if local debugging is off.

StackOverflowException
UnityEngine.GUILayoutEntry.ApplyStyleSettings (UnityEngine.GUIStyle style) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/LayoutEntry.cs:63)
UnityEngine.GUILayoutGroup.ApplyStyleSettings (UnityEngine.GUIStyle style) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/LayoutGroup.cs:85)
UnityEngine.GUILayoutEntry.set_style (UnityEngine.GUIStyle value) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/LayoutEntry.cs:27)
UnityEngine.GUILayoutEntry..ctor (System.Single _minWidth, System.Single _maxWidth, System.Single _minHeight, System.Single _maxHeight, UnityEngine.GUIStyle _style) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/LayoutEntry.cs:43)
UnityEngine.GUILayoutGroup..ctor () (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/LayoutGroup.cs:41)
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <cfc149f8218b496788d8493c87de777a>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <cfc149f8218b496788d8493c87de777a>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) (at <cfc149f8218b496788d8493c87de777a>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <cfc149f8218b496788d8493c87de777a>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <cfc149f8218b496788d8493c87de777a>:0)
System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) (at <cfc149f8218b496788d8493c87de777a>:0)
System.Activator.CreateInstance (System.Type type) (at <cfc149f8218b496788d8493c87de777a>:0)
UnityEngine.GUILayoutUtility.CreateGUILayoutGroupInstanceOfType (System.Type LayoutType) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:281)
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs:292)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7787)
UnityEditor.EditorGUILayout.BeginHorizontal (UnityEngine.GUILayoutOption[] options) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:7767)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d47238b754d10f9784b1e>:0)
Entitas.VisualDebugging.Unity.Editor.EntityDrawer.DrawObjectMember (System.Type memberType, System.String memberName, System.Object value, System.Object target, System.Action`2[T1,T2] setValue) (at <1bb29443c31d472<message truncated>

**Comment by thygrrr** [comment]
I suspect this has something to do with the InControl type drawers; probably for PlayerActionSet or InputDevice classes.

**Comment by thygrrr** [comment]
Sorry, super time constrained right now, so this is a somewhat shitty bug report. :)

**Comment by thygrrr** [comment]
I suspect from entities in 2 contexts, game and input, sharing a mutually recursive component called "Binding".

**Comment by thygrrr** [comment]
```
   [Input, Game]
    public sealed class ActionSet : IComponent
    {
        public GamePlayerActionSet value;
    }
    
    [Input, Game]
    public sealed class Controller : IComponent
    {
        [PrimaryEntityIndex] public InputDevice device;
    }


    [Input]
    public sealed class Binding : IComponent
    {
        public GameEntity player;
    }
```

**Comment by sschmid** [comment]
Hi,

Visual Debugging tries to draw components even for custom types. If there is a problem you can either
- use [DontDrawComponent] attribute on the component class to prevent VD from drawing this component
- Implement a custom ITypeDrawe and add your custom draw logic

**Comment by sschmid** [comment]
did this help?

**Comment by sschmid** [comment]
Closed bc inactive
