### ISSUE TITLE
Matcher OnEntityRemoved does not allow accessing components

### ISSUE THREAD

**Issue by npruehs** [sschmid/Entitas-CSharp#69]
Usually, I'd try to use `IReactiveSystems `as much as possible to enforce an event-driven game architecture. However, some systems might require to react to the removal of entities, much like the `ScoreSystem `in Match One:

https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Features/Score/ScoreSystem.cs

However, the `OnEntityRemoved `matcher is triggered after some required components might already have been removed. In another version of the system, I was forced to attach the system to the `OnEntityWillBeDestroyed `event of the pool directly, in order to access relevant component data before it's too late. 

https://github.com/npruehs/Match-One-Blueprints/blob/develop/Source/Assets/Sources/Features/Score/ScoreSystem.cs

Is this the recommended way to design this behaviour? If not, I'd request new matchers for this scenario.

**Comment by trumpets** [comment]
If you want to access the component being removed you can do it by subscribing to the groups removed event which passes the component removed to you.

`pool.GetGroup(Matcher.Score).OnEntityRemoved += (group, entity, componentIndex, component) =>...`

Example here: https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Features/RenderResource/RemoveViewSystem.cs

**Comment by npruehs** [comment]
Nice, thank you! :+1:
