### ISSUE TITLE
How to reset global values when load scene?

### ISSUE THREAD

**Issue by lai32290** [sschmid/Entitas-CSharp#690]
Hi, I created a button to restart my game, but globals are not been reset.

My code is like this:

GameController
```csharp
    private void SetGlobalVars(Contexts contexts)
    {
        contexts.game.SetGlobals(globals);
    }
```

My function to load scene:
```csharp
    public void Restart()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }
```

When the scene has been load, it's printing error in console about some global value is already setted.

How can I reset my Entitas contexts when the scene is load?

**Comment by lai32290** [comment]
Oh, I see, but when I load scene, it’ll not reset entities, is it normal?

**Comment by StormRene** [comment]
Yes it's normal. Take a look at the Contexts in the hierarchy view of unity. They are under the _DontDestroyOnLoad_ Scene - thats a fair hint that the will not be cleared after scene load (although this is just debug view). If you really want to wipe the complete context then you can call the method `context.DestroyAllEntities()`

**Comment by lai32290** [comment]
Why when I use `context.game.DestroyAllEntities()` it's throwing error like this?

```
ContextStillHasRetainedEntitiesException: 'Game' detected retained entities although all entities got destroyed!
Did you release all entities? Try calling systems.ClearReactiveSystems()before calling context.DestroyAllEntities() to avoid memory leaks.
Entity_4(*2)() - Collector(Group(AllOf(Asset, View))), Collector(Group(AllOf(Player, PlayerStatus)))
Entitas.Context`1[TEntity].DestroyAllEntities ()
MainPageController.Restart () (at Assets/Scripts/MainPageController.cs:24)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:165)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:36)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:45)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()
```

But if I remove them one by one, this problem is not happening
```csharp
_contexts.game.GetEntities().ToList().ForEach(e => e.Destroy());
```

**Comment by StormRene** [comment]
This error means that something has at this specific moment a reference to an entity and therefore It couldn't realease it. Is it possible that you are trying to clear the context inside a event listener?

**Comment by lai32290** [comment]
That's weird, because I have a function like this:
```csharp
public void Restart()
{
    _contexts.game.GetEntities().ToList().ForEach(e => e.Destroy());
    SceneManager.LoadScene("Main");
}
```

And this function is being called by UI button directly.

**Comment by StormRene** [comment]
I don't know your whole project, but you can see in the exception which group is getting retained `Collector(Group(AllOf(Asset, View))), Collector(Group(AllOf(Player, PlayerStatus)))`. Do you save somewhere in a MonoBehaviour a reference to a Entity?

**Comment by lai32290** [comment]
Thanks @StormRene ! cleaning reactive systems just fixed my problems!!!
