### ISSUE TITLE
[Issue] Entitas 1.5.2 does not work with unity 2018.1

### ISSUE THREAD

**Issue by Cosmik11** [sschmid/Entitas-CSharp#699]
Hello, recently updated to unity 2018.1 and I believe something is different with the type drawer because although I can still create entities when I click on the entity to view the current attached components or to create a component Unity crashes. In the attached image after clicking the entity with the position component attached unity freezes
![entitaserror2](https://user-images.githubusercontent.com/26536123/39680972-757aeb9c-5174-11e8-8e28-b4c2cbf523ec.png)

Cheers

**Comment by TheHacky** [comment]
Did you have a look into Editor.log?

**Comment by WeslomPo** [comment]
I'am using unity 2018 from start, and it is buggy as hell. It is not Entitas problem. Just wait for patch release.
I have a tested bug with opening properties from Entitas preferences window - after click Unity immediatly falling down. xD. Or when you forget to stop unity and go to IDE and back - it may crash sometimes.

**Comment by sschmid** [comment]
Is this still an issue? I'm using Unity 2018.1 and I'm not experiencing any issues

**Comment by Cosmik11** [comment]
no it is not the crash that was caused was mentioned in #711 so I just modified my custom point struct to avoid the editor crash
