### ISSUE TITLE
How to get started with components and systems

### ISSUE THREAD

**Issue by takaaptech** [sschmid/Entitas-CSharp#7]
Hi,
I am studying Entitas-CSharp via Match-One example. I can understand almost class but i can not understand how to create classes, step by step.
For now i just understand that components class should be create and generated first, but can not understand how to create system and then link them together with game controller?
Could you please take some notes to describe process to create classes, step by step? I mean how to create a skeleton of project.
Thank so much for awesome framework! (Sorry for my bad of english)

**Comment by sschmid** [comment]
Hi, I will add some more documentation soon. Usually when you want to add a new feature, you
- create components (e.g. [PositionComponent](https://github.com/sschmid/Entitas-CSharp-Example/blob/master/Assets/Sources/Features/Move/PositionComponent.cs) and [MoveComponent](https://github.com/sschmid/Entitas-CSharp-Example/blob/master/Assets/Sources/Features/Move/MoveComponent.cs)).

Afterwards you want to
- [use the CodeGenerator](https://github.com/sschmid/Entitas-CSharp/wiki/Generate-your-first-component) to enjoy a more readable and natural api.

Next, you might want to
- implement a system which is modifying some data, e.g [MoveSystem](https://github.com/sschmid/Entitas-CSharp-Example/blob/master/Assets/Sources/Features/Move/MoveSystem.cs).

Next, you could
- create a MonoBehaviour as an entrypoint to the game, where you start and execute your systems in `Start` and `Update` (see [GameController](https://github.com/sschmid/Entitas-CSharp-Example/blob/master/Assets/Scripts/GameController.cs))

Hope that helps!

**Comment by takaaptech** [comment]
Thank you so much! I can follow now.
