### ISSUE TITLE
Handling component properties, not only fields

### ISSUE THREAD

**Issue by Roms6** [sschmid/Entitas-CSharp#70]
Hello,

First I want to say I really enjoy Entitas, and the efforts you put in easing coding in Unity :)

I noticed that the CodeGen isn't handling component properties actually, only fields. Could this case be handled? It would be very convenient, I'm using NoesisGUI and the XAML bindings require properties.

**Comment by sschmid** [comment]
Hi, I'm glad you like it :)
The reason I removed support for properties is because you can actually hide logic in getters and setters. Components represent data only and properties could indicate sth else.
What is your use-case with NoesisGUI? Can that be solved differently?

**Comment by Roms6** [comment]
Well, my current use is implementing a group of entities as a DependencyProperty. Let's say those entities are Countries. This way in my xaml file, I can easily call the DependencyProperty as an ItemsSource named Countries. I couldn't fill a ListBox more easily, let's say I want to show country names, I just need a {Binding country.Tag} (country being a CountryComponent and Tag the Property) set in a DataTemplate. If I want to show more data, I just need more bindings like this one.

For now I can see two other ways to achieve this. Due to the nature of Entitas (it's reactive), I could handle adding/updating/removing myself, that means way more lines of C# code and avoiding the binding feature. Also I could create a data Model that would mimic my components structure, except fields would be properties this time. To sum it up, it can be solved differently but it's far from convenient.

I understand why you're enforcing this rule, but a guideline should be enough, don't you think ? :)

**Comment by BrightBlueFlame** [comment]
You could always create a separate interface with your properties defined then refer to the component by that interface if you wanted.

**Comment by sschmid** [comment]
I'll reenable support for properties in the next version

**Comment by sschmid** [comment]
@Roms6 Read-Write properties are now supported in [Entitas 0.29.0](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.29.0)

Please let me know if it works for you now.

**Comment by Roms6** [comment]
Hey @sschmid, thanks for reenabling this feature. I just made a quick test, and it seems the CodeGenerator is behaving the same way : properties are just ignored. I made a simple TestComponent with a string property (fully declared, not an auto-property).

**Comment by sschmid** [comment]
My bad... I saw the TypeReflectionProvider is not updated yet... sorry :) I'll update it!

**Comment by sschmid** [comment]
I fixed it. Here are the zip files, so you don't have to wait for the next release ;)
[Entitas-CSharp.zip](https://github.com/sschmid/Entitas-CSharp/files/160570/Entitas-CSharp.zip)
[Entitas-Unity.zip](https://github.com/sschmid/Entitas-CSharp/files/160571/Entitas-Unity.zip)

**Comment by Roms6** [comment]
It works like a charm. Thank you very much :)

**Comment by sschmid** [comment]
Awesome! You're welcome :)

**Comment by Roms6** [comment]
I just noticed we can't visualize / edit component properties through the Unity Editor. But I guess that's more a matter of finishing making Entitas "friendly" towards component properties.

**Comment by sschmid** [comment]
You are right. I will reopen this issue to remind to fix that.

**Comment by sschmid** [comment]
Hey! Should work now in [release 0.29.1](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.29.1)

Updated VisualDebugging and CodeGenerator

**Comment by Roms6** [comment]
Thank you, I just updated it and everything seems perfect :)
