### ISSUE TITLE
High level view for Interested people

### ISSUE THREAD

**Issue by aammfe** [sschmid/Entitas-CSharp#700]
Hello,
 
I'm very interested in buying your asset from mega sale and want to use it in a project that is due next month. however I need a high level view of how i should approach my project from architecture/organisational point of view including using all of your new features such as job system.
I'm building a color by number app which will have 3 main views
1- gallery view which will show thumbnails of each art, where each art will have thumbnail, title, description, whether its favourite or not, created by current user or someone else, ratings, views (like a youtube video s list when we search)
2- selecting that thumbnail will open the coloring view, where we draw grid of ugui images with TMPRO text in each image based on 2d array reperesentation of each sketch, all of these images will belong to some color groups, each image will have is colored state, and so on
3- third view will b more like combination of both but will b used in a multiplayer way where users will join a contentst and try to complete early to win that contest

we will also have smaller views like share artwork, leaderboards, authentication etc

I'd really appreciate if you could give me a high level view of architecture, how many systems, contexts and wht components should i be using etc. I
Thanks

**Comment by StormRene** [comment]
Don't get me wrong, but your request seems like you need someone to take on the task of an architect for your future project. Sounds like paid work to me. Have you already looked at all the resources here in the community? I am sure the community can help you with specific questions about your implementation ideas. Do you already have experience with ECS and already a rough idea? Here you can find more information and inspiration:
- https://github.com/sschmid/Entitas-CSharp/wiki/How-I-build-games-with-Entitas-%28FNGGames%29
- https://github.com/sschmid/Entitas-CSharp/issues/610

**Comment by sschmid** [comment]
A very high level summary would be:
- All data is in components (e.g. imagePath, title, description, position)
- All logic is in systems (e.g. ShowSelectedThumbnailSystem, RatingSystem)
- Components can be added to entities in any combination
- Entities are created, managed and destroyed by a context
- I recommend starting with a one context for the app, e.g. GameContext, and one for input, InputContext

[Match One](https://github.com/sschmid/Match-One) is a good starting point.
The links provided by @StormRene are a good to learn more.
The videos on the [Desperate Devs] YouTube Channel should help, too
https://www.youtube.com/desperatedevs

**Comment by aammfe** [comment]
Thank you very much, i decided to build a small matching game like project from a learning point of view, will ask questions related to it in future.
