### ISSUE TITLE
Q: Future development direction

### ISSUE THREAD

**Issue by c0ffeeartc** [sschmid/Entitas-CSharp#701]
Currently Entitas places itself as a game architecture framework, and I think it could be used for all kinds of software. More particularly I want for one app to have multiple Entitas environments, sandboxed from each other (could be even different versions), but open for extension. And looks like it's only few steps away from doing it but doesn't.

What's the broad view and next dev steps? Has Entitas finished what it was supposed to do? Public roadmap would be great to follow

**Comment by TheHacky** [comment]
For a roadmap have a look at https://waffle.io/sschmid/Entitas-CSharp

**Comment by c0ffeeartc** [comment]
Well, that's somewhat alternative look at github issues. Here is bolt's roadmap for example [link](https://support.ludiq.io/communities/5/topics/392-roadmap), it has features per version, research and few other sections.
There was something similar in this repository issues, most features were finished time ago

**Comment by sschmid** [comment]
I'm using Entitas on a daily basis. Personally, there's nothing missing for me atm. There is no roadmap other than if you guys come up with features and requests. I have nothing big planned atm but I'm open for improvements!

**Comment by c0ffeeartc** [comment]
Ok, so submitting feature suggestions and pull requests is the way to go.
