### ISSUE TITLE
About component inherit.

### ISSUE THREAD

**Issue by Hersenberg** [sschmid/Entitas-CSharp#703]
Hi,

I have an  question want to contribute.

How clould the component inherit other component, Is it allowed?

**Comment by buihuuloc** [comment]
Yes, It is allowed to do so.
The properties of the component will come from both inheritance component and itself.

```c#


[Game ]
public class  TriggerComponent : IComponent, IBehaviourTrigger {
   public ITrigger trigger;
}
[Game]
public class OnHitTrigger: TriggerComponent {
}
```
You can do something like that

**Comment by c0ffeeartc** [comment]
Additional info generator skips abstract classes, could be useful somewhere
