### ISSUE TITLE
Example Mini Project that covers everything "How-I-build-games-with-Entitas"

### ISSUE THREAD

**Issue by kenofori** [sschmid/Entitas-CSharp#705]
Hi,

I went through  "How-I-build-games-with-Entitas" and its simply awesome, however someone very new to system should really love to take a working mini game project source to understand further. 

So any plans to upgrade Match One game to follow "How-I-build-games-with-Entitas" strategy?

Cheers

**Comment by FNGgames** [comment]
Match-one is following most of the principles I follow. Maybe we could use a slightly more complex example project, but I doubt I'll have much time to make that to the quality it would need to be.

**Comment by kenofori** [comment]
@FNGgames Thank you for your reply, ill definately check this project in detail and ask here to adopt according to your given guide.

Can you please also look at following issue, and advise me how should handle it in an entitas based application where one seperate scene will b doing just that minimal functionality, how should i be using entitas there?
https://github.com/sschmid/Entitas-CSharp/issues/702

Thanks
