### ISSUE TITLE
How to reset the PrimaryEntityIndex?

### ISSUE THREAD

**Issue by SmilingDumbass** [sschmid/Entitas-CSharp#707]
Hi,

I have question want to contribute.

In my game battaleScene, I created PlayerEntity and use PrimaryEntityIndex IDComponent for find them.
But when i want to go the battleScene and Init it again, EntityIndexException told me 
:"EntityIndexException: Entity for key '1' already exists!
Only one entity for a primary key is allowed.".

So how to reset the PrimaryEntityIndex? Or other ways to solve the question?

Sorry for my english is so bad XD, Cheers

**Comment by TheHacky** [comment]
I think there is no reset method for PrimaryEntityIndex, but if you destroy the entity or remove the component the index will be free again. So, be careful to destroy all unneeded entities or remove all unneeded components, especially when (re-)loading a scene.

**Comment by rglobig** [comment]
If your id component is based on the creationIndex you can of course also reset it via the context. The problem you describe, however, is that the scene, i.e. the view, has already been destroyed and reloaded, but the context does not reflect this at all and your logic is based on it. The best thing to do would be to clean up the context first to the state you need and only then to unload and reload the scene.
