### ISSUE TITLE
MissingReferenceException occurs occasionally when stopping game

### ISSUE THREAD

**Issue by SvDvorak** [sschmid/Entitas-CSharp#71]
About 20% of the time I stop the game in the editor I get a MissingReferenceException occurring in VisualDebugging. I created a new project and an empty scene with only a camera with the code in the following gist attached and I still get the error. Try playing and stopping over and over again and you should be able to reproduce it.
https://gist.github.com/SvDvorak/a15926de8c4f8f519498

**Comment by sschmid** [comment]
Ok, thanks. I think I saw that one, too. It won't break anything, but I guess it's annoying :)
I'll take a look at it

**Comment by SvDvorak** [comment]
I've had it for a while and it got a bit too annoying, especially when you have other errors it just becomes noise. Thanks!

**Comment by sschmid** [comment]
I changed a few things in [Entitas 0.29.0](https://github.com/sschmid/Entitas-CSharp/releases/tag/0.29.0)
Let me know if it fixes your issue, otherwise I'll finally add if null check :)

**Comment by JamesMcMahon** [comment]
I haven't seen this in awhile but I didn't really see it in my project when I started it under 0.28.2. I used to see it all the time when working on my [example project](https://github.com/JamesMcMahon/entitas-2d-roguelike).

I do plan to upgrading that project when I get a block of time but it probably won't be for at least a month.

**Comment by trumpets** [comment]
Still happening for me on 0.29.1. Also while exploring the Entities in Pools in the scene hierarchy I get the occasional TreeView exception.

**Comment by sschmid** [comment]
Just fixed it. Will be in the next release. Happy coding! :)
