### ISSUE TITLE
Match-Line Entitas-ECS example in wiki

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#713]
Thanks @RomanZhu for this:
https://github.com/RomanZhu/Match-Line-Entitas-ECS

Reminder to put this in the wiki

**Comment by c0ffeeartc** [comment]
Added.
Feel free to fix/change https://github.com/sschmid/Entitas-CSharp/wiki/Example-projects

**Comment by sschmid** [comment]
Awesome, thanks!
