### ISSUE TITLE
Multiple Event attributes cause error in Rider error analysis

### ISSUE THREAD

**Issue by WeslomPo** [sschmid/Entitas-CSharp#714]
Hi, I have found a strange behaviour. Here are a screenshot.

![image](https://user-images.githubusercontent.com/310008/41019432-aa369b70-696f-11e8-851f-a60745d93a70.png)

```csharp
using Entitas;
using Entitas.CodeGeneration.Attributes;

namespace Ecs.Components.Ui {
	[Ui, Event(true, EventType.Added), Event(true, EventType.Removed)]
	public class SelectedComponent : IComponent { }
}
```

This code makes Rider IDE shows "Duplicate attribute" error . But it will compile in Unity and generate code properly. It is not an inspection and I can't disable it.

And also why there no EventType.AddedOrRemoved type?

**Comment by RomanZhu** [comment]
In my example I have 
```
using Entitas;
using Entitas.CodeGeneration.Attributes;

[Game]
[Event(true, EventType.Added)]
[Event(true, EventType.Removed)]
public sealed class SelectedComponent : IComponent
{
}
```
And it shows no errors in Rider  :c

Try to separate attributes for now

**Comment by WeslomPo** [comment]
![image](https://user-images.githubusercontent.com/310008/41020820-5acdaca8-6975-11e8-956f-9e5160b86966.png)
Same here. Maybe I need to just update Rider...

**Comment by RomanZhu** [comment]
Is that behavior started today? Or it was like that from the beginning

**Comment by WeslomPo** [comment]
Rider updating is not helped here...
I don't know, when it started, I just see it today. Maybe I need to update Entitas (I have 1.5.1)... I try it now.

**Comment by WeslomPo** [comment]
Aha! I was stupid. I update Entitas to 1.5.2 and it is solve my problem. Thanks for help.
