### ISSUE TITLE
Improve Entitas Event API [Event(bool)]

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#717]
Repost from the chat

@rglobig 
> [...] [Event(true)]  [...]@sschmid do us a favor and make this bool to an enum and give it a meaningful name

Suggestions
- [Event(Bind.Any)] and [Event(Bind.Specific)]

**Comment by VergilGao** [comment]
my opinion:
[Game(hasEvent = false /* as default */ ), Ui(hasEvent = true , bindToEntity = false /* same as Event(false) */)]

**Comment by roygear** [comment]
how about ```[Event(Bind.Any)]``` and ```[Event(Bind.Exact)]```

**Comment by RomanZhu** [comment]
I think about Event and GlobalEvent

**Comment by c0ffeeartc** [comment]
`[Event(Listen.Entity)]`, `[Event(Listen.Group)]`

**Comment by sschmid** [comment]
I will most likely go for

```
[Event(EventTarget.Any)]
```
```
[Event(EventTarget.Entity)]

// or
[Event(EventTarget.Self)]
```
