### ISSUE TITLE
Generator does not work if Entitas is not in Assets folder root

### ISSUE THREAD

**Issue by aaronjbaptiste** [sschmid/Entitas-CSharp#72]
Reproduced in a new Unity Project:

1. Create a folder "Plugins" in Assets
1. Add the Entitas package into Plugins. So the structure looks like:

  Assets/Plugins/Entitas/Enitas
  Assets/Plugins/Entitas/Enitas.CodeGenerator
  Assets/Plugins/Entitas/Enitas.*
1. Create a simple PositionComponent
1. Configure Entitas generated folder as: Assets/Source/Generated/
1. Click Generate

Actual: ComponentIds and Pool are Generated, PositionComponent is not. Moving Entitas into Assets fixes the problem.

**Comment by entitas-ecs** [comment]
This has sth to do with the [Special Folders and Script Compilation Order](http://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html) and [partial classes](https://msdn.microsoft.com/library/wa80x488.aspx)

The generated sources files extent the core files of Entitas making use of the 'partial' keyword. This requires Entitas to be in the same assembly as your source files. Moving Entitas to Plugins will actually result it to end up in Assembly-CSharp-firstpass which means you cannot compile.


Entitas for that matter is no Plugin
> Unity lets you add Plugins to a project to extend the features available to Unity. Plugins are native DLLs that are typically written in C/C++. They can access third party code libraries, system calls and other things that are not provided by Unity out of the box. Plugins must be placed in a folder called Plugins to be detected by Unity and like the Editor folder, this affects the order in which scripts are compiled. See the page on Special Folders and Script Compilation Order for further details.

http://docs.unity3d.com/Manual/SpecialFolders.html

**Comment by sschmid** [comment]
This has sth to do with the [Special Folders and Script Compilation Order](http://docs.unity3d.com/Manual/ScriptCompileOrderFolders.html) and [partial classes](https://msdn.microsoft.com/library/wa80x488.aspx)

The generated sources files extent the core files of Entitas making use of the 'partial' keyword. This requires Entitas to be in the same assembly as your source files. Moving Entitas to Plugins will actually result it to end up in Assembly-CSharp-firstpass which means you cannot compile.


Entitas for that matter is no Plugin
> Unity lets you add Plugins to a project to extend the features available to Unity. Plugins are native DLLs that are typically written in C/C++. They can access third party code libraries, system calls and other things that are not provided by Unity out of the box. Plugins must be placed in a folder called Plugins to be detected by Unity and like the Editor folder, this affects the order in which scripts are compiled. See the page on Special Folders and Script Compilation Order for further details.

http://docs.unity3d.com/Manual/SpecialFolders.html
