### ISSUE TITLE
Roslyn generator generates differently on different machines

### ISSUE THREAD

**Issue by dkozlovtsev** [sschmid/Entitas-CSharp#721]
Hi,

We're using Entitas on two different machines, one is using Rider as IDE and another uses VS with Visual Studio Tools for Unity. VSTU changes project name from default `Assembly-CSharp.csproj` to `%project_name%.csproj`, so the `Preferences.properties` file differs for those two machines in ```DesperateDevs.CodeGeneration.Plugins.ProjectPath =``` line.
There are no other noticeable differences between machines.
For some reason generated code on machines is different
for example for component
```
    public class Health : IComponent
    {
        public float value;
    }
```
VSTU machine generates 
```
public sealed class HealthComponent : Entitas.IComponent {
    public ECSGameplay.Health value;
}
```
and Rider machine doesn't.
It makes impossible to work on a project for 2 and more devs concurrently

**Comment by sschmid** [comment]
Hi,

you can find an empty `*.userproperties` file in your project folder. You can use that to overwrite existing keys in your properties file. 

The idea is to put `*.userproperties` in your gitignore and team members can overwrite settings if necessary.

Hope that help

**Comment by sschmid** [comment]
To overwrite a setting selectively add lines you want to overwrite to your own userproperties

```
DesperateDevs.CodeGeneration.Plugins.ProjectPath = %project_name%.csproj
```

**Comment by dkozlovtsev** [comment]
Hi,
My issue is not with config differences between machines, but with code generated being different on different machines.

**Comment by sschmid** [comment]
The generated code should be the same across all machines. Are you sure, the config is setup correctly for everyone?

**Comment by sschmid** [comment]
The code generator is not aware of the IDE. It doesn't matter which IDE you are using. I have the feeling that the properties file might not be set up correctly.

What is the difference of the generated code?

**Comment by dkozlovtsev** [comment]
The only difference in config is ```DesperateDevs.CodeGeneration.Plugins.ProjectPath =``` line that targets different csproj files depending on whether VS or Rider is used.
The project layout is the same for both machines.

**Comment by dkozlovtsev** [comment]
I can only quote the description form original message in the issue
For some reason generated code on machines is different
for example for component
```
    public class Health : IComponent
    {
        public float value;
    }
```
VSTU machine generates
```
public sealed class HealthComponent : Entitas.IComponent {
    public ECSGameplay.Health value;
}
```

and Rider machine doesn't.

**Comment by sschmid** [comment]
Is that true for all components or just the health component?

**Comment by dkozlovtsev** [comment]
For a lot of components it is, can't confirm that it is true for all of them as there are a lot of them
other examples 
```
    [Game]
    public class AuthEventComponent : IComponent
    {
        public AuthEvent evt;
    }
```
```
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class AuthEventComponent : Entitas.IComponent {
    public ECSGameplay.AuthEventComponent value;
}
```

**Comment by sschmid** [comment]
Please check GeneratedFolder/%ContextName%/Components

and see if this folder has all your components.

I cannot think of a case, where not all components are generated, so I still think the properties is not set up correctly.

To test this, you can delete the properties file on the affected machine, open Entitas Preferences window which will regenerate it, then run `jenny auto-import -s`, double check the project path and see if it works

**Comment by dkozlovtsev** [comment]
[VSMachineLog.txt](https://github.com/sschmid/Entitas-CSharp/files/2097656/VSMachineLog.txt)
[RiderMachineLog.txt](https://github.com/sschmid/Entitas-CSharp/files/2097657/RiderMachineLog.txt)

Verbose logs for code generation on different machines, i will try reseting preferences, but I have to stress that configs are identical with exception of project file path line

**Comment by sschmid** [comment]
The rider log contains "GameHealthComponent.cs", looks good to me.

VS log additionally contains "Components\HealthComponent" which is weird.

This file will be generated, if Health doens't implement `Entitas.IComponent`, so there's sth wrong.

**Comment by sschmid** [comment]
Double check if HealthCompoent implements the proper `IComponent` interface. Components\HealthComponent should not exist

**Comment by dkozlovtsev** [comment]
I've double checked it, all the components do implement `Entitas.IComponent` interface
Can it be that something prevents generator from recognizing it?

**Comment by sschmid** [comment]
I would be interested in a diff of the project files. In the past, VS has already produced different project files which affected the the roslyn parser.

**Comment by dkozlovtsev** [comment]
I'm not comfortable exposing project files to the public, can I send them over to the email or something like that?

**Comment by sschmid** [comment]
Sure, I understand. No need to share the project file. Can you do a local diff, just to see if there are any differences. E.g. in the past, this happened #503

**Comment by dkozlovtsev** [comment]
Yes, I'm having exactly the same problem. One thing though I do have FixTargetFrameworkProfile preprocessor enabled, for some reason it doesn't work, can it be because for me it adds `<TargetFrameworkProfile>Unity Full v3.5</TargetFrameworkProfile>` profile and not the one with `Subset` in it?

When i delete the profile before generation it generates just fine, so at least i have a way of generating correct code on my machine

**Comment by sschmid** [comment]
Ok, I can update the pre processor to support this change

**Comment by dkozlovtsev** [comment]
I'm I correct to assume that this dll replaces the one located in `Jenny\Plugins\DesperateDevs`  ? If so - it didn't work.

**Comment by sschmid** [comment]
If you have selected this plugin in the properties, then yes. If you selected the one in the entitas folder, then replace that one

**Comment by dkozlovtsev** [comment]
I've replaced both %)
Doesn't work

**Comment by sschmid** [comment]
did you restart jenny server?

**Comment by dkozlovtsev** [comment]
I'm using `Jenny gen -a` for my test, i assume it doesn't require any additional actions to reload config when used that way

**Comment by sschmid** [comment]
`-a` ?

**Comment by dkozlovtsev** [comment]
Hmm got this key from older discussion and/or documentation, removing it changes nothing though

**Comment by sschmid** [comment]
:) I remember, `-a` was "keep alive", a feature that has been replaced by jenny server

**Comment by sschmid** [comment]
Please patch the dll in DesperateDevs and Entitas.Roslyn

**Comment by dkozlovtsev** [comment]
New error
```Could not load file or assembly 'file:///C:\UnityProjects\prototypeBolt2\Jenny\P
lugins\Entitas.Roslyn\DesperateDevs.CodeGeneration.Plugins.dll' or one of its de
pendencies. Operation is not supported. (Exception from HRESULT: 0x80131515)```

**Comment by dkozlovtsev** [comment]
nwm windows was blocking code from unknown source
Now the issue is solved

**Comment by sschmid** [comment]
ok great!
