### ISSUE TITLE
Security Exception in Unit testing

### ISSUE THREAD

**Issue by DeusExMachina1993** [sschmid/Entitas-CSharp#724]
Hi,
I tried different unit test environment like (xunit, nspec,...) and getting no success with them. 
when unit test code reaches system.Initialize() the Security Exception will be thrown...
the full message is:

"System.Security.SecurityException was unhandled by user code
  HResult=-2146233078
  Message=ECall methods must be packaged into a system module.
  Source=Assembly-CSharp
  StackTrace:
       at TestSystem.Initialize()
       at test.<>c.<when_making_test>b__0_0() in C:\UnityProject\ConsoleApplication1\ConsoleApplication1\test.cs:line 22
       at NSpec.Domain.Example.Run(nspec nspec)
       at NSpec.Domain.ContextUtils.RunAndHandleException(Action`1 action, nspec instance, Exception& targetException)
  InnerException: "

any solution to fix this?
btw I'm working on windows.

Cheers

**Comment by DeusExMachina1993** [comment]
thanks for the reply,
unblocking Dll didn't help me.
base on this [link ](https://forum.unity.com/threads/security-exception-ecall-methods-must-be-packaged-into-a-system-module.98230/) seems specific unity functions only can call inside the editor.
by adding simple try catch temporary ignore exception but I don't know why it's throwing from the system..

**Comment by roygear** [comment]
I had similar problem about error when reaches system.Initialize().

Some configs set before system.Initialize(), and those configs will be loaded in InitializeSystem.
but the path of configs are changed. The configs cannot be loaded.
So, that cause the unit test's error.

You have to ensure every source read correctly before system.Initialize().
