### ISSUE TITLE
Visual Debugger shows no entity in hierarchy 

### ISSUE THREAD

**Issue by yanjingzhaisun** [sschmid/Entitas-CSharp#725]
Hi,

I have a question about visual debugger and context observer behavior. When I load the scene and let it run, everything is good: Context Observer Behavior shows the information, and we can see different entities under the context. However, if I reload the scene and make sure no error happens, The observer shows normally (shows the information of how many entities left and reusable entities and group/collector information), but no entity can be seen under the context Observer behavior. I believe the entity and information is safe, but I can't debug from this anymore. How could I solve this problem?
![Screenshot](https://s1.ax1x.com/2018/06/18/CxtqsA.png)

Thank you very much!

**Comment by yanjingzhaisun** [comment]
turns out that Context.Reset() will turn off the Observer.

**Comment by sschmid** [comment]
Hi, you're right. I should probably change this.
Currently all events are set to null when resetting which means, the observer is not notified anymore

**Comment by sschmid** [comment]
Updated dll
[Entitas.dll.zip](https://github.com/sschmid/Entitas-CSharp/files/2110451/Entitas.dll.zip)

Reset only call
            DestroyAllEntities();
            ResetCreationIndex();

Added
            RemoveAllEventHandlers


Let me know if that works better

**Comment by yanjingzhaisun** [comment]
Thanks! That did work! I was wondering about if there is a way to add the observer event handler back?

**Comment by sschmid** [comment]
I think that's not needed anymore with the fix.
But here's the method that gets call automatically
https://github.com/sschmid/Match-One/blob/master/Assets/Sources/Generated/Contexts.cs#L93-L100
