### ISSUE TITLE
Q: Setup Unit Testing on MacOS with VSC

### ISSUE THREAD

**Issue by AVAVT** [sschmid/Entitas-CSharp#726]
So I don't have Rider, and mainly work on VSC.

I can setup NSpec Tests project on Xamarin Studio. But I want to find a way to run the test cases in VSC or terminal.

Unfortunately `dotnet run` throw this exception:
`error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed.`

I looked for .NETFramework SDK but they only have the windows version. Is there any way I can run the Tests project outside of an IDE?

**Comment by zhuchun** [comment]
How about mono instead? [Check it out](http://www.mono-project.com/archived/guiderunning_mono_applications/)

**Comment by AVAVT** [comment]
Thanks a lot @zhuchun , it seems like the right direction. The compile part seems to work fine, but I can't run the compiled exe. Do you know why?

```
Apples-MacBook-Pro-2:Tests AVAVT$ csc TestRunner.cs -r:Libraries/NSpec.dll
Microsoft (R) Visual C# Compiler version 2.6.0.62309 (d3f6b8e7)
Copyright (C) Microsoft Corporation. All rights reserved.

Apples-MacBook-Pro-2:Tests AVAVT$ mono TestRunner.exe

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'NSpec, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'NSpec, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'NSpec, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'NSpec, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by AVAVT** [comment]
Oh I'm an idiot. Simon already has a bash file for that. Got it running using msbuild.
