### ISSUE TITLE
Can Jenny Server be used for different projects?

### ISSUE THREAD

**Issue by zhuchun** [sschmid/Entitas-CSharp#736]
Hi, I'm developing both Server-side and Client-side codes, they're 2 different projects. Currently, I have to re-run different Jenny Server bat file in their folder before compile, that's tedious somewhat. Is that possible to run them on different ports, or run either of them and compile anywhere?

**Comment by sschmid** [comment]
Yes, you can specify the port

Starting with Entitas 1.6.1, there is a new setting

<img width="449" alt="jenny-port" src="https://user-images.githubusercontent.com/233700/42203275-8d1032ec-7e9e-11e8-8534-a07a459f8dec.png">

Alternatively, open your properties file and update these keys
```
Jenny.Server.Port = 3333
Jenny.Client.Host = localhost
```

**Comment by zhuchun** [comment]
Cool! Didn't notice there's a new update, this helps a lot, thank you!
