### ISSUE TITLE
MultiReactiveSystem Tutorial question

### ISSUE THREAD

**Issue by moixxsyc** [sschmid/Entitas-CSharp#739]
```csharp
using Entitas;
using UnityEngine;

[Game, Input, Ui]
public class DestroyedComponent : IComponent 
{
}
public interface IDestroyEntity : IEntity, IDestroyed { }
```
Hi, I just don't know why editor says  "IDestroyed" is not define, and I also not find it in interface folder.
I  already generate code after I define "DestroyedComponent"

**Comment by FNGgames** [comment]
Hi @moixxsyc - I wrote that tutorial quite a while ago, and back then the generated interface used to be `I{ComponentName}`, but now it is `I{ComponentName}Entity`.  I have updated the tutorial just now to reflect these changes.

Sorry for the confusion this has caused.

**Comment by moixxsyc** [comment]
@zhuchun  thanks，that help me alot ~

**Comment by moixxsyc** [comment]
@FNGgames  thanks for your help~
