### ISSUE TITLE
Add Testing Examples

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#74]
While I love Entitas and I am thinking of using it for a commercial product but I'm struggling a bit with the best way to write tests against an Entitas project.

It would be great if we had some examples of testing an Entitas based project, either by updating the existing examples with test code or adding new examples.

**Comment by sschmid** [comment]
Great to hear that!
I can provide a detailed example with Unity Test Tools and also with nspec test (used also by Entitas itself) soon. It's already started... I'll keep you updated

**Comment by JamesMcMahon** [comment]
Thanks Simon! I figured you guys were working on this but I wanted to file it under Feature Request because having sane automated testing seems like one of the big advantages of using an ECS.

**Comment by sschmid** [comment]
Hey, I added a new example project. It's in veeery early stages, but it's developed test driven. There are Unity Test Tools tests for the view aswell as nspec tests for the game logic (as used in Entitas itself)

https://github.com/sschmid/Entitas-Shmup

**Comment by sschmid** [comment]
Use `runTests.sh` to run the nspec tests

**Comment by JamesMcMahon** [comment]
Thanks Simon. When I get some time I'll take a look.
