### ISSUE TITLE
Enable [Event] for non components

### ISSUE THREAD

**Issue by TheHacky** [sschmid/Entitas-CSharp#743]
Hi,

I have found a bug in event generation. Generate a component for a ScriptableObject work as intended, but when I add an Event attribute the generation is broken.

Here's a simple example.

```csharp
using Entitas;
using Entitas.CodeGeneration.Attributes;
using UnityEngine;

[Gameplay, Unique, Event(true)]
public class TilesBlueprints : ScriptableObject
{
	public string name = '"";
}
```

Actually, I use Entitas 1.5.2 with external code generation. I can reproduce this issue with 1.7.0.

Best regards,
David

**Comment by sschmid** [comment]
Hi, yes that's true.

Event tags currently only work on components

https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration.Plugins/Entitas.CodeGeneration.Plugins/Component/DataProviders/ComponentDataProvider.cs#L96

I could probably add this to `dataFromNonComponents`, too.

**Comment by TheHacky** [comment]
Hi,

that will be great. :)
