### ISSUE TITLE
hi Why I Can't Setup Entitas in Unity2018.2.0 @ Dear sschmid

### ISSUE THREAD

**Issue by yt09** [sschmid/Entitas-CSharp#748]
Hi,

I have an  have question 

I import 1.7 Entitas in Unity 2018.2.0 and then

when i click auto import button in Preferences panel 

it show " Auto Import will autonmatically find and set all plugins for you ...... Do you want to continue ?"

i click " Continue and Overwrite" but nothing happen ,  i can't Setup Entitas.

i have followed the Installation in wiki . 

what should i do ?

please help me  thank you very much 

Cheers

**Comment by zhuchun** [comment]
Greetings, if you've any problem with the asset, try delete and re-import it again. If it doesn't work for you, take a look at [my post](https://github.com/sschmid/Entitas-CSharp/issues/706), you can setup Entitas for any generic environment, w/o a GUI.

**Comment by yt09** [comment]
i use github release Entitas ,it doesn't have jenny.exe

**Comment by yt09** [comment]
哥们 是中国人嘛 要不用中文

**Comment by zhuchun** [comment]
Yes, but the community is open, in case someone meets/solved your problem, let's keep things in English :)

I hadn't tried the GitHub version, but there're things could stop you getting it works, say compiler error, missing files etc. You can try to import Entitas to an empty project again and see if it works.

**Comment by yt09** [comment]
![default](https://user-images.githubusercontent.com/16026634/42937136-b0601070-8b80-11e8-8c62-e35282a1a2b8.png)
@majorika  when i click continue nothing happen .no comsole logs

**Comment by majorika** [comment]
@yt09 
Oh, there are some issue with Chinese character folder name.
You should change path name to english, for now.

**Comment by VergilGao** [comment]
项目路径建议不要用中文（虽然不知道是不是英文路径造成的影响。

**Comment by yt09** [comment]
ok ! it works, it chinese character path cause this problem

**Comment by yt09** [comment]
thank you everybody!
