### ISSUE TITLE
Editor Bug of System 

### ISSUE THREAD

**Issue by tonypig1988** [sschmid/Entitas-CSharp#749]
Hi,

When I run the game ，and click the Systems in Unity Hierarchy ，then 

![qq 20180720223820](https://user-images.githubusercontent.com/37805284/43008432-aa89985e-8c6d-11e8-8a34-e07cdbe627bd.png)

By the Way，I use the Roslyn

**Comment by VergilGao** [comment]
Tools/Entitas/Preferences
Then just close the new window and everything would be ok.

**Comment by tonypig1988** [comment]
@VergilGao Thanks，it works！
