### ISSUE TITLE
How to use GetEntityLink()?

### ISSUE THREAD

**Issue by LonelyEntity** [sschmid/Entitas-CSharp#752]
Hi,

I have a have question.

I have a collider and I'm trying to find the attached entity. How can I do this.

I tried                

```
var entity = collider.gameObject.GetEntityLink().entity;

```
But this gives null reference exceptions.
Am I doing something wrong?

Cheers

**Comment by roygear** [comment]
you have to setup a link for this gameObject first:
gameObject.Link(entity, context);

take a look this sample project:
https://github.com/sschmid/Match-One/blob/master/Assets/Scripts/Views/View.cs

**Comment by LonelyEntity** [comment]
Thank you! It works perfectly now.
________________________________
