### ISSUE TITLE
entity has all components field, it makes debugging  tired.

### ISSUE THREAD

**Issue by raveneer** [sschmid/Entitas-CSharp#753]
Hi, I'm making a simulation game with entitas.

https://youtu.be/h6PBZ3JCgjM

when I try debug some entity, the debugger shows all components of contexts.

![image](https://user-images.githubusercontent.com/19799411/43356722-0a65cef2-92b1-11e8-823e-9f4398a3db9e.png)

my game has 200 + components with [Game] contexts.

how can I check desired, or only has components?

or suggest debugger, please?

**Comment by nomadfighter** [comment]
I think too many components in one context is too hard to maintenance.
split ur game context to multi contexts?

**Comment by raveneer** [comment]
@nomadfighter 
yes you right.
I'm finding a solution before start refactoring...

**Comment by raveneer** [comment]
@rglobig 
Thank you! 
![image](https://user-images.githubusercontent.com/19799411/43363391-b905bef8-933e-11e8-830f-2cb293bee93e.png)
