### ISSUE TITLE
Code generator works weird

### ISSUE THREAD

**Issue by hurog** [sschmid/Entitas-CSharp#757]
Hi,

I'm playing with Entitas for my new project these days.

At some point, Jenny code generation starts working very weird.
It seems like code generation is fixed at some point... meaning
- Adding new IComponent makes no changes for generated (New generated component file doesn't exist)
- Modifying old IComponent makes no changes for generated code
- Even if I delete ALL IComponents files(also generated component files), Jenny exactly generates the same files of some fixed point.

I think that <**some point**> is after making a change for one component, and it caused compile error.
(Is this relevant? https://github.com/sschmid/Entitas-CSharp/wiki/Code-Generator#fixing-compilation-errors)

How can I fix this?
Or is there a proper <**clean all and re-generate code**> way? (deleting Sources/Generated folder and re-generating didn't work)

Working on Mac OS
Unity version - 2018.2.0f2
Entitas version - 1.7.0

Thanks!

**Comment by hurog** [comment]
Oops, I've ignored the grand rule - '_The project has to compile before you can generate_'

I have unchecked Jenny preprocessor 'warn if compilation errors' flag.
So the problem happens after running code generation with compile errors.

https://github.com/sschmid/Entitas-CSharp/wiki/FAQ#q-how-do-i-regenerate-code-when-there-are-compile-errors

Self closing the issue :)

**Comment by StormRene** [comment]
Jenny can generate with compile errors. The statement in FAQ refers to the free version here in github.

**Comment by hurog** [comment]
Both free and paid version calls the code generator 'Jenny'?
I think that's where I started confusing the two different versions.
Thank you for the information. I might try Asset Store version, too.
