### ISSUE TITLE
Jenny/Roslyn code generation with Unity 2018 takes several minutes

### ISSUE THREAD

**Issue by tony707** [sschmid/Entitas-CSharp#758]
Hi,

I tested the Jenny/Roslyn generation with Unity 5.6, 2017.4 and 2018.2 and it turns out the generation is very long on Unity 2018, the other versions are fine (only takes seconds). The basic code generation also runs fine on all versions.

I ran Jenny.exe auto-import the same way on an empty project on each version. Is there something I need to do to improve the generation performance on 2018 ?

Thanks

**Comment by zhuchun** [comment]
I'm using it with 2018.2.0f2, works fine

**Comment by tony707** [comment]
Just tried it on another computer and it works fine on 2018.2.2. I'll try to find what's happening.

**Comment by sschmid** [comment]
@tony707 did you run `jenny auto-import -s` and choose roslyn, maybe this will solve the issue

**Comment by tony707** [comment]
Yes i did run this command. In fact the generation is working but it takes way too long to complete.

**Comment by sschmid** [comment]
Would you mind sharing your properties file?

**Comment by tony707** [comment]
Here it is: https://pastebin.com/EDYET8rZ

**Comment by tony707** [comment]
Ok I think I found the issue, it looks like my Unity 2018 generated several csproj files for several packages. I used to set my entitas project path to ProjectName.csproj and it worked fine on Unity 5.6 and 2017 but here I have both Assembly-CSharp.csproj and ProjectName.csproj. If I set my project path back to Assembly-CSharp.csproj it works fine.
