### ISSUE TITLE
Entitas-Lang bugs with Code-Generation

### ISSUE THREAD

**Issue by kkohno** [sschmid/Entitas-CSharp#760]
Hi,
I use Entitas-Lang Without unity
and found a bug  with VSCode.

It not correctly generates Contexts.

compAndSys file is in root of project.

compAndSys.entitas:
```csharp
target entitas_csharp
context Game(default),Input 
```
and I have not compiled code with error:
The type `Entitas.Context<ProjectEntity>' does not contain a constructor that takes `3' arguments
(no third parameter at all)

generated ContextClasses.cs:

```csharp
using Entitas;

public sealed partial class GameContext : Context<GameEntity> {

	public GameContext() : base(
		GameComponentsLookup.TotalComponents,
		0,
		new ContextInfo(
			"Game Context",
			GameComponentsLookup.componentNames,
			GameComponentsLookup.componentTypes
		)
	) {}
}
public sealed partial class InputContext : Context<InputEntity> {

	public InputContext() : base(
		InputComponentsLookup.TotalComponents,
		0,
		new ContextInfo(
			"Input Context",
			InputComponentsLookup.componentNames,
			InputComponentsLookup.componentTypes
		)
	) {}
}
```

generated ComponentLookups.cs is empty!
```csharp
using Entitas;
```

**Comment by sschmid** [comment]
Hi, I see you already created an issue here
https://github.com/mzaks/Entitas-Lang

it's maintained by @mzaks so hopefully he will reply
Unfortunately, I cannot help here.

**Comment by kkohno** [comment]
thanks, but it is strange, that this project contains tutorial about entitas-lang and cannot support this))

**Comment by sschmid** [comment]
true, this repo references and showcases tools from other people, too. It might happen that people don't update their code when Entitas is updated. Entitas-Lang is open source and can be maintained by the community and people who use it.

**Comment by kkohno** [comment]
thanks, it seems true, that entitas is updated and entitas-lang is not. I advise you to change the tutorial. For example, while studying Centitas, I relied on the possibility of the entitas-lang and was disappointed
