### ISSUE TITLE
Get the corresponding deletion method（_systems.add()）

### ISSUE THREAD

**Issue by lcals** [sschmid/Entitas-CSharp#761]
hi

I am very confused ,
Which method is the deletion method corresponding to Systems.add(),
  I can't seem to find it.
  
I am using the code and I am sure I will not use it in the future.

```csharp

 _systems = new Feature("Systems")
            .Add(new OpeningAnimation_F(contexts));

```

**Comment by StormRene** [comment]
There is none.

**Comment by zhuchun** [comment]
For general purpose, try to design your system as a reactive system, the overhead of an empty one is acceptable.

For something like "OpeningAnimation", either design it as an initialize system or put it in an empty scene so it could be destroyed. However, I think it's fruitless to make everything in ECS.

**Comment by StormRene** [comment]
Define "everything". I would say the business logic should be completly in ECS.

**Comment by sschmid** [comment]
@lcals 
There is no remove method on systems.
Try to design your systems in a way so they don't do anything if not needed. Alternatively, have a separate parent systems that you can execute differently, e.g. AlwaysOnSystems in Update() vs. OtherSystems only when a certain condition is met

**Comment by zhuchun** [comment]
@StormRene That's off topic ;) But specify to this topic, I probably would not write a system to control animation directly, Event is better.
