### ISSUE TITLE
Getting an exception when trying to create component dynamically

### ISSUE THREAD

**Issue by VirtualMaestro** [sschmid/Entitas-CSharp#766]
Hello Simon,
I have such an issue - when I try to add a component dynamically and property of this component marked as **[PrimaryEntityIndex]** I get this exception: 
"_InvalidCastException: Cannot cast from source type to destination type._" 
(if it is not marked, everything works fine)
Is it the intentional behavior or bug?

```csharp
public sealed class MyComponent : IComponent {
	[PrimaryEntityIndex] 
	public bool value;
}

IComponent component = entity.CreateComponent(componentIndex, ComponentsLookup.componentTypes[componentIndex];
entity.AddComponent(componentIndex, component);
```

Thank you

**Comment by sschmid** [comment]
Hi @VirtualMaestro,

I just tested and everything worked as expected

```csharp
var entity = contexts.game.CreateEntity();
const int componentIndex = GameComponentsLookup.My;
var component = entity.CreateComponent(componentIndex, GameComponentsLookup.componentTypes[componentIndex]);
entity.AddComponent(componentIndex, component);

Console.WriteLine("entity.hasMy: " + entity.hasMy);
```

I couldn't reproduce your issue. Did it work out for you in the meantime?
