### ISSUE TITLE
How can a generated component listener react to a component being removed?

### ISSUE THREAD

**Issue by ethankennerly** [sschmid/Entitas-CSharp#770]
Hi,

I enjoy separating business logic and presentation implementation.

When an instance listens to Entitas Event, I didn't notice an API to react to a component being removed.

I did notice a C# event for when a component is removed from an entity. Yet, if that's the ideal API, why is there an Entitas Event generator when there is already C# event for component changers per entity?

I can imagine the removal scenario complicates destroying entities.

I've worked around not having a removal event by not removing the component and changing a component variable.

Thanks for considering.

Ethan

**Comment by sschmid** [comment]
Hi, both exist

EventType (removed)
https://github.com/sschmid/Entitas-CSharp/blob/develop/Addons/Entitas.CodeGeneration.Attributes/Entitas.CodeGeneration.Attributes/EventAttribute.cs#L24-L26

Entity (OnComponentRemoved)
https://github.com/sschmid/Entitas-CSharp/blob/develop/Entitas/Entitas/Entity/Entity.cs#L18-L21

Hope that helps

**Comment by ethankennerly** [comment]
Thank you for quickly pointing out `EventType.Removed` argument for the event attribute. I hadn't paid attention to that second argument.
