### ISSUE TITLE
The scripts for Event have ceased to be generated after the Entitas update

### ISSUE THREAD

**Issue by BorisovAlexey** [sschmid/Entitas-CSharp#776]
Hi,

Updated Entitas version from 1.5.0 to 1.8.0. Scripts for Event are not generated.

```csharp
using Entitas;
using Entitas.CodeGeneration.Attributes;

namespace DuelMagic
{
    [Game, Event(EventTarget.Any, EventType.Added), Event(EventTarget.Any, EventType.Removed)]
    public sealed class PlayerComponent : IComponent
    {
    }
}
```
Only Game\Components\GamePlayerComponent.cs and Components\PlayerComponent.cs are generated.

[doctor-v.txt](https://github.com/sschmid/Entitas-CSharp/files/2321387/doctor-v.txt)

Cheers

**Comment by sschmid** [comment]
Hi, should actually still work.
Did you update the Entitas folder in Assets + the Jenny folder in the root of your project?

I see the searchPaths look a little bit messy. Can you please try this:
instead of the current paths
```
Jenny.SearchPaths = Assets/Entitas/Editor/Plugins/DesperateDevs, \
                    Assets/Entitas/Editor/Plugins/Entitas, \
                    Assets\Entitas\Editor\Plugins\DesperateDevs, \
                    Assets\Entitas\Editor\Plugins\Entitas, \
                    Jenny\Jenny\Plugins\Entitas.Roslyn, \
                    Assets\Libraries\Entitas\Editor\Plugins\DesperateDevs, \
                    Assets\Libraries\Entitas\Editor\Plugins\Entitas, \
                    Jenny\Plugins\Entitas.Roslyn, \
                    Assets\DesperateDevs\Editor\Plugins, \
                    Assets\Libraries\Entitas\Editor\Plugins, \
                    Assets\Entitas\Editor\Plugins 
```

can you please just set it to 
```
Jenny.SearchPaths = Jenny
```

and then run `jenny auto-import -s`

**Comment by BorisovAlexey** [comment]
Hi, Simon.
I set Jenny.SearchPaths to Jenny

`>Jenny\Jenny.exe set Jenny.SearchPaths Jenny`

then run 

`>Jenny\Jenny.exe auto-import -s`

Dump:
`Jenny.SearchPaths
├── Jenny
├── Jenny\Plugins\DesperateDevs
├── Jenny\Plugins\Entitas
└── Jenny\Plugins\Entitas.Roslyn
Jenny.Plugins
├── DesperateDevs.CodeGeneration.Plugins
├── DesperateDevs.CodeGeneration.Unity.Plugins
├── Entitas.CodeGeneration.Plugins
├── Entitas.VisualDebugging.CodeGeneration.Plugins
└── Entitas.Roslyn.CodeGeneration.Plugins
Jenny.PreProcessors
├── DesperateDevs.CodeGeneration.Plugins.ValidateProjectPathPreProcessor
└── DesperateDevs.CodeGeneration.Plugins.TargetFrameworkProfilePreProcessor
Jenny.DataProviders
├── Entitas.CodeGeneration.Plugins.ContextDataProvider
├── Entitas.Roslyn.CodeGeneration.Plugins.CleanupDataProvider
├── Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider
└── Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider
Jenny.CodeGenerators
├── Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator
├── Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator
├── Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator
├── Entitas.CodeGeneration.Plugins.ComponentGenerator
├── Entitas.CodeGeneration.Plugins.ComponentLookupGenerator
├── Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator
├── Entitas.CodeGeneration.Plugins.ContextAttributeGenerator
├── Entitas.CodeGeneration.Plugins.ContextGenerator
├── Entitas.CodeGeneration.Plugins.ContextMatcherGenerator
├── Entitas.CodeGeneration.Plugins.ContextsGenerator
├── Entitas.CodeGeneration.Plugins.EntityGenerator
├── Entitas.CodeGeneration.Plugins.EntityIndexGenerator
├── Entitas.CodeGeneration.Plugins.EventEntityApiGenerator
├── Entitas.CodeGeneration.Plugins.EventListenerComponentGenerator
├── Entitas.CodeGeneration.Plugins.EventListenertInterfaceGenerator
├── Entitas.CodeGeneration.Plugins.EventSystemGenerator
├── Entitas.CodeGeneration.Plugins.EventSystemsGenerator
├── Entitas.Roslyn.CodeGeneration.Plugins.CleanupSystemGenerator
├── Entitas.Roslyn.CodeGeneration.Plugins.CleanupSystemsGenerator
├── Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator
└── Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator
Jenny.PostProcessors
├── DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor
├── DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor
├── DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor
├── DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor
├── DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor
├── DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor
└── DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor
Jenny.Server.Port
└── 3333
Jenny.Client.Host
└── localhost
DesperateDevs.CodeGeneration.Plugins.ProjectPath
└── DuelMagic.csproj
Entitas.CodeGeneration.Plugins.Contexts
├── Game
└── Input
Entitas.CodeGeneration.Plugins.IgnoreNamespaces
└── false
DesperateDevs.CodeGeneration.Plugins.TargetDirectory
└── Assets/Sources
Jenny.Ignore.Keys`

Doctor: 
[doctor-v-2.txt](https://github.com/sschmid/Entitas-CSharp/files/2325579/doctor-v-2.txt)

But this did not solve the problem( 
For some reason, the generator does not see the Event attribute...

**Comment by sschmid** [comment]
Thanks for the very detailed comment, that helps a lot 👍 
The properties file looks correct to me, I would actually expect it to work.

Since it doesn't, please try this:
`jenny scan`

amongst others, the output should contain those classes

```
...
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventEntityApiGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventListenerComponentGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventListenertInterfaceGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventSystemGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventSystemsGenerator
...
```

Can you check if they are present?

**Comment by BorisovAlexey** [comment]
`
>Jenny\Jenny.exe scan
DesperateDevs.CodeGeneration.Plugins: DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor
DesperateDevs.CodeGeneration.Plugins: DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor
DesperateDevs.CodeGeneration.Plugins: DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor
DesperateDevs.CodeGeneration.Plugins: DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor
DesperateDevs.CodeGeneration.Plugins: DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor
DesperateDevs.CodeGeneration.Plugins: DesperateDevs.CodeGeneration.Plugins.TargetFrameworkProfilePreProcessor
DesperateDevs.CodeGeneration.Plugins: DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor
DesperateDevs.CodeGeneration.Plugins: DesperateDevs.CodeGeneration.Plugins.ValidateProjectPathPreProcessor
DesperateDevs.CodeGeneration.Plugins: DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor
DesperateDevs.CodeGeneration.Unity.Plugins: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogDoctor
DesperateDevs.CodeGeneration.Unity.Plugins: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor
DesperateDevs.CodeGeneration.Unity.Plugins: DesperateDevs.CodeGeneration.Unity.Plugins.WarnIfCompilationErrorsDoctor
DesperateDevs.CodeGeneration.Unity.Plugins: DesperateDevs.CodeGeneration.Unity.Plugins.WarnIfCompilationErrorsPreProcessor
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ComponentDataProvider
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ComponentGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ComponentLookupGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ContextAttributeGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ContextDataProvider
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ContextGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ContextMatcherGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.ContextsGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EntityGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EntityIndexGenerator
**Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventEntityApiGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventListenerComponentGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventListenertInterfaceGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventSystemGenerator
Entitas.CodeGeneration.Plugins: Entitas.CodeGeneration.Plugins.EventSystemsGenerator**
Entitas.Roslyn.CodeGeneration.Plugins: Entitas.Roslyn.CodeGeneration.Plugins.CleanupDataProvider
Entitas.Roslyn.CodeGeneration.Plugins: Entitas.Roslyn.CodeGeneration.Plugins.CleanupSystemGenerator
Entitas.Roslyn.CodeGeneration.Plugins: Entitas.Roslyn.CodeGeneration.Plugins.CleanupSystemsGenerator
Entitas.Roslyn.CodeGeneration.Plugins: Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider
Entitas.Roslyn.CodeGeneration.Plugins: Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider
Entitas.VisualDebugging.CodeGeneration.Plugins: Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator
Entitas.VisualDebugging.CodeGeneration.Plugins: Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator
`
List contains required lines. But i fixed my problem :)
**I removed old *.properties file and *.userproperties file and create new properties files.** 

Thanks, Simon, for the help and the time spent!
