### ISSUE TITLE
Error in jenny-auto-import with build 1.8.2 :  Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information

### ISSUE THREAD

**Issue by Pelmog** [sschmid/Entitas-CSharp#779]
Hi,

I have found a bug.

When running Jenny-Auto-Import on build 1.8.2 the file jenny.properties is created and populated, but when Jenny doctor is run, it fails out.

The error given is 

**Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.**

When I run Jenny doctor with the verbose flag, this is the result below.

I am running Unity 2017.3.1f1 and this is a vanilla new 3d project.

G:\My Documents\Austerlitz 4>Jenny\Jenny.exe gen doctor jenny.properties -v
Loading assemblies from G:\My Documents\Austerlitz 4\Jenny
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Analytics.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Analytics.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.CLI.Utils.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.CLI.Utils.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.CodeGeneration.CodeGenerator.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.CodeGeneration.CodeGenerator.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.CodeGeneration.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.CodeGeneration.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Logging.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Logging.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Logging.Formatters.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Logging.Formatters.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Networking.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Networking.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Serialization.CLI.Utils.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Serialization.CLI.Utils.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Serialization.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Serialization.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Utils.dll
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\DesperateDevs.Utils.dll
Name:Jenny.exe
There are no context policies.
 load: G:\My Documents\Austerlitz 4\Jenny\Jenny.exe
  ? Loading: G:\My Documents\Austerlitz 4\Jenny\Jenny.exe
Generating using jenny.properties
Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Plugins
    ? Resolved: Assets\DesperateDevs\Editor\Plugins\DesperateDevs.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Unity.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Unity.Plugins
    ? Resolved: Assets\DesperateDevs\Editor\Plugins\DesperateDevs.CodeGeneration.Unity.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.CodeGeneration.Plugins
  ? Loading: Entitas.CodeGeneration.Plugins
    ? Resolved: Assets\Entitas\Editor\Plugins\Entitas.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.Roslyn.CodeGeneration.Plugins
  ? Loading: Entitas.Roslyn.CodeGeneration.Plugins
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Entitas.Roslyn.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.VisualDebugging.CodeGeneration.Plugins
  ? Loading: Entitas.VisualDebugging.CodeGeneration.Plugins
    ? Resolved: Assets\Entitas\Editor\Plugins\Entitas.VisualDebugging.CodeGeneration.Plugins.dll
  ? Loading Dependency: Entitas.CodeGeneration.Attributes, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Entitas.CodeGeneration.Attributes.dll
Pre Processing: Validate Project Path (2%)
Pre Processing: Fix Target Framework Profile (5%)
Creating model: Context (8%)
Creating model: Cleanup (11%)
Opening Assembly-CSharp.csproj
  ? Loading Dependency: Microsoft.CodeAnalysis.Features, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  ? Loading Dependency: Microsoft.CodeAnalysis.CSharp.Features, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  ? Loading Dependency: Microsoft.CodeAnalysis.VisualBasic.Features, Version=2.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  ? Loading Dependency: System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\System.Collections.Immutable.dll
  ? Loading Dependency: SQLitePCLRaw.core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1488e028ca7ab535
  ? Loading Dependency: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
**System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Host.Mef.DesktopMefHostServices.get_DefaultServices()
   at DesperateDevs.Roslyn.ProjectParser..ctor(String projectPath)
   at DesperateDevs.Roslyn.CodeGeneration.Plugins.PluginUtil.GetCachedProjectParser(Dictionary`2 objectCache, String projectPath)
   at Entitas.Roslyn.CodeGeneration.Plugins.CleanupDataProvider.GetData()
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.generate(String messagePrefix, IPreProcessor[] preProcessors, IDataProvider[] dataProviders, ICodeGenerator[] codeGenerators, IPostProcessor[] postProcessors)
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.Generate()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.GenerateCommand.run()
   at DesperateDevs.Serialization.CLI.Utils.AbstractPreferencesCommand.Run(CLIProgram program, String[] args)
   at DesperateDevs.CLI.Utils.CLIProgram.runCommand(String[] args)**

**Comment by kompyang** [comment]
I encountered the same problem as you did when using the 1.8.1 version of the unity store. Have you updated the jenny file for 1.8.2, I think you should use the latest store version.

**Comment by Pelmog** [comment]
You, my friend, are a steely eyed missile man.
