### ISSUE TITLE
Matcher.AddedOrRemoved has retain bug ???

### ISSUE THREAD

**Issue by wpp1983** [sschmid/Entitas-CSharp#782]
when I use AddedOrRemoved , end destroy the entity, will have a retain link bug

**Comment by gd2020** [comment]
Can I see your codes using TriggerOnEventMatcherExtension::AddedOrRemoved??

**Comment by sschmid** [comment]
@wpp1983 
> retain link bug

Are you talking about EntityLink?

**Comment by wpp1983** [comment]
sorry ，I found my bug is because that I forget call the DeactivateReactiveSystem()
