### ISSUE TITLE
WriteToFile PostProcessor performance improvement

### ISSUE THREAD

**Issue by CCludts** [sschmid/Entitas-CSharp#789]
Hi,

I wrote a small PostProcessor that replaces `CleanTargetDirectoryPostProcessor` and `WriteToDiskPostProcessor` to improve performance. Generating with jenny gen went from 55s to 12s.
Is it appropriate for me to post it here in the entitas repository (the other postprocessors are in DesperateDevs)?

Cheers

**Comment by sschmid** [comment]
> 55s to 12s

???

Really? Usually it should take 1 or 2 s. Or is this a performance test?

**Comment by sschmid** [comment]
Sure, would be great if you could post it here and explain, what is actually improving the performance

**Comment by CCludts** [comment]
We have a rather large project, roughly 4000components. Most of the time goes into writing to disk unnescessarily, since `CleanTargetDirectoryPostProcessor` does 1 write per file, and then `WriteToDiskPostProcessor` does another write for every file.

The performance gains come:
- cleaning after generating, and only cleaning what is required.
- only writing to the file if it changed

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using DesperateDevs.CodeGeneration;
using DesperateDevs.CodeGeneration.Plugins;
using DesperateDevs.Logging;
using DesperateDevs.Serialization;

namespace BestGenerator {
    public class SmartWriteToFilePostProcessor : IPostProcessor, ICodeGenerationPlugin, IConfigurable {
        public string name => "SmartWriteToFilePostProcessor";

        public int priority => 100;

        public bool runInDryMode => false;

        public Dictionary<string, string> defaultProperties {
            get {
                return _targetDirectoryConfig.defaultProperties;
            }
        }

        public void Configure(Preferences preferences) {
            _targetDirectoryConfig.Configure(preferences);
        }

        public CodeGenFile[] PostProcess(CodeGenFile[] files) {
            var fileNameLookup = new HashSet<string>(files.Select(getPath));

            //-- clean files that no longer exist
            Directory.CreateDirectory(_targetDirectoryConfig.targetDirectory);
            foreach (var fileInfo in new DirectoryInfo(_targetDirectoryConfig.targetDirectory).GetFiles("*.cs", SearchOption.AllDirectories)) {
                if (!fileNameLookup.Contains(fileInfo.FullName)) {
                    try {
                        File.Delete(fileInfo.FullName);
                    } catch {
                        _logger.Error("Could not delete file " + fileInfo);
                    }
                }
            }

            //-- update new/changed files. only write if anything changed
            foreach (var codeGenFile in files) {
                string path = getPath(codeGenFile);
                string directoryName = Path.GetDirectoryName(path);

                Directory.CreateDirectory(directoryName);

                if (!File.Exists(path)) {
                    File.WriteAllText(path, codeGenFile.fileContent);
                } else {
                    int comparison = String.Compare(File.ReadAllText(path), codeGenFile.fileContent, StringComparison.OrdinalIgnoreCase);
                    if (comparison != 0) {  // difference
                        File.WriteAllText(path, codeGenFile.fileContent);
                    }
                }
            }
            return files;
        }

        string getPath(CodeGenFile codeGenFile) {
            return Path.GetFullPath(_targetDirectoryConfig.targetDirectory + Path.DirectorySeparatorChar.ToString() + codeGenFile.fileName);
        }

        private readonly Logger _logger = fabl.GetLogger(typeof(CleanTargetDirectoryPostProcessor));
        private readonly TargetDirectoryConfig _targetDirectoryConfig = new TargetDirectoryConfig();
    }
}
```

**Comment by CCludts** [comment]
I should note that the 10ish seconds that remain come almost exclusively from roslyn recompiling the assembly

**Comment by CCludts** [comment]
Random side-benefit worth mentioning: omnisharp-VSCode freaks out if a large amount of files is changed.
In practice this means you have to restart VSCode after generating with the old approach. With `SmartWriteToFilePostProcessor ` it works all nice

**Comment by roygear** [comment]
That very good for Github version.
How about the difference using `client gen` ?

**Comment by CCludts** [comment]
> That very good for Github version.
> How about the difference using `client gen` ?

We didnt see a significant difference between `client gen` and `gen`

**Comment by CCludts** [comment]
there's a small bug in the code I posted. I updated the comment

`int comparison = String.Compare(File.ReadAllText(path), codeGenFile.fileContent, StringComparison.OrdinalIgnoreCase);`
to 
`int comparison = String.Compare(File.ReadAllText(path), codeGenFile.fileContent, StringComparison.Ordinal);`

**Comment by sschmid** [comment]
@CCludts I'm about to add this soon. Did you make any improvements in the meantime that I should consider adding?

**Comment by CCludts** [comment]
@sschmid nope. still using it exactly as posted :)
