### ISSUE TITLE
uFrame ECS vs Entitas?

### ISSUE THREAD

**Issue by chiuan** [sschmid/Entitas-CSharp#79]
Have someone try both?? what's suggestion?

**Comment by sschmid** [comment]
I tried Entitas - I love it ;)

**Comment by Roms6** [comment]
The latest uFrame ECS beta was promising but the editor still had issues (handlers were not generated sometime, for example). Not to mention it lacks useful features from Entitas : component themselves are not used as states (you REALLY want this DeadComponent to be used to check if an entity isDead, why would you include a boolean in your DeadComponent class?), and we cannot make groups based on excluded components.

The current state of uFrame ECS isn't stable, and it didn't get update for months, while Entitas is actively supported.

**Comment by zyzyxdev** [comment]
What I liked about uFrame is the use of reactive extensions (UniRX) and the event bus.

**Comment by buihuuloc** [comment]
@sschmid Do you have any comparison with Artemis ECS?

**Comment by JamesMcMahon** [comment]
RE: uFrame, everytime I try visual coding, I find myself just wanted to type stuff.

RE: Artemis, AFAIK doesn't have the visual debugging aspect that Entitas has.

My recommendation is to try them out by creating a simple ECS app and see what works for you.

**Comment by buihuuloc** [comment]
@JamesMcMahon
uFrame: me too, I'm not a big fan of drag and drop a code block :baby_chick:
Artemis: My wonder is about the performance.

**Comment by sschmid** [comment]
Feel free to close this issue, if answered

**Comment by chiuan** [comment]
thanks all !
