### ISSUE TITLE
XML documentation

### ISSUE THREAD

**Issue by kkohno** [sschmid/Entitas-CSharp#792]
Why you dont include in builds XML documentation for intellisense? This is simple and effective way to learn entitas.

**Comment by kkohno** [comment]
For example: where i can find documentation for EventAttribute and its parameters?

**Comment by sschmid** [comment]
Yeah I know, that's probably just me being me :) I always look at code and when I see the XML comments I always think I'm a human not a html parser. So I got rid of the tags. The IDE was still able to display documentation help popups - but the I switched from deploying Entitas source code to dlls... Now the docs are gone :( I never updated it.

EventAttribute has no docs yet

**Comment by kkohno** [comment]
I see no problems with it. When you write "///" brfore class or method etc. - IDE automatically add the XML documentation template for this.
If you need to compile the DLL go to Project-> Settings-> Compilation and turn on the XML-Document File checkbox. It will generates you XML documentation file when compiling DLL.
If you have generated XML file in the same directory than DLL, IDE will automatically parse DLL and XML files and you will have Intellisence for DLL. And nothing goes away in documentation in another projects, when you use dlls instead full-flaged codes. It is really very usefull for coding.

**Comment by sschmid** [comment]
> turn on the XML-Document 

Awesome thanks! I remember now

**Comment by AtheosCode** [comment]
for c#  document
 When you write "///" brfore class or method etc. - IDE automatically add the XML documentation template for this.
but the final format is like this
```
///<summary>
/// 
///</summary>
```

**Comment by AtheosCode** [comment]
I found that my Visual Studio can help modify this problem with one click, although annotations with parameters in some methods can not be repaired in detail, but it is enough. I will upload it later.
