### ISSUE TITLE
Check for updates: TlsException: Invalid certificate received from server

### ISSUE THREAD

**Issue by movrajr** [sschmid/Entitas-CSharp#8]
Can't check for updates because Mono doesn't trust the connection.

>TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates)

Explanation:

> That’s probably because you do not trust the site you are connecting to. Note that a default installation of Mono doesn’t trust anyone!
http://www.mono-project.com/docs/faq/security/

Possible solution #-1, actively ignore security concerns:

```C#
ServicePointManager.ServerCertificateValidationCallback = (a, b, c, d) => { return true; };
```

Alternative solutions: http://www.mono-project.com/archived/usingtrustedrootsrespectfully/

**Comment by sschmid** [comment]
Hey! I will look into this. It works fine on a Mac. I'll set up a Windows machine to reproduce and then take a look a the solutions described in your links.

**Comment by sschmid** [comment]
Ok, your solution works fine! Thanks! I'll release a new version soon which will contain your fix.
