### ISSUE TITLE
Proper way to TearDown after tests?

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#80]
While you guys (mostly just Simon :smile: ) are working [test documentation](https://github.com/sschmid/Entitas-CSharp/issues/74), I was wondering if you could field a testing related question for me.

I've got tests for my systems up and running using the built in Unity NUnit library. Most of the time it works great, and I get all greens, but occasional I'll run it and all my tests will go red. 

<img width="523" alt="screen shot 2016-03-07 at 10 03 01 pm" src="https://cloud.githubusercontent.com/assets/916676/13590739/74295234-e4b0-11e5-9fa3-16ec29faf29e.png">

The problem also appears to some entity left over after a previous test or run of the application. **What is the recommend way to setup and tear down Entitas when running tests?**

This test parent class encapsulates what I have been doing so far, as I said it works most of the time but then just breaks occasionally:

```
public abstract class SystemTest<T> : AssertionHelper 
    where T: ISystem, new()
{
    protected ISystem system;
    protected Systems systems;
    protected Pool pool;

    [SetUp] 
    protected virtual void Init()
    { 
        pool = Pools.pool;
        systems = new Systems();
        system = pool.CreateSystem<T>();
        systems.Add(system);
        systems.Initialize();
    }

    [TearDown] 
    protected virtual void Dispose()
    {
        pool.ClearComponentPools();
        pool.ClearGroups();
        systems.ClearReactiveSystems();
        pool.DestroyAllEntities();
        systems = null;
        system = null;
    }
}
```

Any advice?

**Comment by sschmid** [comment]
When unit testing, you shouldn't use Pools.pool, because 1. it's a singleton and 2. It also does VisualDebugging related things.
Instead, create a pool like
```csharp
new Pool(CoreComponentIds.TotalComponents);
```

or, to get better error messages
```csharp
new Pool(CoreComponentIds.TotalComponents, 0, new PoolMetaData("Core", CoreComponentIds.componentNames, null));
```

This way, you don't need a teardown anymore

**Comment by JamesMcMahon** [comment]
That makes sense. Thanks for the answer.

Quick follow up questions:

- Any specific reason to omit the `Type[]` parameter from `new PoolMetaData("Core", CoreComponentIds.componentNames, null);`? It also seems to work with `new PoolMetaData("Core", CoreComponentIds.componentNames, CoreComponentIds.componentTypes);`
- Is there any danger of entities hanging around if I remove the tear down? I assume the garbage collector is going to handle everything. Just double checking.

**Comment by sschmid** [comment]
No, there is no specific reason why 3rd parameter is null, you can (and should) also pass in CoreComponentIds.componentTypes. 

When instantiating a new Pool there is no tear down required and everything will be cleaned up automatically

**Comment by JamesMcMahon** [comment]
Thanks!
