### ISSUE TITLE
Standalone Alplication with Roslyn Generator

### ISSUE THREAD

**Issue by Chompetto** [sschmid/Entitas-CSharp#800]
I recently purchased this from the asset store and was able to generate components inside Unity without any real issues, however I am wanting to run the generator in a standalone application.  
I took a look at EntitiasPure, however I was unable to get it working correctly.  I copied over my Jenny.preferences and redirected it to the new application but it doesnt seem to do anything.  I am given no output so I am unsure what is going wrong without any source code. (On that note, are you planning on releasing the source code for Jenny anytime in the future?)

Any help in pointing in the right direction to would be awesome :)

**Comment by roygear** [comment]
Simon replied about EntitasPure here : https://github.com/sschmid/Entitas-CSharp/issues/706
I suggest information about obsolete should be added to that repository to avoid confusion from new user.

We can run the standalone application via IDE. The process shown in this video : https://www.youtube.com/watch?v=L-18XRTarOM, jump to about 5:00

**Comment by sschmid** [comment]
@Chompetto did you manage to make it work?

**Comment by sschmid** [comment]
@Chompetto feel free to close the issue, if you don't have any further questions
