### ISSUE TITLE
Entities leave group on ReplaceComponent

### ISSUE THREAD

**Issue by dogiordano** [sschmid/Entitas-CSharp#807]
Hi, thank you for this very useful framework.
I started experimenting with this philosophy recently and got stuck on a simple task.

I have a PositionComponent defining a group (of all entities with such component) and a System adding/removing a GameObject view whenever an entity enters/exits this group.
The system does so registering callbacks on the group's OnEntityAdded/OnEntityRemoved;

Now, to move the entity, I replace the PositionComponent, but since "replace" actually destroys and recreates, the entity leaves and re-enters the group, causing the GameObject to be destroyed and re-instantiated.
I am actually pooling the GameObject but even just activating/deactivating has some unnecessary footprint.
Also, I find counter-intuitive that updating a position causes the entity to leave the group of "movable entities".

Studying the source, I couldn't find a clean way to listen only OnEntityUpdated (and no OnEntityAdded/OnEntityRemoved) when the component is being replaced.
Nor a way to avoid the entity leaving it's group.

Can this be done or am I blind to the correct phisolophy?
Thanks in advance for your help.

**Comment by TheHacky** [comment]
Hi,

I would suggest to listen for OnEntityAdded only and define a second Component for destroying. If OnEntityAdded is called, you proof for a view and if there isn't one you add it. You can do adding and destroying with very simple ReactiveSystems.

**Comment by dogiordano** [comment]
What you suggested is actually what I'm currently doing but creating a new component (and system) seemed more like a workaround than the intended way to do such a simple thing.
Searching more on the web I found one of the developer proving me wrong.
Thanks a lot for your answer.
