### ISSUE TITLE
Converting Color without Unity's HSVToRGB Method

### ISSUE THREAD

**Issue by Smartis2812** [sschmid/Entitas-CSharp#81]
I'm currently using Unity 5.2.3f and i got an error with the new Entitas Version 0.29.1.
It occurs in "entitas.unity\visualdebugging\entity\editor\entitydrawer.cs" at Line 319:

`var componentColor = Color.HSVToRGB(hue, 0.7f, 1f);`

The problem will be that my current Unity3D Version doesn't support this method.
I just simply added an static method for this by myself.
But maybe we can mark this, so that Entitas will work out-of-the-box or find another solution.

**Comment by sschmid** [comment]
Can you update Unity?

**Comment by Smartis2812** [comment]
In my case, yes. I won't be stuck.

**Comment by sschmid** [comment]
Unfortunately, Unity's documentation doesn't tell in which this method was added. I could add an #if, but maybe updating Unity is a good idea anyway ;)

**Comment by sschmid** [comment]
You can add this piece of code
```csharp
                    #if (UNITY_5_3)
                    var componentColor = Color.HSVToRGB(hue, 0.7f, 1f);
                    #else
                    var componentColor = Color.grey;
                    #endif
```

If you know a way how I can check if the Unity version is greater that 5.3, let me know. The problem with  #if (UNITY_5_3) is, that it only checks the specific version... That means Color.HSVToRGB would also be deactivated in 5.4 which is not intended

**Comment by grygus** [comment]
For this version of unity just change Color to EditorGUIUtility.HSVToRGB, to check if version is greater you can use Application.unityVersion

**Comment by sschmid** [comment]
It says:
> EditorGUIUtility.HSVToRGB is obsolete. Use Color.HSVToRGB instead

**Comment by grygus** [comment]
This is solution for  5.2.x and versions below.
