### ISSUE TITLE
Please generate differently named interfaces for EventTarget.Self and EventTarget.Any

### ISSUE THREAD

**Issue by FNGgames** [sschmid/Entitas-CSharp#810]
Hi,

I am coming across this more and more, and I'm really struggling to work around it. I have situations where I need both the bound event and the unbound event from a component at the same time.

```csharp
// cant use this because it generates 
// 2x ThingListenerComponent,  2x IThingListener and 2x GameThingEventSystem
[Game, Event(EventTarget.Self), Event(EventTarget.Any)]
public class ThingComponent : IComponent 
{
    public float value;
}
```

Using an attack component as an example: I want to have the attack notify the entity's view that an attack has occured so i can switch its animation state, but i _also_ want to have a blood effect controller sitting around and listening for any attacks so it can spawn in particles, and I want this to be global, not hanging off each entit's view. Can you detect when both of these attributes have been added and add the words Self and Any to the listener components and interfaces and whatnot?

**Comment by AVAVT** [comment]
Why not just leave it as `EventTarget.Any` and in the entity's View put a check `if(entity == gameEntity)`?

**Comment by RealCosmik** [comment]
I have also run into this problem to and I think different names would be very useful

**Comment by MrXo** [comment]
@AVAVT This works but is not very convenient. Would also like to have different names for the event listeners.

**Comment by FNGgames** [comment]
@AVAVT this sortof defeats the purpose of an event-driven system. The point is to only call the method when necessary. In some cases this would lead to thousands of unneccesary method calls.

**Comment by sschmid** [comment]
What do you guys think about removing IListener and replace it with

```csharp
public delegate void OnPosition(Vector3 position);
```

```csharp
listener.AddPositionListener(p => transform.position = p);
```

**Comment by FNGgames** [comment]
I like the IListener approach for the same reasons, it's nice and convenient in the IDE and it's extremely readable, right at the top of the class you can see what it's reacting to. I just want support for both types of listener at the same time - perhaps the more cumbersome naming (Including the word Self/Any for example) could be reserved only for when the CG detects that both types are defined on one component?

**Comment by sschmid** [comment]
Just submitted PR #827

```csharp
[Event(EventTarget.Self), Event(EventTarget.Any)]
public sealed class PositionComponent : IComponent
{
    public Vector3 value;
}
```

will generate `IPositionListener` and `IAnyPositionListener`

```csharp
public void OnAnyPosition(GameEntity entity, Vector3 value)
{
    UnityEngine.Debug.Log(entity.creationIndex + " Position: " + value);
}

public void OnPosition(GameEntity entity, Vector3 value)
{
    UnityEngine.Debug.Log(entity.creationIndex + " Position: " + value);
}
```

**Comment by sschmid** [comment]
Need to update roslyn generator and namespace support. Will be in next release.

**Comment by sschmid** [comment]
Delegates might be more flexible, but currently I also prefer IListener being more explicit.
In order not to break existing code when adding a second event attribute at a later point of time, "Any" will always be prefixed. I think that's a good fit as it describes the intend even more
