### ISSUE TITLE
Why is this result?

### ISSUE THREAD

**Issue by kurobon-jp** [sschmid/Entitas-CSharp#813]
Hi,

This code raises an InvalidOperationException.

I have not deleted the entity.

```csharp
public class NewBehaviourScript : MonoBehaviour
{

    // Use this for initialization
    void Start ()
    {
        var context = Contexts.sharedInstance.game;
        var newEntity = context.CreateEntity ();
        newEntity.AddGameObject (gameObject);

        var entities = context.GetEntitiesWithGameObject (gameObject);
        foreach (var e in entities)// InvalidOperationException: HashSet have been modified while it was iterated over
        {
            e.RemoveGameObject ();
        }
    }
}

[Game]
public class GameObjectComponent : IComponent
{
    [EntityIndex]
    public GameObject gameObject;
}
```

Thanks :)

**Comment by sschmid** [comment]
For performance reasons `context.GetEntitiesWithGameObject` returns the internal hashset used to store the entities. As with many other collections, you cannot modify them while iterating over them. There are 2 recommended options:
1. 
```csharp
var group = context.GetEntitiesWithGameObject(gameObject);
foreach (var e in group.GetEntities()) {
    e.RemoveGameObject();
}
```
This returns a new array which makes it safe to modify the hashset. The array is cached, meaning if you call GetEntities() multiple times without while the group hasn't changed you don't allocate unnecessary memory. However, a new array will be created once the group changes.

2.
```csharp
// instance var
readonly List<GameEntity> _buffer = new List<GameEntity>();

var group = context.GetEntitiesWithGameObject(gameObject);
foreach (var e in group.GetEntities(_buffer))
{
    e.RemoveGameObject();
}
```

This will fill the buffer. Useful if the group is expected to change often. You manage the memory manually with the buffer, avoiding to create many arrays

**Comment by kurobon-jp** [comment]
Thank you for the quick response.
I understood your intentions.
By the way, 
```csharp
var group = context.GetEntitiesWithGameObject(gameObject);
```
Is this function generated automatically?

**Comment by sschmid** [comment]
Yes, because you use `[EntityIndex]`

You can do gameObject - entity relations with EntityLink

**Comment by kurobon-jp** [comment]
To me, the group type looks like a HashSet.
Where are GetEntities() defined?

**Comment by sschmid** [comment]
🤦‍♂️ sorry :) I was somewhere totally different in my head. It's not about groups, it's about the entity index, my bad.

Just use ToArray()
```csharp
var entities = context.GetEntitiesWithGameObject(gameObject);
foreach (var e in entities.ToArray()) {
    e.RemoveGameObject();
}```

**Comment by kurobon-jp** [comment]
This problem was resolved thanks to your support.

**Comment by sschmid** [comment]
Great to hear! You're welcome!
