### ISSUE TITLE
Where are those CodeGenInterfaces?

### ISSUE THREAD

**Issue by zhuchun** [sschmid/Entitas-CSharp#815]
Hi, I want to customize Jenny the code generator and wiki points to `ICodeGeneratorDataProvider`, 
 `ICodeGenerator`, `ICodeGenFilePostProcessor`. However, I can't find them anywhere from the asset store version.

**Comment by sschmid** [comment]
Renamed

`IPreProcessor`
`IDataProvider`
`ICodeGenerator`
`IPostProcessor`

**Comment by zhuchun** [comment]
Thanks. But my IDE still can't find them, would you mind show me the namespace, or do I need to download some files from the repo?

**Comment by sschmid** [comment]
`DesperateDevs.CodeGeneration`

**Comment by sschmid** [comment]
Here are the dependencies
https://github.com/sschmid/Entitas-CSharp/tree/develop/Libraries/Dependencies/DesperateDevs

**Comment by zhuchun** [comment]
Great! I've found them, can't wait to see what I can do 😄 

In Unity, these DLLs are in the Editor folder, so the custom script should be put in an Editor folder as well.
Dependencies should be needed for the pure C# project, I will check it out soon.

**Comment by sschmid** [comment]
Have fun :)
