### ISSUE TITLE
Unity Tutorial Simple Entity View and Movement‘s help

### ISSUE THREAD

**Issue by MkVno2** [sschmid/Entitas-CSharp#817]
![o9 3q kp v p nuy2dm4](https://user-images.githubusercontent.com/44113189/47720805-b760ba00-dc89-11e8-8226-6fb075cac333.png)

![gh a03qwo_ i cg eptv7](https://user-images.githubusercontent.com/44113189/47720655-5f29b800-dc89-11e8-8c7a-a01ec1b3336d.png)

CS0117:	“GameMatcher”isn't contain “Sprite” definition

:thinking:

**Comment by MkVno2** [comment]
And this one
![g 1hh0ozob0s f 9wk4](https://user-images.githubusercontent.com/44113189/47722162-b2513a00-dc8c-11e8-92d1-5f6ad1762312.png)

**Comment by StormRene** [comment]
Hello and welcome to the community,
as it seems, the components were not generated correctly. Have you already tried to regenerate them?

**Comment by StormRene** [comment]
Very good. Now it seems to be generated :-)
A small typo, but I think now you can continue happily?

**Comment by MkVno2** [comment]
Ya,thanks XD
