### ISSUE TITLE
Proper way to restart a game?

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#82]
Hello again,

Another question for the Entitas team, what is the proper way to reset a game?

Traditionally, when I want to reset a Unity application I manually reset any static state and reload the scene. In the cause of Entitas game, I need to be able to reset my pools and systems and get them back into the startup state. It appears that there are few helper methods for this, like `systems.DeactivateReactiveSystems()` and `pool.ClearGroups();`. But I haven't yet been able to figure out how to restart my game without the systems not coming back up correctly or groups behaving incorrectly.

This is what I am currently doing, I have a menu display on game over and then flip the Reset bool when a button is hit, then my GameController does the following;

    void Update()
    {
        if (SharedState.Reset)
        {
            // remove all views
            foreach (var e in pool.GetEntities(Matcher.View))
            {
                e.RemoveView();
            }
            // execute the systems once so the RemoveViewSystem can clean up game objects
            systems.Execute();

            systems.DeactivateReactiveSystems();
            pool.ClearComponentPools();
            pool.ClearGroups();
            pool.DestroyAllEntities();
            systems.ActivateReactiveSystems();
            systems.Initialize();
            SharedState.Reset = false;
            return;
        }

        if (!SharedState.Pause && !pool.isGameOver)
        {
            systems.Execute();
        }
    }

I then have issues with this following system pulling entities that are not falling (ie, not in this Matcher):

    Group fallingGroup;

    void ISetPool.SetPool(Pool pool)
    {
        fallingGroup = pool.GetGroup(Matcher.AllOf(Matcher.Position, Matcher.Falling));
    }

    void IExecuteSystem.Execute()
    {
        foreach (var e in fallingGroup.GetEntities())
        {
            // this is where the error happens, the entity doesn't have a falling component
        }
    }

If I disable this system I don't have explicit errors, but reactive systems don't appear to be working anymore. For example, my view objects are never recreated by my AddViewSystem.

Any suggestions?

It would also be great to add an example of an Entitas restart to one of the example applications. Once again, I appreciate the help.

**Comment by JuDelCo** [comment]
Maybe destroying all pools and loaded systems the GC would clean all from memory? (So you need to load all systems and pools again for the new "scene")

**Comment by JamesMcMahon** [comment]
@JuDelCo Entitas doesn't appear to give you any write access to the static pool variable. I think this would be needed to reset the pool by assigning the static pool to a new pool.

Here is the Pools class;
```
public static class Pools {

    static Pool[] _allPools;

    public static Pool[] allPools {
        get {
            if (_allPools == null) {
                _allPools = new [] { pool };
            }

            return _allPools;
        }
    }

    static Pool _pool;

    public static Pool pool {
        get {
            if (_pool == null) {
                _pool = new Pool(ComponentIds.TotalComponents, 0, new PoolMetaData("Pool", ComponentIds.componentNames, ComponentIds.componentTypes));
                #if (!ENTITAS_DISABLE_VISUAL_DEBUGGING && UNITY_EDITOR)
                var poolObserver = new Entitas.Unity.VisualDebugging.PoolObserver(_pool);
                UnityEngine.Object.DontDestroyOnLoad(poolObserver.entitiesContainer);
                #endif
            }

            return _pool;
        }
    }
}
```

If I could reset `_pool` to a new pool I could accomplish your suggestion, but it doesn't seem like that's what the Entitas team intended since `_pool` is private.

**Comment by sschmid** [comment]
To reset the pool, use pool.Reset()
```csharp
/// Resets the pool (clears all groups, destroys all entities and resets creationIndex back to 0).
public void Reset() {
    ClearGroups();
    DestroyAllEntities();
    ResetCreationIndex();
}
```

**Comment by sschmid** [comment]
Before that, call
systems.DeactivateReactiveSystems()

**Comment by sschmid** [comment]
True, it's not intended to manually set a new pool for the static pools like Pools.pool. If you call pool.Reset() it's basically a new one. To also reset all componentPools (use for object pooling of the components) you can also call pool.ClearComponentPools()

**Comment by sschmid** [comment]
If you could manually assign a new pool to Pools.pool, all references in the systems would be out of sync (ISetPool)

**Comment by JamesMcMahon** [comment]
`Pools.pool.Reset()` Doh, can't believe I missed that.

What is the interaction between reseting the pool and the running systems? Seems like I should deactivate the reactive systems as you said, then activate them after the pool reset and then use `systems.Initialize();` to reboot the initializing systems. Anything I am missing there?

**Comment by JamesMcMahon** [comment]
Hmm even after changing:

        pool.ClearComponentPools();
        pool.ClearGroups();
        pool.DestroyAllEntities();

to
  
      pool.Reset()

I am still hitting the same issues.

**Comment by JamesMcMahon** [comment]
Ah that sounds like the issue. Let me try implementing my group configuration in `system.Initialize()` and see if that fixes my issues.

**Comment by sschmid** [comment]
```
void ISetPool.SetPool(Pool pool)
{
    fallingGroup = pool.GetGroup(Matcher.AllOf(Matcher.Position, Matcher.Falling));
}
```
will cause problems. The pool is reseted and groups are removed, but you keep a reference to the old group.

To make your life easier, you can also just throw away all your systems and create new ones... Or, as said above, all your logic has to go into the initialize method

**Comment by JamesMcMahon** [comment]
Still have some issues with my view system,

After:
```
systems.ActivateReactiveSystems();
systems.Initialize();
```

I never see my AddViewSystem get triggered:
```
IMatcher IExcludeComponents.excludeComponents
{
    get { return Matcher.View; }
}

TriggerOnEvent IReactiveSystem.trigger
{
    get { return Matcher.Resource.OnEntityAdded(); }
}

void IReactiveExecuteSystem.Execute(List<Entity> entities)
{
    // never called. I see entities tagged with resource but they never get a view
}
```

**Comment by sschmid** [comment]
True, that's indeed an issue!
ReactiveSystems setup groups in the constructor, not in Activate, that means event handlers will never be reassigned to the new groups.
I personally always recreated all systems when resetting, that's why I guess I never encounter this issue.

I'll put it on my todo!
I keep you updated

**Comment by JamesMcMahon** [comment]
Ah, then what I am seeing makes sense. I am not opposed to recreating the systems, I just end up with a bunch of cruft in the visual debugger (two system views) and the scene view makes it look like both sets of systems are still running, though again that may just be an issue with the visual debugger.

Not to get too far off topic, but is it good practice to store a reference to a particular group in a system instance or is it preferable to take the hit on the dictionary lookup and pull it on every execute? I assumed the reference would be faster and I think one of your example projects had it but now my Initializing systems list is pretty cluttered just for group reference creation.

**Comment by sschmid** [comment]
Basically it means, everywhere you use a group you now have to re-add your event handlers to the new group. The easiest solution would be to recreate all objects. I think it's easy to forget some place in your code where you stored a group in a field... not sure if one can handle this in a big project. Recreating all objects sound more bullet proof... But I'll take a look. Would be nice if Entitas itself can handle this

**Comment by sschmid** [comment]
Personally, I also store group refs when initializing. The dictionary lookup itself is not really a big thing, but hey, why not caching if we can :)
On the other hand if you're fine with the dict lookup, it will be safer for the reasons you just experienced yourself

**Comment by JamesMcMahon** [comment]
Thanks for your help again Simon.

I think it would be cool if reactive systems could reinitialize on activate. Heck, I think it would be create to have a single method to reboot everything for simplicity.

In my case, however, I realized I also have some Unity MonoBehavior scripts that were also attached to out of date groups for even handling. So for now I am going to reload the scene, so now my method does the following.

```
systems.DeactivateReactiveSystems();
pool.Reset();
SceneManager.LoadScene(SceneManager.GetActiveScene().name);
```

Which seems to give me a clean enough break. My game is simple enough that I think reloading the entire scene back into memory will be a non-factor.

Going to close up this question because I consider it empty. Do you want me to create a separate issue for the ReactiveSystem trigger issue?

**Comment by sschmid** [comment]
Ok, sounds good. I also just reset when I switch scenes.
I've put it on my todo list. I think it's more than just the ReactiveSystem. I'd like to check all places where groups are used and verify if they behave correctly when removing all event handlers.

**Comment by JamesMcMahon** [comment]
As an end user it would also be nice to have some place to hook into so I could reset groups attached to MonoBehaviors.

Like this for instance,
```
public class GameOverMenu : MonoBehaviour
{
    Pool pool;

    void Start()
    {
        pool = Pools.pool;
        var gameOverGroup = pool.GetGroup(Matcher.GameOver);
        gameOverGroup.OnEntityAdded += 
            (group, entity, index, component) => EnableGameOverMenu();	
    }
    ....
}
```

**Comment by sschmid** [comment]
You can use `pool.OnGroupCleared`
https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas/Entitas/Pool.cs#L24
