### ISSUE TITLE
Context classes now create error with Entitas 1.9.0

### ISSUE THREAD

**Issue by RealCosmik** [sschmid/Entitas-CSharp#822]
Hi, just updated to 1.9.0 And been following that Entity Creation has changed in the framework. Currently all my context have errors stating 
"There is no argument given that corresponds to the required formal parameter 'entityFactory' of 'Context<TextEntity>.Context(int, int, ContextInfo, Func<IEntity, IAERC>, Func<TextEntity>)"

```csharp
using Entitas;

public sealed partial class TextContext : Entitas.Context<TextEntity> {

    public TextContext()
        : base(
            TextComponentsLookup.TotalComponents,
            0,
            new Entitas.ContextInfo(
                "Text",
                TextComponentsLookup.componentNames,
                TextComponentsLookup.componentTypes
            ),
            (entity) =>

#if (ENTITAS_FAST_AND_UNSAFE)
                new Entitas.UnsafeAERC()
#else
                new Entitas.SafeAERC(entity)
#endif

        ) {
    }
}
```

Cheers

**Comment by sschmid** [comment]
Do you use the roslyn generator? If so, you need to either wait for the AssetStore update, or you can manually overwrite the plugins in the Jenny folder. The code generator was updated

**Comment by sschmid** [comment]
Quickest way to fix it is just to generate.
If you don't use the roslyn generator, open the generated context files and add

```csharp
() => new GameEntity()
```

as a last argument, e.g

```csharp
public sealed partial class GameContext : Entitas.Context<GameEntity> {

    public GameContext()
        : base(
            GameComponentsLookup.TotalComponents,
            0,
            new Entitas.ContextInfo(
                "Game",
                GameComponentsLookup.componentNames,
                GameComponentsLookup.componentTypes
            ),
            (entity) =>

#if (ENTITAS_FAST_AND_UNSAFE)
                new Entitas.UnsafeAERC(),
#else
                new Entitas.SafeAERC(entity),
#endif
            () => new GameEntity() // <------------- add this to make it compile
        ) {
    }
}
```

**Comment by sschmid** [comment]
I updated the release notes
https://github.com/sschmid/Entitas-CSharp/releases/tag/1.9.0

Thanks for letting me know!

**Comment by RealCosmik** [comment]
Sorry for the late response I created a new unity project and checked out the generated code to see what was changed in the context files and noticed the added func delegate so i just went back and changed it in all my files and just noticed your comment THANKS

**Comment by RealCosmik** [comment]
yeah I fixed this issue in my proj
