### ISSUE TITLE
Emergency help on the wiki

### ISSUE THREAD

**Issue by MkVno2** [sschmid/Entitas-CSharp#824]
I am sorry, I made a very big mistake for you, I don't know how to fix it, I hope to get your forgiveness and try to fix my mistake.
I forked your project before and tried to build a Chinese wiki for it. I thought I didn't have permission to modify your wiki, but I messed up everything, which led to some of the chapters in your wiki becoming Chinese.
I hope that the administrator can see this in time, I have already found a way to recover on google, I hope to get your forgiveness.
I am very very sorry, really :(

**Comment by MkVno2** [comment]
Hey looks like it's replied as it is
Did I miss something?

**Comment by sschmid** [comment]
@MkVno2 No problem, don't worry. I reverted it

**Comment by MkVno2** [comment]
Oh, thank God, I thought I made an unforgivable fault, I hope that my behavior has not caused you too much trouble.QAQ

**Comment by sschmid** [comment]
no problem, it's easy to revert
