### ISSUE TITLE
e.GetComponent() as Nullable

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#826]
Hi guys,

I guess you encountered this already:

```csharp
var parent = e.hasParent
    ? e.parent.value
    : null;
```

e.GetComponent() will throw an exception when the component doesn't exist: [see Entity.cs](https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas/Entitas/Entity/Entity.cs#L222-L229)

Now that Unity finally supports .NET 4.x we could write this

```csharp
var parent = e.parent?.value;
```

e.GetComponent() could return null if the entity doesn't have the component.

Any thoughts? Please let me know.

**Comment by zhuchun** [comment]
My general usage is something like this
``
if (e.hasMyComponent){
  // operate multiple properties 
}
``
I'm not sure if I need the nullable version 😅 
``
if (e.myComponent != null){
  // operate multiple properties 
}
``

**Comment by roygear** [comment]
If it is a stable and beneficial functionality, I agree we should use it.

**Comment by StormRene** [comment]
I thought about it a bit and want to throw the saying "crash hard and early" into the room. The syntax of course "fuels" the null check after the assignment. Especially in systems I expect an exception when I access values that are simply not available. Either I didn't think about the correct collector/filter or it's just an error in my logic. I can only imagine the syntax outside of systems in the view. Depending on how you manage your view. What do you think of that?

**Comment by sschmid** [comment]
will close and not change for now
