### ISSUE TITLE
New name for VisualDebugging

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#83]
I bet there is a cooler name instead of VisualDebugging. VisualDebugging started as to be exactely that, but now it it evolved to be way more. It’s basically the lens into Entitas and at least for me is a cool selling point to use Entitas. You can add/remove/replace/ and change components, you can profile your systems and step through them and more.
Do you guys have any suggestions how to call or rename that, or are you happy with the name?
Sth short and catchy would be nice.

Feel free to add your ideas here :)
Thanks

**Comment by sschmid** [comment]
Some ideas so far:

Entitas Editor
Entitas Lens
Entitas Monitor
Entitas Visualizer
Entitas Visualisation
Entitas Analyser
Entitas Eye
Entitas Vision
Entitas Goggles
Entitas Explorer

**Comment by JuDelCo** [comment]
EntitasSuite
EntitasWatchdog
EntityManager
EntitySystemExplorer
EntitySystemVisualizer
EntityWatcher
VisualEntity
VisualManager

**Comment by sschmid** [comment]
Haha:
Theia (Ancient Goddess of sight and the bright sky)

**Comment by sschmid** [comment]
Oculus (latin)

**Comment by JamesMcMahon** [comment]
Visual debugging seems pretty on point to me. Moniter and Analyzer are nice and descriptive as well.

The thing is the VD allows you to things that people take for granted in Unity. I don't think Unity really has a term for the live editing environment you get, it's just Unity.

Few spitballs:
Entitas Visual Debugger (instead of debugging)
Entitas Supervisor
Entitas Visual ECS
Entitas Live Edit
Entitas Live
Entitas Backstage
Entitas Control Panel

**Comment by Smartis2812** [comment]
Some of my ideas:

Entitas Insider
Entitas Inside Lens
Entitas InVision
ESVision
ESLens
ESDebugger

**Comment by deathrat** [comment]
Entitas EyeDebug was an idea I posted in Gitter.

**Comment by chiuan** [comment]
Entitas Console

**Comment by alagatar** [comment]
Entitas Debugger.  Also Entitas Editor will good for blueprint editor

**Comment by WoLfulus** [comment]
Entitas Inspector?

**Comment by srivello** [comment]
Here are my favorites from the lists above;

-Entitas Editor Tools... including

----- Entitas Settings
----- Entitas Editors... including
----- ----- Entitas Blueprint Editor

----- Entitas Inspectors... including
----- ----- Entitas Pool Inspector
----- ----- Entitas Systems Inspector
----- ----- Entitas Component Inspector
