### ISSUE TITLE
Jenny idle CPU spikes

### ISSUE THREAD

**Issue by robulonn** [sschmid/Entitas-CSharp#831]
Hi, I have a question regarding Jenny.
Frequently when Jenny is idle it spikes to using a lot of CPU (ranging from 15% to 70%). 
This can occur even when jenny has been idle for awhile, and I've never sent a gen request to jenny (so it had always been idle, never used to gen). 
Why is this?
I have yet to probe for traffic concerning Jenny w/wireshark, or searched for the source code to review it; because I though it would be faster to just ask regarding this suspicious behavior. 
My regards

**Comment by sschmid** [comment]
Hi,
that's weird. When you start jenny server it opens a socket connection based on your properties (usually localhost or 127.0.0.1) to receive commands like `gen`.

I just checked the code. The connection goes both ways, that means you can type when the server runs and the client will be notified. I think I can remove that code

```csharp
while (true)
{
    server.Send(Encoding.UTF8.GetBytes(Console.ReadLine()));
}
```

I will take a closer look soon and keep you updated

**Comment by sschmid** [comment]
The while keeps the server alive and prevents the program from early termination, but I can remove `Console.ReadLine()`

If I get this correctly, when jenny is idle it basically stops at `Console.ReadLine()`

**Comment by sschmid** [comment]
A quick check on my machine resulted in 0.0% cpu usage when idle

**Comment by robulonn** [comment]
> A quick check on my machine resulted in 0.0% cpu usage when idle
On my machine it's usually at 0.0% CPU usage when idling between gen commands.
Although, that's when I'm intermittently sending gen commands (so consistent usage/gen commands sent, with small breaks ranging from 5 ~ 10min between sending gen commands). 
However, after being idle for a period of time w/no gen requests (for around 15min ~ 1hr) it shoots up to high CPU usage pretty consistently.

**Comment by robulonn** [comment]
I think I resolved the issue
It only occurred when I (mistakenly) had multiples instances of rider's external tool command open upon generating.
When I noticed this, and closed all instances except one; it always stayed at 0.0% idle cpu usage after letting it sit idle for the usual time it took to make it hop in cpu usage.
Thanks for helping

**Comment by sschmid** [comment]
Ok, I'm glad you could resolve your issue
