### ISSUE TITLE
possibly changing Event code generation systems filter and trigger?

### ISSUE THREAD

**Issue by RealCosmik** [sschmid/Entitas-CSharp#834]
Hi So currently when the event system for a component is generated the trigger is only when that component is added and the filter checks if the entity in question has the component in question. dont you think it would be beneficial if the system also executed when the component can be removed?

A use case for event systems that also react when a component is removed is for example: I was making a button pressing game and when a pressable component was added the color of the view was white. now if the entity get the pressable component removed then the color of the view should react and change to black.

This is mostly beneficial for flag components because an issue i see with this idea is that for any other component that has a value and is not a flag component you can no longer guarantee when you are implementing the listener interface that the entity will have the component. a simple fix to this would be you would always have to write this if the listener method involved any component with values
```csharp
using Entitas;

  public void OnButtonState(ButtonEntity entity, ButtonState Value)
    {
        if (entity.hasButtonState)
        {
            //do sth
        }
    }
```
as of right now you dont have to check if the entity has the component like i did above because the event system only executes if the entity has the component and you would only have to do that if the system reacted on removal of the component as well, but in terms of the flag components specifically i was thinking of something like this:

```csharp
using Entitas;

   protected override Entitas.ICollector<ButtonEntity> GetTrigger(Entitas.IContext<ButtonEntity> context) {
        return Entitas.CollectorContextExtension.CreateCollector(
            context, Entitas.TriggerOnEventMatcherExtension.AddedOrRemoved(ButtonMatcher.Pressable)
        );
    }

    protected override bool Filter(ButtonEntity entity) {
        return (entity.isPressable==true||entity.isPressable==false) && entity.hasPressableListener;
    }
```
then you can say 
```csharp
 public void OnPressable(ButtonEntity entity)
    {
        if (entity.isPressable == true)
            Debug.Log("white button");
        else Debug.Log("grey button");    
    }
```
Cheers let me know if my idea or statements were confusing or if its a flat out bad idea :)

**Comment by sschmid** [comment]
Hi, in an earlier version of the event feature it was actually the way you described.
In order to avoid checks like `if (entity.isPressable == true)` I changed the api to
`OnPressable` and `OnPressableRemoved`

You can It's possible to listen for removed events already
Example:
```csharp
[App, Unique, Event(EventTarget.Any), Event(EventTarget.Any, EventType.Removed)]
public sealed class AsyncLoadingComponent : IComponent {
}
```


will result in

```csharp
public void OnAnyAsyncLoading(AppEntity entity) {
    gameObject.SetActive(true);
}

public void OnAnyAsyncLoadingRemoved(AppEntity entity) {
    gameObject.SetActive(false);
}
```

**Comment by RealCosmik** [comment]
ahhhhhhhhh I forgot about that the default value on the eventType param was eventType.Added okay i see glad to have that cleared up. As a followup question i am not sure if this was already explained somewhere or described in some documentation but I noticed that there is 3rd parameter 'priority' which defaults to 0. I have not fiddled with the that param what are the effects of it?
