### ISSUE TITLE
To achieve a Finite State Machines in Entitas, which way is better? Why?

### ISSUE THREAD

**Issue by atkdefender** [sschmid/Entitas-CSharp#837]
There are 2 ways I have thought.

no.1 One component
```
public class State: IComponent
{
    public string value; // = "idle", "move", "atk", "behit "....
}
```

no.2 Each state one component
```
public class StateIdle: IComponent{}
public class StateMove: IComponent{}
public class StateAtk: IComponent{}
...
```

Method no.2 has the benefit when using Collector and Matcher. And it also has the risk that one entity gets two or more states at the same time, which is not I want.
How do you deal with this?

Or is there another way to achieve this? 
Unity's animator controller looks great. But it has to use the animation clip at the same time, and I don't want the latter.

**Comment by atkdefender** [comment]
Had found a way.

**Comment by atkdefender** [comment]
@fraylopez 
Use the unity Animator Controller, without the Animation Clips.
State Machine → Inspector → Add Behaviour
Then you can find some functions like "OnStateEnter", "OnStateExit"...
And this is what I want:D

**Comment by fraylopez** [comment]
Thanks! But how is it integrated within Entitas?

**Comment by atkdefender** [comment]
I write something like:

OnStateEnter(.....)
{
 gameEntity.AddFace();
 gameEntity.AddNumber();
}

Maybe it's not the best way, but to me, it's good enough.

**Comment by fraylopez** [comment]
I see, thanks for your answer!
