### ISSUE TITLE
Is entity order guaranteed?

### ISSUE THREAD

**Issue by zhuchun** [sschmid/Entitas-CSharp#840]
Hi, I use entities to carry networking messages and have a deferred system to send them. I'm wondering if their order inside Collector/Group is ordered by their create time?

**Comment by FNGgames** [comment]
I might be wrong but i think they use HashSets which do not preserver order, so you would need to manually sort them if order was important to you.

**Comment by zhuchun** [comment]
Thank you @FNGgames 😄 
I guess sorting entities by an incrementing id manually would be an easy yet concrete solution

**Comment by FNGgames** [comment]
Or creation time perhaps?

**Comment by StormRene** [comment]
Order is _not_ preserved. You have to save data for ordering yourself. Internal all entities are saved in a HashSet.

**Comment by StormRene** [comment]
Yep. You did. I just wanted to confirm it because you put "I might be wrong but I think" in front of your sentence :smile:

**Comment by zhuchun** [comment]
> Or creation time perhaps?

Good idea! Creation time should be good enough for most cases. In my case, multiple reliable network message(entity) might be created at the same frame and I still want their order to be guaranteed 😄
