### ISSUE TITLE
Errors when unlink game object

### ISSUE THREAD

**Issue by Apelmon** [sschmid/Entitas-CSharp#843]
Hi,

It happened when I unlink gameObject.
If I delete gameObject after unlink then everything works fine, but if I just SetActive(false) I have errors.

<img width="828" alt="screen shot 2018-12-14 at 6 36 07 pm" src="https://user-images.githubusercontent.com/1730325/50015448-48d48300-ffcf-11e8-99cb-ee85d7b5fc73.png">

How to reproduce it.

I unlink the gameObject and set SetActive(false) then I open Hierarchy window and scroll to the first inactive object. After that the window does not respond and the errors appear.

<img width="344" alt="screen shot 2018-12-14 at 6 33 13 pm" src="https://user-images.githubusercontent.com/1730325/50015420-35291c80-ffcf-11e8-8c1a-3ebe4eabadf3.png">

Cheers

**Comment by sschmid** [comment]
Hi, thanks for pointing this out, Just released Entitas 1.12.2 that contains a fix for that!
