### ISSUE TITLE
How to install in Unity?

### ISSUE THREAD

**Issue by benoneal** [sschmid/Entitas-CSharp#85]
I found Entitas and it convinced me to give Unity a trial. I've watched the video and downloaded the free version of Unity, but there are no instructions anywhere on how to install Entitas into a project. 

The video shows a new project, which apparently just has a Libraries folder containing Entitas... but when I create a new project, I only get an Assets folder. If I place the Entitas files in the project's Library folder, they do nothing. If I place them in the Assets folder, they compile and create entitas.meta files... but I don't get the Entitas menu option and the IComponent class isn't available. 

I'd appreciate any guidance.

**Comment by Smartis2812** [comment]
This is not really a issue.

You have to understand Unity3D first before you start handling extensions.

Unity don't create Folders for you, just a root folder (Assets). The meta files are form Unity and not from entitas.

Did you have the C# Version or the Unity3D C# embedded in your Libraries Folder? Often mistaken thous two.

For the classes and Interfaces from Entitas you have to put "using Entitas;" on the top of you C# Script.

Try first some basic tutorials to understand how Unity3D works to avoid this simple questions.

Thanks

**Comment by sschmid** [comment]
Welcome to Unity @benoneal :)
These are the very first steps to get started:
**Step 1:**
Create a new project with Unity. Unity will automatically create all the files it needs. It will also create an empty folder called 'Assets'. This is the place where all your Scripts, Graphics, Sounds, etc go. When you create a new file in Unity, it will automatically end up in this folder.

**Step 2**
Go to the releases page on GitHub and get the latest version of Entitas (https://github.com/sschmid/Entitas-CSharp/releases) In the downloads sections, click 'Entitas-CSharp.zip'

**Step 3:**
Drag and drop the content of the zip file into Unity. It will also end up in the Assets folder. For each Script, Graphic, Sound, etc Unity automatically creates .meta files, this is normal. These files contain import information and also should be committed to your version control system.

Thats it, happy coding!

**Comment by benoneal** [comment]
Thanks @sschmid and @Smartis2812 ; That has cleared things up. It wasn't intuitive that a script would need to already be using Entitas before it would appear in the top menu, so it appeared to not be working after it was installed. But it's sorted now. Cheers. :)

P.S. That blueprints project looks incredibly useful, but isn't being kept up-to-date with Entitas' latest version. Are blueprints (or something functionally similar) on the Entitas roadmap?

**Comment by sschmid** [comment]
Great!
see #76

**Comment by abbail** [comment]
It would be a great idea to add this to the wiki.  Although this is a basic step for veterans, many people only have exposure to adding things to unity through the asset store.

**Comment by sschmid** [comment]
Yes, it's on my list :) will come

**Comment by sschmid** [comment]
Hey, I updated the wiki and added a new page
"Install Entitas and first steps"
https://github.com/sschmid/Entitas-CSharp/wiki/Install-Entitas-and-first-steps

That might help

**Comment by Skybladev2** [comment]
Do you plan to make it available via Unity Asset Store? This will greatly reduce usage entrance barrier.
I know such version will suffer from publishing delay, but if you give proper credits in the description, people will be encouraged to fix things for you.

**Comment by sschmid** [comment]
Yes, it's planned. That would be cool.
