### ISSUE TITLE
Destruction system interfering with events

### ISSUE THREAD

**Issue by RetroBum** [sschmid/Entitas-CSharp#850]
I've just got a handle on Events so let me see if I can explain this coherently. 

I'm using the MultiDestroySystem outlined in the tutorials on the wiki with the addition of Event(EventTarget.Self) on the DestroyedComponent.

For the most part, events work just fine but when I'm setting the isDestroyed flag from the result of an event the MultiDestroySystem is picking up and destroying this entity without firing it's Destroyed event. 

My guess is that it's because the new event would require the event system to be executed again but the MultiDestroySystem is executed before that. Other events seem to work but I believe that may be down to the specific ordering of the event systems inside the generated EventSystems feature.

How should I deal with this? My goal is to have a component: Map. When Map is added a system creates a bunch more entities to represent the map, then when the Map is removed or destroyed, those created entities get removed too.

**Comment by zhuchun** [comment]
There's an auto-generated `Feature` called `GameEventSystems`, check it out, I guess you didn't put it in the loop

**Comment by RetroBum** [comment]
If that was the case none of my events would work at all.

**Comment by zhuchun** [comment]
Interesting. How about changing the implementation a little bit, like using an entity carrying a component to tell others what Map has been destroyed, and have another reactive system to destroy related entities? IIRC, OnComponentRemoved happens after the component has been removed, thus no data could be access anymore. Perhaps event delivery is following this pattern?

**Comment by RetroBum** [comment]
I have considered this but I was hoping to smooth out these issues and stick with events where possible.

**Comment by RetroBum** [comment]
Okay. I think I've got it.
The problem was, indeed the ordering of the generated ComponentEventSystems inside the generated ContextEventSystem.
The Event attribute has a 3rd parameter; Priority which allows you to control the order so I used those to get my event systems executing in the right order.
