### ISSUE TITLE
Deprecate GeneratedContextAttribute

### ISSUE THREAD

**Issue by c0ffeeartc** [sschmid/Entitas-CSharp#852]
Hello,
since there was mention of Entitas 2.0, I'd like to propose deprecation of GeneratedContextAttribute and `ContextAttributeGenerator`.
```
[Context("Input")]
// vs
[Input]
```
So far it adds visual appeal to code, but has number of drawbacks and adds manual work.

### Pros:
  - looks nice

### Cons:
  - adds dependency from component assembly to generated assembly when they are separated
  - not instant clear it's a ContextAttribute
  - adds requirement to provide list of Context names through settings beforehand

**Comment by sschmid** [comment]
@c0ffeeartc actually, one of the first implementations what's like this. I will keep it in mind and reconsider. Thanks for the input!
