### ISSUE TITLE
Confusion caused by PrimaryEntityIndexAttribute and generic PrimaryEntityIndex

### ISSUE THREAD

**Issue by azsdaja** [sschmid/Entitas-CSharp#853]
Hello!

The fact that `PrimaryEntityIndexAttribute` and generic `PrimaryEntityIndex` classes are referenced using the same name can cause problems. Here's mine: I tried to create an index on an IComponent's field:
```csharp
using System;
using Entitas;
using UnityEngine;

namespace Assets.ECS.Features.Identification
{
	[Game, Serializable]
	public class IdComponent : IComponent
	{
		[SerializeField, PrimaryEntityIndex] private int _id;

		public int Id
		{
			get { return _id; }
			set { _id = value; }
		}
	}
}
```
 and were getting nasty compiler errors: `Cannot apply attribute class 'PrimaryEntityIndex<TEntity, TKey>' because it is generic`. Duckducking for information took me a while and gave no insights. I was suspecting that some changes were made to this class after creating some issues and wiki pages advicing to use it like that. Eventually I found out that wrong class is referenced and in order to use the correct one I need to add proper using clause: `using Entitas.CodeGeneration.Attributes;`.

I'm mostly creating this issue to help people that will look for help in the future, but maybe renaming one of these classes could also be helpful. I can guess it can not be worth breaking the backwards compatibility though.

**Comment by sschmid** [comment]
Is there a reason you designed your component like this?

If not, this is all you need
```csharp
public class IdComponent : IComponent {
    [PrimaryEntityIndex]
    public int id;
}
```

**Comment by azsdaja** [comment]
I just have a habit of not using public fields. I know it may be considered an overkill.

**Comment by sschmid** [comment]
ok, if it's just a habit, don't do it. You have to write more code, other people have to read more code and more importantly, the runtime performance is worse for no added benefit.
