### ISSUE TITLE
Potential optimization: Reusing a single instance of a flag component

### ISSUE THREAD

**Issue by JesseTG** [sschmid/Entitas-CSharp#859]
Components without member variables don't inherently maintain state.  Take a look at this `FlagComponent`:

```csharp
using Entitas;

public sealed class FlagComponent : IComponent {
}
```

I'm told, however, that if multiple entities want to use a `FlagComponent`, multiple instances of it would be created and stored in a pool.  **Why?**  Why not just have one instance of `FlagComponent` created at the game's startup?  This way, when an entity needs a `FlagComponent` it can just add the shared instance to its `IComponent` array.

**Comment by sschmid** [comment]
Hi, a single static component is already shared for all entities. Take a look at the generated code
https://github.com/sschmid/Match-One/blob/develop/Assets/Generated/Game/Components/GamePieceComponent.cs#L11

**Comment by JesseTG** [comment]
...it is?  Son of a bitch.  My mistake, then.  Thank you for all you do.
