### ISSUE TITLE
How to implement Finite State Machines in Entitas?

### ISSUE THREAD

**Issue by dxslly** [sschmid/Entitas-CSharp#86]
In the past I've implemented complex logic such as a Platformer Character Controllers as a Finite State Machine.  Using a state for things like Grounded, Airborne, Walled, etc.. with each state containing their own private members as well as logic for transitions.  Coming to Entitas I've been tossing around ideas what the best way to structure something like a Character Controller might be.

What approaches would you take to make FSMs friendly to work with in Entitas?  Or perhaps there are other ways of structuring this kind of logic that I have not thought of.  I appreciate any ideas, thanks!

**Comment by grygus** [comment]
The most straightforward way that comes to my mind is to make reactive system for each transition example IdleRunTransitionSystem that listens for trigger to change state and components for each state, than you would need IExecute,IReactive systems for (IdleStateSystem,RunStateSystem) to start doing stuff when in state. And of course components that directly triggers state transitions.

**Comment by chiuan** [comment]
maybe some example code would be helpful.

**Comment by sschmid** [comment]
Feel free to reopen, if there are still questions

**Comment by zehreken** [comment]
Ok, I'm here to revive the topic. I need an FSM to manage game state. Imagine an Enum {Play, Pause, End, SecondChance}. This machine controls the UI as well as the Systems of Entitas. Only the related system, let's say GameStateSystem, can change the state of the machine. And in Entitas, I don't know any way to encapsulate data. I think it is better not to do it using Entitas but I love debugging by checking the entity and its components.
This is the FSM:
graph TD;
Play --> Pause;
Pause --> Play;
Pause --> End;
Play --> SecondChance;
SecondChance --> End;
End -->Play
