### ISSUE TITLE
Callback from async operation?

### ISSUE THREAD

**Issue by offka** [sschmid/Entitas-CSharp#863]
Hi guys. Can you please help me with understanding of how to get callback from async operations in esc style? 
Little about my problem: i have two asset bundles, one with data (prefabs, scriptable objects etc), second with the scene, and i need to load first bundle async, wait for operation complete, then i need to process loaded data (so i need to have  a link to bundle) and then load the bundle with scene... (sorry for my english :( )
First solution that came into my head is to make async method with callback parameter that i will call inside my system, something like this:
```csharp
_resourcesService.LoadResources(path, (ILoadedData data) =>{
    contexts.Import(data);
    _resourcesService.LoadScene(path, (ILoadedScene scene) => { /* do something here */ }); 
});
```
But as i understand it's not a proper ecs way, right? 
So i think i need to create entities with some Loader component, that will be handled by IExecute system (that system will check AsyncOperation.isDone every frame while its will not be true, and then will add some isDone flag)... This solution, in my opinion, is more fit to ESC phylosophy, but i can't understand how to notify caller entity that loading process is done and where i need to work with this notifications.
Please help me to understand :)
Thank you!

**Comment by JesseTG** [comment]
Here's an idea.

1. Create a component to signal that your scene (or other asynchronously-loaded data) is ready.  Let's call it `SceneLoadedComponent`, and let's say it's in a `State` context.
2. Create a `ReactiveSystem<StateEntity>` subclass, with a `Collector` looking for `StateMatcher.SceneLoaded` (and other components, if needed).  Or create more than one, if you'd like.  Just remember to clean it up after it's been processed.
3. In your delegate (the one marked `/* do something here*/`), do one thing and *one thing only*; create an entity with a `SceneLoadedComponent`, initialized with whatever data it needs.  Or maybe add it to an existing entity, depending on how you use entities.
4. Your data will be processed in the first game loop to start after it's finished loading.

Does this make sense?

**Comment by offka** [comment]
Hi! Thank you. Looks like this is that i searching for :) 👍

**Comment by JesseTG** [comment]
Happy to help.  :)
