### ISSUE TITLE
Getting stuck on Dry Run - Command line Windows 10

### ISSUE THREAD

**Issue by spudbox** [sschmid/Entitas-CSharp#864]
I start with jenny wiz

pick auto import

select Roslyn options

Get the following:

??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.WarnIfCompilationErrorsPreProcessor
??  Available: Entitas.CodeGeneration.Plugins.ComponentDataProvider
??  Available: Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor
Dry Run

Get to "Dry Run" then freezes

Tried several different things all end here. Suggestions on how to debug this? Logs?

Using Entitas 1.12.2 on Windows 10

Thanks

**Comment by sschmid** [comment]
Hi,

try jenny gen -v to see verbose logs

**Comment by sschmid** [comment]
For reference, here's the Jenny.properties from Match-One
https://github.com/sschmid/Match-One/blob/master/Jenny.properties

**Comment by spudbox** [comment]
Some progress! Using -v , it looks like it has a problem with Assembly-CSharp , the last message is Parsing Assembly-CSharp. Our project is quite large now so I've included a partial file. Anything I should be looking for?


[Sample.csproj.txt](https://github.com/sschmid/Entitas-CSharp/files/2886961/Sample.csproj.txt)

**Comment by spudbox** [comment]
FWIW, I tried with a clean unity project and get the same result.

**Comment by spudbox** [comment]
I let doctor run to see if it would ever complete, it does after about 3 minutes. I have everything installed on SSD, going to install on the hard drive and see if that makes a difference.

**Comment by sschmid** [comment]
Can you try the latest Entitas version and see if it helps?

**Comment by spudbox** [comment]
Moving to hard drive and latest entitas gets the same delay, about 3 minutes. Another possibility is my anti-virus setup. I have another machine I'm going to try an experiment with.

**Comment by spudbox** [comment]
Ok. I'm thinking that it is anti-virus related. I'm going to do some more testing but that seems most promising and also why there are no other reports of this issue.

**Comment by spudbox** [comment]
It is my anti-virus. I have to disable to run BUT that's not a jenny issue. You can close this ticket. Thanks for your help!

**Comment by sschmid** [comment]
Happy to hear that you resolved your issue
