### ISSUE TITLE
Unexpected group behavior on ReplaceComponent

### ISSUE THREAD

**Issue by offka** [sschmid/Entitas-CSharp#865]
Hi guys. I think I found a strange behaviour inside the Entitas. 
First, here is the code: 
```csharp
public static class States
{
    public int STATE_PERFORM = 0;
    public int STATE_EXECUTING = 1;
    public int STATE_COMPLETED = 2;
}

[Game, Event(EventTarget.Any)]
public class StateComponent: IComponent
{
    public int value;
}

public class StateExecutingMatcher: IMatcher <GameEntity>
{
    public int [] indices {get; } = new int [] {GameComponentsLookup.State};

    public bool Matches (GameEntity entity)
    {
        return entity.hasState && entity.state.value == States.STATE_EXECUTING;
    }
}

public partial class GameMatcher
{
    private static StateExecutingMatcher _stateExecutingMatcher;

    public static StateExecutingMatcher StateExecutingMatcher => _stateExecutingMatcher ?? (_stateExecutingMatcher = new StateExecutingMatcher());
}

public class ExecuteSystem: IExecuteSystem
{
    private readonly Group<GameEntity> _entities;
    

    public ExecuteSystem(Contexts contexts)
    {
        _entities = contexts.game.GetGroup(ExtendedGameMatchers.StateExecutingMatcher) as Group<GameEntity>;
    }
    
    public void Execute()
    {
        if (_entities.count <= 0) return;
        foreach (var entity in _entities)
        {
            entity.ReplaceUpdate(Timer.DeltaTime);
        }
    }
}
```
Here I have a group with a custom Matcher, which checks not only the presence of the component, but also its value. So when I do ReplaceState(States.STATE_COMPLETED) the entity does not leave the group! The fact is that the Matches method is called only on Add and Remove events, but not on Update. Is this a bug or intentional behavior?
I suspect that I just need to split one component to several flags: isPerform, isExecuting, isCompleted, and then everything will work as it should, but I don’t want to produce unnecessary components.
Another option is instead of Replace to call Remove and Add, but it looks wrong :(
Have you encountered a similar problem and what solution did you use?

**Comment by sschmid** [comment]
Hi,

Matchers are designed to check the existence of components, but not the values. I think what you're looking for is an EntityIndex


```csharp
using Entitas.CodeGeneration.Attributes;

[Game, Event(EventTarget.Any)]
public class StateComponent: IComponent
{
    [EntityIndex]
    public int value;
}
```

If you add the [EntityIndex] attribute you can do this:

```csharp
var entities = contexts.game.GetEntitiesWithState(States.STATE_EXECUTING);
```

EntityIndex and PrimaryEntityIndex will take care of the component value observation for you, and you will get a very fast access to all entities that have the requested state.

I hope this helps!

**Comment by sschmid** [comment]
The code generator will kindly generate all the necessary methods and indices for you

```csharp
public class ExecuteSystem: IExecuteSystem
{
    readonly Contexts _contexts;

    public ExecuteSystem(Contexts contexts)
    {
        _contexts = contexts;
    }
    
    public void Execute()
    {
        foreach (var entity in _contexts.game.GetEntitiesWithState(States.STATE_EXECUTING))
        {
            entity.ReplaceUpdate(Timer.DeltaTime);
        }
    }
}
```

If you're replacing or removing the StateComponent while iterating, make sure to call ToArray()

**Comment by offka** [comment]
Hi. Thanks for your response. This is what I was looking for :)
