### ISSUE TITLE
Garbage allocations in Group<TEntity>.GetEntities(List<TEntity> entities)

### ISSUE THREAD

**Issue by dkozlovtsev** [sschmid/Entitas-CSharp#867]
Hi,

I've noticed some garbage allocations in `Group<TEntity>.GetEntities(List<TEntity> entities)`  inside 
`buffer.AddRange(this._entities);` call that happen due to `AddRange` implementation that iterates over `this._entities` through the `IEnumerable<T>` interface that allocates. This can easily be avoided simply by replacing `AddRange` with something like:
``` 
foreach(var item in this._entities)
{
    buffer.Add(item);
}
```

**Comment by jannysice** [comment]
AddRange shouldn't allocate garbage in this case, since a HashSet<T> is passed. It uses ICollection<T>.CopyTo(), which in the case of a HashSet is allocation free.
It might be that the list resizes in EnsureCapacity, which will allocate some garbage.
The same would happen in your proposed fix.
Put a sample of AddRange below.

```
ICollection<T> objs = collection as ICollection<T>;
if (objs != null)
{
    int count = objs.Count;
    if (count > 0)
    {
        //List might need to resize. Possible GC alloc.
        this.EnsureCapacity(this._size + count);
        if (index < this._size)
            Array.Copy((Array) this._items, index, (Array) this._items, index + count, this._size - index);
        if (this == objs)
        {
            Array.Copy((Array) this._items, 0, (Array) this._items, index, index);
            Array.Copy((Array) this._items, index + count, (Array) this._items, index * 2, this._size - index);
        }
        //Using CopyTo here, which is alloc free in case of HashSet<T>
        else
            objs.CopyTo(this._items, index);
        this._size += count;
    }
}
//Will never go here since the collection passed implements ICollection<T>
else
{
    foreach (T obj in collection)
        this.Insert(index++, obj);
}
```

**Comment by dkozlovtsev** [comment]
@jannysice It looks like you're correct - the implementation I have available to me right now seems to not generate any garbage, but in my profiling I did see allocations that couldn't have been attributed to list resize. I'll try to reproduce it and If I fail I'll close the issue. Thanks for taking the time to dig into this.

**Comment by dkozlovtsev** [comment]
It seems that I was wrong about the cause of allocations I'm seeing, so closing the issue
