### ISSUE TITLE
CleanupMode Error After upgrade Entitas from 1.8 to 1.13

### ISSUE THREAD

**Issue by wpp1983** [sschmid/Entitas-CSharp#868]
Hi,
  
   I upgrade entitas, and the cleanupSystem would not to be generate.

  how can I fix this ?

[Cleanup(CleanupMode.RemoveComponent)]
public class Com : IComponent
{
}

**Comment by wpp1983** [comment]
and I use the Jenny-server,  there is a error about " can't load UnityEditor Version = 0.0.0.0"

**Comment by wpp1983** [comment]
oh, I fix this

**Comment by sschmid** [comment]
👍

**Comment by Besjan** [comment]
Hi,

what was the fix?

**Comment by rayss1** [comment]
Hi, how to fix this issue

**Comment by sschmid** [comment]
My guess is:
The Cleanup generator was not part of the GitHub version, only the Asset Store version.
This changed now and the GitHub version has all features now starting with Entitas 1.14.0, see announcement:
https://github.com/sschmid/Entitas/discussions/1008
