### ISSUE TITLE
VisualDebugger bug when components are added on entity creation

### ISSUE THREAD

**Issue by LinusVanElswijk** [sschmid/Entitas-CSharp#87]
If you add a component to an entity on an `OnEntityCreated` event, 
[line 34 of the PoolObserverInspector](https://github.com/sschmid/Entitas-CSharp/blob/master/Entitas.Unity/Assets/Entitas.Unity/VisualDebugging/PoolObserver/Editor/PoolObserverInspector.cs#L34) will throw an exception whenever you use the CreateEntity button of the visual debugger.

At the time this line of code is executed, the name of `GameObject` that is associated is not yet updated to contain the added component, causing a failure on
`Object.FindObjectsOfType<EntityBehaviour>().Single(eb => eb.name == entity.ToString());`.

The setup I use:
```
public class MySystem : IInitializeSystem {
  ...
  public void Initialize() {
    pool.OnEntityCreated += AddComponent;
  }
  
  //what I would like to do
  public void AddComponent(Pool pool, Entity entity) {
    entity.AddMyComponent(someValue);
  }

  //temporary fix: force the gameObject to update it's name
  public void AddComponent(Pool pool, Entity entity) {
#if (UNITY_EDITOR)  
    var entityBehaviour = GameObject.FindObjectsOfType<EntityBehaviour>()
     .Single(eb => eb.name == entity.ToString());
#endif
    entity.AddMyComponent(someValue);
#if (UNITY_EDITOR)
    entityBehaviour.gameObject.name = entity.ToString();
#endif
  }
  ...
}
```

**Comment by LinusVanElswijk** [comment]
A related issue: if you have multiple pools, then you can end up with multiple entities with the same name, which also causes an exception on the same line of code.

**Comment by sschmid** [comment]
Oh, ok, Thanks, I'll take a look

**Comment by sschmid** [comment]
Hey! It's fixed now, thanks for pointing it out. Will be in the next release! Happy coding :)
