### ISSUE TITLE
The meta component event does not work.

### ISSUE THREAD

**Issue by ArkTarusov** [sschmid/Entitas-CSharp#878]
Hello.
I ran into a problem, I have a meta component in which I store the state of the current match - points, currency.
I need to display this data on ui.
I tried Any event. But why they do not work at all. I followed the recommendations from [here](https://github.com/sschmid/Entitas-CSharp/wiki/FAQ#q-events-feature-does-not-trigger), did not help.
I tried the Self event, just without result, the event does not work.

Here is an example of a listener:
```csharp
public class PhaseScoreBar : MonoBehaviour, IEventListener, IMatchDataListener
{
    public void RegisterEventListeners(IEntity entity)
    {
        Contexts.sharedInstance.meta.matchDataEntity.AddMatchDataListener(this);
      ...
    }
    
    public void OnMatchData(MetaEntity entity, uint numberPhase, uint currentPhaseScore, uint totalScore,
        uint matchGold)
    {
      ...
    }
}
```
and here is an example of changing data in the companente:

```csharp
class DeadListener : MonoBehaviour, IEventListener, IDeadListener
{
    private MetaContext meta;

    public void RegisterEventListeners(IEntity entity)
    {
        meta = Contexts.sharedInstance.meta;
        var gameEntity = entity as GameEntity;
        gameEntity?.AddDeadListener(this);
    }

    public void OnDead(GameEntity entity)
    {
        if (entity.isDead)
        {
            if (entity.hasBasicEnemy && meta.isPlayMatch)
            {
                meta.matchDataEntity.ReplaceMatchData(meta.matchData.NumberPhase,
                    meta.matchData.CurrentPhaseScore += entity.basicEnemy.RewardExp,
                    meta.matchData.TotalScore += entity.basicEnemy.RewardExp,
                    meta.matchData.MatchGold += entity.basicEnemy.RewardGold);
            }

            gameObject.Unlink();
            entity.Destroy();
            gameObject.DestroyGameObject();
        }
    }
}
```
OnDead is called, the matchData update code is also, but OnMatchData is not called. 

Cheers

**Comment by c0ffeeartc** [comment]
Hello, triggering event during eventhandling phase, may not work due to eventSystem ordering. You may adjust `[Event]` priority or better - create additional entity and handle it in some system at the next frame.

**Comment by ArkTarusov** [comment]
I transferred the update of the meta-component to the same system in which the update of the OnDead component.
Did not help.
After that, I moved it to a completely separate IExecuteSystem system and experimented with the order of the call.
Did not help.

New system: 
```cs
using Entitas;

class TestSystem : IExecuteSystem
{
   private readonly MetaContext meta;
   public TestSystem(Contexts contexts)
   {
      meta = contexts.meta;
   }

   public void Execute()
   {
      meta.matchDataEntity.ReplaceMatchData(meta.matchData.NumberPhase,
                            meta.matchData.CurrentPhaseScore,
                            meta.matchData.TotalScore,
                            meta.matchData.MatchGold);
   }
}
```

**Comment by c0ffeeartc** [comment]
Did you add MetaEventSystems to systems in gameController?

**Comment by ArkTarusov** [comment]
@c0ffeeartc Thank! It worked. I was not very attentive. Thank you very much for your time)
