### ISSUE TITLE
Purchased version (Asset store) won't work

### ISSUE THREAD

**Issue by akoolenbourke** [sschmid/Entitas-CSharp#879]
Hi

Running in Windows 10. VS2017 and VS2015 installed.

I purchased the asset store version today and found no documentation on how to get it to work (I am converting an existing project from the open source version). There are a couple of videos where setup is talked about but the instructions did not work. I managed to find a jenny.zip with what looked like the right files but when expanding and running auto-import.bat I get errors and I am not sure if I'm in a good state. (EDIT: See followup comment for more information, it's a command line error during MSBuild)

I selected the rosyln versions of the dll's when prompted here:
`
.\Jenny\Jenny.exe auto-import -s
??  Potential plugin collision: ComponentDataProvider
0: Keep all (no changes)
1: Keep Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider
2: Keep Entitas.CodeGeneration.Plugins.ComponentDataProvider
??  Potential plugin collision: EntityIndexDataProvider
0: Keep all (no changes)
1: Keep Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider
2: Keep Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
`
But when the doctor part of auto-import runs (Or I use jenny.exe gen), I get
`
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.WarnIfCompilationErrorsPreProcessor
??  Available: Entitas.CodeGeneration.Plugins.ComponentDataProvider
??  Available: Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor
Dry Run
One or more errors occurred.
`

Any ideas? Here is my jenny.properties

Jenny.SearchPaths = Assets\DesperateDevs\Editor\Plugins, \
                    Assets\Entitas\Editor\Plugins, \
                    Jenny\Plugins\Entitas.Roslyn

Jenny.Plugins = DesperateDevs.CodeGeneration.Plugins, \
                DesperateDevs.CodeGeneration.Unity.Plugins, \
                Entitas.CodeGeneration.Plugins, \
                Entitas.Roslyn.CodeGeneration.Plugins, \
                Entitas.VisualDebugging.CodeGeneration.Plugins

Jenny.PreProcessors = DesperateDevs.CodeGeneration.Plugins.ValidateProjectPathPreProcessor, \
                      DesperateDevs.CodeGeneration.Plugins.TargetFrameworkProfilePreProcessor

Jenny.DataProviders = Entitas.CodeGeneration.Plugins.ContextDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.CleanupDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider

Jenny.CodeGenerators = Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentLookupGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextAttributeGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextMatcherGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextsGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityIndexGenerator, \
                       Entitas.CodeGeneration.Plugins.EventEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenerComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenertInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemsGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator, \
                       Entitas.Roslyn.CodeGeneration.Plugins.CleanupSystemGenerator, \
                       Entitas.Roslyn.CodeGeneration.Plugins.CleanupSystemsGenerator

Jenny.PostProcessors = DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor

Jenny.Server.Port = 3333
Jenny.Client.Host = localhost
DesperateDevs.CodeGeneration.Plugins.ProjectPath = Assembly-CSharp.csproj
Entitas.CodeGeneration.Plugins.Contexts = Game, \
                                          Input, \
                                          Bootstrap, \
                                          Meta

Entitas.CodeGeneration.Plugins.IgnoreNamespaces = false
DesperateDevs.CodeGeneration.Plugins.TargetDirectory = Assets/Sources

**Comment by akoolenbourke** [comment]
Here is the output from jenne.exe doctor -v 
NOTE: It's a null argument exception when parsing command line it seems

Loading assemblies from C:\dev\Unity\Projects\EntitasPrototype2\Jenny
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Analytics.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Analytics.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.CLI.Utils.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.CLI.Utils.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.CodeGeneration.CodeGenerator.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.CodeGeneration.CodeGenerator.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.CodeGeneration.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.CodeGeneration.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Logging.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Logging.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Logging.Formatters.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Logging.Formatters.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Networking.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Networking.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Serialization.CLI.Utils.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Serialization.CLI.Utils.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Serialization.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Serialization.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Utils.dll
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\DesperateDevs.Utils.dll
Name:Jenny.exe
There are no context policies.
 load: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\Jenny.exe
  ? Loading: C:\dev\Unity\Projects\EntitasPrototype2\Jenny\Jenny.exe
Jenny.SearchPaths = Assets\DesperateDevs\Editor\Plugins, \
                    Assets\Entitas\Editor\Plugins, \
                    Jenny\Plugins\Entitas.Roslyn

Jenny.Plugins = DesperateDevs.CodeGeneration.Plugins, \
                DesperateDevs.CodeGeneration.Unity.Plugins, \
                Entitas.CodeGeneration.Plugins, \
                Entitas.Roslyn.CodeGeneration.Plugins, \
                Entitas.VisualDebugging.CodeGeneration.Plugins

Jenny.PreProcessors = DesperateDevs.CodeGeneration.Plugins.ValidateProjectPathPreProcessor, \
                      DesperateDevs.CodeGeneration.Plugins.TargetFrameworkProfilePreProcessor

Jenny.DataProviders = Entitas.CodeGeneration.Plugins.ContextDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.CleanupDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider, \
                      Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider

Jenny.CodeGenerators = Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentLookupGenerator, \
                       Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextAttributeGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextMatcherGenerator, \
                       Entitas.CodeGeneration.Plugins.ContextsGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityGenerator, \
                       Entitas.CodeGeneration.Plugins.EntityIndexGenerator, \
                       Entitas.CodeGeneration.Plugins.EventEntityApiGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenerComponentGenerator, \
                       Entitas.CodeGeneration.Plugins.EventListenertInterfaceGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemGenerator, \
                       Entitas.CodeGeneration.Plugins.EventSystemsGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.ContextObserverGenerator, \
                       Entitas.VisualDebugging.CodeGeneration.Plugins.FeatureClassGenerator, \
                       Entitas.Roslyn.CodeGeneration.Plugins.CleanupSystemGenerator, \
                       Entitas.Roslyn.CodeGeneration.Plugins.CleanupSystemsGenerator

Jenny.PostProcessors = DesperateDevs.CodeGeneration.Plugins.AddFileHeaderPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.CleanTargetDirectoryPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.MergeFilesPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.NewLinePostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.UpdateCSProjPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.WriteToDiskPostProcessor, \
                       DesperateDevs.CodeGeneration.Plugins.ConsoleWriteLinePostProcessor

Jenny.Server.Port = 3333
Jenny.Client.Host = localhost
DesperateDevs.CodeGeneration.Plugins.ProjectPath = Assembly-CSharp.csproj
Entitas.CodeGeneration.Plugins.Contexts = Game, \
                                          Input, \
                                          Bootstrap, \
                                          Meta

Entitas.CodeGeneration.Plugins.IgnoreNamespaces = false
DesperateDevs.CodeGeneration.Plugins.TargetDirectory = Assets/Sources

Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Plugins
    ? Resolved: Assets\DesperateDevs\Editor\Plugins\DesperateDevs.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Unity.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Unity.Plugins
    ? Resolved: Assets\DesperateDevs\Editor\Plugins\DesperateDevs.CodeGeneration.Unity.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.CodeGeneration.Plugins
  ? Loading: Entitas.CodeGeneration.Plugins
    ? Resolved: Assets\Entitas\Editor\Plugins\Entitas.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.Roslyn.CodeGeneration.Plugins
  ? Loading: Entitas.Roslyn.CodeGeneration.Plugins
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Entitas.Roslyn.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.VisualDebugging.CodeGeneration.Plugins
  ? Loading: Entitas.VisualDebugging.CodeGeneration.Plugins
    ? Resolved: Assets\Entitas\Editor\Plugins\Entitas.VisualDebugging.CodeGeneration.Plugins.dll
  ? Loading Dependency: Entitas.CodeGeneration.Attributes, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Entitas.CodeGeneration.Attributes.dll
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.WarnIfCompilationErrorsPreProcessor
??  Available: Entitas.CodeGeneration.Plugins.ComponentDataProvider
??  Available: Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor
Dry Run
Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Plugins
    ? Resolved: Assets\DesperateDevs\Editor\Plugins\DesperateDevs.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: DesperateDevs.CodeGeneration.Unity.Plugins
  ? Loading: DesperateDevs.CodeGeneration.Unity.Plugins
    ? Resolved: Assets\DesperateDevs\Editor\Plugins\DesperateDevs.CodeGeneration.Unity.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.CodeGeneration.Plugins
  ? Loading: Entitas.CodeGeneration.Plugins
    ? Resolved: Assets\Entitas\Editor\Plugins\Entitas.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.Roslyn.CodeGeneration.Plugins
  ? Loading: Entitas.Roslyn.CodeGeneration.Plugins
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Entitas.Roslyn.CodeGeneration.Plugins.dll
Name:Jenny.exe
There are no context policies.
 load: Entitas.VisualDebugging.CodeGeneration.Plugins
  ? Loading: Entitas.VisualDebugging.CodeGeneration.Plugins
    ? Resolved: Assets\Entitas\Editor\Plugins\Entitas.VisualDebugging.CodeGeneration.Plugins.dll
Opening Assembly-CSharp.csproj
  ? Loading Dependency: Microsoft.CodeAnalysis.Features, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  ? Loading Dependency: Microsoft.CodeAnalysis.Features, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  ? Loading Dependency: Microsoft.CodeAnalysis.CSharp.Features, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  ? Loading Dependency: Microsoft.CodeAnalysis.CSharp.Features, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  ? Loading Dependency: Microsoft.CodeAnalysis.VisualBasic.Features, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  ? Loading Dependency: Microsoft.CodeAnalysis.VisualBasic.Features, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  ? Loading Dependency: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Microsoft.Build.Framework.dll
  ? Loading Dependency: Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Microsoft.Build.dll
  ? Loading Dependency: Microsoft.Build, Version=14.1.0.0, Culture=neutral
    ? Resolved: Jenny\Plugins\Entitas.Roslyn\Microsoft.Build.dll
  ? Loading Dependency: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.resources, Version=14.1.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
  ? Loading Dependency: Microsoft.Build.resources, Version=14.1.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Immutable.ImmutableDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.CodeAnalysis.MSBuild.CommandLineArgumentReader.ReadDebugInfo()
   at Microsoft.CodeAnalysis.CSharp.CSharpCommandLineArgumentReader.ReadCore()
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFile.ReadCommandLineArgs(ProjectInstance project)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.GetCommandLineArgs(ProjectInstance project)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.CreateProjectFileInfo(ProjectInstance project)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.<BuildProjectFileInfoAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.<GetProjectFileInfosAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<DoOperationAndReportProgressAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectFileInfosAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectInfosFromPathAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadProjectInfoAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenProjectAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at DesperateDevs.Roslyn.ProjectParser..ctor(String projectPath)
   at DesperateDevs.Roslyn.CodeGeneration.Plugins.PluginUtil.GetCachedProjectParser(Dictionary`2 objectCache, String projectPath)
   at Entitas.Roslyn.CodeGeneration.Plugins.CleanupDataProvider.GetData()
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.generate(String messagePrefix, IPreProcessor[] preProcessors, IDataProvider[] dataProviders, ICodeGenerator[] codeGenerators, IPostProcessor[] postProcessors)
   at DesperateDevs.CodeGeneration.CodeGenerator.CodeGenerator.DryRun()
   at DesperateDevs.CodeGeneration.CodeGenerator.CLI.DoctorCommand.run()
   at DesperateDevs.CLI.Utils.AbstractCommand.Run(CLIProgram program, String[] args)
   at DesperateDevs.Serialization.CLI.Utils.AbstractPreferencesCommand.Run(CLIProgram program, String[] args)
   at DesperateDevs.CLI.Utils.CLIProgram.runCommand(String[] args)
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Immutable.ImmutableDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.CodeAnalysis.MSBuild.CommandLineArgumentReader.ReadDebugInfo()
   at Microsoft.CodeAnalysis.CSharp.CSharpCommandLineArgumentReader.ReadCore()
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFile.ReadCommandLineArgs(ProjectInstance project)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.GetCommandLineArgs(ProjectInstance project)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.CreateProjectFileInfo(ProjectInstance project)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.<BuildProjectFileInfoAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.<GetProjectFileInfosAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<DoOperationAndReportProgressAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectFileInfosAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectInfosFromPathAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadProjectInfoAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenProjectAsync>d__24.MoveNext()<---

**Comment by FNGgames** [comment]
quick checks:

(1) remove jenny.zip from assets folder where it lands after asset store import
(2) unzip into your unity project folder such that you have the .bat files in the top of your project folder and a Jenny folder in there too (should look like this: MyProject/Jenny/... and MyProject/Jenny-Server.bat
(3) inside unity, open Tools-> Jenny-> preferences, hit auto-import and generate once
(4) run jenny-auto-import.bat (or the other mac equivalent)
(5) if conflicts are shown, choose the Roslyn version of the each conflict by hitting the relevant number key
(6) open jenny-server and leave the command window open
(7) in unity, run tools -> jenny -> generate with server

Let us know if there are still problems after that

**Comment by akoolenbourke** [comment]
Same problem. After selecting Rosyln for the conflicts, a dry run happens and that has the error as outlined above. Here's the complete output (I pressed 2 each time)

.\Jenny\Jenny.exe auto-import -s
??  Potential plugin collision: ComponentDataProvider
0: Keep all (no changes)
1: Keep Entitas.CodeGeneration.Plugins.ComponentDataProvider
2: Keep Entitas.Roslyn.CodeGeneration.Plugins.ComponentDataProvider
??  Potential plugin collision: EntityIndexDataProvider
0: Keep all (no changes)
1: Keep Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
2: Keep Entitas.Roslyn.CodeGeneration.Plugins.EntityIndexDataProvider

C:\dev\Unity\Projects\EntitasPrototype2>.\Jenny\Jenny.exe doctor
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.WarnIfCompilationErrorsPreProcessor
??  Available: Entitas.CodeGeneration.Plugins.ComponentDataProvider
??  Available: Entitas.CodeGeneration.Plugins.EntityIndexDataProvider
??  Available: DesperateDevs.CodeGeneration.Unity.Plugins.DebugLogPostProcessor
Dry Run
One or more errors occurred.

The errors are that null argument exception as mentioned above.

**Comment by akoolenbourke** [comment]
Just to update. I tried with a completely new Unity project with the same results.
