### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by laughsuggestion** [sschmid/Entitas-CSharp#880]
I'm using the paid $90 version, not the Github version.

I'm not sure why I keep having this problem, but I keep having to fight the code generator. I'll write a component like this:

`[Game]
public class Player : IComponent
{
    public int playerID;
}`

And then I'll change it to something like this:

``[Game]
public class Player : IComponent
{
    public Guid playerID;
}``

Now the generator won't work because Unity has errors. This is for multiple reasons, one is the generated code is now broken and secondly because my code now needs updating. But this is code generation... it should not care. So I follow the instructions and disable the warning in the Jenny settings. Now I can generate code, but it generates code that also breaks. Interestingly in this case it generates code where the component still depends on the "int" instead of the "Guid". I haven't looked into the source code for the code-gen tools but it seems like its probably reflecting the last built DLL instead of the code text. This would explain why even if I delete the entire generated folder it still generates garbage based on code prior to the change.

Edit: I do not mind fixing up my code because of a rename, but I find it absurd to fix generated code.

My only solution so far is to muddle through the generated code either fixing or deleting enough code to get Unity in a compiling state and then rebuilding. This is happening a lot at the start of using Entitas as well as being at the start of a new game. A lot of renaming, adding and removing of components and their fields is occurring.

I was going to try putting the components in a different assembly until I realized that your components need attributes which are generated! So the whole system seems to be a circular dependency.

What is the solution to this?

**Comment by c0ffeeartc** [comment]
Sry can't help with generator, would like to note you can use `ContextAttribute` directly along with const strings to remove dependency, example `[Context(Ids.Game)]`

**Comment by c0ffeeartc** [comment]
Honestly it looks like you use unity generator not paid roslyn, you should switch it somewhere and it will work without need to fix compilation errors

**Comment by FNGgames** [comment]
Seems to me like you're either

(a) using the reflection generator that comes with both the free and paid versions
or
(b) are using Roslyn generator but have the "Warn if compilation errors" preprocessor on

**Comment by laughsuggestion** [comment]
Yeah I had to use the external roslyn compiler. I hooked up a Ctrl+Shift+X shortcut to run that process external to Unity so that it doesn't have this problem.

Thank you for your help.
