### ISSUE TITLE
Jenny Generation .properties errors

### ISSUE THREAD

**Issue by RealCosmik** [sschmid/Entitas-CSharp#890]
Hi, So in the Unity editor in the section where you can select the path for you jenny.properties file I selected an incompatible file as a test and received this error. However after doing this there is no way for me to fix the path that I selected
![image](https://user-images.githubusercontent.com/26536123/56485289-6e9ff600-64a1-11e9-9be4-39be0301d3a7.png)

**Comment by sschmid** [comment]
Hi,
you can try this to solve this
1. delete the file
2. fix the file
3. delete EditorPrefs (you may need to create a script for that)

Deleting it w

**Comment by RealCosmik** [comment]
4. Solved this issue thanks
