### ISSUE TITLE
Group.GetEntities Creates Garbage

### ISSUE THREAD

**Issue by laughsuggestion** [sschmid/Entitas-CSharp#893]
Just by inspection it’s looks like the API for getting entities from a group generates garbage. It simply uses lazy creation of an array and copies data. Anytime the group is changed the array is set to null. Next time the method is called the array is recreated... For Unity3D this is not great. Groups can change every frame and the GetEntities is called every frame. I’m going to test this more tonight but I suspect this will be an issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sschmid** [comment]
Hi,
there are 3 ways to iterate over entities in a group, each for a different use-case.
If the group changes often, you should either use

```csharp
foreach (var e in _group) {
    // do sth
}
```

or, if you modify the entities that will affect the group

```
readonly List<GameEntity> _buffer = new List<GameEntity>();

...

foreach (var e in _group.GetEntities(_buffer)) {
    e.Destroy();
}

```

first approach won't create garbage but you cannot change the components if they are also contained in the group.
the 2nd approach uses a custom buffer (list of entities) that will be cleared and refilled. Use this to avoid the allocation of the array that you described when using group.GetEntities()

**Comment by laughsuggestion** [comment]
Ok I a fit into your second situation. Every frame potentially. So what I think would be better is if you had a method for passing in an array and copying to it instead of just creating a new one. It could even expand the array. This would allow us each to hold a reference, keep it growing, and not let it garbage collect. This is all of the top of my head though. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by laughsuggestion** [comment]
>Hi, ...

@sschmid apparently I hadn’t seen the last part of your post or that method. I will use that for sure. That was actually going to be my suggestion if the method didn’t exist. Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
