### ISSUE TITLE
Question about Jenny.exe

### ISSUE THREAD

**Issue by micz84** [sschmid/Entitas-CSharp#895]
Hi,

I was watching a tutorial with unit testing but I do not know how to just Jenny is it available only in asset store release?

Cheers,
Michal

**Comment by FNGgames** [comment]
"Jenny" refers to the Roslyn standalone CLI code generator, as opposed to the reflection based one. Jenny is part of the paid version from the asset store where the reflection based on is free with the open source version.

**Comment by micz84** [comment]
Thank you for your reply. I will find other way to run generation easily.
