### ISSUE TITLE
Failure feedback for migration tools

### ISSUE THREAD

**Issue by JamesMcMahon** [sschmid/Entitas-CSharp#90]
The migration tool doesn't give any feedback on a migration failure.

When running the 0.30 migrations for example, I misunderstood what was meant by project root and run it on the wrong directory, which lead to zero error message. It would be nice if it said something like "Can't find expected file Entitas.properties, aborting migration". Something to let the end use know that the migration did not run as intended.

**Comment by sschmid** [comment]
Yeah, I could do sth like that in future migrations. Thanks, good idea
