### ISSUE TITLE
Remove Events on Unique components

### ISSUE THREAD

**Issue by blisterfingers** [sschmid/Entitas-CSharp#901]
It seems that remove events on unique components don't fire.

I presume because the related entity is destroyed by the unique system, as it's no longer needed, and thus the event systems have nothing to react to when it's their turn.

Makes sense (if it's right) but that being the case how should I handle this? Creating special entities just to hold listeners and then retaining their ids so they can be cleaned up turns my code into the kind of mess I turned to ECS to avoid. 

Any suggestions? 
Thanks.

**Comment by SirMetathyst** [comment]
You could add a destroyed flag to the unique entity and have it be collected by a destroy system after your events systems?

**Comment by SirMetathyst** [comment]
```c#
// part of partial context (add this manually)
        public void RemoveSomeServiceComponent()
        {
// triggers event
            xxxEntity.RemoveSomeService();
        }
```
This would then mean your unique component was essentialled deleted.
```c#
       public xxxEntity xxxEntity
        {
            get
            {
                return GetGroup(MetaMatcher.SomeService).GetSingleEntity();
            }
        }

        public SomeServiceComponent someService
        {
            get
            {
                return xxxEntity.someService;
            }
        }
```

**Comment by SirMetathyst** [comment]
But bare in mind you will be left with an empty entity so you should add a "destroyed" component to it so that it can be cleaned up by a destroy system if you don't use that entity for anything else.

**Comment by blisterfingers** [comment]
Okay, as confused as that made me it actually nudged me in the right direction so thanks to SirMetathyst.

Doing it this way gives me the expected result, using the id method from the wiki

`int id = contexts.uI.showTileSelectionEntity.id.value;
            contexts.uI.showTileSelectionEntity.isShowTileSelection = false;
            contexts.uI.GetEntityWithId(id).isDestroyed = true;`

**Comment by c0ffeeartc** [comment]
Hello, you can change this to
```csharp
var entity = contexts.uI.showTileSelectionEntity;
entity.isShowTileSelection = false;
entity.isDestroyed = true;
```

**Comment by blisterfingers** [comment]
Thanks. And thanks to my brain for missing that obvious way of doing it and opting for the more complicated solution.

**Comment by c0ffeeartc** [comment]
Btw, for `Unique` flags I prefer to use
```
[GameState]
[Unique]
public class SomeComponent: IComponent
{
    public bool Value;
}
```
It makes easier to deal with events and other things
