### ISSUE TITLE
Entitas Chat Poll

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#906]
Hi,

it has been requested to consider other chat solutions other than gitter.

Since I'm revamping the repo and working on Entitas 2.0 it would also be a good time to ask you which platform you want to use to communicate moving forward.

Let's do a simple poll so I can get an overview what the community thinks and prefers

- Gitter: 👀
- Discord: 🚀
- Slack: 🎉

Click the react button to vote. Comment, if you know great reasons why to pick a certain platform

Thanks!

**Comment by JesseTG** [comment]
I have preemptively created [this Discord server](https://discord.gg/WsfguTu).  **Note that is is entirely unofficial unless @sschmid gives it his blessing.**  All moderators of the existing Gitter chat room who join the Discord server will be granted equivalent privileges.  And if @sschmid joins and endorses the Discord, I will transfer ownership to him.

**Comment by WoLfulus** [comment]
Thank god for a discord server

**Comment by laughsuggestion** [comment]
Discord

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bleedingpixels** [comment]
discord

**Comment by sschmid** [comment]
I think I can already see a clear trend ;)

**Comment by JesseTG** [comment]
@sschmid Join the Discord I linked and post your Discord in this thread.  When you do, I will transfer ownership to you.

**Comment by sschmid** [comment]
joined :D

**Comment by JesseTG** [comment]
For future readers: I have granted @sschmid total ownership of the linked Discord server. It is now official.
