### ISSUE TITLE
Internal implementation of EntityIndex doesn't remove empty HashSets. Is this intended?

### ISSUE THREAD

**Issue by hurog** [sschmid/Entitas-CSharp#913]
Hi,

While profiling my project (a mobile game) I found out memory usage has been consistently increased.

After running the game more than 12 hours, memory profiler showed more than 400,000 objects of 
- HashSet<SomeEntity>
- HashSet.Slot<SomeEntity>[]

created.
Each piece of HashSet consumed tiny amount of memory - around 10 to 20 bytes? - but as time goes it became nontrivial, taking 20~30 MBytes of memory.

I realized using EntityIndex caused such allocation of HashSets.

    public HashSet<TEntity> GetEntities(TKey key) {
            HashSet<TEntity> entities;
            if (!_index.TryGetValue(key, out entities)) {
                entities = new HashSet<TEntity>(EntityEqualityComparer<TEntity>.comparer);
                _index.Add(key, entities);
            }
            return entities;
        }

When there's no key found for _index, it allocates a new HashSet.
Unfortunately, the key for this EntityIndex was another entity's id (for referencing)
and when new referencing entity is created, creationIndex increased, failed to find key, and added one more new HashSet.

    protected override void removeEntity(TKey key, TEntity entity) {
            GetEntities(key).Remove(entity);

            var safeAerc = entity.aerc as SafeAERC;
            if (safeAerc != null) {
                if (safeAerc.owners.Contains(this)) {
                    entity.Release(this);
                }
            } else {
                entity.Release(this);
            }
        }

But removeEntity() only remove what's inside the HashSet, but doesn't remove HashSet itself even if it's empty. Is this behavior intended for performance reason?

It's tempting to delete empty HashSet after removing entity
or at least give some way to clear _index by hand.

Am I misusing something?

Cheers

**Comment by sschmid** [comment]
Hi, good find! I guess it makes sense to remove the emoty hashsets and use a hashset pool.

**Comment by hurog** [comment]
For now, I temporarily modified some points and applied new entitas.dll to my project and no more memory problems.
- Read-only GetEntities() call creates bunch of empty new HashSets, so I divided it with two different versions.
- Removed empty HashSet when removing entity


      private static HashSet<TEntity> _emptyIndex = new HashSet<TEntity>();

        public HashSet<TEntity> GetEntities(TKey key) {
            HashSet<TEntity> entities;
            if (!_index.TryGetValue(key, out entities))
            {
                return _emptyIndex;
            }

            return entities;
        }

        private HashSet<TEntity> GetEntitiesInternal(TKey key) {
            HashSet<TEntity> entities;
            if (!_index.TryGetValue(key, out entities)) {
                entities = new HashSet<TEntity>(EntityEqualityComparer<TEntity>.comparer);
                _index.Add(key, entities);
            }

            return entities;
        }

        protected override void addEntity(TKey key, TEntity entity) {
            GetEntitiesInternal(key).Add(entity);

            var safeAerc = entity.aerc as SafeAERC;
            if (safeAerc != null) {
                if (!safeAerc.owners.Contains(this)) {
                    entity.Retain(this);
                }
            } else {
                entity.Retain(this);
            }
        }

        protected override void removeEntity(TKey key, TEntity entity) {
            var hashSet = GetEntitiesInternal(key);
            hashSet.Remove(entity);
            if (hashSet.Count == 0)
                _index.Remove(key);

            var safeAerc = entity.aerc as SafeAERC;
            if (safeAerc != null) {
                if (safeAerc.owners.Contains(this)) {
                    entity.Release(this);
                }
            } else {
                entity.Release(this);
            }
        }

I'll wait for the next release :)
Thank you!
