### ISSUE TITLE
is Entitas obsolete?

### ISSUE THREAD

**Issue by davoodkharmanzar** [sschmid/Entitas-CSharp#936]
hello,

is Entitas obsolete on 2019.3?
and what is difference with Unity ECS?

thanks.

**Comment by BenjaBobs** [comment]
It's been 11 months since last commit. I'm not sure Entitas is actively developed on at this point.

**Comment by hiradyazdan** [comment]
@davoodkharmanzar I don't see what's keeping it from being used in 2019.3, please elaborate where you're facing issues.

**Comment by poettlr** [comment]
@hiradyazdan Visual debugging is not working for me; For example;

**Comment by davoodkharmanzar** [comment]
i think **[Svelto ECS](https://github.com/sebas77/Svelto.ECS)** is better :]

**Comment by hiradyazdan** [comment]
@poettlr I have just installed 2019.2.19 and Visual Debugging works fine. Haven't tried 19.3 yet though.

**Comment by poettlr** [comment]
I'm on 2019.2.17, I will try it out.
Do you use any assembly definition files or just all default?

**Comment by hiradyazdan** [comment]
I have asmdefs too. Your issue might not necessarily be Entitas. That looks to me more of a symptom than a cause. Removing your library and reimporting might help.

**Comment by poettlr** [comment]
I don't see why, since I have the same problem on different computers and the library is not part of my vcs. But I give it a shot.

**Comment by hiradyazdan** [comment]
Also, make sure your roslyn properties/keys are set correctly. If it's not a config issue or some other plugin issue blocking visual debugging to load, then I'm afraid this could be the end of Entitas for me too..

**Comment by poettlr** [comment]
Got it working after updating, but I also had to recreate my scene, dunno why. I just tried a blank scene with 1 entity and visual debugging and it worked. Then I did my whole setup, which in my case is small since everything is generated. Worked.

**Comment by sschmid** [comment]
See #938

**Comment by sschmid** [comment]
I think when a project is mature, the regular update rate can go down. I use Entitas for many games daily in production, so I'd argue Entitas is not obsolete.

Recently there has been lots of activity again, see #1005
