### ISSUE TITLE
How to use state machine about Entitas?

### ISSUE THREAD

**Issue by LastGhost** [sschmid/Entitas-CSharp#94]
Hi,I want know how to use state machine about Entitas.  As I use the Entitas framework , I find it's difficult to deal with the game logic ,such as AI. For 
example: I want to spawn a GameObject(dustbin),and then move the dustbin game object to somewhere, at last , rotating the game object look at a point, Now, my solution is : Add Dustbin Resource Component, then spawn the GameObject and add Move Resource Component  at the AddViewSyste, then ,moving the dustbin game object and add Roate Component in the MoveSystem , at last, rotating the game object  in the RotateSystem ,That's very difficult to understand it, I hope some state machine can solve the problem ,and make code clear.

**Comment by sschmid** [comment]
#see 86

**Comment by LastGhost** [comment]
Is there any example code?I hope to see it to understanding.

**Comment by sschmid** [comment]
Maybe you can reopen #86 and revive the conversation. Also, you could try to ask in the Entitas chat: https://gitter.im/sschmid/Entitas-CSharp
Maybe someone can help you there
Personally, I cannot provide any examples for state machine
