### ISSUE TITLE
Is this repo the same as the Entities in the unity package manager？

### ISSUE THREAD

**Issue by zhoujiazhi222** [sschmid/Entitas-CSharp#944]
The status of the entities in the unity package manager is the preview, do I install the unity entities directly or git clone here
<img width="266" alt="Screen Shot 2020-07-12 at 2 41 54 PM" src="https://user-images.githubusercontent.com/20750357/87240642-d5fee880-c44d-11ea-994d-552e0cc8a6ce.png">

**Comment by c0ffeeartc** [comment]
No, that's Unity ECS in unity package manager. Completely different package.
If you want Entitas check [releases](https://github.com/sschmid/Entitas-CSharp/releases)

**Comment by zhoujiazhi222** [comment]
Thank you for your reply , And do you know which of the two frameworks has better performance
@c0ffeeartc

**Comment by c0ffeeartc** [comment]
Unity ECS has best performance over every other ECS framework used within Unity, also it’s one of the hardest to learn and use

**Comment by zhoujiazhi222** [comment]
@c0ffeeartc 
Thank you ， And I am looking for a server-side framework now. Can you give me some suggestions ，for example, photon

**Comment by c0ffeeartc** [comment]
> @c0ffeeartc
> Thank you ， And I am looking for a server-side framework now. Can you give me some suggestions ，for example, photon

Can't, maybe someone else can.

**Comment by zhoujiazhi222** [comment]
@c0ffeeartc 
OK ， Thank you for your help
