### ISSUE TITLE
Will Entitas be in sale this year?

### ISSUE THREAD

**Issue by olaf-svenson** [sschmid/Entitas-CSharp#946]
Hi everyone!
Any chance Entitas will be in sale with discount this year in the Asset Store? :)

Like here https://twitter.com/entitas_csharp/status/1067111618226647041

**Comment by sschmid** [comment]
Yes, I'm happy to announce, Entitas is on sale!

http://u3d.as/NuJ

**Comment by olaf-svenson** [comment]
awesome :)
