### ISSUE TITLE
context

### ISSUE THREAD

**Issue by bayganik** [sschmid/Entitas-CSharp#949]
Hi,

I have an idea / suggestion / found a bug / have question / want to contribute.

Here's some code

```csharp
using Entitas;

public sealed class MyComponent : IComponent {
}
```

Cheers

**Comment by sschmid** [comment]
Your issue "context" is missing context ;)

**Comment by sschmid** [comment]
I guess that's just the issue template. Feel free to create a new issue or to reopen, if you have a question
