### ISSUE TITLE
GUI entitas does not have button generate

### ISSUE THREAD

**Issue by vovasazonov** [sschmid/Entitas-CSharp#950]
Hi,

I try generate context and source files but my GUI looks like this.
![image](https://user-images.githubusercontent.com/48253536/94127160-9bf88c80-fe69-11ea-9a87-9fa3499b19e3.png)

using 
unity 2019.3.2f1
windows 10

**Comment by sschmid** [comment]
Hi,

go to Tools -> Jenny - Preferences...

<img width="576" alt="Screen Shot 2020-09-24 at 12 02 17" src="https://user-images.githubusercontent.com/233700/94131205-ed028380-fe5d-11ea-8fcc-64f4c6e99415.png">
