### ISSUE TITLE
I‘m a program noob. Is there a way to make "if(entity.hasComponent){ entity.component... }" shorter?

### ISSUE THREAD

**Issue by atkdefender** [sschmid/Entitas-CSharp#952]
C# in unity

Without "if(entity.hasComponent)", "entity.component" sometimes cause a error.
But it make my code to long.

**Comment by StormRene** [comment]
It will not sometimes indicate an error, but always. You try to access data that does not exist. 

Tip: If you use `ReactiveSystem`s you can also set the filter method correctly in advance. Like in this example here:
[https://github.com/sschmid/Match-One/blob/master/Assets/Features/Board/Systems/FallSystem.cs](url)
The filter also checks if it is a piece before the execute is called.

How would you wish what would happen if the component did not exist on the entity?

**Comment by atkdefender** [comment]
> It will not sometimes indicate an error, but always. You try to access data that does not exist.
> 
> Tip: If you use `ReactiveSystem`s you can also set the filter method correctly in advance. Like in this example here:
> [https://github.com/sschmid/Match-One/blob/master/Assets/Features/Board/Systems/FallSystem.cs](url)
> The filter also checks if it is a piece before the execute is called.
> 
> How would you wish what would happen if the component did not exist on the entity?

Something like "entity.component?.value=...", without error everything is ok.
Maybe I think too much. Thx for answer.
