### ISSUE TITLE
Should any change of the value in component, react by ReactiveSystem?

### ISSUE THREAD

**Issue by atkdefender** [sschmid/Entitas-CSharp#955]
I know that using "e.AddComponent", "e.ReplaceComponent", or "e.RemoveComponent", then the ReactiveSystem can be triggered.
Sometime I change the values in component stealthily, by group some components and foreach.
Like:
```
foreach(e in entities)
{
 e.position.value = (2,3);  //This bypass the ReactiveSystem
}
```

Is this bad? What's the consequence?

**Comment by rglobig** [comment]
The consequence is that the systems and group events are not triggered. If you want this behavior you can do that.

**Comment by atkdefender** [comment]
> The consequence is that the systems and group events are not triggered. If you want this behavior you can do that.

Thx for answer:D
