### ISSUE TITLE
How many entities should a hero has? Hero has some game status(atk, hp, def...), and some show thing(bones animation...).

### ISSUE THREAD

**Issue by atkdefender** [sschmid/Entitas-CSharp#960]
For a hero, he has some game status(atk, hp, def...), and some showing things(bones animation, moveableComponent, positionComponent...).
Guessing answer:
1. He has the only entity, gameEntity.
2. He has 2 entities, gameEntity & showEntity.
3. He has more than these.

**Comment by c0ffeeartc** [comment]
Hello. It's always up to design.
I usually have 1 entity per character. If hero holds or wears some equipment it can be a separate entity.

2. Interesting idea about gameEntity and showEntity, it may be useful if you wish to display 0..N different showEntities for 1 gameEntity.

3. Usually not, unless 1 is not enough.

**Comment by atkdefender** [comment]
> Hello. It's always up to design.
> I usually have 1 entity per character. If hero holds or wears some equipment it can be a separate entity.
> 
> 1. Interesting idea about gameEntity and showEntity, it may be useful if you wish to display 0..N different showEntities for 1 gameEntity.
> 2. Usually not, unless 1 is not enough.

Thx for the answer:D!
