### ISSUE TITLE
Using without Unity

### ISSUE THREAD

**Issue by eranimo** [sschmid/Entitas-CSharp#986]
The readme says it can be used without Unity (I'm using Godot) but all the documentation for the code generator part assumes you are using Unity. Is there any way to get the code generator working without Unity?

**Comment by ilywkaa** [comment]
Check here https://github.com/sschmid/Entitas-CSharp/wiki/Entitas-pure-C%23

**Comment by Jennal** [comment]
@ilywkaa I want to use Entitas on server side, which are writen in .net6. How do I recompile Entitas dlls into .net6?

**Comment by Jennal** [comment]
> @ilywkaa I want to use Entitas on server side, which are writen in .net6. How do I recompile Entitas dlls into .net6?

I just make it a try.  net6 project can reference all the 3 dlls without error. But Jenny.exe can't find any component in the project.
My component looks like this:

```
using Entitas;
using Entitas.CodeGeneration.Attributes;

[Game]
[Event(EventTarget.Self)]
public sealed class PlayerComponent : IComponent
{
    public string Name;
}
```

**Comment by sschmid** [comment]
@Jennal fyi, Entitas 1.14 will be netstandard2.1 and net6.0
https://github.com/sschmid/Entitas-CSharp/issues/992#issuecomment-1227761712

Jenny will also run on net6.0 and will be able to parse both the old unity csproj + the "new" sdk-style csproj
