### ISSUE TITLE
Are there any plans to overhaul and extend the tutorial series?

### ISSUE THREAD

**Issue by jtuchel** [sschmid/Entitas-CSharp#987]
Hi,
I would like to know if there are any plans to overhaul the tutorial series taken from here

https://github.com/sschmid/Entitas-CSharp#video-tutorials--unity-unite-talks

Things might have changed (or not) but I'm missing a more in depth guide (view, best practices, ...). The only thing I found was an older workshop for Asteroids

https://www.youtube.com/watch?v=1qh6fTHeb5E

Creating a small game e.g. Snake from scratch would show how to use Entitas with Unity's "view" ( working with the new input system, moving a GameObject, scene management, ... ). Currently I personally think the written tutorials e.g. https://github.com/FNGgames/Entitas-Simple-Movement-Unity-Example are still nice ones but as I mentioned before I personally would prefer a small "full" game with

- a main menu
- starting the game until the game over
- loading another scene to decide between restart / quit

Just a suggestion but I would be interested in it :)

**Comment by RustedGames** [comment]
https://www.youtube.com/playlist?list=PLlTjzpNeSTixk0tbFZai130v_rvtJkL8z

**Comment by sschmid** [comment]
@jtuchel Yes, I will start working on new Videos starting September 2022 😬

**Comment by lightjiao** [comment]
> @jtuchel Yes, I will start working on new Videos starting September 2022 😬

Hi, Is the new video tutorial finished?  I don'nt know how to use Entitas 1.4.1 code generator.
