### ISSUE TITLE
Pool vs Context

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas-CSharp#99]
Hey guys, this is more or less a poll:
What do you guys actually think of the name Pool? I was thinking calling it Context instead of Pool. I started thinking that it might be a better name since we often use it to spilt our games into different 'contexts' like Core, Meta, UI

Let me know what you think, maybe you have even better suggestions...

**Comment by JuDelCo** [comment]
Pool is more short to write.

Yes, i'm very lazy

**Comment by grygus** [comment]
I also prefer Pool, i think it's more sexy, like eye candy :)

**Comment by SvDvorak** [comment]
Pools makes me think of object pools which in one way is fitting because it refers to a pool of objects but at the same time it doesn't fit the pattern itself since we're querying and actually using the pool contents directly. Then again, pool is shorter to write as @JuDelCo mentioned =)

**Comment by JamesMcMahon** [comment]
Yeah maybe I am just used to it, but I like the terminology Pool. It is a nice description of what it is and I think Context would actually be less clear.

Also JuDelCo is right about it being shorter 🍺

**Comment by Fijit** [comment]
I also prefer **Pool** for pretty much the same reasons @JamesMcMahon has already stated. I've used it for years and know what it means as I glance over code.

It also doesn't compete for auto-completion space unlike Context (ContextMenu in UnityEngine for example) - A feeble argument but I needed to add something unique to the poll  ;-)

**Comment by sschmid** [comment]
Seems like you guys are outvoting me :)

**Comment by JamesMcMahon** [comment]
It's your project Simon so ultimately it's your call. But I will say from experience that sometimes you can stare at a project so long that you see flaws where there are none. 😄

**Comment by mcavila** [comment]
What about "Group" 😉

**Comment by sschmid** [comment]
Thanks for your input and opinions. Pool will stay Pool :)
For now... 😈

**Comment by sschmid** [comment]
Old ghosts being reawakened. After experiencing confusion when talking about object pools and Entitas pools and after writing explanation like "a pool is basically a context" I finally decided to rename Pool to Context  😱
