### ISSUE TITLE
Unity 2020/2021 Crash while selecting entity game object (Windows)

### ISSUE THREAD

**Issue by zendorx** [sschmid/Entitas-CSharp#990]
https://user-images.githubusercontent.com/909905/145678347-e79df163-5174-4734-b648-9dc042074f10.mp4

**Comment by zendorx** [comment]
same for 2021 unity

**Comment by zendorx** [comment]
found the reason. It because component contains int2 property. And workaround here?

**Comment by sschmid** [comment]
Hi, a custom TypeDrawer for that type might help, example
https://github.com/sschmid/Entitas-CSharp/blob/master/Addons/Entitas.VisualDebugging.Unity.Editor/Entitas.VisualDebugging.Unity.Editor/Entity/TypeDrawer/Vector2TypeDrawer.cs

Save them in an Editor folder.

Maybe sth goes wrong close to here
https://github.com/sschmid/Entitas-CSharp/blob/master/Addons/Entitas.VisualDebugging.Unity.Editor/Entitas.VisualDebugging.Unity.Editor/Entity/Entity/EntityDrawer.cs#L301-L328

**Comment by sschmid** [comment]
@zendorx I hope that helped.
Feel free to reopen if you still have issues
