### ISSUE TITLE
Entitas unity asset doubt unity V-2019.4.37f1

### ISSUE THREAD

**Issue by macho-de-catachan** [sschmid/Entitas-CSharp#995]
Hi, excuse me but new to unity and programming an recently view one of the videos in tandem with unity ECS got curious and went looking for entitas in the asset store. (for clarity i only have installed in my machine unity versions: 2019.4.37f1 and the latest 2021.3.1f1)

so i gave it a go, tested in both versions and it run without issue in 2019.4.37f1 then went to the tutorials and followed them to the last but after the first step creating the first component. ↓↓

`DebugMessageComponent.cs

using Entitas;

[Game]
public class DebugMessageComponent : IComponent 
{    
    public string message;
}
Save your file, go back to Unity, wait for the compiler to complete, then click Generate again. You should now have a file inside your generated folder called GameDebugMessageComponent.cs (in Generated -> Game -> Components).`

why does every initial script that i place in the project [disappears](https://www.loom.com/share/98c44553d4b84595923688edaf170725) form where i had it? even in the console appear warnings of directory not found.

please if you could help solve this doubt and issue i'll be most grateful.

PS: as a side note how do you set up the other code generator that comes in the zip file on a windows sistem or the server as you did back in 2018 in the tutorial video on visual studio 2017?

**Comment by sschmid** [comment]
@macho-de-catachan 
The generated folder will be updated and files will be overwritten.
Don't place you source code in the generated folder, they will be lost

**Comment by macho-de-catachan** [comment]
thank you for the answer!
